
= #Scissione dei pagamenti - Split payment# (CIUS domestica)

La scissione dei pagamenti o split payment è un regime particolare che stabilisce che il debitore dell'IVA sia il cessionario/committente anziché, come avviene normalmente, il cedente/prestatore.

Per supportare questo particolare caso si valorizza il *cac:TaxCategory/cbc:ID* (BT-118 VAT Category code) utilizzando il TaxCategory 'B' (Transferred VAT) secondo la codifica UN/ECE 5305.

[NOTE]
====
Il valore dell’IVA split va ricompreso nel valore inserito in cbc:PrepaidAmount. Si evidenzia che il cbc:PrepaidAmount non è supportato in FatturaPA ma viene utilizzato per valorizzare correttamente il dato cbc:PayableAmount (BT-115 Amount due for payment) che è obbligatorio per la EN 16931.
====


.Esempio di Scissione dei pagamenti
L'esempio riportato è relativo alla fattura emessa ad una PA soggetta alla scissione pagamento.

[source, xml, indent=0]
----
<cac:TaxTotal>
  <cbc:TaxAmount currencyID="EUR">22.00</cbc:TaxAmount>
  <cac:TaxSubtotal>
    <cbc:TaxableAmount currencyID="EUR">100.00</cbc:TaxableAmount>
    <cbc:TaxAmount currencyID="EUR">22.00</cbc:TaxAmount>
    <cac:TaxCategory>
      <cbc:ID>B</cbc:ID>
      <cbc:Percent>22</cbc:Percent>
    </cac:TaxCategory>
    <cac:TaxScheme>
      <cbc:ID>VAT</cbc:ID>
    </cac:TaxScheme>
  </cac:TaxSubtotal>
</cac:TaxTotal>
<cac:LegalMonetaryTotal>
  <cbc:TaxExclusiveAmount currencyID="EUR">100.00</cbc:TaxExclusiveAmount>
  <cbc:TaxInclusiveAmount currencyID="EUR">122.00</cbc:TaxInclusiveAmount>
  <cbc:PrepaidAmount currencyID="EUR">22.00</cbc:PrepaidAmount>
  <cbc:PayableAmount currencyID="EUR">100.00</cbc:PayableAmount>
</cac:LegalMonetaryTotal>
----

= Indicazione acconto in fattura
L’indicazione dell’acconto in fattura è operata attraverso l’inserimento di una specifica riga di fattura di importo negativo. Pertanto, è necessario che l’elemento cbc:InvoicedQuantity (BT-129 Invoiced Quantity) venga valorizzato a “-1.00”. 

La riga di acconto ha la medesima natura della prestazione oggetto della fattura di saldo. 

.Esempio indicazione di un acconto del valore di 100 euro nella fattura di saldo 

[source, xml, indent=0]
----
<ubl:Invoice> 
... 
<cac:InvoiceLine> 
          <cbc:ID>2</cbc:ID> 
          <cbc:InvoicedQuantity unitCode="C62">-1.00</cbc:InvoicedQuantity > 
          <cbc:LineExtensionAmount currencyID="EUR">-100.00</cbc:Amount> 
          <cac:Item> 
                    <cbc:Name>Acconto su prestazione</cbc:ID> 
                    <cac:ClassifiedTaxCategory> 
                              <cbc:ID>S</cbc:ID> 
                              <cbc:Percent>22</cbc:Percent> 
                              <cac:TaxScheme> 
                                        <cbc:ID>VAT</cbc:ID> 
                              </cac:TaxScheme> 
                    </cac: ClassifiedTaxCategory > 
          </cac:Item> 
          <cac:Price > 
                    <cbc:PriceAmount currencyID="EUR">100.00</cbc:PriceAmount> 
                    <cbc:BaseQuantity unitCode="C62">1</cbc:BaseQuantity> 
                    <cac:AllowanceCharge> 
                               <cbc:ChargeIndicator>false</cbc:ChargeIndicator> 
                               <cbc:Amount currencyID="EUR">0.00</cbc:Amount> 
                               <cbc:BaseAmount currencyID="EUR">100.00</cbc:BaseAmount> 
                    </cac:AllowanceCharge> 
          </cac:Price> 
</cac:InvoiceLine> 
----