
= #Imposta di Bollo# (CIUS domestica)

La gestione del bollo è operata come sconto o maggiorazione a livello di documento a mezzo dell’utilizzo del *cac:AllowanceCharge* (BG-21 Document level charge): +

* nel caso di bollo su fattura, inserendo il *cbc:ChargeIndicator* = true;
* nel caso di bollo su nota di credito, inserendo il *cbc:ChargeIndicator* = false.

L'emittente fattura può decidere se:
[loweralpha]
. effettuare la rivalsa dell'imposta di bollo indicando una maggiorazione di 2 euro a livello di testata nell'elemento *cac:AllowanceCharge/cbc:Amount* (FPA 2.1.1.6.2 ImportoBollo);
. non effettuare la rivalsa indicando una maggiorazione di 0 euro a livello di testata nell'elemento *cac:AllowanceCharge/cbc:Amount* (FPA 2.1.1.6.2 ImportoBollo).

Il *cac:TaxCategory/cbc:ID* (BT-95 Document level charge VAT category code) viene posto a Z (zero) per indicare che l’importo è escluso IVA ex art. 15 DPR n. 633 del 1972 (per ulteriori dettagli vedi paragrafo 7.3). +

Il *cbc:AllowanceChargeReasonCode* (BT-105 Document level charge reason code) è valorizzato con SAE ed il *cbc:AllowanceChargeReason* (BT-104 Document level charge reason) è valorizzato con la stringa BOLLO. +


== Caso 1 - Bollo su fattura non addebitato al Cliente

In questo caso si valorizza il *cbc:Amount* (BT-99 Document level charge amount) con il valore 0 così che il valore del bollo non influisca sul *cbc:TaxInclusiveAmount* (BT-112 Invoice total amount with VAT). +


.Esempio di fattura per prestazione esente del valore di 100 euro con bollo non addebitato al Cliente
[source, xml, indent=0]
----
<ubl:Invoice>
...
<cac:AllowanceCharge>
  <cbc:ChargeIndicator>true</cbc:ChargeIndicator>
  <cbc:AllowanceChargeReasonCode>SAE</cbc:AllowanceChargeReasonCode>
  <cbc:AllowanceChargeReason>BOLLO</cbc:AllowanceChargeReason>
  <cbc:Amount currencyID="EUR">0</cbc:Amount>
  <cac:TaxCategory>
    <cbc:ID>Z</cbc:ID>
    <cbc:Percent>0</cbc:Percent>
    <cac:TaxScheme>
      <cbc:ID>VAT</cbc:ID>
    </cac:TaxScheme>
  </cac:TaxCategory>
  </cac:AllowanceCharge>
  <cac:TaxTotal>
    <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount>
    <cac:TaxSubtotal>
      <cbc:TaxableAmount currencyID="EUR">100.00</cbc:TaxableAmount>
      <cbc:TaxAmount currencyID="EUR">0</cbc:TaxAmount>
      <cac:TaxCategory>
        <cbc:ID>E</cbc:ID>
      </cac:TaxCategory>
      <cbc:TaxExemptionReasonCode>vatex-eu-132</cbc:TaxExemptionReasonCode>
      <cbc:TaxExemptionReason>N4</cbc:TaxExemptionReason>
      <cac:TaxScheme>
        <cbc:ID>VAT</cbc:ID>
      </cac:TaxScheme>
    </cac:TaxSubtotal>
    <cac:TaxSubtotal>
      <cbc:TaxableAmount currencyID="EUR">0.00</cbc:TaxableAmount>
      <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount>
      <cac:TaxCategory>
        <cbc:ID>Z</cbc:ID>
        <cbc:Percent>0</cbc:Percent>
      <cac:TaxScheme>
        <cbc:ID>VAT</cbc:ID>
      </cac:TaxScheme>
      </cac:TaxCategory>
    </cac:TaxSubtotal>
  </cac:TaxTotal>
  <cac:LegalMonetaryTotal>
    <cbc:TaxExclusiveAmount currencyID="EUR">100.00</cbc:TaxExclusiveAmount>
    <cbc:TaxInclusiveAmount currencyID="EUR">100.00</cbc:TaxInclusiveAmount>
    <cbc:ChargeTotalAmount currencyID="EUR">0.00</cbc:ChargeTotalAmount>
    <cbc:PayableAmount currencyID="EUR">100.00</cbc:PayableAmount>
  </cac:LegalMonetaryTotal>
----


== Caso 2 - Bollo su fattura addebitato al Cliente

In questo caso si valorizza il *cbc:Amount* (BT-99 Document level charge amount) con il valore 2 così che il valore del bollo influisca sul *cbc:TaxInclusiveAmount* (BT-112 Invoice total amount with VAT). +



.Esempio di fattura per prestazione esente del valore di 100 euro con bollo addebitato al Cliente
[source, xml, indent=0]
----
<ubl:Invoice>
...
<cac:AllowanceCharge>
  <cbc:ChargeIndicator>true</cbc:ChargeIndicator>
  <cbc:AllowanceChargeReasonCode>SAE</cbc:AllowanceChargeReasonCode>
  <cbc:AllowanceChargeReason>BOLLO</cbc:AllowanceChargeReason>
  <cbc:Amount currencyID="EUR">2.00</cbc:Amount>
  <cac:TaxCategory>
    <cbc:ID>Z</cbc:ID>
    <cbc:Percent>0</cbc:Percent>
    <cac:TaxScheme>
      <cbc:ID>VAT</cbc:ID>
    </cac:TaxScheme>
  </cac:TaxCategory>
  </cac:AllowanceCharge>
  <cac:TaxTotal>
    <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount>
    <cac:TaxSubtotal>
      <cbc:TaxableAmount currencyID="EUR">100.00</cbc:TaxableAmount>
      <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount>
      <cac:TaxCategory>
        <cbc:ID>E</cbc:ID>
      </cac:TaxCategory>
      <cbc:TaxExemptionReasonCode>vatex-eu-132</cbc:TaxExemptionReasonCode>
      <cbc:TaxExemptionReason>N4</cbc:TaxExemptionReason>
      <cac:TaxScheme>
        <cbc:ID>VAT</cbc:ID>
      </cac:TaxScheme>
    </cac:TaxSubtotal>
    <cac:TaxSubtotal>
      <cbc:TaxableAmount currencyID="EUR">2.00</cbc:TaxableAmount>
      <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount>
      <cac:TaxCategory>
        <cbc:ID>Z</cbc:ID>
        <cbc:Percent>0</cbc:Percent>
      </cac:TaxCategory>
      <cac:TaxScheme>
        <cbc:ID>VAT</cbc:ID>
      </cac:TaxScheme>
    </cac:TaxSubtotal>
  </cac:TaxTotal>
  <cac:LegalMonetaryTotal>
    <cbc:LineExtensionAmount currencyID="EUR">100.00</cbc:LineExtensionAmount>
    <cbc:TaxExclusiveAmount currencyID="EUR">102.00</cbc:TaxExclusiveAmount>
    <cbc:TaxInclusiveAmount currencyID="EUR">102.00</cbc:TaxInclusiveAmount>
    <cbc:ChargeTotalAmount currencyID="EUR">2.00</cbc:ChargeTotalAmount>
    <cbc:PayableAmount currencyID="EUR">102.00</cbc:PayableAmount>
  </cac:LegalMonetaryTotal>
----

== Caso 3 - Bollo su nota di credito addebitato al Cliente

Nel caso di bollo su nota di credito si valorizza il *cbc:ChargeIndicator* = false e il *cbc:Amount* (BT-92 Document level allowance amount) con il valore 2 così che il valore del bollo influisca sul *cbc:TaxInclusiveAmount* (BT-112 Invoice total amount with VAT).

Anche in questo caso il *cac:TaxCategory/cbc:ID* (BT-95 Document level charge VAT category code) viene posto a Z (zero) per indicare che l’importo è escluso ex art. 15 DPR n. 633 del 1972. +

Il *cbc:AllowanceChargeReasonCode* (BT-98 Document level allowance reason code) è valorizzato con 95 ed il *cbc:AllowanceChargeReason* (BT-97 Document level allowance reason) è valorizzato con la stringa BOLLO. +

.Esempio di nota di credito di una prestazione esente del valore di 100 euro con bollo addebitato al Cliente
[source, xml, indent=0]
----
<ubl:CreditNote>
...
<cac:AllowanceCharge>
  <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
  <cbc:AllowanceChargeReasonCode>95</cbc:AllowanceChargeReasonCode>
  <cbc:AllowanceChargeReason>BOLLO</cbc:AllowanceChargeReason>
  <cbc:Amount currencyID="EUR">2.00</cbc:Amount>
  <cac:TaxCategory>
    <cbc:ID>Z</cbc:ID>
    <cbc:Percent>0</cbc:Percent>
    <cac:TaxScheme>
      <cbc:ID>VAT</cbc:ID>
    </cac:TaxScheme>
  </cac:TaxCategory>
  </cac:AllowanceCharge>
  <cac:TaxTotal>
    <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount>
    <cac:TaxSubtotal>
      <cbc:TaxableAmount currencyID="EUR">100.00</cbc:TaxableAmount>
      <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount>
      <cac:TaxCategory>
        <cbc:ID>E</cbc:ID>
      </cac:TaxCategory>
      <cbc:TaxExemptionReasonCode>vatex-eu-132</cbc:TaxExemptionReasonCode>
      <cbc:TaxExemptionReason>N4</cbc:TaxExemptionReason>
      <cac:TaxScheme>
        <cbc:ID>VAT</cbc:ID>
      </cac:TaxScheme>
    </cac:TaxSubtotal>
    <cac:TaxSubtotal>
      <cbc:TaxableAmount currencyID="EUR">-2.00</cbc:TaxableAmount>
      <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount>
      <cac:TaxCategory>
        <cbc:ID>Z</cbc:ID>
        <cbc:Percent>0</cbc:Percent>
      </cac:TaxCategory>
      <cac:TaxScheme>
        <cbc:ID>VAT</cbc:ID>
      </cac:TaxScheme>
    </cac:TaxSubtotal>
  </cac:TaxTotal>
  <cac:LegalMonetaryTotal>
    <cbc:LineExtensionAmount currencyID="EUR">100.00</cbc:LineExtensionAmount>
    <cbc:TaxExclusiveAmount currencyID="EUR">98.00</cbc:TaxExclusiveAmount>
    <cbc:TaxInclusiveAmount currencyID="EUR">98.00</cbc:TaxInclusiveAmount>
    <cbc:AllowanceTotalAmount currencyID="EUR">2.00</cbc:AllowanceTotalAmount>
    <cbc:PayableAmount currencyID="EUR">98.00</cbc:PayableAmount>
  </cac:LegalMonetaryTotal>
----
