
[[antiblastici]]
== #Esempio avanzato nel settore Health: gli antiblastici#

Nel caso sia necessario identificare più precisamente la merce pericolosa è possibile fornire ulteriori informazioni come l’*identificativo della sostanza pericolosa* secondo la convenzione dichiarata nell’UNDGCode, la *denominazione tecnica* e la *categoria sostanza pericolosa*.

Per il trasporto di medicinali pericolosi (antiblastici) su gomma viene usata la convenzione ADR che definisce le classi di pericolosità (Hazard class) e identifica ogni sostanza con un UN Number.

Si forniscono a titolo di esempio gli identificativi e le relative classi di pericolosità più utilizzate nel trasporto degli antiblastici:

.Classi di pericolosità
[width="100%", cols="2h,3m,1m"]
|===
| *Numero UN*
| *Denominazione UN*
| *Classe di pericolosità*

| UN 1851
| Medicine, liquid, toxic, n.o.s
| 6.1

| UN 3248
| Medicine, liquid, flammable, toxic, n.o.s
| 3

| UN 3249
| Medicine, solid, toxic, n.o.s
| 6.1
|===

Di seguito un esempio significativo:

.Esempio Antiblastici:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-3.xml[tags=antiblastici]
----

L’esempio avanzato sopra riportato denota l’uso di:

<1> L’identificativo UN (UN Number) assegnato alla sostanza: 3249
<2> La convenzione: ADR (European agreement on the international carriage of dangerous goods on road) secondo la codifica UNCL8273 (Dangerous goods regulations code)
<3> La denominazione tecnica del medicinale: Medicine, solid, toxic, n.o.s
<4> La categoria del medicinale: ANTIBLASTICI
<5> La classe di pericolosità

Per ricercare gli UN Number disponibili è disponbile il seguente tool:

{link-hazmattool}
 

