[[Classificazione-prodotto]]
= #Classificazione prodotto#

Per ciascun prodotto, all’interno della relativa linea del DDT, è possibile specificare uno o più codici di classificazione, valorizzando il campo “ItemClassificationCode/ID” dell’elemento “CommodityClassification”. 

Si raccomanda comunque di utilizzare almeno uno dei sistemi di classificazione di beni e servizi riportati nella tabella che segue, ove applicabili.


[cols="1,3,2", options="header"]
|====
s|Codice
s|Descrizione dello standard di classificazione
s|Ambito di utilizzo

|*STI*
|Sistema ufficiale europeo di classificazione unico per gli appalti pubblici (CPV – Common Procurement Vocabulary)
|Prodotti e servizi oggetto di appalti pubblici

|*STL*
|Sistema di classificazione anatomico, terapeutico e chimico (ATC - Anatomical Therapeutic Chemical classification system)
|Farmaci

|*STO*
|Classificazione Nazionale italiana dei Dispositivi medici (CND)
|Dispositivi medici

|*STH*
|Classificazione commerciale dei prodotti (GPC – Global Product Classification)
|Beni di largo consumo

|*IB*
|Sistema di identificazione internazionale dei libri (ISBN - International Standard Book Number)
|Libri (anche in formato elettronico e altri prodotti creati per essere utilizzati come libro

|*ZZZ*
|Sistema definito mutualmente tra le parti
|Per i dispositivi medici permette di specificare i valori “DM1”, “DM2” o “DM0” (quando non applicabili i primi due)
|====

[NOTE]
====
Si raccomanda indicare dettagliatamente [underline]#su linee d’ordine separate# i prodotti caratterizzati da codice prodotto differenti.
====


.Esempio di indicazione della classificazione prodotto
[source, xml, indent=0]
----
    <cac:CommodityClassification>
            <cbc:ItemClassificationCode listID="STL">N05BA01</cbc:ItemClassificationCode>
    </cac:CommodityClassification>
----

:leveloffset: +1

[[Indicazioni-per-i-dispositivi-medici]]
= Indicazioni per i dispositivi medici

In questo esempio `cac:CommodityClassification`/`cbc:ItemClassificationCode` viene fornito il numero di registrazione attribuito al dispositivo medico nella "Banca dati dei dispositivi medici" dal Ministero della Salute.

Si rammenta, infatti che, come indicato nella Circolare del Ministero della Salute DGSISS-0002051-P-08/02/2019 l’attributo schemeID dovrà essere valorizzato con:

* DM1 per “Dispositivo medico o Dispositivo diagnostico in vitro”

* DM2 per “Sistema o kit Assemblato”

* DM0 per "Nessun numero di repertorio"

.Esempio di indicazione di doppia classificazione del prodotto
[source, xml, indent=0]
----
    <cac:Item>
        <cbc:Name>Nome del Dispositivo</cbc:Name>
        <cac:SellersItemIdentification>
            <cbc:ID>Codice attribuito dal Fornitore</cbc:ID>
        </cac:SellersItemIdentification>
        <cac:CommodityClassification>
            <cbc:ItemClassificationCode listID="STO">P09070302</cbc:ItemClassificationCode>
        </cac:CommodityClassification>
        <cac:CommodityClassification>
            <cbc:ItemClassificationCode listID="ZZZ">DM1:229026</cbc:ItemClassificationCode>
        </cac:CommodityClassification>
    </cac:Item>
----

Si noti che, nell’esempio, l’elemento “CommodityClassificationCode” è utilizzato due volte (ciò è possibile in quanto tale elemento ha cardinalità multipla), perché è stato indicato anche il corrispondente codice STO relativo alla classificazione del prodotto nel sistema di Classificazione Nazionale italiana dei Dispositivi medici.

:leveloffset: -1






    