[[parti]]
= Parti

Le seguenti parti/I seguenti ruoli possono essere specificate/i nel messaggio:

[[sellersupplierparty-seller]]
== Fornitore/Venditore (SellerSupplierParty)

Il fornitore è colui che vende la merce o i servizi al cliente. Il fornitore è obbligatorio in quanto destinatario dell'ordine PEPPOL, pertanto è obbligatori includere l'EndpointID (ParticipantID) con il quale è registrato su PEPPOL.


.Esempio di informazioni per un fornitore italiano con indicazione della Partita Iva nell'Endpoint
[source, xml, indent=0]
----
<cac:SellerSupplierParty>
    <cac:Party>
	 <cbc:EndpointID schemeID="9906">IT01234567890</cbc:EndpointID>
	 <cac:PartyName>
	 	<cbc:Name>Fornitore S.p.A.</cbc:Name>
	 </cac:PartyName>
	 <cac:PostalAddress>
	 	<cbc:StreetName>Indirizzo Riga 1</cbc:StreetName>
	 	<cbc:AdditionalStreetName>Indirizzo Riga 2</cbc:AdditionalStreetName  >
	 	<cbc:CityName>Bologna</cbc:CityName>
	 	<cbc:PostalZone>40121</cbc:PostalZone>
	 	<cbc:CountrySubentity>BO</cbc:CountrySubentity >
	 	<cac:AddressLine>
	 		<cbc:Line>Zona Savena</cbc:Line>
	 	</cac:AddressLine>
	 	<cac:Country>
	 	<cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
	 	</cac:Country>
	 </cac:PostalAddress>
	 <cac:PartyLegalEntity>
	 	<cbc:RegistrationName>Azienda fornitore</cbc:RegistrationName>
	 	<cbc:CompanyID>PIVA:IT01234567890</cbc:CompanyID>
	 	<cac:RegistrationAddress>
	 		<cbc:CityName>Bologna</cbc:CityName>
	 		<cac:Country>
            <cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
	 		</cac:Country>
	 	</cac:RegistrationAddress>
	 </cac:PartyLegalEntity>
	 <cac:Contact>
	 	<cbc:Name>Lucio Grande</cbc:Name>
	 	<cbc:Telephone>051102030</cbc:Telephone>
	 	<cbc:ElectronicMail>lucio.grande@fornitore.it</cbc:ElectronicMail>
	 </cac:Contact>
    </cac:Party>
</cac:SellerSupplierParty>
----

#Se il Fornitore è un'amministrazione pubblica, il campo *EndpointID/@schemeID* deve essere valorizzato con “0201:” seguito dal Codice UFE della PA.#

#Nel caso in cui non si inserisca la Partita IVA nell'EndpointID, la Partita IVA va indicata nel *Seller party identification*.#

#Nel caso in cui si voglia indicare anche il Codice Fiscale, quest'ultimo va indicato nel *Seller legal registration identifier*#.

.Esempio di indicazione della Partita Iva e del Codice Fiscale
[source, xml, indent=0]
----
<cac:SellerSupplierParty>
 <cac:Party>
	<cbc:EndpointID schemeID="0201">UFY9MH</cbc:EndpointID>
	<cac:PartyIdentification>
		<cbc:ID>PIVA:IT01598570354</cbc:ID>
	</cac:PartyIdentification>
	<cac:PartyName>
		<cbc:Name>Azienda USL di Reggio Emilia</cbc:Name>
	</cac:PartyName>
	<cac:PostalAddress>
		<cbc:StreetName>Via Amendola 2</cbc:StreetName>
		<cbc:CityName>Reggio Emilia</cbc:CityName>
		<cbc:PostalZone>42122</cbc:PostalZone>
		<cbc:CountrySubentity>RE</cbc:CountrySubentity>
		<cac:Country>
			<cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
		</cac:Country>
	</cac:PostalAddress>
	<cac:PartyLegalEntity>
		<cbc:RegistrationName>Azienda USL di Reggio Emilia</cbc:RegistrationName>
		<cbc:CompanyID>CF:01598570354</cbc:CompanyID>
		<cac:RegistrationAddress>
			<cbc:CityName>Reggio Emilia</cbc:CityName>
			<cac:Country>
				<cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
			</cac:Country>
		</cac:RegistrationAddress>
	</cac:PartyLegalEntity>
	<cac:Contact>
		<cbc:Name>Giovanni Rossi</cbc:Name>
		<cbc:Telephone>0522335111</cbc:Telephone>
		<cbc:ElectronicMail>giovanni.rossi@ausl.re.it</cbc:ElectronicMail>
	</cac:Contact>
    </cac:Party>
</cac:SellerSupplierParty>
----

.Esempio di informazioni per un fornitore estero
[source, xml, indent=0]
----
<cac:SellerSupplierParty>
    <cac:Party>
	 <cbc:EndpointID schemeID="9925">0999999999</cbc:EndpointID
	 <cac:PartyName>
	 	<cbc:Name>Fornitore Estero</cbc:Name>
	 </cac:PartyName>
	 <cac:PostalAddress>
	 	<cbc:StreetName> Rue Emile Claus 28</cbc:StreetName>
		<cbc:AdditionalStreetName>Quartiere</cbc:AdditionalStreetName>
		<cbc:CityName>Bruxelles</cbc:CityName>
		<cbc:PostalZone>1050</cbc:PostalZone>
		<cac:AddressLine>
		<cbc:Line>Deposito Consegnatario: Fornitore Estero</cbc:Line>
		</cac:AddressLine>
			<cac:Country>
			<cbc:IdentificationCode listID="ISO3166-1:Alpha2">BE</cbc:IdentificationCode>
			</cac:Country>
	 </cac:PostalAddress>
	 <cac:PartyLegalEntity>
	 	<cbc:RegistrationName>Fornitore Estero</cbc:RegistrationName>
	 	<cbc:CompanyID>0999999999</cbc:CompanyID>
	 	<cac:RegistrationAddress>
	 		<cbc:CityName>Bologna</cbc:CityName>
	 		<cac:Country>
            <cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
	 		</cac:Country>
	 	</cac:RegistrationAddress>
	 </cac:PartyLegalEntity>
	 <cac:Contact>
	 	<cbc:Name>Lucio Grande</cbc:Name>
	 	<cbc:Telephone>003241102030</cbc:Telephone>
	 	<cbc:ElectronicMail>lucio.grande@belgio.be</cbc:ElectronicMail>
	 </cac:Contact>
    </cac:Party>
</cac:SellerSupplierParty>
----

[yellow-background]#Il Fornitore è un elemento essenziale del processo che, eccezionalmente, può non essere determinato a priori, ma divenirlo solo al momento della cessione dei beni e/o della prestazione dei servizi. Ad esempio quando la facoltà di scegliere il Fornitore è riservata al Beneficiario.# 

[yellow-background]#In questo caso (Fornitore non predeterminato) l'elemento “SellerSupplierParty/Party” deve contenere solo i campi di seguito indicati:# 

* [yellow-background]#“EndpointID”, valorizzato con “9999999999999999” (sedici volte 9) indicando il valore "9907" per lo "Scheme ID";# 

* [yellow-background]#“PostalAddress/Country/IdentificationCode”, valorizzato con il codice corrispondente allo Stato in cu verrà effettuato l'acquisto (per l'Italia “IT”);# 

* [yellow-background]#“PartyLegalEntity/RegistrationName”, valorizzato con “NDEF”.# 

.Esempio di Informazioni del fornitore non identificato
[source, xml, indent=0]
----
<cac:SellerSupplierParty>
    <cac:Party>
	 <cbc:EndpointID schemeID="9907">9999999999999999</cbc:EndpointID>
	 <cac:PartyName>
	 	<cbc:Name>Fornitore S.p.A.</cbc:Name>
	 </cac:PartyName>
	 <cac:PostalAddress>
	 	<cac:Country>
	 	<cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
	 	</cac:Country>
	 </cac:PostalAddress>
	 <cac:PartyLegalEntity>
	 	<cbc:RegistrationName>NDEF</cbc:RegistrationName>
	 	<cac:RegistrationAddress>
	 		<cac:Country>
            <cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
	 		</cac:Country>
	 	</cac:RegistrationAddress>
	 </cac:PartyLegalEntity>
    </cac:Party>
</cac:SellerSupplierParty>
----


[[buyercustomerparty-buyer]]
== Cliente/Acquirente (BuyerCustomerParty)

Il cliente è colui che acquista la merce o i servizi dal fornire. Il cliente è obbligatorio in quanto mittente del messaggio dell'ordine PEPPOL, pertanto è necessario includere l'EndpointID (ID partecipante) con il quale è registrato in PEPPOL.

#Se l'Amministrazione Aggiudicatrice è identificata in PEPPOL con il Codice UFE (ID Partecipante nei registri SMP), deve essere indicato l'Identificativo UFE come endpoint (cac:EndpointID):#

[source, xml, indent=0]
----
<cac:BuyerCustomerParty>
    <cac:Party>
        <cbc:EndpointID schemeID="0201">ABCDEF</cbc:EndpointID>
    …
    </cac:Party>
</cac:BuyerCustomerParty>
----

La Partita IVA invece va indicata nel cac:Tax Scheme/cbc:CompanyID.

.Esempio di informazioni del cliente
[source, xml, indent=0]
----
<cac:BuyerCustomerParty>
<cac:Party>
	<cbc:EndpointID schemeID="0201">UFY9MH</cbc:EndpointID>
	<cac:PartyName>
		<cbc:Name>Azienda USL di Reggio Emilia</cbc:Name>
	</cac:PartyName>
	<cac:PostalAddress>
		<cbc:StreetName>Via Amendola 2</cbc:StreetName>
		<cbc:CityName>Reggio Emilia</cbc:CityName>
		<cbc:PostalZone>42122</cbc:PostalZone>
		<cbc:CountrySubentity>RE</cbc:CountrySubentity>
		<cac:Country>
			<cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
		</cac:Country>
	</cac:PostalAddress>
	<cac:PartyTaxScheme>
		<cbc:CompanyID>IT01598570354</cbc:CompanyID>
		<cac:TaxScheme>
			<cbc:ID>VAT</cbc:ID>
		</cac:TaxScheme>
	</cac:PartyTaxScheme>
	<cac:PartyLegalEntity>
		<cbc:RegistrationName>Azienda USL di Reggio Emilia</cbc:RegistrationName>
		<cbc:CompanyID schemeID="0201">UFY9MH</cbc:CompanyID>
		<cac:RegistrationAddress>
			<cbc:CityName>Reggio Emilia</cbc:CityName>
			<cac:Country>
				<cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
			</cac:Country>
		</cac:RegistrationAddress>
	</cac:PartyLegalEntity>
	<cac:Contact>
		<cbc:Name>Giovanni Bianchi</cbc:Name>
		<cbc:Telephone>0522335111</cbc:Telephone>
		<cbc:ElectronicMail>giovanni.bianchi@ausl.re.it</cbc:ElectronicMail>
	</cac:Contact>
</cac:Party>
</cac:BuyerCustomerParty>
----

[[originatorcustomerparty-originator]]
== Committente (OriginatorCustomerParty)

Generalmente, il committente è l'utente finale che emette l'ordine. Le informazioni presenti nel messaggio dell'ordine inerenti al committente sono facoltative.

.Esempio di informazioni del committente appartenente alla medesima organizzazione del cliente/acquirente
[source, xml, indent=0]
----
<cac:OriginatorCustomerParty>
    <cac:Party>
	<cac:PartyIdentification>
			<cbc:ID schemeID="0201">ABCDEF</cbc:ID>
	</cac:PartyIdentification>
	<cac:PartyName>
		<cbc:Name>U.O. Farmacia Ospedaliera</cbc:Name>
	</cac:PartyName>
	<cac:Contact>
		<cbc:Name>Roberto Gastone</cbc:Name>
		<cbc:Telephone>010150847</cbc:Telephone>
		<cbc:ElectronicMail>roberto.gastone@ospedale.it</cbc:ElectronicMail>
	</cac:Contact>
    </cac:Party>
</cac:OriginatorCustomerParty>
----

[yellow-background]#Qualora il Documento sia emesso con l'uso di strumenti messi a disposizione da un Intermediario (ad esempio, un Ordine emesso utilizzando la piattaforma telematica di una centrale di acquisto), è possibile evidenziare il committente valorizzando l'elemento “OriginatorCustomerParty”, come mostrato nel seguente esempio.#

.Esempio di informazioni del committente che utilizza una piattaforma telematica di un terzo intermediario per l'emissione dell'ordine
[source, xml, indent=0]
----
<cac:OriginatorCustomerParty>
    <cac:Party>
	<cac:PartyIdentification>
		<cbc:ID schemeID="0201">AABBCC</cbc:ID>
	</cac:PartyIdentification>
	<cac:PartyName>
		<cbc:Name>AUSL SALERNO </cbc:Name>
	</cac:PartyName>
	<cac:Contact>
		<cbc:Name>Roberto Gastone</cbc:Name>
		<cbc:Telephone>010150847</cbc:Telephone>
		<cbc:ElectronicMail>roberto.gastone@ospedale.it</cbc:ElectronicMail>
	</cac:Contact>
    </cac:Party>
</cac:OriginatorCustomerParty>
----

[[accountingcustomerparty-invoicee]]
==  Intestatario fattura (AccountingCustomerParty)

L'intestatario della fattura è la persona giuridica che agisce per conto del Cliente e che riceve la fattura relativa all'ordine. Le informazioni sull'intestatario della fattura sono opzionali nel messaggio dell'Ordine PEPPOL. 

[IMPORTANT]
====
Qualora l'Acquirente (BuyerCustomerParty) sia una Pubblica Amministrazione, l'informazione deve essere fornita anche quando Intestatario della fattura (AccountingCustomerParty) e Acquirente coincidono, in tal caso il codice IPA deve essere inserito riportato nel *cac:EndpointID.*
====

.Esempio di informazioni dell'intestatario fattura
[source, xml, indent=0]
----
<cac:AccountingCustomerParty>
    <cac:Party>
        <cbc:EndpointID schemeID=”0201”>ABCDEF</cbc:EndpoinID>
        <cac:PartyName>
            <cbc:Name>Ospedale Sant'Anna</cbc:Name>
        </cac:PartyName>
        <cac:PostalAddress>
            <cbc:StreetName>Via del pensiero, 1</cbc:StreetName>
            <cbc:AdditionalStreetName>Primo Piano</cbc:AdditionalStreetName>
            <cbc:CityName>Maranello</cbc:CityName>
            <cbc:PostalZone>41053</cbc:PostalZone>
            <cbc:CountrySubentity>Modena</cbc:CountrySubentity>
            <cac:AddressLine>
                <cbc:Line>Stanza 18</cbc:Line>
            </cac:AddressLine>
            <cac:Country>
                <cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
            </cac:Country>
        </cac:PostalAddress>
        <cac:PartyTaxScheme>
            <cbc:CompanyID>00234567890</cbc:CompanyID>
            <cac:TaxScheme>
                <cbc:ID>VAT</cbc:ID>
            </cac:TaxScheme>
        </cac:PartyTaxScheme>
        <cac:PartyLegalEntity>
            <cbc:RegistrationName>OspedaleSant'Anna</cbc:RegistrationName>
            <cbc:CompanyID <cbc:ID>IT:CF:00234567890</cbc:CompanyID>
            <cac:RegistrationAddress>
                <cbc:CityName>Modena</cbc:CityName>
                <cac:Country>
                    <cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
                </cac:Country>
            </cac:RegistrationAddress>
        </cac:PartyLegalEntity>
        <cac:Contact>
            <cbc:Name>ResponsabileFatturazione</cbc:Name>
            <cbc:ElectronicMail>responsabile.fatturazione@ospedale.it</cbc:ElectronicMail>
        </cac:Contact>
    </cac:Party>
</cac:AccountingCustomerParty>
----
