[[Ordine-con-sostituzione-articolie-consegna-fuori-tempo]]
= Ordine con sostituzione articoli e consegna fuori tempo

Una risposta d’ordine può sostituire gli articoli in due modalità. Se viene sostituita la quantità totale di un articolo, tale informazione può essere fornita utilizzando l’elemento che identifica il nuovo venditore (`cac:SellerSubstitutedLineItem`) nella risposta di fatturazione, come illustrato nell’esempio seguente.

.Esempio di articolo sostituito in un messaggio di risposta d’ordine
[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
        <cbc:ID>6</cbc:ID>
        <cbc:LineStatusCode>3</cbc:LineStatusCode>
        <cac:Item>
            <cbc:Name>Salviette umide</cbc:Name>
            <cac:SellersItemIdentification>
                <cbc:ID>SItemNo011</cbc:ID>
            </cac:SellersItemIdentification>
            <cac:StandardItemIdentification>
                <cbc:ID schemeID="0160">05704368876486</cbc:ID>
            </cac:StandardItemIdentification>
        </cac:Item>
    </cac:LineItem>
    <cac:SellerSubstitutedLineItem> <1>
        <cbc:ID>2</cbc:ID>
        <cac:Item>
            <cbc:Name>Salviette umide</cbc:Name>
            <cac:SellersItemIdentification>
                <cbc:ID>SItemNo012</cbc:ID>
            </cac:SellersItemIdentification>
            <cac:StandardItemIdentification>
                <cbc:ID schemeID="0160">05704368643453</cbc:ID>
            </cac:StandardItemIdentification>
            <cac:CommodityClassification>
                <cbc:ItemClassificationCode listID="STI">675634</cbc:ItemClassificationCode>
            </cac:CommodityClassification>
        </cac:Item>
    </cac:SellerSubstitutedLineItem>
    <cac:OrderLineReference>
        <cbc:LineID>5</cbc:LineID>
    </cac:OrderLineReference>
</cac:OrderLine>
----

<1> Le informazioni sull’articolo sostituito vengono inviate `cac:SellerSubstitutedLineItem`

Se il venditore sostituisce una parte della quantità d’ordine o consegna la quantità d’ordine in date diverse, potrebbe dover aggiungere righe e/o contrassegnare le righe ordinate come consegnate, come illustrato nell’esempio seguente. +

Nell’esempio un venditore conferma la prima riga d’ordine, fornisce due date di consegna per la riga del secondo ordine di 3 pezzi (Prodotto B) aggiungendo una nuova riga e quindi conferma che la riga d’ordine 3 è già stata consegnata.

.Esempio di righe aggiuntive e consegna fuori tempo
[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
        <cbc:ID>1</cbc:ID>
        <cbc:LineStatusCode>5</cbc:LineStatusCode>
        <cac:Item>
            <cbc:Name>Prodotto A</cbc:Name>
            <cac:SellersItemIdentification>
                <cbc:ID>Pr00A</cbc:ID>
            </cac:SellersItemIdentification>
        </cac:Item>
    </cac:LineItem>
    <cac:OrderLineReference>
        <cbc:LineID>1</cbc:LineID>
    </cac:OrderLineReference>
</cac:OrderLine>
<cac:OrderLine>
    <cac:LineItem>
        <cbc:ID>2</cbc:ID>
        <cbc:LineStatusCode>3</cbc:LineStatusCode>
        <cbc:Quantity unitCode="C62">2</cbc:Quantity>
        <cac:Delivery>
            <cac:PromisedDeliveryPeriod>
                <cbc:StartDate>2018-07-01</cbc:StartDate>
            </cac:PromisedDeliveryPeriod>
        </cac:Delivery>
        <cac:Item>
            <cbc:Name>Prodotto B</cbc:Name>
            <cac:SellersItemIdentification>
                <cbc:ID>Pr00B</cbc:ID>
            </cac:SellersItemIdentification>
        </cac:Item>
    </cac:LineItem>
    <cac:OrderLineReference>
        <cbc:LineID>2</cbc:LineID>
    </cac:OrderLineReference>
</cac:OrderLine>
<cac:OrderLine>
    <cac:LineItem>
        <cbc:ID>3</cbc:ID>
        <cbc:LineStatusCode>1</cbc:LineStatusCode>
        <cbc:Quantity unitCode="C62">1</cbc:Quantity>
        <cac:Delivery>
            <cac:PromisedDeliveryPeriod>
                <cbc:StartDate>2018-07-05</cbc:StartDate>
            </cac:PromisedDeliveryPeriod>
        </cac:Delivery>
        <cac:Item>
            <cbc:Name>Prodotto B</cbc:Name>
            <cac:SellersItemIdentification>
                <cbc:ID>Pr00B</cbc:ID>
            </cac:SellersItemIdentification>
        </cac:Item>
    </cac:LineItem>
    <cac:OrderLineReference>
        <cbc:LineID>2</cbc:LineID>
    </cac:OrderLineReference>
</cac:OrderLine>
<cac:OrderLine>
    <cac:LineItem>
        <cbc:ID>4</cbc:ID>
        <cbc:LineStatusCode>42</cbc:LineStatusCode>
        <cac:Item>
            <cbc:Name>Prodotto C</cbc:Name>
            <cac:SellersItemIdentification>
                <cbc:ID>Pr00C</cbc:ID>
            </cac:SellersItemIdentification>
        </cac:Item>
    </cac:LineItem>
    <cac:OrderLineReference>
        <cbc:LineID>3</cbc:LineID>
    </cac:OrderLineReference>
</cac:OrderLine>
----


