
= Allowances and Charges


The order transaction has elements for Allowance/charge on 2 levels.

The element `cac:AllowanceCharge` with sub element `cbc:ChargeIndicator` indicates whether the instance is a charge (true) or an allowance (false).

The header level:: _Applies to the whole order and is included in the calculation of the order total amount (if specified)._
* Several allowances and charges may be supplied
* Specification of TAX for allowances and charges, `cac:TaxCategory` with sub elements, shall be supplied
* The sum of all allowances and charges on the header level shall be specified in `cbc:AllowanceTotalAmount` and `cbc:ChargeTotalAmount` respectively. See <<totals>>

The line level Price element:: _The price itself shall always be the net price, i.e. the base amount reduced with a discount (allowance)._
* Only one occurrence of allowance (discount) is allowed.
* Specification of TAX for allowance shall not be specified
* Allowance related to Price shall not be part of any other calculations.
* Allowance related to Price may specify amount and the base amount.


== Calculation of allowance/charge amount

Allowance and charge on document level consists of elements carrying information on the allowance/charge base amount
and the allowance/charge percentage. These are, if present in the invoice instance, used for calculating the allowance/charge amount.

If base amount is present, the percentage shall also be present, and if percentage is present, the base amount shall also be present,
and the calculation of the amount shall be:

====
stem:["Amount" = "Base amount" times ("Percentage" div 100)]
====


.Example of allowance and charges on the header level di UBL
[source, xml, indent=0]
----
<cac:AllowanceCharge>
        <cbc:ChargeIndicator>true</cbc:ChargeIndicator> <1>
        <cbc:AllowanceChargeReasonCode>FC</cbc:AllowanceChargeReasonCode>
        <cbc:AllowanceChargeReason>Freight service</cbc:AllowanceChargeReason>
        <cbc:MultiplierFactorNumeric>2</cbc:MultiplierFactorNumeric> <4>
        <cbc:Amount currencyID="EUR">20</cbc:Amount> <5>
        <cbc:BaseAmount currencyID="EUR">1000.00</cbc:BaseAmount> <3>
        <cac:TaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>22</cbc:Percent>
                <cac:TaxScheme>
                        <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
        </cac:TaxCategory>
</cac:AllowanceCharge>
<cac:AllowanceCharge>
        <cbc:ChargeIndicator>false</cbc:ChargeIndicator> <2> 
        <cbc:AllowanceChargeReasonCode>65</cbc:AllowanceChargeReasonCode>
        <cbc:AllowanceChargeReason>Production error discount</cbc:AllowanceChargeReason>
        <cbc:Amount currencyID="EUR">10.00</cbc:Amount>
        <cac:TaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>22</cbc:Percent>
                <cac:TaxScheme>
                        <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
        </cac:TaxCategory>
</cac:AllowanceCharge>
----

<1> ChargeIndicator = true to indicate a charge
<2> ChargeIndicator = false to indicate an allowance
<3> Base amount, to be used with the percentage to calculate the amount
<4> Charge percentage
<5> stem:["Amount" = "Base amount" times ("Percentage" div 100)]


.Example of a charge for packing costs
[source, xml, indent=0]
----
<cac:AllowanceCharge>
    <cbc:ChargeIndicator>true</cbc:ChargeIndicator>
    <cbc:AllowanceChargeReasonCode>ABL</cbc:AllowanceChargeReasonCode>
    <cbc:AllowanceChargeReason>Costi diimballaggio</cbc:AllowanceChargeReason>
    <cbc:MultiplierFactorNumeric>20</cbc:MultiplierFactorNumeric>
    <cbc:Amount currencyID="EUR">10.00</cbc:Amount>
    <cbc:BaseAmount currencyID="EUR">50.00</cbc:BaseAmount>
</cac:AllowanceCharge>
----

.Example of a discount for the whole order
[source, xml, indent=0]
----
<cac:AllowanceCharge>
    <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
    <cbc:AllowanceChargeReasonCode>41</cbc:AllowanceChargeReasonCode>
    <cbc:AllowanceChargeReason>Sconto</cbc:AllowanceChargeReason>
    <cbc:MultiplierFactorNumeric>2</cbc:MultiplierFactorNumeric>
    <cbc:Amount currencyID="EUR">2.00</cbc:Amount>
    <cbc:BaseAmount currencyID="EUR">100.00</cbc:BaseAmount>
</cac:AllowanceCharge>
----


== #Allowance and charges on price#

The following example shows an allowance of 10 EUR applied to the base amount price:

[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
        <cbc:ID>1</cbc:ID>
        <cbc:Quantity unitCode="C62" unitCodeListID="UNECERec20">20</cbc:Quantity>
        <cbc:LineExtensionAmount currencyID="EUR">1800.00</cbc:LineExtensionAmount>
        ...
        <cac:Price>
            <cbc:PriceAmount currencyID="EUR">90.00</cbc:PriceAmount>
            <cac:AllowanceCharge>
                <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
                <cbc:Amount currencyID="EUR">10.00</cbc:Amount>
                <cbc:BaseAmount currencyID="EUR">100.00</cbc:BaseAmount>
            </cac:AllowanceCharge>
        </cac:Price>
    </cac:LineItem>
</cac:OrderLine>
----

:leveloffset: +1

[[titolo]]
= #Allowance and charges on line level#

The following example shows an allowance applied to the whole order line:

[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
        <cbc:ID>1</cbc:ID>
        <cbc:Quantity unitCode="C62" unitCodeListID="UNECERec20">10</cbc:Quantity>
        <cbc:LineExtensionAmount currencyID="EUR">90.00</cbc:LineExtensionAmount>
        <cac:AllowanceCharge>
          <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
          <cbc:AllowanceChargeReason>Sconto sulla riga</cbc:AllowanceChargeReason>
          <cbc:MultiplierFactorNumeric>10</cbc:MultiplierFactorNumeric>
          <cbc:Amount currencyID="EUR">10.00</cbc:Amount>
          <cbc:BaseAmount currencyID="EUR">100.00</cbc:BaseAmount>
        </cac:AllowanceCharge>
        <cac:Price>
            <cbc:PriceAmount currencyID="EUR">10.00000</cbc:PriceAmount><!-- Opzionale -->
        </cac:Price>
    </cac:LineItem>
</cac:OrderLine>
----

:leveloffset: -1


:leveloffset: +1

[[titolo]]
= #Discounts#

For sale in the form of discounts, awards or allowance it is necessary to insert a distinct order line, paying attention to indicate the relative VAT exemption code.

In these cases, the discounts are out of scope VAT based on Art. 15 D.P.R. 633/72.

[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
        <cbc:ID>1</cbc:ID>
        <cbc:Quantity unitCode="C62" unitCodeListID="UNECERec20">10</cbc:Quantity>
        <cbc:LineExtensionAmount currencyID="EUR">0.00</cbc:LineExtensionAmount>
        <cac:AllowanceCharge>
            <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
            <cbc:AllowanceChargeReason>Sconto Merce</cbc:AllowanceChargeReason>
            <cbc:MultiplierFactorNumeric>100</cbc:MultiplierFactorNumeric>
            <cbc:Amount currencyID="EUR">90.00</cbc:Amount>
            <cbc:BaseAmount currencyID="EUR">90.00</cbc:Amount>
        </cac:AllowanceCharge>
        <cac:Price>
            <cbc:PriceAmount currencyID="EUR">9.00000</cbc:PriceAmount>
        </cac:Price>
        <cac:Item>
            <cbc:Description>1x12 PACCHI</cbc:Description>
            <cbc:Name>ARTICOLO MERCE</cbc:Name>
            <cac:ClassifiedTaxCategory>
                <cbc:ID>O</cbc:ID>
            </cac:ClassifiedTaxCategory>
        </cac:Item>
    </cac:LineItem>
</cac:OrderLine>
----

:leveloffset: -1


:leveloffset: +1

[[titolo]]
= #Free items#

To include free items in the order it is necessary to indicate them on a different line than paid items and also to indicate both the line amount and the price equal to 0 (zero).

.Example of an order line with 12 free packages of glucose test strips:
[source, xml, indent=0]
----
<cac:orderline>
    <cac:LineItem>
        <cbc:ID>1</cbc:ID>
        <cbc:Quantity unitCode="C62" unitCodeListID=”UNECERec20”>20</cbc:Quantity>
        <cbc:LineExtensionAmount currencyID="EUR">0</cbc:LineExtensionAmount>
        <cac:Price>
            <cbc:PriceAmount currencyID="EUR">0</cbc:PriceAmount>
            <cbc:BaseQuantity unitCode="C62" unitCodeListID=”UNECERec20”>1</cbc:BaseQuantity>
            <cac:AllowanceCharge>
                <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
                <cbc:Amount currencyID="EUR">5.00</cbc:Amount>
                <cbc:BaseAmount currencyID="EUR">5.00</cbc:BaseAmount>
            </cac:AllowanceCharge>
        </cac:Price>
        <cac:Item>
            <cbc:Description>1x12 pacchi</cbc:Description>
            <cbc:Name>Striscie per glucosio</cbc:Name>
            <cac:SellersItemIdentification>
               <cbc:ID>79847-E</cbc:ID>
            </cac:SellersItemIdentification>
            <cac:ClassifiedTaxCategory>
                <cbc:ID schemeID="UNCL5305">S</cbc:ID>
                <cbc:Percent>22</cbc:Percent></cac:Item>
                <cac:TaxScheme>
                     <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:ClassifiedTaxCategory>
        </cac:Item>
    </cac:LineItem>
</cac:OrderLine>
----

:leveloffset: -1
