[[attachements]]
= Attachments

Non-XML documents can be sent as attachments to the PEPPOL BIS Order.
This could be drawings or time sheets or other documents relevant for the order.
The attachment can either be sent as a binary object encoded in Base64 embedded in the message or as a URI to an external address as a link.

NOTE: It is recommended to send attachments as embedded, binary objects and not as external references.


#Valid values (i.e. compatible with con NSO) are listed and highlighted in the codelist link:../../../../../../xml/ITA/peppol-bis-3/codelist/MimeCode.html[Mime code].#


.Example of attachment as an embedded, binary object
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-01.xml[tags=attachment]
----
<1> It is recommended to use element `cac:AdditionalDocumentReference/cbc:DocumentType` to send a short description of the content of the attachment.
<2> File name and extension should be sent in the filename attribute to the `cbc:EmbeddedDocumentBinaryObject` element.  


IMPORTANT: Attachments should be used for additional information and not as order copies.


#In the event of goods and services orders that to be processed require necessarily the presence of certain documents (ex. Patient Cars), it is necessary that these documents need to be trasmitted through NSO as an attached PDF to the electronic order.#

#Where the information contained in the attachments may involve privacy issues, these attachments can be in encrypted form or it is possible to use the element *cac:ExternalReference*, which access can be limited to appropriate profiling.#

