[[attachements]]
= Attachments

Non-XML documents can be sent as attachments to the PEPPOL BIS Order.
This could be drawings or time sheets or other documents relevant for the order.
The attachment can either be sent as a binary object encoded in Base64 embedded in the message or as a URI to an external address as a link.

NOTE: It is recommended to send attachments as embedded, binary objects and not as external references.


#Valid values (i.e. compatible with con NSO) are listed and highlighted in the codelist *Mime code (IANA Subset)*.#


.Example of attachment as an embedded, binary object
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-01.xml[tags=attachment]
----
<1> It is recommended to use element `cac:AdditionalDocumentReference/cbc:DocumentType` to send a short description of the content of the attachment.
<2> File name and extension should be sent in the filename attribute to the `cbc:EmbeddedDocumentBinaryObject` element.  


IMPORTANT: Attachments should be used for additional information and not as order copies.


#Nel caso di ordini di beni o servizi che per essere evasi richiedono obbligatoriamente la presenza di documenti (es. Scheda Paziente), è necessario che tali documenti siano trasmessi tramite NSO come allegato PDF all’ordine elettronico.#

#Ove le informazioni contenute negli allegati possano comportare problemi legati alla privacy, i medesimi allegati possono essere in formato cifrato oppure è possibile ricorrere all’uso di riferimenti esterni (elemento *cac:ExternalReference*), il cui accesso può essere limitato utlizzando idonea profilatura.#

