[[confezionamento]]
= #Confezionamento#

Per fornire informazioni sul confezionamento è possibile usare due diverse modalità a seconda di come è stato effettuato l’ordine, e quindi se l’articolo corrisponde alla singola unità "C62" o alla confezione "XPK". +

Se l’articolo ordinato è una confezione è importante indicarne l’unità di misura corretta.

Nella tabella seguente si forniscono chiarimenti per aggiungere informazioni sulle singole unità all’interno della confezione e viceversa, quando l’articolo coincide con l’unità base, per fornire informazioni sul confezionamento.


|===
|**Tipo di informazione** | **Descrizione** 
|PackSizeNumeric |	Indica il numero di articoli contenuti in un confezionamento primario (ad esempio, quante pasticche o unità “C62” una confezione “XPK”)|PackQuantity
|Indica il numero di sotto-unità contenute in un confezionamento secondario (ad esempio, quante scatole o confezioni “XPK” sono presenti in un imballaggio “XBX”) |	Indica il numero di sotto-unità contenute in un confezionamento secondario (ad esempio, quante scatole o confezioni “XPK” sono presenti in un imballaggio “XBX”)
|===


Seguono due esempi significativi.

== Caso 1: Articolo ordinato per singola unità

Esempio in cui l’articolo viene ordinato per singola unità e non a confezione, ed indicazione del numero di pezzi per confezione primaria:

[source, xml]

<cac:DespatchLine>
    <!-- 5000 guanti -->
    <cbc:Quantity unitCode="C62">5000</cbc:Quantity>
    <cac:Item>
        <cbc:Name>Guanti</cbc:Name>
        <cac:SellersItemIdentification>
            <!-- O altro identificativo (es. Standard) -->
            <cbc:ID>XYZ</cbc:ID>
        </cac:SellersItemIdentification>
        <cac:AdditionalItemProperty>
            <!-- Una confezione contiene 500 pezzi -->
            <cbc:Name>PackSizeNumeric</cbc:Name>
            <cbc:Value>500</cbc:Value>
        <cac:AdditionalItemProperty>
        <cac:AdditionalItemProperty>
            <cbc:Name>PackIdentification</cbc:Name>
            <!-- Codice confezione -->
            <cbc:Value>XYZ500</cbc:Value>
        </cac:AdditionalItemProperty>
    </cac:Item>
</cac:DespatchLine>



== Caso 2: Articolo ordinato a confezione

Esempio in cui l’articolo viene ordinato a confezione:

[source, xml]

<cac:DespatchLine>
    <!--10 confezioni di guanti -->
    <cbc:Quantity unitCode="XPK">10</cbc:Quantity>
    <cac:Item>
        <cbc:Name>CONFEZIONE GUANTI</cbc:Name>
        <cac:SellersItemIdentification>
            <!-- O altro identificativo (es. Standard) -->
            <cbc:ID>XYZ500</cbc:ID>
        </cac:SellersItemIdentification>
        <cac:AdditionalItemProperty>
            <!-- Una articolo (confezione) contiene 500 pezzi -->
            <cbc:Name>PackQuantity</cbc:Name>
            <cbc:Value>500</cbc:Value>
        <cac:AdditionalItemProperty>
        <cac:AdditionalItemProperty>
            <cbc:Name>UnitIdentification</cbc:Name>
            <!-- Codice unità base -->
            <cbc:Value>XYZ</cbc:Value>
        </cac:AdditionalItemProperty>
    </cac:Item>
</cac:DespatchLine>

