
[[partitamerce]]
= Specifiche Partita Merce
#Per fornire ulteriori informazioni sulla partita merce è possibile utilizzare l'aggregato informativo cac:Shipment/cac:GoodsItem a livello di riga, come parte delle informazioni sulla spedizione.#

#In particolare è possibile specificare le temperature impostate e raccomandate col descritto nel paragrafo seguente.#

[[temperatura]]
== Temperatura
#Per indicare la temperatura impostata e raccomandata per talune merci o la temperatura minima/massima tollerata è possibile specificarlo sempre nel dettaglio della spedizione come nell’esempio seguente:#

.Esempio settaggi temperatura:
[source, xml, indent=0]
----
<cac:DespatchLine>
	<cac:Shipment>
		<cac:GoodsItem>
			<cac:Temperature>
				<cbc:AttributeID>Recommended</cbc:AttributeID>
				<cbc:Measure unitCode="CEL">-20</cbc:Measure> 
			</cac:Temperature>
			<cac:MinimumTemperature>
				<cbc:AttributeID>Allowable</cbc:AttributeID>
				<cbc:Measure unitCode="FAH">-20</cbc:Measure> 
			</cac:MinimumTemperature>
			<cac:MaximumTemperature>
				<cbc:AttributeID>Allowable</cbc:AttributeID>
				<cbc:Measure unitCode="FAH">15</cbc:Measure> 
			</cac:MaximumTemperature>
		</cac:GoodsItem>
	</cac:Shipment>
</cac:DespatchLine>
----

#L’esempio denota l’uso delle unità di misura Celsius (CEL) e Fahrenheit (FAH). L’elemento AttributeID è obbligatorio ma può essere ignorato valorizzandolo con NA, tuttavia in alcuni casi può migliorare la comprensione della misura fornita (es. Recommended, Allowable, Alert).#

NOTA: #Le misure (***Measure) sono obbligatoriamente espresse secondo la codifica {UNRec20} e non è richiesto qualificarle con ulteriori attributi.#

