
= #Social security contribution (Domestic CIUS)#

The social security contribution is treated as a charge at the document level using *cac:AllowanceCharge* (BG-21 Document level charge). +

The taxable base amount of the contribution is entered in *cbc:BaseAmount* (BT-100 Document level charge base amount). +
The rate is entered in *cbc:MultiplierFactorNumeric* (BT-101 Document level charge percentage), and the contribution amount is entered in *cbc:Amount* (BT-99 Document level charge amount). +

The information regarding the social security contribution type (FPA 2.1.1.7.1), withholding (FPA 2.1.1.7.6), and nature (FPA 2.1.1.7.7) are concatenated with the "#" symbol in *cbc:AllowanceChargeReason* (BT-104 Document level charge reason). 

The *cbc:AllowanceChargeReasonCode* (BT-105 Document level charge reason code) is entered as "ZZZ". +

VAT information is filled in according to the need. +

.Example of social security contribution charge on a taxable service
The example refers to a service of 1,000 euros subject to ordinary VAT with a contribution rate of 4%. 

[source, xml, indent=0]
----
<cac:AllowanceCharge>
  <cbc:ChargeIndicator>true</cbc:ChargeIndicator>
  <cbc:AllowanceChargeReasonCode>ZZZ</cbc:AllowanceChargeReasonCode>
  <cbc:AllowanceChargeReason>TC02#SI#</cbc:AllowanceChargeReason>
  <cbc:MultiplierFactorNumeric>4</cbc:MultiplierFactorNumeric>
  <cbc:Amount currencyID="EUR">40.00</cbc:Amount>
  <cbc:BaseAmount currencyID="EUR">1000.00</cbc:BaseAmount>
  <cac:TaxCategory>
    <cbc:ID>S</cbc:ID>
    <cbc:Percent>22</cbc:Percent>
    <cac:TaxScheme>
      <cbc:ID>VAT</cbc:ID>
    </cac:TaxScheme>
  </cac:TaxCategory>
</cac:AllowanceCharge>
----

.Example of social security contribution charge on a service not subject to VAT
The example refers to a service of 1,000 euros not subject to VAT with a contribution rate of 4%. 

[source, xml, indent=0]
----
<cac:AllowanceCharge>
  <cbc:ChargeIndicator>true</cbc:ChargeIndicator>
  <cbc:AllowanceChargeReasonCode>ZZZ</cbc:AllowanceChargeReasonCode>
  <cbc:AllowanceChargeReason>TC04#SI#N2.2</cbc:AllowanceChargeReason>
  <cbc:MultiplierFactorNumeric>4</cbc:MultiplierFactorNumeric>
  <cbc:Amount currencyID="EUR">40.00</cbc:Amount>
  <cbc:BaseAmount currencyID="EUR">1000.00</cbc:BaseAmount>
  <cac:TaxCategory>
    <cbc:ID>E</cbc:ID>
    <cac:TaxScheme>
      <cbc:ID>VAT</cbc:ID>
    </cac:TaxScheme>
  </cac:TaxCategory>
</cac:AllowanceCharge>
----