
= Rivalsa Cassa previdenziale

Gli enti previdenziali (o enti pubblici previdenziali), nell'ordinamento giuridico italiano, sono le istituzioni previste ai sensi dell'art. 38 della Costituzione che gestiscono la previdenza e l'assistenza previste dall'Assicurazione Generale Obbligatoria o sue forme sostitutive secondo il modello previdenziale corporativo.

Ogni ente gestisce a livello nazionale una cassa di previdenza sociale obbligatoria codificata secondo la specifica della FatturaPA del Sistema d'Interscambio (SDI) dell'Agenzia delle Entrate.

La rivalsa può essere fatta per una o più casse previdenziali, in base alle voci di fattura imponibili, aggiungendo una riga fattura per ogni cassa previdenziale.

.Esempio UBL di rivalsa di due casse previdenziali
L'esempio riportato è relativo alla fattura emessa da un professionista in regime ordinario appartenente sia alla Cassa dei Commercialisti che alla gestione separata INPS, nonchè soggetto a ritenuta d'acconto.
[source, xml, indent=0]
----
include::../{snippet-dir}/Esempio-Fattura-Professionista-Ordinario-con-Cassa-e-Ritenuta.xml[tags=cassa]
----
<1> L'importo contributo cassa.
<2> La denominazione riga fattura dedicata alla cassa di previdenza (Deve essere sempre valorizzato con 'IT:CASSA').
<3> Il tipo Cassa espresso mediante un 'cac:AdditionalItemProperty/cbc:Name' valorizzato con 'IT:CASSA:TIPO' e il codice tipo cassa in 'cac:AdditionalItemProperty/cbc:Value' secondo la codifica disponibile nella FatturaPA.
<4> L'aliquota Cassa espressa mediante un 'cac:AdditionalItemProperty/cbc:Name' valorizzato con 'IT:CASSA:ALIQUOTA' e l'aliquota in 'cac:AdditionalItemProperty/cbc:Value'.
<5> L'imponibile Cassa espresso mediante un 'cac:AdditionalItemProperty/cbc:Name' valorizzato con 'IT:CASSA:IMPONIBILE' e l'importo in 'cac:AdditionalItemProperty/cbc:Value'.
<6> Il riferimento amministrativo espresso mediante un 'cac:AdditionalItemProperty/cbc:Name' valorizzato con 'IT:CASSA:RIFAMM' e il testo in 'cac:AdditionalItemProperty/cbc:Value'.
<7> L'aliquota della ritenuta espressa mediante un 'cac:AdditionalItemProperty/cbc:Name' valorizzato con 'IT:RITENUTA:ALIQUOTA' e l'aliquota in 'cac:AdditionalItemProperty/cbc:Value'.
<8> Il tipo della ritenuta relativa alla Cassa espresso mediante un 'cac:AdditionalItemProperty/cbc:Name' valorizzato con 'IT:RITENUTA:TIPO' e il codice tipo ritenuta in 'cac:AdditionalItemProperty/cbc:Value' secondo la codifica disponibile nella FatturaPA.
<9> La causale della ritenuta relativa alla Cassa espressa mediante un 'cac:AdditionalItemProperty/cbc:Name' valorizzato con 'IT:RITENUTA:CAUSALE' e il codice tipo ritenuta in 'cac:AdditionalItemProperty/cbc:Value' secondo la codifica disponibile nella FatturaPA.
