= #Split payment (Domestic CIUS)#

Split payment is a special regime that establishes that the VAT debtor is the purchaser/client instead of, as normally happens, the seller/provider.

To support this particular case, the element *cac:TaxCategory/cbc:ID* (BT-118 VAT Category code) is set using the TaxCategory 'B' (Transferred VAT) according to the UN/ECE 5305 coding.

[NOTE]
====
The split VAT amount must be included in the value entered in cbc:PrepaidAmount. It should be noted that cbc:PrepaidAmount is not supported in FatturaPA but is used to correctly populate the cbc:PayableAmount (BT-115 Amount due for payment) which is mandatory for EN 16931. 
====

.Example of Split Payment
The example provided relates to an invoice issued to a Public Administration subject to split payment.

[source, xml, indent=0]
----
<cac:TaxTotal>
  <cbc:TaxAmount currencyID="EUR">22.00</cbc:TaxAmount>
  <cac:TaxSubtotal>
    <cbc:TaxableAmount currencyID="EUR">100.00</cbc:TaxableAmount>
    <cbc:TaxAmount currencyID="EUR">22.00</cbc:TaxAmount>
    <cac:TaxCategory>
      <cbc:ID>B</cbc:ID>
      <cbc:Percent>22</cbc:Percent>
    </cac:TaxCategory>
    <cac:TaxScheme>
      <cbc:ID>VAT</cbc:ID>
    </cac:TaxScheme>
  </cac:TaxSubtotal>
</cac:TaxTotal>
<cac:LegalMonetaryTotal>
  <cbc:TaxExclusiveAmount currencyID="EUR">100.00</cbc:TaxExclusiveAmount>
  <cbc:TaxInclusiveAmount currencyID="EUR">122.00</cbc:TaxInclusiveAmount>
  <cbc:PrepaidAmount currencyID="EUR">22.00</cbc:PrepaidAmount>
  <cbc:PayableAmount currencyID="EUR">100.00</cbc:PayableAmount>
</cac:LegalMonetaryTotal>
----

= Indication of down payment in the final invoice
The indication of the down payment in the final invoice is done by inserting a specific invoice line with a negative amount. Therefore, the element *cbc:InvoicedQuantity* (BT-129 Invoiced Quantity) must be set to “-1.00”. 

The down payment line has the same nature as the service to which the final invoice refers.

.Example of indicating a down payment of 100 euros in the final invoice 

[source, xml, indent=0]
----
<ubl:Invoice> 
... 
<cac:InvoiceLine> 
          <cbc:ID>2</cbc:ID> 
          <cbc:InvoicedQuantity unitCode="C62">-1.00</cbc:InvoicedQuantity > 
          <cbc:LineExtensionAmount currencyID="EUR">-100.00</cbc:Amount> 
          <cac:Item> 
                    <cbc:Name>Acconto su prestazione</cbc:ID> 
                    <cac:ClassifiedTaxCategory> 
                              <cbc:ID>S</cbc:ID> 
                              <cbc:Percent>22</cbc:Percent> 
                              <cac:TaxScheme> 
                                        <cbc:ID>VAT</cbc:ID> 
                              </cac:TaxScheme> 
                    </cac:ClassifiedTaxCategory> 
          </cac:Item> 
          <cac:Price > 
                    <cbc:PriceAmount currencyID="EUR">100.00</cbc:PriceAmount> 
                    <cbc:BaseQuantity unitCode="C62">1</cbc:BaseQuantity> 
                    <cac:AllowanceCharge> 
                               <cbc:ChargeIndicator>false</cbc:ChargeIndicator> 
                               <cbc:Amount currencyID="EUR">0.00</cbc:Amount> 
                               <cbc:BaseAmount currencyID="EUR">100.00</cbc:BaseAmount> 
                    </cac:AllowanceCharge> 
          </cac:Price> 
</cac:InvoiceLine> 
----