= #Stamp duty (Domestic CIUS)#

The indication of the virtual stamp duty is applied both on the invoice and on the credit note as a charge at the document header level through the use of the *cac:AllowanceCharge* structure (BG-21 Document level charge) by specifying: 

* the element cbc:ChargeIndicator set to “true”;
* the element cbc:AllowanceChargeReasonCode (BT-105 Document level charge reason code) set to “SAE”;
* the element cbc:AllowanceChargeReason (BT-104 Document level charge reason) with the string “BOLLO”;
* the element cbc:Amount (BT-99 Document level charge amount) with the value 0;
* the element cac:TaxCategory/cbc:ID (BT-95 Document level charge VAT category code) set to Z (zero).

If the intention is not to charge the stamp duty back, the insertion of a specific line related to it is not required.

.Example of an invoice for an exempt service worth 100 euros without stamp duty charge.
[source, xml, indent=0]
----
<ubl:Invoice>
...
<cac:AllowanceCharge>
          <cbc:ChargeIndicator>true</cbc:ChargeIndicator>
          <cbc:AllowanceChargeReasonCode>SAE</cbc:AllowanceChargeReasonCode>
          <cbc:AllowanceChargeReason>BOLLO</cbc:AllowanceChargeReason>
          <cbc:Amount currencyID="EUR">0</cbc:Amount>
          <cac:TaxCategory>
                    <cbc:ID>Z</cbc:ID>
                    <cbc:Percent>0</cbc:Percent>
                    <cac:TaxScheme>
                              <cbc:ID>VAT</cbc:ID>
                    </cac:TaxScheme>
          </cac:TaxCategory>
</cac:AllowanceCharge>
<cac:TaxTotal>
            <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount>
            <cac:TaxSubtotal>
                      <cbc:TaxableAmount currencyID="EUR">100.00</cbc:TaxableAmount>
                      <cbc:TaxAmount currencyID="EUR">0</cbc:TaxAmount>
                      <cac:TaxCategory>
                              <cbc:ID>E</cbc:ID>
                              <cbc:Percent>0</cbc:Percent>
                              <cbc:TaxExemptionReasonCode>vatex-eu-132</cbc:TaxExemptionReasonCode>
                              <cbc:TaxExemptionReason>N4</cbc:TaxExemptionReason>
                              <cac:TaxScheme>
                                        <cbc:ID>VAT</cbc:ID>
                              </cac:TaxScheme>
              	</cac:TaxCategory>
            </cac:TaxSubtotal>
            <cac:TaxSubtotal>
                      <cbc:TaxableAmount currencyID="EUR">0.00</cbc:TaxableAmount>
                      <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount>
                      <cac:TaxCategory>
                                <cbc:ID>Z</cbc:ID>
                                <cbc:Percent>0</cbc:Percent>
                                <cac:TaxScheme>
                                        <cbc:ID>VAT</cbc:ID>
                                </cac:TaxScheme>
                      </cac:TaxCategory>
            </cac:TaxSubtotal>
</cac:TaxTotal>
<cac:LegalMonetaryTotal>
        <cbc:LineExtensionAmount currencyID="EUR">100.00</cbc:LineExtensionAmount>
            <cbc:TaxExclusiveAmount currencyID="EUR">100.00</cbc:TaxExclusiveAmount>
            <cbc:TaxInclusiveAmount currencyID="EUR">100.00</cbc:TaxInclusiveAmount>
            <cbc:ChargeTotalAmount currencyID="EUR">0.00</cbc:ChargeTotalAmount>
            <cbc:PayableAmount currencyID="EUR">100.00</cbc:PayableAmount>
</cac:LegalMonetaryTotal>
----

== Stamp Duty charging

If the seller intends to charge the stamp duty to the buyer, a dedicated invoice line must be included, containing the following:

* the element cac:Item/cbc:Description (BT-154 Item description) set to "Rivalsa Bollo"; 
* the elements cac:Price/cbc:PriceAmount (BT-146 Item net price) and cac:AllowanceCharge/cbc:BaseAmount (BT-148 Item gross price) set to:
** 2.00, in the case of an invoice (refer to examples Invoice No. 04_FT, 14_FT, 17_FT, and 30_FT);
** -2.00, in the case of a credit note (refer to example Credit Note No. 04_NC).

The charging line must reflect the same nature (in terms of tax treatment) as the service to which the charging applies. 

.Example of an invoice for an exempt service worth 100 euros with stamp duty charge.
[source, xml, indent=0]
----
<ubl:Invoice> 
... 
<cac:AllowanceCharge> 
          <cbc:ChargeIndicator>true</cbc:ChargeIndicator> 
          <cbc:AllowanceChargeReasonCode>SAE</cbc:AllowanceChargeReasonCode> 
          <cbc:AllowanceChargeReason>BOLLO</cbc:AllowanceChargeReason> 
          <cbc:Amount currencyID="EUR">0.00</cbc:Amount> 
          <cac:TaxCategory> 
                    <cbc:ID>Z</cbc:ID> 
                    <cbc:Percent>0</cbc:Percent> 
                    <cac:TaxScheme> 
                              <cbc:ID>VAT</cbc:ID> 
                    </cac:TaxScheme> 
          </cac:TaxCategory> 
</cac:AllowanceCharge> 
<cac:TaxTotal> 
            <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount> 
            <cac:TaxSubtotal> 
                      <cbc:TaxableAmount currencyID="EUR">102.00</cbc:TaxableAmount> 
                      <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount> 
                      <cac:TaxCategory> 
                                <cbc:ID>E</cbc:ID> 
                                <cbc:Percent>0</cbc:Percent> 
                                <cbc:TaxExemptionReasonCode>vatex-eu-132<cbc:TaxExemptionReasonCode> 
                                <cbc:TaxExemptionReason>N4<cbc:TaxExemptionReason> 
                                <cac:TaxScheme> 
                                        <cbc:ID>VAT</cbc:ID> 
                                </cac:TaxScheme> 
                      </cac:TaxCategory> 
            </cac:TaxSubtotal> 
            <cac:TaxSubtotal> 
                      <cbc:TaxableAmount currencyID="EUR">0.00</cbc:TaxableAmount> 
                      <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount> 
                      <cac:TaxCategory> 
                                <cbc:ID>Z</cbc:ID> 
                                <cbc:Percent>0</cbc:Percent> 
                                <cac:TaxScheme> 
                                        <cbc:ID>VAT</cbc:ID> 
                                </cac:TaxScheme> 
                      </cac:TaxCategory> 
            </cac:TaxSubtotal> 
</cac:TaxTotal> 
<cac:LegalMonetaryTotal> 
            <cbc:LineExtensionAmount currencyID="EUR">102.00</cbc:LineExtensionAmount> 
            <cbc:TaxExclusiveAmount currencyID="EUR">102.00</cbc:TaxExclusiveAmount> 
            <cbc:TaxInclusiveAmount currencyID="EUR">102.00</cbc:TaxInclusiveAmount> 
            <cbc:ChargeTotalAmount currencyID="EUR">0.00</cbc:ChargeTotalAmount> 
            <cbc:PayableAmount currencyID="EUR">102.00</cbc:PayableAmount> 
</cac:LegalMonetaryTotal> 
[…] 
<cac:InvoiceLine> 
            <cbc:ID>2</cbc:ID> 
            <cbc:InvoicedQuantity unitCode="C62">1.00</cbc:InvoicedQuantity> 
            <cbc:LineExtensionAmount currencyID="EUR">2.00</cbc:LineExtensionAmount> 
            <cac:Item> 
                       <cbc:Name>Rivalsa bollo</cbc:Name> 
                       <cac:ClassifiedTaxCategory> 
                                  <cbc:ID>E</cbc:ID> 
                                  <cbc:Percent>0</cbc:Percent> 
                                  <cac:TaxScheme> 
                                              <cbc:ID>VAT</cbc:ID> 
                                  </cac:TaxScheme> 
                       </cac:ClassifiedTaxCategory> 
                       <cac:AdditionalItemProperty> 
                                  <cbc:Name>NATURA</cbc:Name> 
                                  <cbc:Value>N4</cbc:Value> 
                       </cac:AdditionalItemProperty> 
            </cac:Item> 
            <cac:Price> 
                       <cbc:PriceAmount currencyID="EUR">2.00</cbc:PriceAmount> 
                       <cbc:BaseQuantity unitCode="C62">1.00</cbc:BaseQuantity> 
                       <cac:AllowanceCharge> 
                                  <cbc:ChargeIndicator>false</cbc:ChargeIndicator> 
                                  <cbc:Amount currencyID="EUR">0.00</cbc:Amount> 
                                  <cbc:BaseAmount currencyID="EUR">2.00</cbc:BaseAmount> 
                       </cac:AllowanceCharge> 
           </cac:Price> 
</cac:InvoiceLine> 
----

.Example of a credit note for an exempt service worth 100 euros with stamp duty charge. 
[source, xml, indent=0]
----
<ubl:CreditNote> 
... 
<cac:AllowanceCharge> 
          <cbc:ChargeIndicator>true</cbc:ChargeIndicator> 
          <cbc:AllowanceChargeReasonCode>SAE</cbc:AllowanceChargeReasonCode> 
          <cbc:AllowanceChargeReason>BOLLO</cbc:AllowanceChargeReason> 
          <cbc:Amount currencyID="EUR">0.00</cbc:Amount> 
          <cac:TaxCategory> 
                    <cbc:ID>Z</cbc:ID> 
                    <cbc:Percent>0</cbc:Percent> 
                    <cac:TaxScheme> 
                              <cbc:ID>VAT</cbc:ID> 
                    </cac:TaxScheme> 
          </cac:TaxCategory> 
</cac:AllowanceCharge> 
<cac:TaxTotal> 
            <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount> 
            <cac:TaxSubtotal> 
                      <cbc:TaxableAmount currencyID="EUR">98.00</cbc:TaxableAmount> 
                      <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount> 
                      <cac:TaxCategory> 
                                <cbc:ID>E</cbc:ID> 
                                <cbc:Percent>0</cbc:Percent> 
                                <cbc:TaxExemptionReasonCode>vatex-eu-132<cbc:TaxExemptionReasonCode> 
                                <cbc:TaxExemptionReason>N4<cbc:TaxExemptionReason> 
                                <cac:TaxScheme> 
                                        <cbc:ID>VAT</cbc:ID> 
                                </cac:TaxScheme> 
                      </cac:TaxCategory> 
            </cac:TaxSubtotal> 
            <cac:TaxSubtotal> 
                      <cbc:TaxableAmount currencyID="EUR">0.00</cbc:TaxableAmount> 
                      <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount> 
                      <cac:TaxCategory> 
                                <cbc:ID>Z</cbc:ID> 
                                <cbc:Percent>0</cbc:Percent> 
                                <cac:TaxScheme> 
                                        <cbc:ID>VAT</cbc:ID> 
                                </cac:TaxScheme> 
                      </cac:TaxCategory> 
            </cac:TaxSubtotal> 
</cac:TaxTotal> 
<cac:LegalMonetaryTotal> 
            <cbc:LineExtensionAmount currencyID="EUR">98.00</cbc:LineExtensionAmount> 
            <cbc:TaxExclusiveAmount currencyID="EUR">98.00</cbc:TaxExclusiveAmount> 
            <cbc:TaxInclusiveAmount currencyID="EUR">98.00</cbc:TaxInclusiveAmount> 
            <cbc:ChargeTotalAmount currencyID="EUR">0.00</cbc:ChargeTotalAmount> 
            <cbc:PayableAmount currencyID="EUR">98.00</cbc:PayableAmount> 
</cac:LegalMonetaryTotal> 
[…] 
<cac:CreditNoteLine> 
            <cbc:ID>2</cbc:ID> 
            <cbc:CreditedQuantity unitCode="C62">-1.00</cbc:CreditedQuantity> 
            <cbc:LineExtensionAmount currencyID="EUR">-2.00</cbc:LineExtensionAmount> 
            <cac:Item> 
                       <cbc:Name>Rivalsa bollo</cbc:Name> 
                       <cac:ClassifiedTaxCategory> 
                                  <cbc:ID>E</cbc:ID> 
                                  <cbc:Percent>0</cbc:Percent> 
                                  <cac:TaxScheme> 
                                              <cbc:ID>VAT</cbc:ID> 
                                  </cac:TaxScheme> 
                       </cac:ClassifiedTaxCategory> 
                       <cac:AdditionalItemProperty> 
                                  <cbc:Name>NATURA</cbc:Name> 
                                  <cbc:Value>N4</cbc:Value> 
                       </cac:AdditionalItemProperty> 
            </cac:Item> 
            <cac:Price> 
                       <cbc:PriceAmount currencyID="EUR">2.00</cbc:PriceAmount> 
                       <cbc:BaseQuantity unitCode="C62">1.00</cbc:BaseQuantity> 
                       <cac:AllowanceCharge> 
                                  <cbc:ChargeIndicator>false</cbc:ChargeIndicator> 
                                  <cbc:Amount currencyID="EUR">0.00</cbc:Amount> 
                                  <cbc:BaseAmount currencyID="EUR">2.00</cbc:BaseAmount> 
                       </cac:AllowanceCharge> 
           </cac:Price> 
</cac:CreditNoteLine> 
----

== Stamp Duty Refund
If the seller, upon issuance of a credit note, wishes to refund the stamp duty previously charged in an invoice, a dedicated credit note line must be included, containing the following:

* the element cac:Item/cbc:Description (BT-154 Item description) set to "Rimborso Bollo"; 
* the elements cac:Price/cbc:PriceAmount (BT-146 Item net price) and cac:AllowanceCharge/cbc:BaseAmount (BT-148 Item gross price) both set to 2.00 (refer to example Credit Note No. 05_NC).

The refund line must reflect the same nature (in terms of tax treatment) as the service to which the original stamp duty charging was applied. 

.Example of a credit note for an exempt service worth 100 euros with stamp duty refund.
[source, xml, indent=0]
----
<ubl:CreditNote> 
... 
<cac:AllowanceCharge> 
          <cbc:ChargeIndicator>true</cbc:ChargeIndicator> 
          <cbc:AllowanceChargeReasonCode>SAE</cbc:AllowanceChargeReasonCode> 
          <cbc:AllowanceChargeReason>BOLLO</cbc:AllowanceChargeReason> 
          <cbc:Amount currencyID="EUR">0.00</cbc:Amount> 
          <cac:TaxCategory> 
                    <cbc:ID>Z</cbc:ID> 
                    <cbc:Percent>0</cbc:Percent> 
                    <cac:TaxScheme> 
                              <cbc:ID>VAT</cbc:ID> 
                    </cac:TaxScheme> 
          </cac:TaxCategory> 
</cac:AllowanceCharge> 
<cac:TaxTotal> 
            <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount> 
            <cac:TaxSubtotal> 
                      <cbc:TaxableAmount currencyID="EUR">102.00</cbc:TaxableAmount> 
                      <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount> 
                      <cac:TaxCategory> 
                                <cbc:ID>E</cbc:ID> 
                                <cbc:Percent>0</cbc:Percent> 
                                <cbc:TaxExemptionReasonCode>vatex-eu-132<cbc:TaxExemptionReasonCode> 
                                <cbc:TaxExemptionReason>N4<cbc:TaxExemptionReason> 
                                <cac:TaxScheme> 
                                        <cbc:ID>VAT</cbc:ID> 
                                </cac:TaxScheme> 
                      </cac:TaxCategory> 
            </cac:TaxSubtotal> 
            <cac:TaxSubtotal> 
                      <cbc:TaxableAmount currencyID="EUR">0.00</cbc:TaxableAmount> 
                      <cbc:TaxAmount currencyID="EUR">0.00</cbc:TaxAmount> 
                      <cac:TaxCategory> 
                                <cbc:ID>Z</cbc:ID> 
                                <cbc:Percent>0</cbc:Percent> 
                                <cac:TaxScheme> 
                                        <cbc:ID>VAT</cbc:ID> 
                                </cac:TaxScheme> 
                      </cac:TaxCategory> 
            </cac:TaxSubtotal> 
</cac:TaxTotal> 
<cac:LegalMonetaryTotal> 
            <cbc:LineExtensionAmount currencyID="EUR">102.00</cbc:LineExtensionAmount> 
            <cbc:TaxExclusiveAmount currencyID="EUR">102.00</cbc:TaxExclusiveAmount> 
            <cbc:TaxInclusiveAmount currencyID="EUR">102.00</cbc:TaxInclusiveAmount> 
            <cbc:ChargeTotalAmount currencyID="EUR">0.00</cbc:ChargeTotalAmount> 
            <cbc:PayableAmount currencyID="EUR">102.00</cbc:PayableAmount> 
</cac:LegalMonetaryTotal> 
[…] 
<cac:CreditNoteLine> 
            <cbc:ID>2</cbc:ID> 
            <cbc:CreditedQuantity unitCode="C62">1.00</cbc:CreditedQuantity> 
            <cbc:LineExtensionAmount currencyID="EUR">2.00</cbc:LineExtensionAmount> 
            <cac:Item> 
                       <cbc:Name>Restituzione bollo applicato su Fattura precedente</cbc:Name> 
                       <cac:ClassifiedTaxCategory> 
                                  <cbc:ID>E</cbc:ID> 
                                  <cbc:Percent>0</cbc:Percent> 
                                  <cac:TaxScheme> 
                                              <cbc:ID>VAT</cbc:ID> 
                                  </cac:TaxScheme> 
                       </cac:ClassifiedTaxCategory> 
                       <cac:AdditionalItemProperty> 
                                 <cbc:Name>NATURA</cbc:Name> 
                                  <cbc:Value>N4</cbc:Value> 
                       </cac:AdditionalItemProperty> 
            </cac:Item> 
            <cac:Price> 
                       <cbc:PriceAmount currencyID="EUR">2.00</cbc:PriceAmount> 
                       <cbc:BaseQuantity unitCode="C62">1.00</cbc:BaseQuantity> 
                       <cac:AllowanceCharge> 
                                  <cbc:ChargeIndicator>false</cbc:ChargeIndicator> 
                                  <cbc:Amount currencyID="EUR">0.00</cbc:Amount> 
                                  <cbc:BaseAmount currencyID="EUR">2.00</cbc:BaseAmount> 
                       </cac:AllowanceCharge> 
           </cac:Price> 
</cac:CreditNoteLine> 
----