= #Withholding Tax# (extension)

The Withholding Tax section highlights: +

* an Irpef withholding (for individuals’ income) or Ires withholding (for legal entities: organizations) applied on the taxable total of the invoice sent to the Client by the Seller, who acts as the withholding agent;
* a social security contribution withholding applied on the taxable total of the invoice sent to the Client by the Seller, who will be responsible for the subsequent payment to the relevant social security authority.

Both types of withholding tax can be included in the same invoice.

The *type of withholding* applied must be indicated in the document header within a separate UBL extension. If no type of withholding is indicated but at least one withholding has been specified, the default value will be RT01 for individuals and RT02 for legal entities.

The use of this UBL extension is recommended to explicitly specify the type of withholding(s) where applied. +

[NOTE]
====
The total amount of withholdings must be included in the value inserted in cbc:PrepaidAmount. Please note that cbc:PrepaidAmount is not supported in FatturaPA but is used to correctly fill the data cbc:PayableAmount (BT-115 Amount due for payment), which is mandatory for EN 16931.
====

The *ExtensionURI* must contain the prefix 'urn:fdc:agid.gov.it:fatturapa:TipoRitenuta' and the occurrence number of the withholding '::n'. 

.UBL example of a double withholding tax in the header 
[source, xml, indent=0]
----
include::../{snippet-dir}/agid-extensions.xml[tags=ext_TipoRitenuta]
----

.UBL example of withholding tax in the invoice header
In the invoice it is possible to specify one or more withholdings in the WithholdingTaxTotal element at the header level, as shown in the example provided. 

[source, xml, indent=0]
----
	<!-- Ritenuta ENASARCO su imponibile prestazione -->
	<cac:WithholdingTaxTotal>
		<cbc:TaxAmount currencyID="EUR">82.50</cbc:TaxAmount>
		<cac:TaxSubtotal>
			<cbc:TaxableAmount currencyID="EUR">1000.00</cbc:TaxableAmount>
			<cbc:TaxAmount currencyID="EUR">82.50</cbc:TaxAmount>
			<cac:TaxCategory>
				<cbc:ID>S</cbc:ID>
				<cbc:Percent>8.25</cbc:Percent><!-- 50% dell'aliquota 16.50% -->
				<cac:TaxScheme>
					<cbc:ID>SWT</cbc:ID>
					<cbc:TaxTypeCode>R</cbc:TaxTypeCode><!-- provvigioni corrisposte ad agente o rappresentante di commercio plurimandatario -->
				</cac:TaxScheme>
			</cac:TaxCategory>
		</cac:TaxSubtotal>
	</cac:WithholdingTaxTotal>
----

.UBL example of withholding tax in the invoice lines
In the invoice it is possible to specify that a line is subject to withholding, as shown in the example provided.

[source, xml, indent=0]
----
<cac:InvoiceLine>
    <!-- ... -->
    <cac:Item>
        <!-- ... -->
        <cac:AdditionalItemProperty>
            <cbc:Name>RITENUTA</cbc:Name>
            <cbc:Value>SI</cbc:Value>
        </cac:AdditionalItemProperty>
    </cac:Item>
    <!-- ... -->
</cac:InvoiceLine>
----

.UBL example of withholding tax in the credit note
In the UBL 2.1 credit note the WithholdingTaxTotal element, used to indicate applied withholdings, is not present, however it can be included as a UBL extension in the document header, as shown in the example provided.

[source, xml, indent=0]
----
include::../{snippet-dir}/agid-extensions.xml[tags=ext_ritenuta_NC]
----