////

= Link al Portale Specifiche

https://peppol-docs.agid.gov.it/docs/my_index.jsp/[Vai al Portale Specifiche]


= Introduzione a openPeppol e alla BIS

[preface]
Questa {peppol} BIS fornisce un insieme di specifiche per l’implementazione di un processo di business {peppol}.

Questo documento è volto a chiarire i requisiti necessari ad assicurare l'interoperabilità nell'eProcurement Pubblico pan-Europeo e fornisce le linee guida per il supporto e l'implementazione di questi requisiti anche in Italia.

Questa specifica è una Core Invoice Usage Specification (CIUS) della {EN16931}, che ne segue le indicazioni fornite al capitolo 7. Qualsiasi documento compatibile a questa specifica sarà sempre compatibile alla normativa europea ({EN16931}).

L’obiettivo di questo documento è descrivere l’uso dei messaggi della fattura e della nota di credito in PEPPOL, e facilitare un’efficiente implementazione e diffusione delle collaborazioni elettroniche per il processo di fatturazione in questi formati.

== A chi si rivolge

Questo documento si rivolge alle organizzazioni che intendono essere abilitate a Peppol per scambiare fatture e note di credito elettroniche, e/o ai loro fornitori ICT. Queste organizzazioni potrebbero essere:

     * Fornitori di Servizi (SP)
     * Autorità appaltanti (CA)
     * Operatori Economici (EO)
     * Sviluppatori Software

Più specificatamente, i ruoli affrontati sono i seguenti:

    * Architetti ICT
    * Sviluppatori ICT
    * Esperti di Business

Per ulteriori informazioni su Peppol/OpenPeppol, leggete {common}
////