[[use-case-1---simple-despatch]]
== Caso d’uso 1 – Spedizione semplice

Questo caso d’uso è una spedizione semplice dove non viene usata alcuna unità logistica nel Documento di Trasporto.
Vi sono solo due parti (soggetti giuridici) in questo caso.

[cols="1,5",options="header",]
|====
|*Nr. Caso d’uso* |1
|*Nome Caso d’uso* |Spedizione Semplice
|*Descrizione Caso d’uso* |Questo caso d’uso è una spedizione semplice dove non viene usata alcuna unità logistica nel Documento di Trasporto. Vi sono solo due parti (soggetti giuridici) in questo caso.
|*Parti coinvolte* a|
* Speditore (In UBL: DespatchSupplierParty) (stesso soggetto giuridico del Fornitore/Venditore in questo caso)
* Consegnatario (In UBL: DeliveryCustomerParty) (stesso soggetto giuridico del Cliente/Acquirente in questo caso)


|*Assunzioni* a|
1.  Il Venditore ha ricevuto un ordine dall’Acquirente con 
a.  2 righe (2 articoli)
b.  Da consegnare ad un singolo indirizzo di consegna 
c.  Allo stesso tempo.
2.  Il Venditore ha accettato l’ordine senza modifiche.
3.  Lo Speditore evade l’ordine completo come accettato.

|*Il flusso* a|
1.  Il Venditore preleva gli articoli ordinati
2.  Il Venditore dispone gli articoli in casse
3.  Lo Speditore crea un DDT 
4.  Lo Speditore invia il DDT al Consegnatario
5.  Il Consegnatario riceve il DDT
6.  Il Consegnatario utilizza il contenuto del DDT per registrare l’accettazione.
a.  Due righe di spedizione, due articoli (Nessuna unità logistica nel messaggio)

|*Risultati* a|
1.  Il Documento di Trasporto ha aiutato il Consegnatario a preparare l’accettazione 
a.  Allo stesso tempo
b.  Nel luogo corretto (indirizzo)
2.  Il Documento di Trasporto e ha aiutato il Consegnatario nella registrazione dell’accettazione per identificare:
a.  L’ordine
b.  Le righe d’ordine
c.  Gli articoli
d.  La quantità evasa

|*Esempio XML* | Vedi sezione download nella Homepage.

|====
