[[buyerref]]
= Buyer reference

The buyer reference, known as Your ref, is *conditional*. An invoice shall have either the buyer reference or the order reference (see <<orderref>>) 

The element is used for the reference of who ordered the products/services. Example being the name of the person ordering, employee number or a code identifying this person or department/group. This reference is often used for internal routing at recipient, and hence it is important to fill this element with the correct values according to the need of the recipient.

#If the invoice is issued within a Order Only or an Ordering process relevant to the NSO system, the elements OrderID, IssueDate and EndpointID ("Tripletta") should be reported in *cbc:BuyerReference* (BT-10 Buyer reference) separated by the symbol &#x0023; without interposition of spaces, as in the following example:#

[source, xml, indent=0]
----
<cbc:BuyerReference>110#2018-01-30#aaaaaa</cbc:BuyerReference>
----

#If the invoice is referred to an analogic order issued by an Italian public health institution (for example by e-mail, fax, etc…), it could be indicated with the text "&#x0023;NO&#x0023;" in *cbc:BuyerReference* (BT-10 Buyer reference).#