[[orderref]]
= Purchase order and sales order reference

The purchase order is *conditional*. If order reference exist, use that, else use Buyer reference (see <<buyerref>>).

The buyer will issue an order with a unique order number. This unique purchase order number should be supplied as the order reference on the invoice. 

*At the header level*::

If the order reference is stated at header level, the order reference element on line level can be used to state the order line numbers. 

A sales order is issued by the seller, confirming the sale of specified products. 

IMPORTANT: In the invoice, both a purchase order and a sales order reference can be given, but be aware that an invoice instance cannot have a sales order reference, without the corresponding purchase order reference.

include::../../../syntax/references/_order.adoc[]

#If the invoice is referred to an electronic order issued by an Italian public health institution, the order reference (“tripletta”) should be indicated in the following way:#

1. #In cac:OrderReference/cbc:ID (BT-13 Purchase order reference) insert only the order identifier. Insert the order date in the cac:OrderReference/cbc:IssueDate:#
+
[source, xml, indent=0]
----
<cac:OrderReference>
    <cbc:ID>110</cbc:ID>
    <cbc:IssueDate>2018-01-30</cbc:IssueDate>
</cac:OrderReference>
----

2. #In cbc:BuyerReference (BT-10 Buyer reference) report the complete identifier “Triplet” composed by the elements (Id, date e Endpoint) concatenated by the '#' symbol and without spaces interpositions, as in the following example:#
+
[source, xml, indent=0]
----
<cbc:BuyerReference>110#2018-01-30#aaaaaa</cbc:BuyerReference>
----

#If the invoice is referred to an analogic order issued by an Italian public health institution, this should be# indicated as follows:

[source, xml, indent=0]
----
<cbc:BuyerReference>#NO#</cbc:BuyerReference>
----

#If the invoice is not preceded by an order, this should be# indicated as follows:

[source, xml, indent=0]
----
<cac:OrderReference>
    <cbc:ID>#NO#</cbc:ID>
</cac:OrderReference>
----

#If the invoice is referred to more than one electronic order with the order reference stated at the line level, this should be indicated as follows:#

[source, xml, indent=0]
----
<cac:OrderReference>
    <cbc:ID>#MULTI#</cbc:ID>
</cac:OrderReference>
----

#If you intend to specify the link between an order line and an invoice line whose reference is inserted at the header level, you must indicate the order line identifier in the cac:OrderLineReference/cbc:LineID element of the invoice line (cac:InvoiceLine) as follows:#

[source, xml, indent=0]
----
<cac:OrderLineReference> 
    <cbc:LineID>3</cbc:LineID> 
</cac:OrderLineReference> 
----

*At the line level*

#The order reference at the line level is made using the structures cac:OrderLineReference and cac:DocumentReference.#

#If the invoice is issued within a Order Only or an Ordering electronic process relevant to the NSO system, the order reference should be reported in cac:OrderLineReference and the elements OrderID, IssueDate and EndpointID (“Tripletta”) should be reported in *cac:DocumentReference*. In the cac:OrderLineReference/cbc:LineID element, it is possible to indicate the identifier of the order line to which the invoice line specifically refers. Otherwise, the element must be valued as "NA".#

.UBL Example of invoice line with generic reference to an order sent via NSO
[source, xml, indent=0]
----
<cac:OrderLineReference>
        <cbc:LineID>NA</cbc:LineID>
        <cac:OrderReference>
                <cbc:ID>123</cbc:ID>
                <cbc:IssueDate>2020-10-01</cbc:IssueDate>
        </cac:OrderReference>
</cac:OrderLineReference>
<cac:DocumentReference>
    <cbc:ID schemeID="ON">123#2020-10-01#aaaaaa</cbc:ID>
    <cbc:DocumentTypeCode>130</cbc:DocumentTypeCode>
</cac:DocumentReference>
----

.UBL Example of invoice line with specific reference to an order line sent via NSO

[source, xml, indent=0]
----
<cac:OrderLineReference>
        <cbc:LineID>2</cbc:LineID>
        <cac:OrderReference>
                <cbc:ID>123</cbc:ID>
                <cbc:IssueDate>2020-10-01</cbc:IssueDate>
        </cac:OrderReference>
</cac:OrderLineReference>
<cac:DocumentReference>
    <cbc:ID schemeID="ON">123#2020-10-01#aaaaaa</cbc:ID>
    <cbc:DocumentTypeCode>130</cbc:DocumentTypeCode>
</cac:DocumentReference>
----

#If the invoice is referred to an analogic order, the order reference should be reported in the cac:OrderLineReference element.#

#In the cac:OrderLineReference/cbc:LineID element, it is possible to indicate the identifier of the order line to which the invoice line specifically refers. Otherwise, the element must be valued as "NA".#

.UBL Example of invoice line with generic reference to an analogic order

[source, xml, indent=0]
----
<cac:OrderLineReference>
        <cbc:LineID>NA</cbc:LineID>
        <cac:OrderReference>
                <cbc:ID>456</cbc:ID>
                <cbc:IssueDate>2021-11-03</cbc:IssueDate>
        </cac:OrderReference>
</cac:OrderLineReference>
----