


[[orderref]]
= Purchase order and sales order reference

The purchase order is **conditional**. If order reference exist, use that, else use Buyer reference (see <<buyerref>>).

The customer will issue an order with a unique order number. This unique purchase order number should be supplied as the order reference on the invoice.


The header level::

If order reference is stated at header level, the order reference element on line level can be used to state the order line numbers.

IMPORTANT: In the invoice, both a purchase order and a sales order reference can be given, but be aware that an invoice instance cannot have a sales order reference, without the corresponding purchase order reference.

include::../../../syntax/references/_order.adoc[]

#Se la fattura viene emessa nell’ambito di un processo di Ordinazione elettronica, occorre riportare il riferimento all’ordine ("tripletta") nel seguente modo:#

1.	#Nel cac:OrderReference/cbc:ID (BT-13 Purchase order reference) riportare il solo identificativo dell’ordine, deve inoltre essere riportata la data dell’ordine nel cac:OrderReference/cbc:IssueDate:#
+
[source, xml, indent=0]
----
<cac:OrderReference>
    <cbc:ID>110</cbc:ID>
    <cbc:IssueDate>2018-01-30</cbc:IssueDate>
</cac:OrderReference>
----

2.	#Nel cbc:BuyerReference (BT-10 Buyer reference) riportare la Tripletta di identificazione completa separando i componenti (Id, data e Endpoint) con il carattere # senza interposizione di spazi, come nel seguente esempio:#
+
[source, xml, indent=0]
----
<cbc:BuyerReference>110#2018-01-30#aaaaaa</cbc:BuyerReference>
----

#Se invece la fattura viene emessa a fronte di un ordine analogico se ne può dare evidenza nel seguente modo:#


[source, xml, indent=0]
----
<cbc:BuyerReference>#NO#</cbc:BuyerReference>
----

#Se la fattura non è stata preceduta da un ordine occorre indicarlo nel seguente modo:#


[source, xml, indent=0]
----
<cac:OrderReference>
    <cbc:ID>#NO#</cbc:ID>
</cac:OrderReference>
----

#Ove la fattura sia riferita a più ordini (elettronici o analogici) referenziati in riga, occorre indicarlo nel seguente modo (non valorizzando il cbc:BuyerReference):#


[source, xml, indent=0]
----
<cac:OrderReference>
    <cbc:ID>#MULTI#</cbc:ID>
</cac:OrderReference>
----


*A livello di riga*

#Il riferimento ad un ordine sulle righe di fattura avviene utilizzando gli elementi cac:OrderLineReference e cac:DocumentReference.# +

[blue]#_Riferimento all'intero ordine sulla riga di fattura_#

#Se la riga si riferisce genericamente all'ordine senza specificare la riga dell'ordine, si procede come da esempio:#

.Esempio UBL con riferimento esplicito ad un Ordine completo a livello di riga fattura
[source, xml, indent=0]
----
<cac:OrderLineReference>
	<cbc:LineID>NA</cbc:LineID>
	<cac:OrderReference>
		<cbc:ID>123</cbc:ID>
		<cbc:IssueDate>2020-10-01</cbc:IssueDate>
	</cac:OrderReference>
</cac:OrderLineReference>
----

#Se la fattura viene messa nell'ambito di un processo di Ordinazione Semplice o Ordinazione Completa rilevante ai fini del sistema NSO, occorre riportare il riferimento all'ordine ("tripletta") nel seguente modo:#

.Esempio UBL con riferimento esplicito ad un Ordine inviato a mezzo NSO
[source, xml, indent=0]
----
<cac:OrderLineReference>
	<cbc:LineID>NA</cbc:LineID>
	<cac:OrderReference>
		<cbc:ID>123</cbc:ID>
		<cbc:IssueDate>2020-10-01</cbc:IssueDate>
	</cac:OrderReference>
</cac:OrderLineReference>
<cac:DocumentReference>
    <cbc:ID schemeID="ON">123#2020-10-01#aaaaaa</cbc:ID>
    <cbc:DocumentTypeCode>130</cbc:DocumentTypeCode>
</cac:DocumentReference>
----

[blue]#_Riferimento alla riga d'ordine sulla riga di fattura_#

#Se la riga si riferisce specificamente ad una riga d'ordine, si procede con le seguenti modalità alternative:# +

.Esempio UBL con riferimento implicito all’Ordine fornito a livello testata
[source, xml, indent=0]
----
<cac:OrderLineReference>
	<cbc:LineID>3</cbc:LineID>
</cac:OrderLineReference>
----

.Esempio UBL con riferimento esplicito alla riga di un Ordine a livello di riga fattura
[source, xml, indent=0]
----
<cac:OrderLineReference>
	<cbc:LineID>4</cbc:LineID>
	<cac:OrderReference>
		<cbc:ID>123</cbc:ID>
		<cbc:IssueDate>2020-10-01</cbc:IssueDate>
	</cac:OrderReference>
</cac:OrderLineReference>
----

#Se la fattura viene messa nell'ambito di un processo di Ordinazione Semplice o Ordinazione Completa rilevante ai fini del sistema NSO, occorre riportare il riferimento all'ordine ("tripletta") nel seguente modo:# +

.Esempio UBL con riferimento esplicito alla riga di un Ordine inviato a mezzo NSO a livello di riga fattura
[source, xml, indent=0]
----
<cac:OrderLineReference>
	<cbc:LineID>4</cbc:LineID>
	<cac:OrderReference>
		<cbc:ID>123</cbc:ID>
		<cbc:IssueDate>2020-10-01</cbc:IssueDate>
	</cac:OrderReference>
</cac:OrderLineReference>
<cac:DocumentReference>
    <cbc:ID schemeID="ON">123#2020-10-01#aaaaaa</cbc:ID>
    <cbc:DocumentTypeCode>130</cbc:DocumentTypeCode>
</cac:DocumentReference>
----


