[[altri-riferimenti]]
= #Summary of references to other documents#

[cols="2,2,3,6", options="header"]
|====
^.^|Reference
^.^|Description
^.^|FatturaPA element
^.^|Instructions

|*ORDER*
|Paper or electronic order
|2.1.2.2 IdDocumento +
2.1.2.3 Data +
2.1.2.5 CodiceCommessaConvenzione
|At header level +
`cac:OrderReference/cbc:ID` and +
`cbc:BuyerReference` +

At line level +
`cac:InvoiceLine/cac:OrderLineReference/cac:OrderReference/cbc:ID` +
and +
`cac:InvoiceLine/cac:DocumentReference/cbc:ID` +
with @schemeID = ON

|*CONTRACT*
|Contract details
|2.1.3.2 IdDocumento
|At header level +
`cac:ContractDocumentReference/cbc:ID` +

At line level +
`cac:InvoiceLine/cac:DocumentReference/cbc:ID` +
with @schemeID = CT

|*DESPATCH ADVICE*
|Despatch Advice (DDT) +
|2.1.8.1 NumeroDDT
|At header level +
`cac:DespatchDocumentReference/cbc:ID` +

At line level +
`cac:InvoiceLine/cac:DespatchLineReference/cac:DocumentReference/cbc:ID`

|*TENDER*
|Tender Identification Code (CIG) +
|2.1.3.7 CodiceCIG
|At header level +
`cac:OriginatorDocumentReference/cbc:ID` +

At line level +
`cac:InvoiceLine/cac:DocumentReference/cbc:ID` +
with @schemeID = AGB

|*PROJECT*
|Unique Project Code (CUP)
|2.1.3.6 CodiceCUP
|At header level +
`cac:ProjectReference/cbc:ID` +

At line level +
`cac:InvoiceLine/cac:DocumentReference/cbc:ID` +
with @schemeID = AEP

|*FRAMEWORK AGREEMENT*
|Framework Agreement details
|2.1.4.2 IdDocumento
|At header level +
`cac:AdditionalDocumentReference/cbc:ID` +
with @schemeID = AVV

At line level +
`cac:InvoiceLine/cac:DocumentReference/cbc:ID` +
with @schemeID = AVV

|*WORK IN PROGRESS PHASE (WIP)*
|Reference to a work in progress phase
|2.1.7.1 RiferimentoFase
|At header level +
`cac:AdditionalDocumentReference/cbc:ID` +
with @schemeID = AOR

|====