= Allowances and charges

The Invoice and credit note transactions has elements for Allowance/charge on 3 levels.

The element `cac:AllowanceCharge` with sub element `cbc:ChargeIndicator` indicates whether the instance is a charge (true) or an allowance (false).

The header level:: _Applies to the whole invoice and is included in the calculation of the invoice total amount._
* Several allowances and charges may be supplied
* Specification of VAT for allowances and charges, `cac:TaxCategory` with sub elements, shall be supplied
* The sum of all allowances and charges on the header level shall be specified in `cbc:AllowanceTotalAmount` and `cbc:ChargeTotalAmount` respectively. See <<totals>>

[IMPORTANT]
====
#For invoicing towards Italian entities, this section is used only for Stamp Duty (see paragraph 5.9) and Social Security Contribution (see paragraph 5.8).#
====

_#Allowances and charges that do not affect the taxable amount#_

* #Expressed through UBL extension.#
* #Multiple allowances and charges can be indicated.#
* #They do not modify either the taxable amount or the VAT.#

[NOTE]
#The algebraic sum of the charges (with a negative sign) and allowances (with a positive sign) must be included in the value entered in cbc:PrepaidAmount. It should be noted that cbc:PrepaidAmount is not supported in FatturaPA, but it is used to correctly populate the cbc:PayableAmount (BT-115 Amount due for payment), which is mandatory according to EN 16931.#

.#UBL example of allowance at the document level through extension#.
[source, xml, indent=0]
----
include::../../../rules/snippets/agid-extensions.xml[tag=ext_ScontoFatturaPA]
----

The line level:: _Applies to the line level and is included in the calculation of the line amount._
* Several allowances and charges may be supplied
* Specification of VAT for allowances and charges shall not be specified, as the VAT category stated for the invoice line itself, applies also to the allowances or charges of that line.
* The sum of all allowances and charges on the line level shall be taken into account, subtracted or added, when calculating the line extension amount. These line level allowances and charges shall not be calculated into the header level elements.

[IMPORTANT]
====
#For invoicing towards Italian entities, allowances or charges at the line level are not used.#
====

The line level Price element::
_A way to inform the buyer how the price is set. Is also relevant if the seller or buyer want to post the allowance in their accounting systems. The price itself shall always be the net price, i.e. the base amount reduced with a discount (allowance)._
* The net price (cbc:PriceAmount) must always be expressed
* #The gross price (cbc:BaseAmount) must always be expressed#
* #The cac:AllowanceCharge element must always be expressed#
* The cbc:ChargeIndicator element must always be expressed and valued with "false"
* To indicate an allowance, provide a positive amount in cac:AllowanceCharge/cbc:Amount. +
To indicate a charge, provide a negative amount in cac:AllowanceCharge/cbc:Amount. +
If any Charge/Allowance is applied to the item, put "0 as a value in cac:AllowanceCharge/cbc:Amount.#
* Only one occurrence of the discount is allowed. 
* Percentage-based allowances/charges are not permitted. 
* VAT related to allowances/charges must not be specified. 
* Allowances and charges related to the price must not be part of any other calculation.

Further details on the calculation of allowances/charges are available in <<allowance-calc>>
//include::../../syntax/_allowance.adoc[]

.#_UBL example of allowance at the line level price_#
[source, xml, indent=0]
----
<cac:InvoiceLine>
    <!-- ... -->
    <cac:Price>
      <cbc:PriceAmount currencyID="EUR">5.00</cbc:PriceAmount>
      <cac:AllowanceCharge>
        <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
        <cbc:Amount currencyID="EUR">1.00</cbc:Amount>
        <cbc:BaseAmount currencyID="EUR">6.00</cbc:BaseAmount>
      </cac:AllowanceCharge>
    </cac:Price>
</cac:InvoiceLine>
----