
= Allowances and Charges


The Invoice and credit note transactions has elements for Allowance/charge on 3 levels.

The element `cac:AllowanceCharge` with sub element `cbc:ChargeIndicator` indicates whether the instance is a charge (true) or an allowance (false).

The header level:: _Applies to the whole invoice and is included in the calculation of the invoice total amount._
* Several allowances and charges may be supplied
* Specification of VAT for allowances and charges, `cac:TaxCategory` with sub elements, shall be supplied
* The sum of all allowances and charges on the header level shall be specified in `cbc:AllowanceTotalAmount` and `cbc:ChargeTotalAmount` respectively. See <<totals>>
[IMPORTANT]
====
#Per la fatturazione verso soggetti italiani la sezione è utilizzata solo per Bollo (vedi paragrafo 4.9) e Rivalsa Cassa Previdenziale (vedi paragrafo 4.8).#
====

_#Sconti e maggiorazioni che non incidono sull’imponibile.#_

* #Espressi mediante estensione UBL.#
* #Possono essere indicati diversi sconti e maggiorazioni.#
* #Non modificano nè l'imponibile, nè l'IVA.#


[NOTE]
====
La somma algebrica delle maggiorazioni (con segno meno) e degli sconti (con segno più) va ricompresa nel valore inserito in cbc:PrepaidAmount. Si evidenzia che il cbc:PrepaidAmount non è supportato in FatturaPA ma viene utilizzato per valorizzare correttamente il dato cbc:PayableAmount (BT-115 Amount due for payment) che è obbligatorio per la EN 16931.
====

.#Esempio UBL per fornire lo sconto sul totale documento, mediante estensione#.
[source, xml, indent=0]
----
include::../../../rules/snippets/agid-extensions.xml[tag=ext_ScontoFatturaPA]
----

The line level:: _Applies to the line level and is included in the calculation of the line amount._
* Several allowances and charges may be supplied
* Specification of VAT for allowances and charges shall not be specified, as the VAT category stated for the invoice line itself, applies also to the allowances or charges of that line.
* The sum of all allowances and charges on the line level shall be taken into account, subtracted or added, when calculating the line extension amount . These line level allowances and charges shall not be calculated into the header level elements.

[IMPORTANT]
====
#Per la fatturazione verso soggetti italiani la sezione sconto/maggiorazione a livello di riga non è utilizzata.#
====


The line level Price element:: _A way to inform the buyer how the price is set. Is also relevant if the seller or buyer want to post the allowance in their accounting systems. The price itself shall always be the net price, i.e. the base amount reduced with a discount (allowance)._
* Il prezzo netto (cbc:PriceAmount) deve essere sempre espresso 
* L'elemento cbc:ChargeIndicator deve essere sempre espresso e valorizzato con "false".
* #Il prezzo lordo (cbc:BaseAmount) deve essere sempre espresso.#
* #Il segmento cac:AllowanceCharge deve essere sempre espresso#
* #Per indicare uno sconto, fornire un importo positivo nel cac:AllowanceCharge/cbc:Amount. +
Per indicare una maggiorazione, fornire un importo negativo nel cac:AllowanceCharge/cbc:Amount. +
Se nessuno Sconto/Maggiorazione è applicato all'articolo, valorizzare cac:AllowanceCharge/cbc:Amount con "0".# 
* Only one occurence of allowance (discount) is allowed.
* Specification of VAT for allowance shall not be specified
* Allowance related to Price shall not be part of any other calculations.
* Allowance related to Price may specify amount and the base amount.

Further details of the calculation of allowance/charge amount, can be found in <<allowance-calc>>
//include::../../syntax/_allowance.adoc[]

.Esempio UBL di sconto su prezzo
[source, xml, indent=0]
----
<cac:InvoiceLine>
    <!-- ... -->
    <cac:Price>
      <cbc:PriceAmount currencyID="EUR">5.00</cbc:PriceAmount>
      <cac:AllowanceCharge>
        <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
        <cbc:Amount currencyID="EUR">1.00</cbc:Amount>
        <cbc:BaseAmount currencyID="EUR">6.00</cbc:BaseAmount>
      </cac:AllowanceCharge>
    </cac:Price>
</cac:InvoiceLine>
----
