
= Delivery Details (Date and Location)

Delivery details may be given at document level.

Place and date of delivery is recommended, and should be sent unless this does not affect the ability to ensure the correctness of the invoice.

The delivery element contains information on name, address and delivery location identifier (`cac:Delivery/cac:DeliveryLocation/cbc:ID`) which may be used if the place of delivery is defined through an identifier. For example GLN (Global Location Number)issued by GS1. +

#In italia, in seguito alle Regole Tecniche NSO, l'identificativo del luogo di consegna per le PA segue la codifica https://www.puntidiconsegna-nso.it/[Punti di consegna].# +

#Quando la fattura si riferisce ad un unico Documento di Trasporto, la data del DDT viene riportata nel *cac:DespatchDocumentReference/cbc:IssueDate*.#


include::../../syntax/_delivery.adoc[]

:leveloffset: +1

//include::_ext-vettore.adoc[]

//include::_ext-ritiro-merce.adoc[]

//include::_ext-spedizione.adoc[]

:leveloffset: -1