= Item information

== Item identifiers

In an invoice line the seller item identifier, the buyer item identifier and the standard item identifier can be provided. For sellers and buyers item identifiers, no scheme attribute is used, whilst the `schemeID`
is mandatory for the standard item identification, and must be from the ISO 6523 ICD list.

include::../../syntax/_item-identification.adoc[]

== Item classification

Several different item classification codes can be provided per invoice line, and the codes must be from one of the classification schemes in code list UNCL7143.

include::../../syntax/_item-classification.adoc[]

== #Tipo cessione prestazione#

La gestione del tipo cessione prestazione è operata a mezzo dell’utilizzo di: +

1.	*cac:AdditionalItemProperty/cbc:Name* 
(BT-160 Item attribute name), inserendo la stringa _TipoCessionePrestazione_;
2. *cac:AdditionalItemProperty/cbc:Value* 
(BT-161 Item attribute value) inserendo il valore ammesso da FatturaPA: _[SC] sconto, [PR] premio, [AB] abbuono, [AC] spesa accessoria_.

.Esempio sulla gestione del tipo cessione prestazione

[source, xml, indent=0]
----
<cac:InvoiceLine>
  <!-- ... -->
  <cac:Item>
    <!-- ... -->
    <cac:AdditionalItemProperty>
      <cbc:Name>TipoCessionePrestazione</cbc:Name>
      <cbc:Value>AB</cbc:Value>
    </cac:AdditionalItemProperty>
  </cac:Item>
</cac:InvoiceLine>
----
