= Item information

== Item identifiers

In an invoice line the seller item identifier, the buyer item identifier and the standard item identifier can be provided. For sellers and buyers item identifiers, no scheme attribute is used, whilst the `schemeID`
is mandatory for the standard item identification, and must be from the ISO 6523 ICD list.

include::../../syntax/_item-identification.adoc[]

== Item classification

Several different item classification codes can be provided per invoice line, and the codes must be from one of the classification schemes in code list UNCL7143.

include::../../syntax/_item-classification.adoc[]

== #Type of transfer#

The type of transfer is managed using: +

1. *cac:AdditionalItemProperty/cbc:Name* (BT-160 Item attribute name), inserting the string _TipoCessionePrestazione_;
2. *cac:AdditionalItemProperty/cbc:Value* (BT-161 Item attribute value) inserting the value allowed by the FatturaPA codelist: _[SC] for charge, [PR] for premium , [AB] for allowance, [AC] for related expenses_.

.UBL example of the management of TipoCessionePrestazione

[source, xml, indent=0]
----
<cac:InvoiceLine>
  <!-- ... -->
  <cac:Item>
    <!-- ... -->
    <cac:AdditionalItemProperty>
      <cbc:Name>TipoCessionePrestazione</cbc:Name>
      <cbc:Value>AB</cbc:Value>
    </cac:AdditionalItemProperty>
  </cac:Item>
</cac:InvoiceLine>
----