= Payment means information

== Credit transfer

If payment is made by credit transfer, the Payment account identifier (BT-84) is mandatory

See <<payment-means>> for all allowed codes. Examples of codes for payment by credit transfer are:

* 30 - Credit transfer
* 58 - SEPA credit transfer ?
* #56 - Giroconto bancario#

include::../../syntax/_credit-payment.adoc[]

== Card Payment

If the Buyer had opted to pay by using a payment card such as a credit or debit card, information on the Primary Account Number (PAN) shall be present in the invoice.

See <<payment-means>> for all allowed codes. Examples of codes for payment by card are:

* 48 - Bank card
* 54 - Credit card
* 55 - Debet card

include::../../syntax/_card-payment.adoc[]

== Direct debit

See <<payment-means>> for all allowed codes. Examples of codes for payment by direct debit are:

* 49 - Direct debit
* 59 - SEPA direct debit

include::../../syntax/_direct-debit.adoc[]

== Payment by postgiro

See <<payment-means>> for all allowed codes. Examples of codes for payment by giro are:

* 50 - Payment by postgiro

include::../../syntax/_giro.adoc[]

== #Payment by Cash#

See <<payment-means>> for all allowed codes. Example of code for cash payment is:

* 10 - Cash

include::../../syntax/_cash-payment.adoc[]

//== Pagamento non specificato

If the seller does not provide any instructions on how to settle the invoice, there is usually a contract that governs this.

By using code 1, the buyer is not informed about the payment method for the invoice, and only a due date can be specified.

include::../../syntax/_unspecified-payment.adoc[]

== #Payment by PagoPA# (Domestic CIUS)

Within the Italian context, the code "9" (National or regional clearing) of the Payment means type code list is connected with the code "MP23" (PagoPA) of the FatturaPA payment means type code list. +

The Unique Payment Identifier ("Identificativo Univoco di versamento") must be indicated in cbc:PaymentID. 

.UBL example of payment by PagoPA
[source, xml, indent=0]
----
<cac:PaymentMeans>
    <cbc:PaymentMeansCode name="PagoPA">9</cbc:PaymentMeansCode>
    <cbc:PaymentID>302000000000001404<cbc:PaymentID>
</cac:PaymentMeans>
----