
= Payment means information

== Credit transfer

If payment is made by credit transfer, the Payment account identifier (BT-84) is mandatory

See <<payment-means>> for all allowed codes. Examples of codes for payment by credit transfer are:

* 30 - Credit transfer
* 58 - SEPA credit transfer ?
* #56 - Giroconto bancario#

include::../../syntax/_credit-payment.adoc[]

== Card Payment

If the Buyer had opted to pay by using a payment card such as a credit or debit card, information on the Primary Account Number (PAN) shall be present in the invoice.

See <<payment-means>> for all allowed codes. Examples of codes for payment by card are:

* 48 - Bank card
* 54 - Credit card
* 55 - Debet card

include::../../syntax/_card-payment.adoc[]

== Direct debit

See <<payment-means>> for all allowed codes. Examples of codes for payment by direct debit are:

* 49 - Direct debit
* 59 - SEPA direct debit

include::../../syntax/_direct-debit.adoc[]

== Payment by post- or bank giro

See <<payment-means>> for all allowed codes. Examples of codes for payment by giro are:

* 50 - Payment by postgiro
* ? 56 - Bankgiro


include::../../syntax/_giro.adoc[]

== #Pagamento mediante contante#

Vedi <<payment-means>> per tutti i codici ammessi. Esempio di codice per il pagamento in contante:

* 10 - Contante

include::../../syntax/_cash-payment.adoc[]


//== Pagamento non specificato

Se il venditore non dà indicazioni su come regolarizzare il pagamento della fattura, esiste solitamente un contratto che lo regola.

Indicando il codice 1, l’acquirente non viene informato sulle modalità di pagamento della fattura e può essere indicata solo una data di pagamento.

include::../../syntax/_unspecified-payment.adoc[]

== #Pagamento mediante PagoPA#

Il codice 9 (National or regional clearing) viene mappato con MP23 – PagoPA: +

* 9 - PagoPA

.Esempio UBL di modalità pagamento con PagoPA
[source, xml, indent=0]
----
<cac:PaymentMeans>
    <cbc:PaymentMeansCode name="PagoPA">9</cbc:PaymentMeansCode>
</cac:PaymentMeans>
----

