[[Specifiche-Partita-Merce]]
= #Specifications on the Consigment#

To provide further details about a Consignment it is possible to utilize the segment *cac:Shipment/cac:GoodsItem* on the line level, as part of information about the shipment.

In particular, it is possible to specify information about the temperature recommended and allowable as described below.

[[temperatura]]
== Temperature

To indicate the recommended and allowable temperature for some goods or the minimum/maximum tolerated temperature, it is possible to specify it always in the detail of the shipment as shown in the following example:

.Example of temperature settingsmperatura:
[source, xml, indent=0]
----
<cac:DespatchLine>
	<cac:Shipment>
		<cac:GoodsItem>
			<cac:Temperature>
				<cbc:AttributeID>Recommended</cbc:AttributeID>
				<cbc:Measure unitCode="CEL">-20</cbc:Measure> 
			</cac:Temperature>
			<cac:MinimumTemperature>
				<cbc:AttributeID>Allowable</cbc:AttributeID>
				<cbc:Measure unitCode="FAH">-20</cbc:Measure> 
			</cac:MinimumTemperature>
			<cac:MaximumTemperature>
				<cbc:AttributeID>Allowable</cbc:AttributeID>
				<cbc:Measure unitCode="FAH">15</cbc:Measure> 
			</cac:MaximumTemperature>
		</cac:GoodsItem>
	</cac:Shipment>
</cac:DespatchLine>
----

The example denotes the use of unit of measures Celsius (CEL) and Fahrenheit (FAH). The element *cbc:AttributeID* is mandatory but can be ignored valorizing it as NA. However in some cases can improve the understanding of the temperature provided (es. Recommended, Allowable, Alert).

[NOTE]
Measures are necesseraly expressed according to the codelists {UNRec20} and it is not required to qualify them with further attributes.

