[[despatch-advice-transaction-business-requirements]]
= I requisiti di business della transazione del Documento di Trasporto


.Requisiti generali (gli identificatori nella prima colonna sono referenziati dalla struttura dettagliata del messaggio)
[cols="1h,5",options="header",]
|====
|ID |Requisito
|tbr16-016 |Il Documento di Trasporto (DDT) deve essere identificato con un identificatore, con la data di emissione e possibilmente anche l’ora.
|tbr16-001 |Il messaggio del Documento di Trasporto (DDT) è utilizzato dal fornitore per indicare al recevente la merce in spedizione e come questa è imballata.
|tbr16-002 a|
Per supportare il trasporto delle merci, una consegna (delivery) è intesa come un numero di articoli che vengono spediti come consegna unica ad un singolo indirizzo di consegna. 
* Ogni consegna deve essere accompagnata dal suo Documento di Trasporto
* Ogni Documento di Trasporto si riferisce a un solo indirizzo di consegna 
* Ci possono essere più Documenti di Trasporto a fronte di un ordine di acquisto

|tbr16-003 a|
Il Documento di Trasporto (DDT) può fare riferimento a un ordine. 
* Ogni Documento di Trasporto si riferisce a un singolo ordine.

|tbr16-011 |Il Documento di Trasporto (DDT) può indicare il motivo per la modalità/mezzo di trasporto.
|tbr16-015 |Il Documento di Trasporto (DDT) può indicare il volume e il peso della consegna.
|tbr16-017 |Il Documento di Trasporto (DDT) può contene una nota testuale.
|====

.Parti
[cols="1h,5",options="header",]
|====
|ID |Requisito
|tbr16-004 a|
Il Documento di Trasporto (DDT) deve identificare lo Speditore, che è responsabile per il trasporto fisico della merce. 
* Lo speditore può agire per conto del fornitore
* Il ricevitore della merce può aver bisogno di contattare la persona responsabile per la spedizione della merce.  

|tbr16-005 a|
Il Documento di Trasporto (DDT) può identificare il Consegnatario, che è responsabile per l’accettazione della merce. 
* Il ricevitore può agire per conto del cliente. 
* Il cliente può necessitare di individuare e verificare l’indirizzo di spedizione effettivo della merce. L’indirizzo di spedizione è quello dove gli articoli sono stati spediti. 

|tbr16-006 a|
Il Documento di Trasporto (DDT) può identificare l’Acquirente, che è commercialmente responsabile e per il quale la merce viene ricevuta.
* L’acquirente viene identificato fornendo almento il nome completo e un indirizzo postale 
* Le informazioni sull’acquirente includono la persona di contatto che emette o riceve la consegna per informazioni sullo stato della spedizione, come movimenti interni di magazzino o di accettazione. 

|tbr16-012 |Il Documento di Trasporto (DDT) può includere l’indirizzo di consegna.
|tbr16-013 a|
Il Documento di Trasporto (DDT) può identificare il Venditore, che è legalmente responsabile di fornire la merce e per cui conto la merce viene inviata.
* Il Venditore viene identificato fornendo almeno il nome completo, l’indirizzo postale e la partita IVA (o altro identificativo fiscale VAT)
* Le informazioni sul Venditore includono la persona di contatto che l’emettente o il ricevitore possono contattare per informazioni sullo stato della spedizione. 

|tbr16-014 a|
Se il trasporto fisico è fornito da una terza parte, il Documento di Trasporto (DDT) può identificare quel trasportatore.
* Le informazioni sul trasportatore possono includere il nome dell’autista. 

|====

.Line Item
[cols="1h,5",options="header",]
|====
|ID |Requisito
|tbr16-007 a|
Ogni riga di dettaglio della spedizione dovrebbe descrivere la spedizione di uns singola riga d’ordine. La riga dorvebbe fornire il riferimento a 
* Riga d’ordine, 
* Quantità spedita, quantità inevasa (da consegnare in una spedizione separata).  
* La riga dovrebbe fornire anche delle note. 

|tbr16-008 a|
Ogni riga dovrebbe identificare il prodotto spedito in modo che il ricevitore possa verificare il suo contenuto. Questo può includere 
* Nome dell’articolo, 
* ID del Venditore 
* ID standard dell’articolo
* Date, come “preferibilmente entro”, data di fabbricazione, ecc.

|tbr16-009 |Ogni riga dovrebbe identificare la merce pericolosa che può richiedere uno speciale trattamento durante il trasporto, l’accettazione della merce e lo stoccaggio.
|tbr16-010 |Ogni riga può identificare l’unità logistica per ogni unità di merce spedita. Le unità logistiche possono avere marche o codici a barre esterni che – durante l’accettazione della merce – permette la tracciatura e la localizzazione delle unità di imballo dove la merce è situata.
|====
