
= Restrizioni ai processi supportati

Il capitolo 5.2 nella {EN16931} definisce i processi di business supportati dalla {EN16931}.

Questo {CIUS} ha applicato delle restrizioni per non supportare esplicitamente i seguenti processi di business:

P10 - Fattura correttiva::
Il processo come descritto per la fatturazione correttiva è stato interpretato come poco chiara la differenza tra la fattura correttiva e la nota di credito, e questo processo è stato per questo definito fuori ambito.

P11 - Fatturazione parziale e finale::
Per il fatto che sia la fatturazione partiale che finale non necessitano di tutte le informazioni obbligatorie, questo process è fuori ambito in questa PEPPOL BIS.

P12 - Auto fatturazione:: La Direttiva 2006/112/EC (Articolo 224) richiede che venga osservato un processo specifico, in base ad un accordo precedente e una procedura secondo la quale il fornitore deve accettare ogni fattura. L'auto-fatturazione richiede una configurazione specifica per i requisiti dettati da accordi precedenti e una procedura per l'accettazione di ogni auto-fattura. Specifici traguardi devono essere osservati nel momento in cui sarà configurato come pure durante la messa in produzione del self-billing.
