[[EndpointID]]
= #Endpoint ID - Identificativo di instradamento sulla rete Peppol#

Quando si specifica un Endpoint ID nel documento si vuole mantenere l’informazione dell’indirizzo elettronico del mittente o destinatario utilizzati per l’instradamento dei messaggi (delivery) sul circuito Peppol. 

Le tipologie di identificativi italiani riconosciuti da Peppol e consigliati sono:

* *0211* per le partite IVA;

* *0210* per i Codici Fiscali di persona fisica o giuridica;

* *0201* per il Codice Univoco Ufficio (c.d. Codice iPA, riportato nella rubrica "indicepa" dell'Indice delle Pubbliche Amministrazioni). +

In Italia la registrazione delle pubbliche amministrazione sulla rete Peppol avviene attraverso l'uso del Codice Univoco Ufficio.



.Esempio di Endpoint di un’Amministrazione registrata in Peppol tramite il Codice Univoco Ufficio:
[source, xml, indent=0]
----
    <cbc:EndpointID schemeID="0201">ABCDEF</cbc:EndpointID>
----

----

.Esempio di Endpoint di Fornitore registrato in Peppol con la Partita IVA:
[source, xml, indent=0]
----
    <cbc:EndpointID schemeID="0211">IT07643520567</cbc:EndpointID>
----

.Esempio di Endpoint di fornitore registrato in Peppol con un GLN (Global Location Number) secondo gli standard GS1:
[source, xml, indent=0]
----
    ​<cbc:EndpointID schemeID="0088">5790000435968</cbc:EndpointID>
----
