[[tipologia-documento]]
= #Tipologia di Documento#


I Documenti, che costituiscono il Corpo del messaggio, contengono le istruzioni che Clienti e Fornitori si scambiano per regolare la fornitura dei beni e dei servizi.

Nella tabella seguente sono elencati i sotto- tipi e le varianti per l'Ordine e per l'Ordine Pre-concordato, descritti nei Paragrafi che seguono.


[width="100%", cols="2,3,3", options="header"]
|===

^.^|*Tipo Documento* 
^.^|*Sotto-tipo*
^.^|*Variante* 

.3+^.^|*Ordine* 
.3+.^| Ordine di riscontro  | Ordine di riscontro per conferma | Ordine di riscontro per diniego | Ordine di riscontro sostitutivo 


.8+^.^|*Ordine
pre-concordato* 
| Ordine pre-concordato iniziale | -
| Ordine pre-concordato di revoca | -  
| Ordine pre-concordato sostitutivo  | -
| Ordine pre-concordato collegato  | - 
| Ordine pre-concordato di convalida | - 


|===



*[red]#Ordine pre-concordato  di revoca#*

In alcune circostanze può essere utile revocare un Ordine precedentemente emesso (Ordine pre-concordato di revoca). +

L’Ordine pre-concordato di revoca è un Ordine che contiene il riferimento all’Ordine che si intende revocare e l’indicazione che si tratta di una “revoca” (“Cancelled”), inoltre ha una sola linea d’ordine priva di contenuto.

Per le regole di compilazione, vedi paragrafo 6.12.


*[red]#Ordine pre-concordato sostitutivo#*

Ove occorra le istruzioni contenute in un Ordine (o in un Ordine pre-concordato)
possono essere modificate mediante l’emissione di un Ordine sostitutivo (o di un
Ordine pre-concordato sostitutivo). Tuttavia, salvo che non sia previsto diversamente da norme, usi commerciali o accordi tra le parti, il Fornitore è tenuto a considerare efficaci solo le sostituzioni di ordini pervenute prima che abbia dato luogo all’esecuzione della fornitura. 

L’Ordine pre-concordato sostitutivo è un nuovo Ordine, completo di tutte le linee di ordine, che contiene il riferimento all’Ordine che si intende sostituire e l’indicazione che si tratta di una “sostituzione” (“Revised”).

In alcune circostanze, però, può essere necessario modificare le informazioni
contenute in un Ordine (o in un Ordine pre-concordato) precedente anche dopo la
conclusione del processo di fornitura o, perfino, successivamente all’emissione della
relativa fattura (quando il Documento è emesso al solo fine regolare aspetti di dettaglio di un processo già concluso).

[NOTE]
In questi casi l’Ordine sostitutivo deve riportare l’indicazione del sotto-tipo di Ordinazione “OR”, (c.d. “Ordine sostitutivo di regolazione“, vedi paragrafo 4.4).

Per le regole di compilazione, vedi paragrafo 6.12.


*[red]#Ordine pre-concordato collegato#*

In alcune circostanze può essere utile evidenziare che un Ordine pre-concordato, seppur indipendente, è genericamente relazionato a un altro Documento. 

In questi casi è possibile evidenziare tale generica relazione con l’uso dell’*Ordine pre-concordato collegato*, un Ordine in cui è presente il riferimento al Documento collegato e l’indicazione che si tratta di un mero collegamento (“Connected”).


[NOTE]
L’Ordine pre-concordato collegato può essere utilizzato esclusivamente per tenere memoria che il nuovo processo che si intende avviare è collegato ad un processo precedente e non deve mai essere usato al posto degli altri strumenti (Ordine pre-concordato di revoca, Ordine pre-concordato sostitutivo e Ordine di riscontro) appositamente realizzati per revocare, sostituire (o integrare), confermare o rifiutare un altro Documento.

Per le regole di compilazione, vedi paragrafo 6.12.


*[red]#Ordine pre-concordato di convalida#*

L’*Ordine pre-concordato di convalida* è un Ordine in cui è presente il riferimento alla fattura da regolarizzare e l’indicazione che si tratta della convalida di fattura (“Invoice”). 

L’Ordine pre-concordato di convalida può essere utilizzato esclusivamente: +

* per convalidare una fattura emessa in assenza della relativa ordinazione della fornitura tramite NSO;
* se necessario, per convalidare una fattura emessa a fronte di una Ordinazione già effettuata da un soggetto diverso dal Cliente (ad esempio, da una centrale d’acquisto o da un altro ente che è stato successivamente incorporato, ceduto o diviso).

[NOTE]
L’Ordine pre-concordato di convalida non deve mai essere usato al posto degli altri strumenti (Ordine di revoca, Ordine sostitutivo e Ordine di riscontro) appositamente realizzati per revocare, sostituire, confermare o rifiutare un altro Documento.

.Regole di compilazione 

In caso di *Ordine pre-concordato di convalida*, bisogna riportare gli estremi della fattura da regolarizzare nell’elemento “OrderDocumentReference/ID”, valorizzandolo con i valori e l'ordine di successione riportato:

* il *numero* della fattura che si intende convalidare:

* la *data di emissione* della fattura che si intende convalidare;

* l’*identificativo fiscale* del soggetto che ha emesso la fattura che si intende convalidare;

* il testo *“Invoice”* per indicare che si tratta di un Ordine di convalida di una fattura (o di una richiesta di pagamento equivalente).

.Esempio
[source, xml, indent=0]
----
<cac:OrderDocumentReference>
    <cbc:ID>57#2018-01-30# ITccccccccccc#Invoice</cbc:ID>
</cac:OrderDocumentReference >
----






