[[benefits]]
= Benefici

La fattura e la nota di credito forniscono un supporto semplice per le casistiche di fatturazione complessa, laddove è necessaria la nota di credito in aggiunta alla fattura. Altri potenziali benefici sono:

* Può essere resa obbligatoria di base per iniziative di fatturazione elettronica nazionale o regionale.
* Le stazioni appaltanti possono usarla come base per spostare tutte le fatturazioni in formato elettronica. La flessibilità delle specifiche permette agli acquirenti di automatizzare gradualmente l’elaborazione delle fatture, mediante diversi set di identificatori o riferimenti, e basandosi su un approccio costi/benefici.
* Le PMI possono offrire ai loro partner commerciali l’opzione di scambiare documenti standardizzati in un modo uniforme e quindi muovere tutte le fatture/n.c. in formato elettronico.
* Le grandi aziende possono implementare queste transazioni come documenti standardizzati per l’operatività generale e implementare connessioni bilaterali customizzate verso partner commerciali più grandi.
* Supportare i clienti che hanno bisogno nelle interazioni più complesse.
* Può essere utilizzato come base per ristrutturare i processi interni di fatturazione.
* La stazione appaltante può realizzare un notevole risparmio automatizzando e razionalizzando i suoi processi interni. La contabilità può essere automatizzata in modo significante, il ciclo di approvazione può essere semplificato e razionalizzato, i pagamenti possono essere programmati in tempo e la revisione contabile automatizzata.
