[[Accounting-Cost]]
= #Accounting Cost#

The accounting classification can be indicated at the document level valorizing the element “AccountingCost”.

For instance, given the cost account “BA0040 – Medicinal products with AIC”:


[source, xml, indent=0]
----
<cbc:AccountingCost>BA0040</cbc:AccountingCost>
----

To indicate the accounting classification at the line level it is necessary to valorize the element "AccountingCost” within the segment “OrderLine/LineItem". +

For istance, given the cost account “BA0350 – Informatic support and stationary”:


[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
        <cbc:AccountingCost>BA0350</cbc:AccountingCost>
    </cac:LineItem>
</cac:OrderLine>
----

With reference to the medical devices, the element  “AccountingCost” must be always valorized to provide information about the entry of the Balance Sheet/Income Statement, which needs to be reported later in the Invoice by the Seller into the element of FatturaPA “RiferimentoAmministrazione”, according to the instruction of Ministerial Circular MEF-MDS of 17 March 2020 “Fatture elettroniche riguardanti dispositivi medici - Individuazione delle fatture di interesse per l'applicazione delle disposizioni previste dall'articolo 9-ter del decreto-legge 19 giugno 2015 n. 78, come modificato dalla Legge 30 dicembre 2018, n. 145, art. 1, comma 557”. +

In all the remaining cases, the element “AccountingCost” can be valorized as the most appropriate way, for example with a cost account, center account, both, or any other accounting classification. +

The information must be separated by the character "#".

Given the provisions of regulation in force, the placelement of information in the fiels "AccountingCost" must comply with the following order of priority:

* if necessary, the indication “COV-20” (see below);
* if necessary, the indication about RiferimentoAmministrazione of a medical device;
* further indications.


:leveloffset: +1

= Covid-19 epidemiological emergency

The Article 18 of Decree Law of 17 March 2020 prescribes the opening of a dedicated cost-center and marked with the unique code *"COV 20"*, in order to guarantee a distinction of the accounting eventi related to the management of Covid-19 epidemiological emergency.

*The appropriate element* to be used is the field `cbc:AccountingCost` (available both on the header and the line level), with the indication of the string "COV20".

Since in the section `cac:AdditionalDocumetReference` it is also possible to report information about possible measures for reference, such as expenditure deliberation (delibera), expenditure commitment (impegno), etc. (see paragraph 6.14), in order to facilitate the dinstiction of order strictly and uniquely related to COVID-1' emergency management, it is recommended to issue specific order for this purpose.

If this criterion is adopted, alternatively or in addition to what aforementioned, it is possible also to insert the string "COV20” inside the element for *Order identification* (`cbc:ID`). 


:leveloffset: -1





