[[Accounting-Cost]]
= #Accounting Cost#

The accounting classification can be indicated at the document level valorizing the element “AccountingCost”.

For instance, given the cost account “BA0040 – Medicinal products with AIC”:


[source, xml, indent=0]
----
<cbc:AccountingCost>BA0040</cbc:AccountingCost>
----

To indicate the accounting classification at the line level it is necessary to valorize the element "AccountingCost” within the segment “OrderLine/LineItem". +

For istance, given the cost account “BA0350 – Informatic support and stationary”:


[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
        <cbc:AccountingCost>BA0350</cbc:AccountingCost>
    </cac:LineItem>
</cac:OrderLine>
----

With reference to the medical devices, the element  “AccountingCost” must be always valorized to provide information about the entry of the Balance Sheet/Income Statement, which needs to be reported later in the Invoice by the Seller into the element of FatturaPA “RiferimentoAmministrazione”, according to the instruction of Ministerial Circular MEF-MDS of 17 March 2020 “Fatture elettroniche riguardanti dispositivi medici - Individuazione delle fatture di interesse per l'applicazione delle disposizioni previste dall'articolo 9-ter del decreto-legge 19 giugno 2015 n. 78, come modificato dalla Legge 30 dicembre 2018, n. 145, art. 1, comma 557”. +

In all the remaining cases, the element “AccountingCost” can be valorized as the most appropriate way, for example with a cost account, center account, both, or any other accounting classification. +

The information must be separated by the character "#".

Given the provisions of regulation in force, the placelement of information in the fiels "AccountingCost" must comply with the following order of priority:

* if necessary, the indication “COV-20” (see below);
* if necessary, the indication about RiferimentoAmministrazione of a medical device;
* further indications.


:leveloffset: +1

= Emergenza epidemiologica da Covid-19

L’articolo 18 del decreto-legge 17 marzo 2020, n. 18 prescrive l'apertura di un centro di costo dedicato contrassegnato dal codice univoco *"COV 20"*, al fine di garantire una tenuta distinta degli accadimenti contabili legati alla gestione dell’emergenza epidemiologica da COVID-19.

*L’elemento appropriato* da utilizzare è il campo `cbc:AccountingCost` (presente sia a livello di testata del Documento, sia a livello di linee d’ordine), con l’indicazione del testo "COV20".

Poiché nella sezione `cac:AdditionalDocumetReference` è anche possibile riportare informazioni su eventuali provvedimenti cui far riferimento, come delibere, impegni, ecc. (v. Paragrafo 6.14), per facilitare la distinzione degli acquisti legati  alla  gestione dell’emergenza epidemiologica da COVID-19, si suggerisce di emettere ordini specifici a tale fine.

Se si adotta questa soluzione, in alternativa o in aggiunta a quanto indicato nel precedentemente, è possibile inserire il testo "COV20” all’interno dell’*identificativo dell’Ordine* (campo `cbc:ID`). 


:leveloffset: -1





