[[altri-riferimenti]]
= #Other references#

To provide the details of CUP, DDT, IMPEGNO, DELIBERA, CONTRATTO and CONVENZIONE see the table below.

[cols="1,2,7", options="header"]
|====
s|Reference
s|Description
s|When to use it

|*CUP*
|Codice Unico Progetto
|At document level use +
`cac:AdditionalDocumentReference` (0.n) +

At line level use +
`cac:OrderLine/cac:LineItem/cac:Item/cac: ItemSpecificationDocumentReference/ID` (0..n)

|*DDT*
|Documento di Trasporto +
(usare solo per riferirsi a DDT precedentemente ricevuti nel corso di un conto deposito merce)
|At document level use +
`cac:AdditionalDocumentReference` (0.n) +

At line level use +
`cac:OrderLine/cac:LineItem/cac:Item/cac: ItemSpecificationDocumentReference/ID` (0..n)


|*IMPEGNO*
|Estremi Impegno
|At document level use +
`cac:AdditionalDocumentReference` (0.n) +

At line level use +
`cac:OrderLine/cac:LineItem/cac:Item/cac: ItemSpecificationDocumentReference/ID` (0..n)

|*DELIBERA*
|Estremi Delibera
|At document level use +
`cac:AdditionalDocumentReference` (0.n) +

At line level use +
`cac:OrderLine/cac:LineItem/cac:Item/cac: ItemSpecificationDocumentReference/ID` (0..n)

|*CONTRATTO*
|Estremi Contratto
|At document level use +
`cac:Contract` (0.1) +

At line level use +
`cac:OrderLine/cac:LineItem/cac:Item/cac: ItemSpecificationDocumentReference/ID` (0..n)

|*CONVENZIONE*
|Estremi Convenzione
|At document level use +
`cac:AdditionalDocumentReference` (0.n) +

At line level use +
`cac:OrderLine/cac:LineItem/cac:Item/cac: ItemSpecificationDocumentReference/ID` (0..n)

|====

.Example of a reference to the CUP code on the header level
[source, xml, indent=0]
----
<cac:AdditionalDocumentReference>
    <cbc:ID>J31E01000010004</cbc:ID>
<cbc:DocumentType>CUP</cbc:DocumentType>
</cac:AdditionalDocumentReference>
----
.Example of a reference to IMPEGNO and Despatch Advice on the line level
[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
        <cac:Item>
		...
            <cac:ItemSpecificationDocumentReference>
                <cbc:Id>IMPEGNO:123/2019 </cbc:Id>
            </cac:ItemSpecificationDocumentReference>
            <cac:ItemSpecificationDocumentReference>
                <cbc:Id>DDT:00001253/2019</cbc:Id>
            </cac:ItemSpecificationDocumentReference>
		...
        </cac:Item>
    </cac:LineItem>
</cac:OrderLine>
----


