[[Consegna-Delivery]]
= #Delivery#

:leveloffset: +1

= Delivery Location

Delivery information is required if the address differs from that of the party issuing the order. +

The place of delivery shall be the place where the supply of goods and/or services is to take place. It is indicated, at document header level, in the "Delivery/DeliveryLocation" element. +

If the place of delivery is an institutional address of the Customer to which a unique identifier made available to the Supplier has been associated, as in the case of the places of delivery for the PA recorded according to the coding published at the following link https://www.puntidiconsegna-nso.it/[Punti di consegna NSO], is possible to indicate the identifier in the cbc:ID element. 

.Example of delivery at Institutional Address 
[source, xml, indent=0]
----
<cac:Delivery> 
    <cac:DeliveryLocation> 
        <cbc:ID>CF-IdShipTo</cbc:ID> 
        <Name>Magazzino centralizzato</Name> 
    </cac:DeliveryLocation> 
    <cac:RequestedDeliveryPeriod> <1> 
        <cbc:StartDate>2018-05-15</cbc:StartDate> 
        <cbc:StartTime>08:00:00</cbc:StartTime> 
        <cbc:EndDate>2018-05-15</cbc:EndDate> 
        <cbc:EndTime>13:00:00</cbc:EndTime> 
    </cac:RequestedDeliveryPeriod> 
    <cac:DeliveryParty> 
        <cac:PartyIdentification> 
            <cbc:ID schemeID="0201">AAFF33</cbc:ID> 
        </cac:PartyIdentification> 
        <cac:PartyName> 
            <cbc:Name>Centro Logistico Beni Sanit-Ecom Area 2</cbc:Name> 
        </cac:PartyName> 
        <cac:Contact> 
            <cbc:Name>ResponsabileMagazzino</cbc:Name> 
            <cbc:Telephone>0516361509</cbc:Telephone> 
      <cbc:ElectronicMail>responsabile.magazzino@aziendasanitaria.it</cbc:ElectronicMail> 
        </cac:Contact> 
    </cac:DeliveryParty> 
</cac:Delivery> 
<cac:DeliveryTerms> 
    <cbc:ID>PORTO FRANCO</cbc:ID> 
</cac:DeliveryTerms> 
----
<1> Requested delivery period: specify in this structure the information if the day ("StartDate/EndDate" fields) and the time ("StartTime/EndTime" fields) of the delivery execution has been agreed. 

If, on the other hand, the delivery of goods and/or the provision of services is to take place at a non-institutional place or in an institutional place not coded (even temporarily), all parts of the sub-element "Address" must be precisely indicated as shown in the following example: 

. Example of delivery at non-Institutional Address 
[source, xml, indent=0]
<cac:Delivery> 
    <cac:DeliveryLocation> 
        <Name>Nuovo magazzino di reparto</Name> 
        <cac:Address> 
            <cbc:StreetName>Viale Ercolani, 4</cbc:StreetName> 
            <cbc:CityName>Bologna</cbc:CityName> 
            <cbc:PostalZone>40138</cbc:PostalZone> 
            <cbc:CountrySubentity>BO</cbc:CountrySubentity> 
            <cac:AddressLine> 
                <cbc:Line>Orario:Lunedì-Venerdì 8:00-13:00 - Sabato 8:00-12:00</cbc:Line> <1>
            </cac:AddressLine> 
            <cac:Country> 
                <cbc:IdentificationCode>IT</cbc:IdentificationCode> 
            </cac:Country> 
        </cac:Address> 
… 
    </cac:DeliveryLocation> 
</cac:Delivery> 
----
<1> Information on the opening time of the warehouse. 

If it is a home delivery (for example, to a patient’s address), this circumstance must be specified by enhancing the "ID" field with the text "Home delivery" and indicating precisely in the structure "Address" the exact delivery address, as shown in the following example: 

.Example of home delivery
[source, xml, indent=0]
----
<cac:Delivery> 
    <cac:DeliveryLocation> 
        <cac:ID>Consegna domiciliare</cac:ID> 
        <Name>Entrata lato portineria</Name> 
        <cac:Address> 
            <cbc:StreetName>Via Attanasio Soldati 80</cbc:StreetName> 
            <cbc:AdditionalStreetName>Località La Rustica</cbc:AdditionalStreetName> 
            <cbc:CityName>Roma</cbc:CityName> 
            <cbc:PostalZone>00155</cbc:PostalZone> 
            <cbc:CountrySbentity>Lazio</cbc:CountrySubentity> 
            <cac:AddressLine> 
                <cbc:Line>Edificio C, Quarto piano, Stanza 01</cbc:Line> 
            </cac:AddressLine> 
            <cac:Country> 
              <cbc:IdentificationCode>IT</cbc:IdentificationCode> 
            </cac:Country> 
        </cac:Address> 
    </cac:DeliveryLocation> 
</cac:Delivery> 
----


:leveloffset: -1


:leveloffset: +1

= Delivery Party

If the delivery party, the party to whom the goods are delivered, is a determined subject, it is necessary to indicate it with precisely by valorizing the fields of the element `cac:DeliveryParty`. +

The indication of the Deliver party is possible only with the reference to the whole Document. +

The following example describes a delivery to a particular organizational unit:

[source, xml, indent=0]
----
<cac:Delivery>
    <cac:DeliveryParty>
          <cac:PartyIdentification>
          <cbc:ID>UO07</cbc:ID>
          <cac:PartyName>
              <cbc:Name>Centro logistico</cbc:Name>
     </cac:PartyName>
     <cac:Contact>
         <cbc:Name>James Bond</Name
         <cbc:Telephone>0647611</cbc:Telephone>
         <cbc:ElectronicMail>james.bond@peo.it</ ElectronicMail>
        </cac:Contact>
        </cac:PartyIdentification>
    </cac:DeliveryParty>
</cac:Delivery>
---- 

When the "Beneficiary" needs to be indicated, the identifier (field “ID”) and denomination (field “Name”) of the organizational unit are both mandatory. If the identifier is unknown or does not exist, it is sufficient to fill the element with the text “UO” (abbreviation for organizational unit). +

If the Beneficiary is a natural person, it is necessary to balance the need of protecting their confidentiality with the necessity of giving complete and exhaustive information for the delivery. To this end: +

* if it is not strictly necessary to indicate the extended name of the Beneficiary, the field “Name” must be filled with “PF” (abbreviation for physical person).
* if an identifier was assigned to the Beneficiary, this must be indicated into the field “ID”,  otherwise even this must be filled with “PF”.

:leveloffset: -1


:leveloffset: +1

= Shipping Marks

The Buyer can require to the Seller, if needed, to print a text over the shipping label by properly valorizing the field “TransportHandlingUnit/ShippingMarks” of the element “Shipment”, as shown below:

[source, xml, indent=0]
----
<cac:Delivery>
    <cbc:ID>NA</cbc:ID> 
    <cac:Shipment>
        <cac:TransportHandlingUnit>
            <cbc:ShippingMarks>aaaaaaaaaa</cbc:ShippingMarks>
        </cac:TransportHandlingUnit>
    </cac:Shipment>
</cac:Delivery>
---- 

:leveloffset: -1
