[[Consegna-Delivery]]
= #Delivery#

:leveloffset: +1

= Delivery Location


Information about the delivery are necessary if the address differ from the one of the Party that send the order and if allows to provide more precise indications about the returns of goods (DeliveryTerms). The warehouse opening time needs to be inserted in the elements "AddressLine/Line" of segment "Address".

The delivery location is the location in which the provision of goods or services needs to happen. It is represented by the elements “Delivery/DeliveryLocation”.

Il luogo di consegna può essere indicato anche a livello di linea d’ordine
utlizzando il campo "Delivery/ID" dell’elemento "OrderLine/LineItem". Si tratta, tuttavia,
di una pratica sconsigliata se non preventivamente concordata tra Cliente e Fornitore. +

.Esempio dell'indicazione del Delivery/ID sulle linee d'ordine
[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
        ...
        <cac:Delivery>
            <cbc:ID>123456788901-acdg45</cbc:ID>
            ...
        </cac:Delivery>
        ...
    <cac:LineItem>
</cac:OrderLine>
----

If the delivery address is the Client's institutional address to which a unique identifier has been associated, made available by the Seller, it is necessary to provide also this identifier, as shown by the followign example:

[source, xml, indent=0]
----
<cac:Delivery>
    <cac:DeliveryLocation>
        <cbc:ID>CF-IdShipTo</cbc:ID>
        <Name>Magazzino centralizzato</Name>
        <cac:Address>
            <cbc:StreetName>Viale Ercolani, 4</cbc:StreetName>
            <cbc:CityName>Bologna</cbc:CityName>
            <cbc:PostalZone>40138</cbc:PostalZone>
            <cbc:CountrySubentity>BO</cbc:CountrySubentity>
            <cac:AddressLine>
                <cbc:Line>Orario:Lunedì-Venerdì 8:00-13:00 - Sabato 8:00-12:00</cbc:Line>
            </cac:AddressLine>
            <cac:Country>
                <cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
            </cac:Country>
        </cac:Address>
    </cac:DeliveryLocation>
    <cac:RequestedDeliveryPeriod>
        <cbc:StartDate>2018-05-15</cbc:StartDate>
        <cbc:EndDate>2018-05-15</cbc:EndDate>
    </cac:RequestedDeliveryPeriod>
    <cac:DeliveryParty>
        <cac:PartyIdentification>
            <cbc:ID schemeID="0201">AAFF33</cbc:ID>
        </cac:PartyIdentification>
        <cac:PartyName>
            <cbc:Name>Centro Logistico Beni Sanit-Ecom Area 2</cbc:Name>
        </cac:PartyName>
        <cac:Contact>
            <cbc:Name>ResponsabileMagazzino</cbc:Name>
            <cbc:Telephone>0516361509</cbc:Telephone>
            <cbc:ElectronicMail>responsabile.magazzino@aziendasanitaria.it</cbc:ElectronicMail>
        </cac:Contact>
    </cac:DeliveryParty>
</cac:Delivery>
<cac:DeliveryTerms>
    <cbc:ID>PORTO FRANCO</cbc:ID>
</cac:DeliveryTerms>
----

On the other hand, if the provision of goods and services  must take place in a non-institutional location or institutional location not coded (even temporarily), it is necessary to indicate precisely all the elements and sub-information inside de segment “Address”, as shown by the following example:

.Example
[source, xml, indent=0]
----
<cac:Delivery>
    <cac:DeliveryLocation>
        <Name>Entrata magazzino merci</Name>
        <cac:Address>
            <cbc:StreetName>Via Attanasio Soldati 80</cbc:StreetName>
            <cbc:AdditionalStreetName>Località La Rustica</cbc:AdditionalStreetName>
            <cbc:CityName>Roma</cbc:CityName>
            <cbc:PostalZone>00155</cbc:PostalZone>
            <cbc:CountrySbentity>Lazio</cbc:CountrySubentity>
            <cac:AddressLine>
                <cbc:Line>Edificio C, Quarto piano, Stanza 01</cbc:Line>
            </cac:AddressLine>
            <cac:Country>
                <cbc:IdentificationCode>IT</cbc:IdentificationCode>
            </cac:Country>
        </cac:Address>
    </cac:DeliveryLocation>
</cac:Delivery>
----

In the case of *home delivery* (for example, delivery to the address of a patient) this circumstance needs to be specified valorizing the field “ID” with the text “Consegna domiciliare” and indicating accurately in the element “AddressLine/Line” the exact delivery address (for instance, including the flat number), as shown by the following example:


.Example
[source, xml, indent=0]
----
<cac:Delivery>
    <cac:DeliveryLocation>
        <cac:ID>Consegna domiciliare</cac:ID>
        <Name>Entrata lato portineria</Name>
        <cac:Address>
            <cbc:StreetName>Via Attanasio Soldati 80</cbc:StreetName>
            <cbc:AdditionalStreetName>Località La Rustica</cbc:AdditionalStreetName>
            <cbc:CityName>Roma</cbc:CityName>
            <cbc:PostalZone>00155</cbc:PostalZone>
            <cbc:CountrySbentity>Lazio</cbc:CountrySubentity>
            <cac:AddressLine>
                <cbc:Line>Edificio C, Quarto piano, Stanza 01</cbc:Line>
            </cac:AddressLine>
            <cac:Country>
                <cbc:IdentificationCode>IT</cbc:IdentificationCode>
            </cac:Country>
        </cac:Address>
    </cac:DeliveryLocation>
</cac:Delivery>
----

:leveloffset: -1

:leveloffset: +1

= Etichette imballaggio (ShippingMarks)

Se necessario, il Cliente può richiedere al Fornitore di stampare un testo sull’etichetta di imballaggio, valorizzando in modo appropriato il campo “TransportHandlingUnit/ShippingMarks” dell’elemento “Shipment”, come mostrato nel seguente esempio:

[source, xml, indent=0]
----
<cac:Delivery>
 <cac:Shipment>
  <cac:TransportHandlingUnit>
   <cbc:ShippingMarks>aaaaaaaaaa</cbc:ShippingMarks>
  </cac:TransportHandlingUnit>
 </cac:Shipment>
</cac:Delivery>
---- 

:leveloffset: -1
