[[Accounting-Cost]]
= #Accounting Cost#

Per indicare la classificazione contabile a livello di testata, occorre valorizzare l’elemento “AccountingCost”.

Ad esempio, dato il conto di costo “BA0040 – Medicinali con AIC”:


[source, xml, indent=0]
----
<cbc:AccountingCost>BA0040</cbc:AccountingCost>
----

Per indicare la classificazione contabile a livello di linea d’ordine, occorre valorizzare il campo “AccountingCost” dell’elemento “OrderLine/LineItem". Ad esempio, dato il conto di costo “BA0350 – Supporti informatici e cancelleria”:


[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
        <cbc:AccountingCost>BA0350</cbc:AccountingCost>
    </cac:LineItem>
</cac:OrderLine>
----

Con riguardo agli ordini di dispositivi medici si segnala che l’elemento “AccountingCost” deve essere necessariamente valorizzato per fornire l’informazione circa la voce di Stato Patrimoniale/Conto Economico, che deve essere poi riportata in fattura dal Fornitore nel campo “RiferimentoAmministrazione” secondo le previsioni della Circolare MEF-MDS del 17 marzo 2020 “Fatture elettroniche riguardanti dispositivi medici - Individuazione delle fatture di interesse per l'applicazione delle disposizioni previste dall'articolo 9-ter del decreto-legge 19 giugno 2015 n. 78, come modificato dalla Legge 30 dicembre 2018, n. 145, art. 1, comma 557”. +

[NOTE]
====
L’elemento “AccountingCost” deve essere utilizzato anche per evidenziare le spese riferibili al centro di costo “COV20” previsto dall’articolo 18 del decreto-legge 17 marzo 2020, n. 18. 
====

Negli altri casi, l’elemento “AccountingCost” può essere valorizzato nel modo che si ritiene più adeguato, ad esempio con il conto di costo, con il centro di costo, con entrambi o con qualsivoglia altra classificazione contabile. +

Le informazioni devono essere separate con il carattere “#.


