[[order-reference]]
= Riferimento all’Ordine

Usato per fornire riferimento all’ordine d’acquisto sul quale il Documento di Trasporto si basa.
Ci potrebbero essere molteplici documenti di trasporto a fronte di un ordine d’acquisto. +

Quando tutte le righe del Documento di Trasporto sono relative allo stesso ordine di acquisto, il riferimento dell'ordine è indicato solo in testata. +
Quando le righe del Documento di Trasporto sono relative a diversi ordini di acquisto, i riferimenti all’ordine devono essere indicati a livello di riga. +


Inoltre, la sintassi UBL richiede di indicare obbligatoriamente nell’elemento *cbc:LineID* il numero della riga d’ordine cui si riferisce la riga del DDT.
Per soddisfare gli scenari in cui non esiste alcun riferimento alla riga dell'ordine, è necessario applicare un valore fittizio. Il valore fittizio deve essere costituito dai caratteri *NA*.

#Per riferirsi a un ordine elettronico è necessario riportare gli elementi che lo identificano mediante la concatenazione dei seguenti campi:#

* #ID dell’ordine;#
* #IssueDate valorizzato con la data dell’ordine;#
* #EndpointID dell’elemento BuyerCustomerParty dell’ordine;#

.Esempio a livello di testata
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-2.xml[tags=ref-order]
----

.Esempio 1 a livello di riga
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-2.xml[tags=ref-orderline]
----

.Esempio 2 a livello di riga
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-2.xml[tags=ref-orderlinena]
----

E' inoltre possibile riferirsi a più di un ordine in un singolo documento di trasporto.
In questo caso non ci deve essere un riferimento all'ordine a livello di testata.

#Per riferirsi a più ordini sarà quindi possibile indicare uno o più numeri d’ordine su ogni riga del DDT.#

.Esempio 3 a livello di riga con riferimento a più ordini
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-3.xml[tags=ref-orderlinemulti]
----

== Riferimento supplementare all’Ordine
#Quando il documento di trasporto si riferisce ad un singolo ordine dalla testata, con l'elemento cbc:CustomerReference è possibile fornire un ulteriore riferimento del cliente.#

#Questo ulteriore riferimento si presta ad essere utilizzato come riferimento emesso dal cliente per identificare l'oggetto della spedizione, come ad esempio il destinatario finale di farmaci (ID Paziente) in una consegna domiciliare (vedi §. 6.3.1)#

.Esempio di riferimento del cliente in una consegna domiciliare:
[source, xml, indent=0]
----
<cac:OrderReference>
    <cbc:ID>4321#2013-01-30#ABCDEF</cbc:ID>
    <!-- ID Paziente -->
    <cbc:CustomerReference>123</cbc:CustomerReference>
</cac:OrderReference>
----