[[parties]]
= Parti e Ruoli

Le seguenti parti/ruoli possono essere specificate nel messaggio.  Lo stesso attore gioca più di un ruolo a seconda dei casi.

[[despatch-party-despatchsupplierparty]]
== Speditore/Mittente (DespatchSupplierParty)

Lo Speditore/Mittente è la persona giuridica o l'organizzazione che spedisce la merce e/o i servizi ed è un’informazione obbligatoria. Questo ruolo viene ricoperto dal Fornitore o per suo conto. +
#Ai sensi dell’Art. 21, comma 4 del DPR n. 633/1972 lo Speditore/Mittente corrisponde al Venditore qualora la sezione Venditore non sia valorizzata.#


.Esempio di informazioni dello Speditore/Mittente
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=despatchsupplier]
----

<1> la Partita IVA viene specificata inserendo l'attributo @schemeID valorizzato con il codice "0211"


[[consignee-deliverycustomerparty]]
== Consegnatario/Destinatario (DeliveryCustomerParty)

Il Consegnatario/Destinatario è la persona giuridica o l’organizzazione che riceve beni e/o servizi oggetto dell’ordine ed è un’informazione obbligatoria. Questo ruolo viene ricoperto dal Cliente o per suo conto. +
#Ai sensi dell’Art. 21, comma 4 del DPR n. 633/1972 il Consegnatario/Destinatario corrisponde all’Acquirente qualora la sezione Acquirente non sia valorizzata.#


.Esempio di informazioni del Consegnatario/Destinatario
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=deliverycustomer]
----

<1> il Codice Fiscale viene specificato inserendo l'attributo @schemeID valorizzato con il codice "0210"


[[buyer-buyercustomerparty]]
== Acquirente (BuyerCustomerParty)

L’Acquirente è la persona giuridica o l’organizzazione che acquista beni e/o servizi. +
#Ai sensi dell’Art. 21, comma 4 del DPR n. 633/1972 il Consegnatario/Destinatario corrisponde all’Acquirente qualora la sezione Acquirente non sia valorizzata.#

.Esempio di informazioni dell’Acquirente
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=buyer]
----


[[seller-sellersupplierparty]]
== Venditore (SellerSupplierParty)

Il Venditore è la persona giuridica o l’organizzazione che vende beni e/o servizi. +
#Ai sensi dell’Art. 21, comma 4 del DPR n. 633/1972 lo Speditore/Mittente corrisponde al Venditore qualora la sezione Venditore non sia valorizzata.#

.Esempio di informazioni del Venditore
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=seller]
----


[[originating-party-originatorcustomerparty]]
== Richiedente (OriginatorCustomerParty)

Il Richiedente è la persona giuridica o l’organizzazione che inizializza il processo di emissione dell'Ordine e per la quale l'Acquirente effettua l'acquisto. +
Il Richiedente è un’informazione opzionale.

.Esempio di informazioni del Richiedente
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=originator]
----


[[carrier-party-carrierparty]]
== Vettore (CarrierParty)

Il Vettore è la persona giuridica o l'organizzazione che gestisce la consegna/trasporto fisico della spedizione. Utilizzato se il trasporto è effettuato da una terza parte. +
#Ai sensi dell’Art. 21, comma 4 del DPR n. 633/1972 il Vettore è un’informazione obbligatoria.#

.Esempio di informazioni del Vettore
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=carrier]
----
