[[parties]]
= Parti e Ruoli

Le seguenti parti/ruoli possono essere specificate nel messaggio.  Lo stesso attore gioca più di un ruolo a seconda dei casi.

[[despatch-party-despatchsupplierparty]]
== Speditore/Mittente (DespatchSupplierParty)

Lo Speditore/Mittente è la persona giuridica o l’organizzazione che spedisce la merce e/o eroga i servizi ed è un’informazione obbligatoria. Questo ruolo viene ricoperto dal Fornitore o per suo conto.


.Esempio di informazioni dello Speditore/Mittente
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=despatchsupplier]
----

<1> Il campo cbc:ID deve contenere l’identificativo fiscale dello Speditore/Mittente, preceduto dal prefisso corrispondente al paese in cui risiede, e valorizzato dallo @schemeID corrispondente secondo la codelist ISO 6523 ICD list. In caso di OE italiano, il campo DEVE contenere la Partita IVA del soggetto, preceduta dal prefisso “IT”, valorizzata con lo @schemeID pari a “0211”. 
<2> Le informazioni di indirizzo dello Speditore/Mittente sono obbligatorie. +

Se lo Speditore/Mittente è un’amministrazione pubblica, il campo EndpointID deve contenere il Codice Univoco Ufficio (c.d. "Codice IPA", riportato nell’Indice delle Pubbliche Amministrazioni) della PA e il relativo @schemeID deve essere valorizzato con “0201”. In aggiunta, il campo RegistrationName deve contenere la denominazione della PA in forma estesa. 

.Esempio di informazioni dello Speditore/Mittente in caso di Pubblica Amministrazione italiana
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=despatchsupplierpa]
----

<1> Il campo cbc:EndpointID contiene il Codice IPA dell’Ufficio che emette il DDT, valorizzato con lo @schemeID pari a “0201”;
<2> Il campo cbc:ID contiene la Partita IVA della PA valorizzata con lo @schemeID pari a “0211”;
<3> La struttura contiene le informazioni di indirizzo relative alla sede legale della PA; 
<4> Il campo contiene la denominazione della PA in forma estesa.



[[consignee-deliverycustomerparty]]
== Consegnatario/Destinatario (DeliveryCustomerParty)

Il Consegnatario/Destinatario è la persona giuridica o l’organizzazione che riceve beni e/o servizi oggetto dell’ordine ed è un’informazione obbligatoria. Questo ruolo viene ricoperto dal Cliente o per suo conto.


.Esempio di informazioni del Consegnatario/Destinatario
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=deliverycustomer]
----

<1> #Il campo cbc:EndpointID DEVE contenere il Codice Univo Ufficio della pubblica amministrazione (codice IPA) valorizzato con lo @schemeID pari a “0201”;#
<2> #Il campo cbc:ID DEVE contenere il Codice Fiscale del Consegnatario/Destinatario valorizzato con lo @schemeID pari a “0210”;#
<3> #Le informazioni di indirizzo del Consegnatario/Destinatario sono obbligatorie e devono corrispondere alla sede legale della PA;# 
<4> #Il campo deve essere compilato con la denominazione della PA in forma estesa.#



[[buyer-buyercustomerparty]]
== Acquirente (BuyerCustomerParty)

#L'Acquirente corrisponde alla parte Cessionaria ai sensi dell’Art. 1, comma 3 del DPR n. 472/1996 ed è un'informazione obbligatoria.#
.Esempio di informazioni dell’Acquirente
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=buyer]
----

<1> #Il campo cbc:ID DEVE contenere il Codice Fiscale dell’Acquirente valorizzato con lo @schemeID pari a “0210”;#
<2> #Il campo deve essere compilato con la denominazione della PA in forma estesa#
<3> #Le informazioni di indirizzo dell’Acquirente sono obbligatorie e devono corrispondere alla sede legale della PA;#

[NOTE]
In caso di coincidenza tra Acquirente e Consegnatario/Destinatario entrambe le parti devono riportare la medesima denominazione della PA cliente in forma estesa.

[[seller-sellersupplierparty]]
== Venditore (SellerSupplierParty)

#Il Venditore corrisponde alla parte Cedente ai sensi dell’Art. 1, comma 3 del DPR n. 472/1996 ed è un'informazione obbligatoria.#

.Esempio di informazioni del Venditore
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=seller]
----

<1> Il campo cbc:ID DEVE contenere l’identificativo fiscale del Venditore, preceduto dal prefisso corrispondente al paese in cui risiede, e valorizzato dallo @schemeID corrispondente secondo la codelist ISO 6523 ICD list. #In caso di OE italiano, il campo DEVE contenere la Partita IVA del soggetto, preceduta dal prefisso “IT”, valorizzata con lo @schemeID pari a “0211”;#
<2> #Le informazioni di indirizzo del Venditore sono obbligatorie.#


[[originating-party-originatorcustomerparty]]
== Richiedente (OriginatorCustomerParty)

Il Richiedente è l'Unità Organizzativa facente parte dell'Acquirente o la persona fisica che esprime il fabbisogno che dà avvio al processo di acquisto.
Il Richiedente è un’informazione opzionale.

.Esempio di informazioni del Richiedente
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=originator]
----


[[carrier-party-carrierparty]]
== Vettore (CarrierParty)

#Il Vettore è un'informazione obbligatoria ai sensi dell’Art. 1, comma 3 del DPR n. 472/1996.#

.Esempio di informazioni del Vettore
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=carrier]
----

<1> Il campo cbc:ID DEVE contenere l’identificativo fiscale del Vettore, preceduto dal prefisso corrispondente al paese in cui risiede, e valorizzato dallo @schemeID corrispondente secondo la codelist ISO 6523 ICD list. #In caso di OE italiano, il campo DEVE contenere la Partita IVA del soggetto, preceduta dal prefisso “IT”, valorizzata con lo @schemeID pari a “0211”;#
<2> #Le informazioni di indirizzo del Vettore sono obbligatorie.#

