[[shipment]]
= Spedizione

Descrizione della spedizione effettiva che contiene la merce che è stata spedita.

[[shipment-id]]
== ID Spedizione, #informazioni di trasporto ed evasione#

#L’identificativo indica una determinata spedizione ed, in particolare, è utilizzato per restituire informazioni sull’esito della stessa all'interno dell’avviso di ricezione. Pertanto, nei casi in cui è applicabile, è obbligatorio valorizzare il campo con un codice identificativo.#

In alcuni usi del Documento di Trasporto, non c’è un unico identificatore assegnato alla spedizione. Comunque, la sintassi UBL richiede che lo Shipment ID sia specificato. Conseguentemente, per poter utilizzare elementi come GrossWeightMeasure o CarrierParty, lo Shipment/ID deve essere valorizzato. Per supportare scenari dove non è disponibile o non è utilizzato l’ID della spedizione si deve usare il valore **NA**.

Come parte delle informazioni di spedizione (Shipment) vengono forniti: peso, volume, colli, vettore, tempi di consegna stimati e di effettiva evasione.

[NOTE]
#Le misure come peso e volume sono obbligatoriamente espresse secondo unità di misura in base alla codifica link:../../../../../../xml/ITA/peppol-bis-3/codelist/UNECERec20-11e.html[UN/ECE Recommendation 20, including Recommendation 21 codes]. Le codifiche utilizzabili sono quelle correlate ad unità di misura italiane ed evidenziate in azzuro.#

.Esempio di informazioni relative a spedizione, trasporto ed evasione:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-3.xml[tags=shipment]
----

<1> Codice identificativo della spedizione;
<2> Peso lordo – #informazione obbligatoria ai sensi dell’Art. 1, comma 3 del DPR n. 472/1996;#
<3> Volume lordo;
<4> Numero di colli #(da esprimere come numero intero) – informazione obbligatoria ai sensi Art. 1, comma 3 del DPR n. 472/1996;#
<5> Codice identificativo del trasporto;
<6> Informazioni sul Vettore, si rimanda al paragrafo 6.1.6 Vettore (CarrierParty);
<7> Informazioni sulle modalità di spedizione;
<8> Tempi di consegna stimati;
<9> Indirizzo di consegna, si rimanda al paragrafo 6.3.2 Luogo di consegna.


[[despatchaddress]]
== #Indirizzo di consegna#

Le informazioni relative al luogo di consegna devono essere indicate all’interno della struttura cac:DespatchAddress in cui è possibile specificare l’indirizzo e la denominazione del luogo di consegna.

Se il luogo di consegna è un indirizzo istituzionale del Cliente a cui è stato associato un identificativo univoco reso disponibile al Fornitore, come avviene nel caso dei luogo di consegna per le PA censiti secondo la codifica https://www.puntidiconsegna-nso.it/[Punti di consegna], è possibile indicare anche tale identificativo, come mostrato nel seguente esempio:

.Esempio di indicazione dell’indirizzo di consegna:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-3.xml[tags=despatchaddress]
----

<1> Codice identificativo del luogo di consegna secondo un sistema di codifica conosciuto dalle parti
<2> Indirizzo del luogo di consegna
<3> #Denominazione del luogo di consegna#

Se la consegna è di tipo domiciliare, effettuata presso l'abitazione di una persona fisica, è possibile indicarlo inserendo la stringa "PF" all'interno dell'elemento cbc:ID della struttura cac:DespatchAddress.