
[[allowance-calc]]
= Calculation of allowance/charge amount

Allowance and charge on document- and line level consists of elements carrying information on the allowance/charge base amount and the allowance/charge percentage. These are, if present in the invoice instance, used for calculating the allowance/charge amount.

If base amount is present, the percentage shall also be present, and if percentage is present, the base amount shall also be present, and the calculation of the amount shall be:

====
stem:["Amount" =  "Base amount" times ("Percentage" div 100)]
====

[IMPORTANT]
#Within the national context, allowance and charge on document level is used only for social security contribution (see paragraph 5.8) and stamp duty (see paragraph 5.9).#

#A typical example of a charge expressed with both a base amount and a percentage is the social security contribution (see paragraph 5.8).#

.UBL example of calculations of allowances and charges where base amount and percentage exist
[source, xml, indent=0]
----
<cac:AllowanceCharge>
    <cbc:ChargeIndicator>true</cbc:ChargeIndicator>
    <cbc:AllowanceChargeReasonCode>CG</cbc:AllowanceChargeReasonCode>
    <cbc:AllowanceChargeReason>Cleaning</cbc:AllowanceChargeReason>
    <cbc:MultiplierFactorNumeric>20</cbc:MultiplierFactorNumeric> <!--2-->
    <cbc:Amount currencyID="EUR">200</cbc:Amount> <!--3-->
    <cbc:BaseAmount currencyID="EUR">1000</cbc:BaseAmount> <!--1-->
    <cac:TaxCategory>
        <cbc:ID>S</cbc:ID>
        <cbc:Percent>25</cbc:Percent>
        <cac:TaxScheme>
            <cbc:ID>VAT</cbc:ID>
        </cac:TaxScheme>
    </cac:TaxCategory>
</cac:AllowanceCharge>
----

<1> Base amount, to be used with the percentage to calculate the amount
<2> Charge percentage
<3> stem:["Base amount" times ("Percentage" div 100) = "Amount"]

#A typical example of an allowance/charge with only an amount is the stamp duty (see paragraph 5.9).#

.UBL example of calculations of allowances and charges where base amount and percentage does not exist
[source, xml, indent=0]
----
<cac:AllowanceCharge>
    <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
    <cbc:AllowanceChargeReasonCode>95</cbc:AllowanceChargeReasonCode>
    <cbc:AllowanceChargeReason>Discount</cbc:AllowanceChargeReason>
    <cbc:Amount currencyID="EUR">200</cbc:Amount> <!--1-->
    <cac:TaxCategory>
        <cbc:ID>S</cbc:ID>
        <cbc:Percent>25</cbc:Percent>
        <cac:TaxScheme>
            <cbc:ID>VAT</cbc:ID>
        </cac:TaxScheme>
    </cac:TaxCategory>
</cac:AllowanceCharge>
----

<1> Amount of allowance without calculations based on base amount and percentage