= Calcolo delle imposte

[[vat-calc]]
== Totale imposte

L'importo totale delle imposte (es. IVA in Italia) può essere specificato senza fornire il riepilogo delle imposte, ma se questo è presente, l'importo totale delle imposte è dato dalla somma di tutte le imposte per ogni categoria.


====
stem:["Importo totale IVA" = sum("Importo categoria IVA")]
====

== Riepilogo imposte

In Italia deve essere fornito il Riepilogo IVA per ogni combinazione distinta di codice categoria e aliquota IVA presente a livello di riga nelle informazioni IVA o in testata nelle maggiorazioni e sconti.

Per ogni combinazione distinta di codice categoria e aliquota IVA il calcoli necessari sono:
====
stem:["Imponibile IVA categoria" = sum("Importi netti di riga")] +
stem:[+ "Importo maggiorazione a livello di testata" - "Importo sconto a livello di testata"]
====

====
stem:["Importo categoria IVA" = "Imponibile categoria IVA" per ("Aliquota IVA" div 100)]
====

IMPORTANT: Per riepiloghi IVA dove la categoria IVA non è soggetta a IVA (O), l'importo categoria IVA deve essere zero.

Notate che per le aliquote IVA dovrebbero essere considerati solo i decimali significativi, es. qualsiasi differenza negli zeri finali non dovrebbe causare differenze nei riepiloghi IVA.

.Esempio
====
Riga 1 ha il codice categoria = S e aliquota IVA = *25* +
Riga 2 ha il codice categoria = S e aliquota IVA = *25.00* +
Questo dovrebbe dare origine ad un solo riepilogo IVA.
====

.Esempio UBL di totale e riepilogo imposte
[source, xml, indent=0]
----
include::../../snippets/snippet-oa-vat.xml[tags=taxtotal]
----
<1> La classe `cac:TaxCategory` è utilizzata per le informazioni sulla categoria d'imposta
<2> Categoria IVA secondo la codifica {vat-codes}
<3> Aliquota IVA
