.UBL example of using CPV
[source, xml, indent=0]
----
include::{snippet-dir}/item.xml[tags=cpv]
----
<1> listID must be from UNCL7143 code list, and code STI indicates this is a CPV classification.

.UBL example of UNSPSC
[source, xml, indent=0]
----
include::{snippet-dir}/item.xml[tags=unspsc]
----
<1> listID must be from UNCL7143 code list, and code TST indicates this is a UNSPSC classification, listVersionID is optional, but can be used to specify the version of UNSPSC. NOTE, in previous versions code MP was used as temporary workaround to identify UNSPSC. In fall release 2019 it is replaced with the new 7143 code TST that is specific for UNSPSC.


.Esempio UBL di Dispositivo medico
#In questo esempio viene fornito il numero di registrazione attribuito al dispositivo medico nella Banca dati e Repertorio Dispositivi Medici dal Ministero della Salute.#

#L’attributo schemeID dovrà essere valorizzato con:#

* #DM1 per “Dispositivo medico o Dispositivo diagnostico in vitro”#
* #DM2 per “Sistema o kit Assemblato”#
* #DM0 per "Nessun numero di repertorio"#

[source, xml, indent=0]
----
<cac:CommodityClassification>
    <cbc:ItemClassificationCode listID="ZZZ">DM1:130209/R</cbc:ItemClassificationCode> <1>
</cac:CommodityClassification>
<cac:CommodityClassification>
    <cbc:ItemClassificationCode listID="STO">M0201030202</cbc:ItemClassificationCode> <2> 
</cac:CommodityClassification>
----
<1> Il listID deve essere fra quelli della codifica UNCL7143 e il codice *ZZZ* indica che questo è una classificazione in base ad accordi bilaterali, mentre il listVersionID è opzionale.
<2> Il listID deve essere fra quelli della codifica UNCL7143 e il codice *STO* indica il codice CNDM (Classificazione Nazionale dei Dispositivi Medici)

