.UBL example of using CPV
[source, xml, indent=0]
----
<cac:CommodityClassification>
    <cbc:ItemClassificationCode listID="STI">09348023</cbc:ItemClassificationCode> <1>
</cac:CommodityClassification>
----
<1> listID must be from UNCL7143 code list, and code STI indicates this is a CPV classification.

.UBL example of UNSPSC
[source, xml, indent=0]
----
include::{snippet-dir}/item.xml[tags=unspsc]
----
<1> listID must be from UNCL7143 code list, and code TST indicates this is a UNSPSC classification, listVersionID is optional, but can be used to specify the version of UNSPSC. NOTE, in previous versions code MP was used as temporary workaround to identify UNSPSC. In fall release 2019 it is replaced with the new 7143 code TST that is specific for UNSPSC.


.#UBL example for Medical Device#
[source, xml, indent=0]
----
<cac:Item>
	<cbc:Description>Dispositivo Medico</cbc:Description>
	<cbc:Name>Prodotto 1143668 DEFIBRILLATORE SEMIAUTOMATICO LIFEPAK 1000</cbc:Name>
	<cac:SellersItemIdentification>
		<cbc:ID>1143668</cbc:ID> <1>
	</cac:SellersItemIdentification>
	<cac:CommodityClassification>
		<cbc:ItemClassificationCode listID="ZZZ">DM1:918674</cbc:ItemClassificationCode> <2>
	</cac:CommodityClassification>
	<cac:CommodityClassification>
		<cbc:ItemClassificationCode listID="STO">Z12030501</cbc:ItemClassificationCode> <3>
	</cac:CommodityClassification>
[…]
</cac:Item>
----
<1> Code of the medical device assigned by the Seller;
<2> #IlistID must be from UNCL7143 code list, and code ZZZ can be used to indicate the registration number assigned to the medical device in the Database and Register (BDR) of Medical Devices managed by the Italian Ministry of Health.# +

#The Registration number must be preceded by the following string:#
* "DM1:" for a Medical Device or In Vitro Diagnostic Device;
* "DM2:" for a System or Assembled Kit;
* "DM0" should be indicated if the medical device does not have a registration number.
<3> The listID must be one of those from the UNCL7143 code list, and the code STO indicates the code assigned to the medical device by the National Classification of Medical Devices (CND).