= Seller (AccountingSupplierParty)

Seller is mandatory information and provided in element *cac:AccountingSupplierParty*. +
The Seller is the natural person, legal person or organisation who provides products or services. The Seller is a mandatory information as it is the issuer of the document and it is inserted in the element *cac:AccountingSupplierParty*. Its EndpointID is also a mandatory element. #The Seller corresponds to the Cedente/Prestatore of the invoice pursuant to DPR no. 633/1972.#

.UBL example of information for an Italian seller with VAT number included in the Endpoint 
[source, xml, indent=0]
----
<cac:AccountingSupplierParty>
    <cac:Party>
	 <cbc:EndpointID schemeID="0211">IT01234567890</cbc:EndpointID>
	 <cac:PartyName>
	 	<cbc:Name>Fornitore S.p.A.</cbc:Name>
	 </cac:PartyName>
	 <cac:PostalAddress>
	 	<cbc:StreetName>Indirizzo Riga 1</cbc:StreetName>
	 	<cbc:AdditionalStreetName>Indirizzo Riga 2</cbc:AdditionalStreetName>
	 	<cbc:CityName>Bologna</cbc:CityName>
	 	<cbc:PostalZone>40121</cbc:PostalZone>
	 	<cbc:CountrySubentity>BO</cbc:CountrySubentity >
	 	<cac:AddressLine>
	 		<cbc:Line>Zona Savena</cbc:Line>
	 	</cac:AddressLine>
	 	<cac:Country>
	 	<cbc:IdentificationCode>IT</cbc:IdentificationCode>
	 	</cac:Country>
	 </cac:PostalAddress>
	 <cac:PartyTaxScheme>
	    <cbc:CompanyID>IT01234567890</cbc:CompanyID>
	    <cac:TaxScheme>
	        <cbc:ID>VAT</cbc:ID>
	    </cac:TaxScheme>
	 </cac:PartyTaxScheme>
	 <cac:PartyLegalEntity>
	 	<cbc:RegistrationName>Azienda fornitore</cbc:RegistrationName>
	 	<cbc:CompanyID schemeID="0210">01234567890</cbc:CompanyID>
	</cac:PartyLegalEntity>
	 <cac:Contact>
	 	<cbc:Name>Lucio Grande</cbc:Name>
	 	<cbc:Telephone>051102030</cbc:Telephone>
	 	<cbc:ElectronicMail>lucio.grande@fornitore.it</cbc:ElectronicMail>
	 </cac:Contact>
    </cac:Party>
</cac:AccountingSupplierParty>
----

#If the seller is a public administration, the element *EndpointID/@schemeID* must be set to *"0201:"* followed by the receiving Office Code (codice IPA) provided by the Public Administration.#

#The VAT number must be indicated in *cac:PartyTaxScheme/cbc:CompanyID*.#

#The Tax Identification Number (Codice Fiscale) must be indicated in *cac:PartyLegalEntity/cbc:CompanyID*, setting the *@schemeID* to *"0210"*.#

.UBL example of indicating VAT number and Tax Identification Number

[source, xml, indent=0]
----
<cac:AccountingSupplierParty>
 <cac:Party>
	<cbc:EndpointID schemeID="0201">UFY9MH</cbc:EndpointID>
	<cac:PartyName>
		<cbc:Name>Azienda USL di Reggio Emilia</cbc:Name>
	</cac:PartyName>
	<cac:PostalAddress>
		<cbc:StreetName>Via Amendola 2</cbc:StreetName>
		<cbc:CityName>Reggio Emilia</cbc:CityName>
		<cbc:PostalZone>42122</cbc:PostalZone>
		<cbc:CountrySubentity>RE</cbc:CountrySubentity>
		<cac:Country>
			<cbc:IdentificationCode>IT</cbc:IdentificationCode>
		</cac:Country>
	</cac:PostalAddress>
	<cac:PartyTaxScheme>
	    <cbc:CompanyID>IT01598570354</cbc:CompanyID>
	    <cac:TaxScheme>
	        <cbc:ID>VAT</cbc:ID>
	    </cac:TaxScheme>
	</cac:PartyTaxScheme>
	<cac:PartyLegalEntity>
		<cbc:RegistrationName>Azienda USL di Reggio Emilia</cbc:RegistrationName>
		<cbc:CompanyID schemeID="0210">01598570354</cbc:CompanyID>
	</cac:PartyLegalEntity>
	<cac:Contact>
		<cbc:Name>Giovanni Rossi</cbc:Name>
		<cbc:Telephone>0522335111</cbc:Telephone>
		<cbc:ElectronicMail>giovanni.rossi@ausl.re.it</cbc:ElectronicMail>
	</cac:Contact>
    </cac:Party>
</cac:AccountingSupplierParty>
----

.UBL example of information for a foreign seller
[source, xml, indent=0]
----
</cac:AccountingSupplierParty>
    <cac:Party>
	 <cbc:EndpointID schemeID="9925">0999999999</cbc:EndpointID
	 <cac:PartyName>
	 	<cbc:Name>Fornitore Estero</cbc:Name>
	 </cac:PartyName>
	 <cac:PostalAddress>
	 	<cbc:StreetName> Rue Emile Claus 28</cbc:StreetName>
		<cbc:AdditionalStreetName>Quartiere</cbc:AdditionalStreetName>
		<cbc:CityName>Bruxelles</cbc:CityName>
		<cbc:PostalZone>1050</cbc:PostalZone>
		<cac:AddressLine>
		<cbc:Line>Deposito Consegnatario: Fornitore Estero</cbc:Line>
		</cac:AddressLine>
			<cac:Country>
			<cbc:IdentificationCode>BE</cbc:IdentificationCode>
			</cac:Country>
	 </cac:PostalAddress>
	 <cac:PartyTaxScheme>
	    <cbc:CompanyID>BE0848934496</cbc:CompanyID>
	    <cac:TaxScheme>
	        <cbc:ID>VAT</cbc:ID>
	    </cac:TaxScheme>
	 </cac:PartyTaxScheme>
	 <cac:PartyLegalEntity>
	 	<cbc:RegistrationName>Fornitore Estero</cbc:RegistrationName>
	 </cac:PartyLegalEntity>
	 <cac:Contact>
	 	<cbc:Name>Lucio Grande</cbc:Name>
	 	<cbc:Telephone>003241102030</cbc:Telephone>
	 	<cbc:ElectronicMail>lucio.grande@belgio.be</cbc:ElectronicMail>
	 </cac:Contact>
    </cac:Party>
</cac:AccountingSupplierParty>
----

#Information related to the Professional Association (“Albo”) can be provided in the *cac:PartyIdentification/cbc:ID* by concatenating the Association Name, the Registration number and the registration date with the symbol "&#x0023;", by dismissing the @schemeID attribute and including the prefix "ALBO:", as in the example below.#

[NOTE]
This pertains to domestic CIUS (DC).

.UBL example of inserting information related to the Albo

[source, xml, indent=0]
----
</cac:AccountingSupplierParty>
    <cac:Party>
    ...
        <cac:PartyIdentification>
            <cbc:ID>ALBO:NomeAlbo#12345#YYYY-MM-DD</cbc:ID>
        </cac:PartyIdentification>
    ...
    </cac:Party>
</cac:AccountingSupplierParty>
----

#The EORI code number (Economic Operator Registration and Identification), based on the Regulation (CE) n. 312 dated 16th April 2009 and in force since 1st July 2009, can be also stated in the element *cac:PartyIdentification/cbc:ID*, by dismissing the @schemeID and including the prefix "EORI:" as in the example below.#

.UBL example to state the EORI code
[source, xml, indent=0]
----
<cac:PartyIdentification>
    <cbc:ID>EORI:12345678901</cbc:ID>
</cac:PartyIdentification>
----

#Finally, the element *cac:PartyIdentification/cbc:ID* can also be used to indicate information related to the seller’s registration code as recorded in the Enterprise Register Office held by the Italian Chamber of Commerce (FPA 1.2.4.1 Ufficio and FPA 1.2.4.2 Numero REA)  by dismissing the @schemeID, including the prefix "REA:", and concatenating the two data with the "&#x0023;" symbol, as in the example below.#

[NOTE]
This pertains to domestic CIUS (DC).

.UBL example to state information related to Numero REA
[source, xml, indent=0]
----
<cac:PartyIdentification>
    <cbc:ID>REA:MI#1713601</cbc:ID>
</cac:PartyIdentification>
----

#The element *cac:PartyLegalEntity/cbc:RegistrationName* can be used to indicate the Denomination data (FPA 1.2.1.3.1). If the Seller is a natural person, the Name (FPA 1.2.1.3.2) and Surname (FPA 1.2.1.3.3) can be inserted in the element *cac:PartyLegalEntity/cbc:RegistrationName* proceeded by "Nome#Cognome:" and linked by "&#x0023;".#

#The element *cac:PartyLegalEntity/cbc:CompanyLegalForm* can be used to indicate additional legal information requested by the FatturaPA specification such as CapitaleSociale (FPA 1.2.4.3), SocioUnico (FPA 1.2.4.4), and StatoLiquidazione (FPA 1.2.4.5), concatenating the elements with the "&#x0023;" symbol.#

[NOTE]
This pertains to domestic CIUS (DC).

.UBL example to indicate the Capitale Sociale

[source, xml, indent=0]
----
<cac:PartyLegalEntity>
    ...
    <cbc:CompanyLegalForm>100000##</cbc:CompanyLegalForm>
    ...
</cac:PartyLegalEntity>
----

#When using the information aggregate *cac:PostalAddress*, it is mandatory to use the address, postal code, municipality, and country information..# +

[NOTE]
This pertains to domestic CIUS (DC).

#Two examples of how to fill in the address information are provided as follows.#

.UBL example of simple address
[source, xml]
<cac:PostalAddress>
	<cbc:StreetName>Via principale 2, Palazzo 4</cbc:StreetName>
	<cbc:CityName>Grande città</cbc:CityName>
	<cbc:PostalZone>54321</cbc:PostalZone>
	<cac:Country>
		<cbc:IdentificationCode>IT</cbc:IdentificationCode>
	</cac:Country>
</cac:PostalAddress>

.UBL example of complete address
[source, xml]
<cac:PostalAddress>
	<cbc:StreetName>Corso di Francia</cbc:StreetName>
	<cbc:AdditionalStreetName>I Parioli</cbc:AdditionalStreetName>
	<cbc:CityName>Roma</cbc:CityName>
	<cbc:PostalZone>00197</cbc:PostalZone>
	<cbc:CountrySubentity>RM</cbc:CountrySubentity>
	<cac:AddressLine>
		<cbc:Line>Informazioni Aggiuntive</cbc:Line>
	</cac:AddressLine>
	<cac:Country>
		<cbc:IdentificationCode>IT</cbc:IdentificationCode>
	</cac:Country>
</cac:PostalAddress>

= Buyer (AccountingCustomerParty)

Buyer is mandatory information and provided in element *cac:AccountingCustomerParty*. +

The Buyer is the natural person, legal person or organisation who requests goods or services. +
	
The Buyer is a mandatory information as it is the recipient of the document. Its EndpointID is also a mandatory element. #The Buyer corresponds to the Cessionario/Committente of the invoice pursuant to DPR no. 633/1972.#

The buyer can be a Public Administration, [lime-background]#an economic operator, a citizen, or an entity resident, non-resident, or not established/identified in Italy.#

#If the buyer has a VAT number, the VAT number must be indicated in *cac:PartyTaxScheme/cbc:CompanyID*.#

#If the buyer has a Tax Identification Number, this must be indicated in *cac:PartyLegalEntity/cbc:CompanyID*, setting the @schemeID to "0210".#

[IMPORTANT]
At least one between the VAT number and the Tax Identification Number must be included in the invoice.

#The element *cac:PartyLegalEntity/cbc:RegistrationName* can be used to indicate the Denomination data (FPA 1.4.1.3.1).# [lime-background]#If the Buyer is a natural person, the Name (FPA 1.4.1.3.2) and Surname (FPA 1.4.1.3.3) can be inserted in the element *cac:PartyLegalEntity/cbc:RegistrationName* proceeded by "Nome"&#x0023;"Cognome:" and linked by "&#x0023;".#

[lime-background]#The EORI code number (Economic Operator Registration and Identification), based on the Regulation (CE) n. 312 dated 16th April 2009 and in force since 1st July 2009, can be stated in the element *cac:PartyIdentification/cbc:ID* by dismissing the @schemeID but including the prefix "EORI:" as in the example below.#

.UBL example to state the EORI code
[source, xml, indent=0]
----
<cac:PartyIdentification>
    <cbc:ID>EORI:12345678901</cbc:ID>
</cac:PartyIdentification>
----

#Within the B2G or G2G context, the Buyer must be identified through the receiving Office code (codice IPA) provided by the Public Administration.#

.UBL example of Buyer information
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=buyer]
----
<1> SchemeID is mandatory for electronic address (i.e. EndpointID)
<2> VAT identifiers must be prefixed with the country code
<3> The Tax Identification Number must be prefixed with @schemeID set to "0210".

[lime-background]#Within the B2B or G2B context, the Buyer can be identified through the Recipient Code (Codice Destinatario).# 

[NOTE]
This pertains to a domestic CIUS valid for invoicing towards private customers. 

.UBL Example of an entity (not a natural person) holding a Recipient Code accredited by the Italian Tax Agency.
[source, xml, indent=0]
----
<cbc:EndpointID schemeID="0205">L0U7KO4</cbc:EndpointID>
----

.UBL Example of endpoint usage for Esterometro purposes.
[source, xml, indent=0]
----
<cbc:EndpointID schemeID="0205">XXXXXXX</cbc:EndpointID>
----

[lime-background]#Within B2C and G2C contexts, the Buyer is a natural person.#

[NOTE]
This pertains to a domestic CIUS valid for invoicing towards private customers.

.UBL Example of a resident entity holding a PEC (Certified Email Address)
[source, xml, indent=0]
----
<cac:AccountingCustomerParty>
	<cac:Party>
		<cbc:EndpointID schemeID="0202">nome.cognome@pec-domain.it</cbc:EndpointID>
		<cac:PostalAddress>
			<cbc:StreetName>Via Riviera di Chiaia, 99A</cbc:StreetName>
			<cbc:CityName>Napoli</cbc:CityName>
			<cbc:PostalZone>80121</cbc:PostalZone>
			<cac:AddressLine>
				<cbc:Line> Informazioni Aggiuntive </cbc:Line>
			</cac:AddressLine>
			<cac:Country>
				<cbc:IdentificationCode>IT</cbc:IdentificationCode>
			</cac:Country>
		</cac:PostalAddress>
		<cac:PartyTaxScheme>
			<cbc:CompanyID>IT01234567890</cbc:CompanyID>
			<cac:TaxScheme>
				<cbc:ID>VAT</cbc:ID>
			</cac:TaxScheme>
		</cac:PartyTaxScheme>
		<cac:PartyLegalEntity>
			<cbc:RegistrationName>Nome#Cognome:Mario#Rossi</cbc:RegistrationName>
			<cbc:CompanyID schemeID="0210">RSSMRA00A01E123H</cbc:CompanyID>
		</cac:PartyLegalEntity>
		<cac:Contact>
			<cbc:Telephone>06123456</cbc:Telephone>
			<cbc:ElectronicMail>nome.cognome@pec-domain.it</cbc:ElectronicMail>
		</cac:Contact>
	</cac:Party>
</cac:AccountingCustomerParty>
----

.UBL Example of a resident entity without a Recipient Code and without a PEC
[source, xml, indent=0]
----
<cbc:EndpointID schemeID="0205">0000000</cbc:EndpointID>
----

= Payment receiver (PayeeParty)

The Payment receiver (or Payee) is the natural person, legal person or organisation who has the right to receive the payment (e.g. factoring society) and is an optional information. If this information is not provided, the Payment receiver results in the Seller.

To reflect the assignment of an Invoice to a factor there is a need to:

. have a disclaimer (notification notice) on the Invoice that the Invoice has been assigned to a factor. The disclaimer should be given using the Invoice note (BT-22) on document level.

. identify the Factor as the Payee

. to have the bank account changed in favour of the Factor.

.UBL example of payee information
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=payee]
----

#The element *cac:PartyIdentification/cbc:ID* can be used to provide the anagraphic information of the *Quietanzante* by indicating the *NomeQuietanzante* (FPA 2.4.2.9) and *CognomeQuietanzante* (FPA 2.4.2.8) data concatenated with the symbol "&#x0023;".#

= Sellers Tax Representative (TaxRepresentativeParty) 

The Tax Representative is the natural person, legal person or organisation who is responsible, on behalf of companies, of the correct management and the regularisation of the VAT tax, consistent with the domestic legislation. 

Tax representative party for the seller is relevant for sellers delivering goods and services in a country where they do not have a permanent establishment. In such cases, information on the tax representative shall be included in the invoice.

#The Tax Identification Number can be indicated in the element *cac:PartyIdentification/cbc:ID* setting the @schemeID to "0210".#

#The EORI Code can be indicated in the element *cac:PartyIdentification/cbc:ID* by dismissing the @schemeID attribute and including the prefix "EORI:”.#

#The VAT Number must be indicated in *cac:PartyTaxScheme/cbc:CompanyID*.#

#The element *cac:PartyName/cbc:Name* can be used to indicate the Denomination data (FPA 1.3.1.3.1). In the case of a natural person acting as the Sellers Tax Representative, it can be used to indicate the Name (FPA 1.3.1.3.2) and Surname (1.3.1.3.3) data, preceded by the string "Nome#Cognome:" and concatenated with the "&#x0023;" symbol.#

.UBL example of Sellers Tax Representative information
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=taxrep]
----
<1> VAT identifiers must be prefixed with the country code and must be preceded by the schemeID "“"0211"

= #Sellers Permanent Establishment (AccountingSupplierParty/AgentParty)# – Extension

In the case of a Permanent Establishment in Italy of a non-resident Seller, the data of the Permanent Establishment must be indicated within the structure *cac:AgentParty*.

.UBL example for the sellers permanent establishment
[source, xml, indent=0]
----
include::../../rules/snippets/agid-extensions.xml[tag=stabile_organizzazione_fornitore]
----

= #Third Intermediary or Issuing Party of the Seller (AccountingSupplierParty/ServiceProviderParty)# – Extension

In the case where a third party issues the invoice on behalf of the Seller, it can be specified in the invoice as part of the seller’s data within the structure *cac:ServiceProviderParty*. +

If the third party is Italian, the Tax Identification Number (Codice Fiscale) must be included within the Party information using the element PartyIdentification/ID, setting the @schemeID to "0210", as shown in the example below. +

.UBL Example for the third intermediary or issuing party on behalf of the seller
[source, xml, indent=0]
----
<cac:ServiceProviderParty>
        <cac:Party>
                <cac:PartyIdentification>
                        <cbc:ID  schemeID="0210">CXXNXX68M06E123H</cbc:ID>
                </cac:PartyIdentification>
                <cac:PartyName>
                        <cbc:Name>Terzo Intermediario Srl</cbc:Name>
                </cac:PartyName>
                <cac:PartyTaxScheme>
                        <cbc:CompanyID>IT07643520567</cbc:CompanyID>
                        <cac:TaxScheme>
                                <cbc:ID>VAT</cbc:ID>
                        </cac:TaxScheme>
                </cac:PartyTaxScheme>
        </cac:Party>
</cac:ServiceProviderParty>
----

The EORI Code can be expressed in the element *cac:PartyIdentification/cbc:ID* by dismissing the @schemeID attribute and including the prefix "EORI:", as shown in the example below.

.UBL example to express the EORI code
[source, xml, indent=0]
----
<cac:PartyIdentification>
    <cbc:ID>EORI:12345678901</cbc:ID>
</cac:PartyIdentification>
----

= [lime-background]#Buyer’s Tax Representative (AccountingCustomerParty/PowerOfAttorney) – Extension#

Within the billing process towards private entities context (B2B, B2C, G2B, and G2C), if the Buyer makes use of a tax representative in Italy, this can be specified in the invoice as part of the seller’s data in the PowerOfAttorney structure, as a proxy for tax representation. 

.UBL example for the Buyer’s tax representative
[source, xml, indent=0]
----
<cac:PowerOfAttorney>
        <cbc:Description>Rappresentante Fiscale</cbc:Description>
        <cac:AgentParty>
                <cac:PartyTaxScheme>
                        <cbc:CompanyID>IT07643520567</cbc:CompanyID>
                        <cac:TaxScheme>
                                <cbc:ID>VAT</cbc:ID>
                        </cac:TaxScheme>
                </cac:PartyTaxScheme>
                <cac:PartyLegalEntity>
                        <cbc:RegistrationName>Rappresentante Fiscale Srl</cbc:RegistrationName>
                </cac:PartyLegalEntity>
        </cac:AgentParty>
</cac:PowerOfAttorney>
----

= [lime-background]#Buyer’s Permanent Establishment (AccountingCustomerParty/AgentParty) – Extension#

In the case of a Permanent Establishment in Italy of a non-resident Buyer, the data of the Permanent Establishment must be indicated within the structure *cac:AgentParty*.

.UBL example for the Buyer’s permanent establishment
[source, xml, indent=0]
----
<cac:AgentParty>
        <cac:PostalAddress>
                <cbc:StreetName>Via Navigli, 100</cbc:StreetName>
                <cbc:CityName>Milano</cbc:CityName>
                <cbc:PostalZone>20100</cbc:PostalZone>
                <cbc:CountrySubentity>MI</cbc:CountrySubentity>
                <cac:Country>
                        <cbc:IdentificationCode>IT</cbc:IdentificationCode>
                </cac:Country>
        </cac:PostalAddress>
</cac:AgentParty>
----

= #Carrier Party (Delivery/CarrierParty) – Extension#

The Carrier party is the legal entity or organization that manages the physical delivery/transport of the shipment. It is used when the transport is carried out by a third party.

The Tax Identification Number (Codice Fiscale) can be indicated in the element *cac:PartyIdentification/cbc:ID* by setting the @schemeID to "0210", as shown in the example below. The VAT Number must be indicated in *cac:PartyTaxScheme/cbc:CompanyID*.

.UBL example for the carrier party managing the delivery/transport
[source, xml, indent=0]
----
include::{snippet-dir}/agid-extensions.xml[tag=info_vettore]
----