
= #Ritenuta d'acconto (estensione)#

La sezione ritenuta d'acconto serve ad evidenziare: +

* una trattenuta Irpef (per i redditi delle persone fisiche) o Ires (per le persone giuridiche: società) che viene effettuata sul totale imponibile della fattura inviata al Cliente da parte del Fornitore, che agisce come sostituto d'imposta;
* una trattenuta previdenziale che viene effettuata sul totale imponibile della fattura inviata al Cliente da parte del Fornitore che si occuperà del successivo riversamento all'Ente previdenziale di riferimento.

[IMPORTANT]
====
Paragrafo da completare
====


/// esempio da rivedere

.Esempio UBL di ritenuta d'acconto 
L'esempio riportato è relativo alla fattura emessa da un professionista con regime dei minimi e soggetto a ritenuta d'acconto.
[source, xml, indent=0]
----
include::../{snippet-dir}/Esempio-Fattura-Professionista-Minimi-con-Cassa-Ritenuta-e-Bollo.xml[tags=ritenuta]
----
<1> L'aliquota della ritenuta espressa mediante un 'cac:AdditionalItemProperty/cbc:Name' valorizzato con 'IT:RITENUTA:ALIQUOTA' e l'aliquota in 'cac:AdditionalItemProperty/cbc:Value'.
<2> Il tipo della ritenuta espresso mediante un 'cac:AdditionalItemProperty/cbc:Name' valorizzato con 'IT:RITENUTA:TIPO' e il codice tipo ritenuta in 'cac:AdditionalItemProperty/cbc:Value' secondo la codifica disponibile nella FatturaPA.
<3> La causale della ritenuta espressa mediante un 'cac:AdditionalItemProperty/cbc:Name' valorizzato con 'IT:RITENUTA:CAUSALE' e il codice tipo ritenuta in 'cac:AdditionalItemProperty/cbc:Value' secondo la codifica disponibile nella FatturaPA.

