[[Consegna-Delivery]]
= #Consegna (Delivery)#

:leveloffset: +1

= Luogo di consegna (DeliveryLocation)

Le informazioni di consegna sono necessarie qualora l’indirizzo differisca da quello della parte che emette l’ordine. +

Il luogo di consegna è la sede in cui deve avvenire la cessione dei beni e/o la prestazione dei servizi. È indicato, a livello di testata documento, all’interno dell’elemento “Delivery/DeliveryLocation”. +

Se il luogo di consegna è un indirizzo istituzionale del Cliente a cui è stato associato un identificativo univoco reso disponibile al Fornitore, come avviene nel caso dei luoghi di consegna per le PA censiti secondo la codifica pubblicata al seguente link https://www.puntidiconsegna-nso.it/[Punti di consegna NSO], è possibile indicare anche tale identificativo all’interno del campo cbc:ID. 

.Esempio di consegna al Punto Istituzionale di un Ente 
[source, xml, indent=0]
----
<cac:Delivery> 
    <cac:DeliveryLocation> 
        <cbc:ID>CF-IdShipTo</cbc:ID> 
        <Name>Magazzino centralizzato</Name> 
    </cac:DeliveryLocation> 
    <cac:RequestedDeliveryPeriod> <1>
        <cbc:StartDate>2018-05-15</cbc:StartDate> 
        <cbc:StartTime>08:00:00</cbc:StartTime> 
        <cbc:EndDate>2018-05-15</cbc:EndDate> 
        <cbc:EndTime>13:00:00</cbc:EndTime> 
    </cac:RequestedDeliveryPeriod> 
    <cac:DeliveryParty> 
        <cac:PartyIdentification> 
            <cbc:ID schemeID="0201">AAFF33</cbc:ID> 
        </cac:PartyIdentification> 
        <cac:PartyName> 
            <cbc:Name>Centro Logistico Beni Sanit-Ecom Area 2</cbc:Name> 
        </cac:PartyName> 
        <cac:Contact> 
            <cbc:Name>ResponsabileMagazzino</cbc:Name> 
            <cbc:Telephone>0516361509</cbc:Telephone> 
      <cbc:ElectronicMail>responsabile.magazzino@aziendasanitaria.it</cbc:ElectronicMail> 
        </cac:Contact> 
    </cac:DeliveryParty> 
</cac:Delivery> 
<cac:DeliveryTerms> 
    <cbc:ID>PORTO FRANCO</cbc:ID> 
</cac:DeliveryTerms> 
----
<1> Periodo di esecuzione della fornitura: specificare in questa struttura le informazioni nel caso in cui sia stato concordato il giorno (campi “StartDate/EndDate”) e l’orario (campi “StartTime/EndTime) dell’esecuzione della fornitura. 

Se, invece, la consegna dei beni e/o la prestazione dei servizi deve avvenire presso un luogo non istituzionale o in un luogo istituzionale non codificato (anche temporaneamente), vanno indicate con precisione tutte le parti del sotto-elemento “Address”, come mostrato nel seguente esempio: 

.Esempio di consegna presso un luogo non istituzionale o luogo istituzionale non codificato 
[source, xml, indent=0]
----
<cac:Delivery> 
    <cac:DeliveryLocation> 
        <Name>Nuovo magazzino di reparto</Name> 
        <cac:Address> 
            <cbc:StreetName>Viale Ercolani, 4</cbc:StreetName> 
            <cbc:CityName>Bologna</cbc:CityName> 
            <cbc:PostalZone>40138</cbc:PostalZone> 
            <cbc:CountrySubentity>BO</cbc:CountrySubentity> 
            <cac:AddressLine> 
                <cbc:Line>Orario:Lunedì-Venerdì 8:00-13:00 - Sabato 8:00-12:00</cbc:Line> <1>
            </cac:AddressLine> 
            <cac:Country> 
                <cbc:IdentificationCode>IT</cbc:IdentificationCode> 
            </cac:Country> 
        </cac:Address> 
… 
    </cac:DeliveryLocation> 
</cac:Delivery> 
----
<1> Informazioni degli orari di apertura del magazzino.  

Se trattasi di consegna domiciliare (ad esempio, all’indirizzo di un paziente), questa circostanza va specificata valorizzando il campo “ID” con il testo “Consegna domiciliare” e indicando con precisione nella struttura “Address” l’indirizzo esatto di consegna, come mostrato nel seguente esempio: 

.Esempio di consegna presso un domicilio 
[source, xml, indent=0]
----
<cac:Delivery> 
    <cac:DeliveryLocation> 
        <cac:ID>Consegna domiciliare</cac:ID> 
        <Name>Entrata lato portineria</Name> 
        <cac:Address> 
            <cbc:StreetName>Via Attanasio Soldati 80</cbc:StreetName> 
            <cbc:AdditionalStreetName>Località La Rustica</cbc:AdditionalStreetName> 
            <cbc:CityName>Roma</cbc:CityName> 
            <cbc:PostalZone>00155</cbc:PostalZone> 
            <cbc:CountrySbentity>Lazio</cbc:CountrySubentity> 
            <cac:AddressLine> 
                <cbc:Line>Edificio C, Quarto piano, Stanza 01</cbc:Line> 
            </cac:AddressLine> 
            <cac:Country> 
              <cbc:IdentificationCode>IT</cbc:IdentificationCode> 
            </cac:Country> 
        </cac:Address> 
    </cac:DeliveryLocation> 
</cac:Delivery> 
----

:leveloffset: -1



:leveloffset: +1


= Etichette imballaggio (ShippingMarks)

Se necessario, il Cliente può richiedere al Fornitore di stampare un testo sull’etichetta di imballaggio, valorizzando in modo appropriato il campo “TransportHandlingUnit/ShippingMarks” dell’elemento “Shipment”, come mostrato nel seguente esempio:

[source, xml, indent=0]
----
<cac:Delivery>
     <cac:Shipment>
          <cbc:ID>NA</cbc:ID>
          <cac:TransportHandlingUnit>
              <cbc:ShippingMarks>aaaaaaaaaa</cbc:ShippingMarks>
          </cac:TransportHandlingUnit>
     </cac:Shipment>
</cac:Delivery>
---- 

:leveloffset: -1


:leveloffset: +1


= Indicazione della priorità della consegna

Il Cliente può indicare al Fornitore il livello di priorità richiesta nell'evasione dell'ordine valorizzando il campo "ShippingPriorityLevelCode" dell'elemento "Shipment", inserendo il relativo codice tra quelli presenti nella codelist "Transport service priority code (UNCL4219)" come mostrato nell'esempio.

.Esempio di indicazione di un ordine urgente (consegna entro 24 ore)
[source, xml, indent=0]
----
<cac:Delivery>
    <cac:Shipment>
         <cbc:ID>NA</cbc:ID>
         <cbc:ShippingPriorityLevelCode>1</cbc:ShippingPriorityLevelCode>
   </cac:Shipment>
</cac:Delivery>
----

:leveloffset: -1