[[parti-e-ruoli]]
= Parti e ruoli

Le seguenti parti/I seguenti ruoli possono essere specificate/i nel messaggio:

[[sellersupplierparty-seller]]
== Fornitore/Venditore (SellerSupplierParty)

Il fornitore è la persona giuridica che agisce per conto del fornitore e che vende la merce o i servizi al cliente. Il fornitore è obbligatorio in quanto destinatario dell’ordine PEPPOL, pertanto è obbligatori includere l’EndpointID (ParticipantID) con il quale è registrato su PEPPOL.

Si rammenta che, se il Fornitore è un’amministrazione pubblica, il campo “EndpointID/@schemeID” deve essere valorizzato con “0201:” seguito dal Codice IPA della PA.

.Esempio di informazioni per un fornitore italiano
[source, xml, indent=0]
----
<cac:SellerSupplierParty>
    <cac:Party>
	 <cbc:EndpointID schemeID="9906">IT01234567890</cbc:EndpointID>
	 <cac:PartyName>
	 	<cbc:Name>Fornitore S.p.A.</cbc:Name>
	 </cac:PartyName>
	 <cac:PostalAddress>
	 	<cbc:StreetName>Indirizzo Riga 1</cbc:StreetName>
	 	<cbc:AdditionalStreetName>Indirizzo Riga 2</cbc:AdditionalStreetName  >
	 	<cbc:CityName>Bologna</cbc:CityName>
	 	<cbc:PostalZone>40121</cbc:PostalZone>
	 	<cbc:CountrySubentity>BO</cbc:CountrySubentity >
	 	<cac:AddressLine>
	 		<cbc:Line>Zona Savena</cbc:Line>
	 	</cac:AddressLine>
	 	<cac:Country>
	 	<cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
	 	</cac:Country>
	 </cac:PostalAddress>
	 <cac:PartyLegalEntity>
	 	<cbc:RegistrationName>Azienda fornitore</cbc:RegistrationName>
	 	<cbc:CompanyID schemeID="ZZZ">00000</cbc:CompanyID>
	 	<cac:RegistrationAddress>
	 		<cbc:CityName>Bologna</cbc:CityName>
	 		<cac:Country>
            <cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
	 		</cac:Country>
	 	</cac:RegistrationAddress>
	 </cac:PartyLegalEntity>
	 <cac:Contact>
	 	<cbc:Name>Lucio Grande</cbc:Name>
	 	<cbc:Telephone>051102030</cbc:Telephone>
	 	<cbc:ElectronicMail>lucio.grande@fornitore.it</cbc:ElectronicMail>
	 </cac:Contact>
    </cac:Party>
</cac:SellerSupplierParty>
----

.Esempio di informazioni per un fornitore estero
[source, xml, indent=0]
----
<cac:SellerSupplierParty>
    <cac:Party>
	 <cbc:EndpointID schemeID="9925">0999999999</cbc:EndpointID
	 <cac:PartyName>
	 	<cbc:Name>Fornitore Estero</cbc:Name>
	 </cac:PartyName>
	 <cac:PostalAddress>
	 	<cbc:StreetName> Rue Emile Claus 28</cbc:StreetName>
		<cbc:AdditionalStreetName>Quartiere</cbc:AdditionalStreetName>
		<cbc:CityName>Bruxelles</cbc:CityName>
		<cbc:PostalZone>1050</cbc:PostalZone>
		<cac:AddressLine>
		<cbc:Line>Deposito Consegnatario: Fornitore Estero</cbc:Line>
		</cac:AddressLine>
			<cac:Country>
			<cbc:IdentificationCode listID="ISO3166-1:Alpha2">BE</cbc:IdentificationCode>
			</cac:Country>
	 </cac:PostalAddress>
	 <cac:PartyLegalEntity>
	 	<cbc:RegistrationName>Fornitore Estero</cbc:RegistrationName>
	 	<cbc:CompanyID>0999999999</cbc:CompanyID>
	 	<cac:RegistrationAddress>
	 		<cbc:CityName>Bologna</cbc:CityName>
	 		<cac:Country>
            <cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
	 		</cac:Country>
	 	</cac:RegistrationAddress>
	 </cac:PartyLegalEntity>
	 <cac:Contact>
	 	<cbc:Name>Lucio Grande</cbc:Name>
	 	<cbc:Telephone>003241102030</cbc:Telephone>
	 	<cbc:ElectronicMail>lucio.grande@belgio.be</cbc:ElectronicMail>
	 </cac:Contact>
    </cac:Party>
</cac:SellerSupplierParty>
----

[yellow-background]#Il Fornitore è un elemento essenziale del processo che, eccezionalmente, può non essere determinato a priori, ma divenirlo solo al momento della cessione dei beni e/o della prestazione dei servizi. Ad esempio quando la facoltà di scegliere il Fornitore è riservata al Beneficiario.# 

[yellow-background]#In questo caso (Fornitore non predeterminato) l’elemento “SellerSupplierParty/Party” deve contenere solo i campi di seguito indicati:# 

* [yellow-background]#“EndpointID”, valorizzato con “9999999999999999” (sedici volte 9) indicando il valore "9907" per lo "Scheme ID";# 

* [yellow-background]#“PostalAddress/Country/IdentificationCode”, valorizzato con il codice corrispondente allo Stato in cu verrà effettuato l’acquisto (per l’Italia “IT”);# 

* [yellow-background]#“PartyLegalEntity/RegistrationName”, valorizzato con “NDEF”.# 


[[buyercustomerparty-buyer]]
== Cliente/Acquirente (BuyerCustomerParty)

Il cliente è la persona giuridica che agisce per conto del cliente e che acquista la merce o i servizi. Il cliente è obbligatorio in quanto mittente del messaggio dell’ordine PEPPOL, pertanto si raccomanda di includere l’EndpointID (ID partecipante) con il quale è registrato in PEPPOL. +

[yellow-background]#Il nome e l’identificativo fiscale del cliente sono inoltre un requisito di questa implementazione per permettere all’access point di identificare ed autorizzare il mittente all’inoltro dell’ordine sulla rete (INT-T01-R002). Il campo “PartyIdendification/ID” è obbligatorio e deve essere presente con una sola istanza (molteplicità = 1), in quanto si tratta di uno dei tre elementi che identificano univocamente il Messaggio nel NSO.#

.Esempio di informazioni del cliente
[source, xml, indent=0]
----
<cac:BuyerCustomerParty>
<cac:Party>
	<cbc:EndpointID schemeID="0201">ABCDEF</cbc:EndpointID>
	<cac:PartyIdentification>
		<cbc:ID schemeID="0201">ABCDEF</cbc:ID>
	</cac:PartyIdentification>
	<cac:PartyName>
		<cbc:Name>Cliente Pubblico S.p.A.</cbc:Name>
	</cac:PartyName>
	<cac:PostalAddress>
		<cbc:StreetName>Indirizzo Riga 1</cbc:StreetName>
		<cbc:AdditionalStreetName>Indirizzo Riga 2</cbc:AdditionalStreetName>
		<cbc:CityName>Genova</cbc:CityName>
		<cbc:PostalZone>16121</cbc:PostalZone>
		<cbc:CountrySubentity>GE</cbc:CountrySubentity>
		<cac:Country>
			<cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
		</cac:Country>
		<cac:AddressLine>
			<cbc:Line>Zona Porto</cbc:Line>
		</cac:AddressLine>
	</cac:PostalAddress>
	<cac:PartyTaxScheme>
		<cbc:CompanyID>IT00234567890</cbc:CompanyID>
		<cac:TaxScheme>
			<cbc:ID>VAT</cbc:ID>
		</cac:TaxScheme>
	</cac:PartyTaxScheme>
	<cac:PartyLegalEntity>
		<cbc:RegistrationName>Cliente Pubblico S.p.A.</cbc:RegistrationName>
		<cbc:CompanyID schemeID="0201">ABCDEF</cbc:CompanyID>
		<cac:RegistrationAddress>
			<cbc:CityName>Genova</cbc:CityName>
			<cac:Country>
				<cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
			</cac:Country>
		</cac:RegistrationAddress>
	</cac:PartyLegalEntity>
	<cac:Contact>
		<cbc:Name>Doria Samp</cbc:Name>
		<cbc:Telephone>010150846</cbc:Telephone>
		<cbc:ElectronicMail>doria.samp@cliente.it</cbc:ElectronicMail>
	</cac:Contact>
</cac:Party>
</cac:BuyerCustomerParty>
----

[[originatorcustomerparty-originator]]
== Committente (OriginatorCustomerParty)

Generalmente, il committente è l’utente finale che emette l’ordine. Le informazioni presenti nel messaggio dell’ordine inerenti al committente sono facoltative.

.Esempio di informazioni del committente appartenente alla medesima organizzazione del cliente/acquirente
[source, xml, indent=0]
----
<cac:OriginatorCustomerParty>
    <cac:Party>
	<cac:PartyIdentification>
			<cbc:ID schemeID="0201">ABCDEF</cbc:ID>
	</cac:PartyIdentification>
	<cac:PartyName>
		<cbc:Name>U.O. Farmacia Ospedaliera</cbc:Name>
	</cac:PartyName>
	<cac:Contact>
		<cbc:Name>Roberto Gastone</cbc:Name>
		<cbc:Telephone>010150847</cbc:Telephone>
		<cbc:ElectronicMail>roberto.gastone@ospedale.it</cbc:ElectronicMail>
	</cac:Contact>
    </cac:Party>
</cac:OriginatorCustomerParty>
----

[yellow-background]#Qualora il Documento sia emesso con l’uso di strumenti messi a disposizione da un Intermediario (ad esempio, un Ordine emesso utilizzando la piattaforma telematica di una centrale di acquisto), è possibile evidenziare il committente valorizzando l’elemento “OriginatorCustomerParty”, come mostrato nel seguente esempio:#

.Esempio di informazioni del committente che utilizza una piattaforma telematica di un terzo intermediario per l’emissione dell’ordine
[source, xml, indent=0]
----
<cac:OriginatorCustomerParty>
    <cac:Party>
	<cac:PartyIdentification>
		<cbc:ID schemeID="0201">AABBCC</cbc:ID>
	</cac:PartyIdentification>
	<cac:PartyName>
		<cbc:Name>AUSL SALERNO </cbc:Name>
	</cac:PartyName>
	<cac:Contact>
		<cbc:Name>Roberto Gastone</cbc:Name>
		<cbc:Telephone>010150847</cbc:Telephone>
		<cbc:ElectronicMail>roberto.gastone@ospedale.it</cbc:ElectronicMail>
	</cac:Contact>
    </cac:Party>
</cac:OriginatorCustomerParty>
----

[[accountingcustomerparty-invoicee]]
==  Intestatario fattura (AccountingCustomerParty)

L’intestatario della fattura è la persona giuridica che agisce per conto del Cliente e che riceve la fattura relativa all’ordine. Le informazioni sull’intestatario della fattura sono opzionali nel messaggio dell’Ordine PEPPOL. 

.Esempio di informazioni dell’intestatario fattura
[source, xml, indent=0]
----
<cac:AccountingCustomerParty>
    <cac:Party>
        <cbc:EndpointID schemeID=”0201”>ABCDEF</cbc:EndpoinID>
        <cac:PartyIdentification>
            <cbc:ID schemeID="0201">ABCDEF</cbc:ID>
        </cac:PartyIdentification>
        <cac:PartyName>
            <cbc:Name>Ospedale Sant’Anna</cbc:Name>
        </cac:PartyName>
        <cac:PostalAddress>
            <cbc:StreetName>Via del pensiero, 1</cbc:StreetName>
            <cbc:AdditionalStreetName>Primo Piano</cbc:AdditionalStreetName>
            <cbc:CityName>Maranello</cbc:CityName>
            <cbc:PostalZone>41053</cbc:PostalZone>
            <cbc:CountrySubentity>Modena</cbc:CountrySubentity>
            <cac:AddressLine>
                <cbc:Line>Stanza 18</cbc:Line>
            </cac:AddressLine>
            <cac:Country>
                <cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
            </cac:Country>
        </cac:PostalAddress>
        <cac:PartyTaxScheme>
            <cbc:CompanyID>00234567890</cbc:CompanyID>
            <cac:TaxScheme>
                <cbc:ID>VAT</cbc:ID>
            </cac:TaxScheme>
        </cac:PartyTaxScheme>
        <cac:PartyLegalEntity>
            <cbc:RegistrationName>OspedaleSant’Anna</cbc:RegistrationName>
            <cbc:CompanyID <cbc:ID>IT:CF:00234567890</cbc:CompanyID>
            <cac:RegistrationAddress>
                <cbc:CityName>Modena</cbc:CityName>
                <cac:Country>
                    <cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
                </cac:Country>
            </cac:RegistrationAddress>
        </cac:PartyLegalEntity>
        <cac:Contact>
            <cbc:Name>ResponsabileFatturazione</cbc:Name>
            <cbc:ElectronicMail>responsabile.fatturazione@ospedale.it</cbc:ElectronicMail>
        </cac:Contact>
    </cac:Party>
</cac:AccountingCustomerParty>
----
