
= Imposta sul valore aggiunto (IVA)

I capitoli seguenti descrivono le diverse informazioni in materia dell'IVA che possono essere fornite in questo BIS.

Si consiglia di consultare anche i {vat-codes} per dettagli sulla codifica delle categorie IVA e il <<vat-calc>> per una rappresentazione più dettagliata ed esempi su come eseguire i calcoli nel riepilogo IVA.

:leveloffset: +1

include::../../shared/files/vat-cat-line.adoc[]

:leveloffset: -1

[[vat-allowance]]
== Informazioni VAT negli Sconti e maggiorazioni

Ogni sconto o maggiorazione a livello di testata viene espresso mediante l'elemento UBL `cac:AllowanceCharge`. Ulteriori dettagli sugli sconti e maggiorazioni si trovano in <<allowance>>.

Ogni sconto o maggiorazione a livello di testata deve avere il codice di categoria IVA. Per tutte le categorie IVA, eccetto "Non soggetto ad IVA" (O), deve essere fornita l'aliquota IVA.

.Esempio UBL di maggiorazione con informazioni sulla categoria IVA
[source, xml, indent=0]
----
include::../snippets/snippet-oa-vat.xml[tags=vat-allowance]
----
<1> La classe `cac:TaxCategory` è utilizzata per informazioni dulla categoria IVA
<2> Categoria IVA secondo la codifica {vat-codes}
<3> Aliquota IVA
