[preface]

= Link to main site of documentation

link:pass:[${peppoldocs.root.url}/my_index_fatt-ENG.jsp][Main site of documentation]

= Introduction to openPeppol and BIS

This {peppol} BIS provides a set of specifications for implementing a {peppol} business process.

This specification is a Core Invoice Usage Specification (CIUS) of {EN16931}, following the guidance given in chapter 7 of the {EN16931}. Any instance documents compliant to this specification will be compliant with the European Standard ({EN16931}).

#In this document the Italian usage rules (CIUS) and the sections specifically applicable to the Italian context are highlighted in yellow, with a clear distinction between:# +

* #the CIUS applicable to the invoices from abroad, also called cross-border (CIUS);#
* #the CIUS applicable to domestic invoices (domestic CIUS);#
* #the Extensions applicable to the domestic invoices (extension).#

#Pursuant to the Italian Ministry of Economy and Finance (MEF) Decree of 21.06. 2021, the rules of the domestic market shall apply to electronic invoicing to and from San Marino.#

[lime-background]#The usage rules and the sections specifically applicable to domestic billing process towards private customers are highlighted in green.#

#For further details see also section 12.2 and Appendix A.#

The *purpose* of this document is to facilitate an efficient implementation and increase the usage of electronic transactions regarding the billing process.

== Document Structure

This document is structured as follows:

*	*Chapters 1 - 5* gives general information on the business processes, requirements and functionalities
*	*Chapter 6* describes the semantical data types
*	*Chapters 7 - 9* describes VAT, calculations and rounding.
*	*Chapter 10* provides examples of selected parts of the invoice
*	*Chapter 11* gives details and links to all code lists used
*   *Chapter 12* gives information on Peppol identifiers
*	*Chapter 13* describes in detail central information elements.
*	*Chapters 14 and 15* provides information on validation and validation rules
*	*Annexes* give information on restrictions according to {EN16931}, use of Cross Industry Invoice syntax and national and syntax rules.

== Scope

This document is concerned with clarifying requirements for ensuring interoperability and provides guidelines for the support and implementation of these requirements. This document will also provide a detailed implementation guideline for the invoice and credit note transactions.

#This document provides indications specifically for the following business scenarios:#

* #B2G – Business to Government#
* #G2G – Government to Government#
* [lime-background]#B2B – Business to Business#
* [lime-background]#B2C – Business to Consumer#
* [lime-background]#G2B – Government to Business#
* [lime-background]#G2C – Government to Consumer#

== Audience

The audience for this document is organisations wishing to be Peppol enabled for exchanging electronic invoices, and/or their ICT-suppliers. These organisations may be:

     * Service providers
     * Contracting Authorities (CA)
     * Economic Operators (EO)
     * Software Developers

More specifically, roles addressed are the following:

    * ICT Architects
    * ICT Developers
    * Business Experts

For further information on Peppol/OpenPeppol, please see {common}
