[preface]
= Introduction to openPEPPOL and BIS

This {peppol} BIS provides a set of specifications for implementing a {peppol} business process.

Questa Business Interoperability Specification (BIS) fornisce un insieme di specifiche per l'implementanzione della fatturazione elettronica e pubblicato come parte delle specifiche https://docs.peppol.eu/poacc/billing/3.0/[Peppol].

#In questo documento le regole d’uso ed i paragrafi applicabili specificatamente al contesto italiano sono evidenziate in giallo, con chiara distinzione:# +

* #delle CIUS da applicare alle fatture dall’estero, ovvero cross-border (CIUS);#
* #delle CIUS da applicare alle fatture domestiche (CIUS domestica);#
* #delle Estensioni da applicare alle fatture domestiche (estensione).#

[lime-background]#Le regole d’uso ed i paragrafi applicabili specificatamente alla fatturazione domestica verso i privati sono invece evidenziate in verde.#

#Per ulteriori dettagli vedi anche i paragrafi 12.2 e Appendix A.#

The *purpose* of this document is to facilitate an efficient implementation and increased use of electronic collaboration regarding the billing process.

== Document Structure

This document is structured as follows:

*	*Chapters 1 - 5* gives general information on the business processes, requirements and functionalities
*	*Chapter 6* describes the semantical data types
*	*Chapters 7 - 9* describes VAT, calculations and rounding.
*	*Chapter 10* provides examples of selected parts of the invoice
*	*Chapter 11* gives details and links to all code lists used
* *Chapter 12* gives information on PEPPOL identifiers
*	*Chapter 13* describes in detail central information elements.
*	*Chapters 14 and 15* provides information on validation and validation rules
*	*Annexes* give information on restrictions according to {EN16931}, use of Cross Industry Invoice syntax and national and syntax rules.

== Scope

Questo documento  fornisce le linee guida per il supporto e l'implementazione delle transazioni relative a fatture e note di credito.

This document is concerned with clarifying requirements for ensuring interoperability  and provides guidelines for the support and implementation of these requirements. This document will also provide a detailed implementation guideline for the invoice and credit note transactions.

#Sono supportati specificatamente i seguenti scenari di business:#

* #B2G – Business to Government#
* #G2G – Government to Government#
* [lime-background]#B2B – Business to Business#
* [lime-background]#B2C – Business to Consumer#
* [lime-background]#G2B – Government to Business#
* [lime-background]#G2C – Government to Consumer#

== Audience

The audience for this document is organisations wishing to be PEPPOL enabled for exchanging electronic invoices, and/or their ICT-suppliers. These organisations may be:

     * Service providers
     * Contracting Authorities (CA)
     * Economic Operators (EO)
     * Software Developers

More specifically, roles addressed are the following:

    * ICT Architects
    * ICT Developers
    * Business Experts

For further information on PEPPOL/OpenPEPPOL, please see {common}
