.Esempio UBL per l'uso del CPV
[source, xml, indent=0]
----
<cac:CommodityClassification>
    <cbc:ItemClassificationCode listID="STI">09348023</cbc:ItemClassificationCode>(1)
</cac:CommodityClassification>
----
<1> Il listID deve essere fra quelli della codifica UNCL7143 e il codice STI indica che questo è una classificazione CPV.

.Esempio UBL di UNSPSC (United Nation Standard Products and Services Code) 
[source, xml, indent=0]
----
include::{snippet-dir}/item.xml[tags=unspsc]
----
<1> Il listID deve essere fra quelli della codifica UNCL7143 e il codice TST indica che questo è una classificazione UNSPSC, mentre il listVersionID è opzionale, ma può essere usato per specificare la versione di UNSPSC. Notare che nelle versioni precedenti il codice MP era usato come soluzione temporanea per identificare UNSPSC. Nella fall release 2019 è stato sostituito con il nuovo codice TST 7143 che è specifico per UNSPSC.

.Esempio UBL di Dispositivo medico
#In questo esempio viene fornito il numero di registrazione attribuito al dispositivo medico nella Banca dati e Repertorio Dispositivi Medici dal Ministero della Salute.#

#L’attributo schemeID dovrà essere valorizzato con:#

* #DM1 per “Dispositivo medico o Dispositivo diagnostico in vitro”#
* #DM2 per “Sistema o kit Assemblato”#
* #DM0 per "Nessun numero di repertorio"#

[source, xml, indent=0]
----
<cac:Item>
	<cbc:Description>Dispositivo Medico</cbc:Description>
	<cbc:Name>Prodotto 1143668 DEFIBRILLATORE SEMIAUTOMATICO LIFEPAK 1000</cbc:Name>
	<cac:SellersItemIdentification>
		<cbc:ID>1143668</cbc:ID> (1)
    </cac:SellersItemIdentification>
	<cac:CommodityClassification>
		<cbc:ItemClassificationCode listID="ZZZ">DM1:918674</cbc:ItemClassificationCode> (2)
    </cac:CommodityClassification>
	<cac:CommodityClassification>
		<cbc:ItemClassificationCode listID="STO">Z12030501</cbc:ItemClassificationCode> (3)
    </cac:CommodityClassification>
[…]
</cac:Item>
----
<1> Codice del dispositivo medico attribuito dal Fornitore;
<2> #Il listID deve essere fra quelli della codifica UNCL7143, il codice ZZZ indica il numero di repertorio attribuito al dispositivo medico nella Banca Dati e Repertorio  (BDR) dei Dispositivi Medici del Ministero della Salute.# +
#Il numero dovrà essere preceduto dalla seguente stringa:#
* #“DM1:” in caso di Dispositivo medico o Dispositivo diagnostico in vitro;#
* #“DM2:” in caso di Sistema o kit Assemblato;#
* #In caso il dispositivo medico non abbia numero di repertorio, il campo sarà valorizzato solo con DM0.#
<3> Il listID deve essere fra quelli della codifica UNCL7143 e il codice STO indica il codice attribuito al dispositivo medico dalla Classificazione Nazionale dei Dispositivi Medici (CND).

