

= Il Fornitore (AccountingSupplierParty)

Il fornitore è colui che vende la merce o i servizi al cliente. Il fornitore è obbligatorio in quanto è il emittente del documento, inoltre è obbligatorio includere l’EndpointID (ParticipantID) con il quale è registrato su PEPPOL.


.Esempio di informazioni per un fornitore italiano con indicazione della Partita Iva nell'Endpoint
[source, xml, indent=0]
----
<cac:AccountingSupplierParty>
    <cac:Party>
	 <cbc:EndpointID schemeID="0211">IT01234567890</cbc:EndpointID>
	 <cac:PartyName>
	 	<cbc:Name>Fornitore S.p.A.</cbc:Name>
	 </cac:PartyName>
	 <cac:PostalAddress>
	 	<cbc:StreetName>Indirizzo Riga 1</cbc:StreetName>
	 	<cbc:AdditionalStreetName>Indirizzo Riga 2</cbc:AdditionalStreetName  >
	 	<cbc:CityName>Bologna</cbc:CityName>
	 	<cbc:PostalZone>40121</cbc:PostalZone>
	 	<cbc:CountrySubentity>BO</cbc:CountrySubentity >
	 	<cac:AddressLine>
	 		<cbc:Line>Zona Savena</cbc:Line>
	 	</cac:AddressLine>
	 	<cac:Country>
	 	<cbc:IdentificationCode>IT</cbc:IdentificationCode>
	 	</cac:Country>
	 </cac:PostalAddress>
	 <cac:PartyTaxScheme>
	    <cbc:CompanyID>IT01234567890</cbc:CompanyID>
	    <cac:TaxScheme>
	        <cbc:ID>VAT</cbc:ID>
	    </cac:TaxScheme>
	 </cac:PartyTaxScheme>
	 <cac:PartyLegalEntity>
	 	<cbc:RegistrationName>Azienda fornitore</cbc:RegistrationName>
	 </cac:PartyLegalEntity>
	 <cac:Contact>
	 	<cbc:Name>Lucio Grande</cbc:Name>
	 	<cbc:Telephone>051102030</cbc:Telephone>
	 	<cbc:ElectronicMail>lucio.grande@fornitore.it</cbc:ElectronicMail>
	 </cac:Contact>
    </cac:Party>
</cac:AccountingSupplierParty>
----

#Se il Fornitore è un’amministrazione pubblica, il campo *EndpointID/@schemeID* deve essere valorizzato con “0201:” seguito dal Codice UFE della PA.#

#Nel caso in cui non si inserisca la Partita IVA nell’EndpointID, la Partita IVA va indicata nel *cac:PartyTaxScheme/cbc:CompanyID*.#

#Nel caso in cui si voglia indicare anche il Codice Fiscale, quest’ultimo va indicato nel *cac:PartyLegalEntity/cbc:CompanyID*.#

.Esempio di indicazione della Partita Iva e del Codice Fiscale
[source, xml, indent=0]
----
<cac:AccountingSupplierParty>
 <cac:Party>
	<cbc:EndpointID schemeID="0201">UFY9MH</cbc:EndpointID>
	<cac:PartyName>
		<cbc:Name>Azienda USL di Reggio Emilia</cbc:Name>
	</cac:PartyName>
	<cac:PostalAddress>
		<cbc:StreetName>Via Amendola 2</cbc:StreetName>
		<cbc:CityName>Reggio Emilia</cbc:CityName>
		<cbc:PostalZone>42122</cbc:PostalZone>
		<cbc:CountrySubentity>RE</cbc:CountrySubentity>
		<cac:Country>
			<cbc:IdentificationCode>IT</cbc:IdentificationCode>
		</cac:Country>
	</cac:PostalAddress>
	<cac:PartyTaxScheme>
	    <cbc:CompanyID>IT01234567890</cbc:CompanyID>
	    <cac:TaxScheme>
	        <cbc:ID>VAT</cbc:ID>
	    </cac:TaxScheme>
	</cac:PartyTaxScheme>
	<cac:PartyLegalEntity>
		<cbc:RegistrationName>Azienda USL di Reggio Emilia</cbc:RegistrationName>
		<cbc:CompanyID>CF:01598570354</cbc:CompanyID>
	</cac:PartyLegalEntity>
	<cac:Contact>
		<cbc:Name>Giovanni Rossi</cbc:Name>
		<cbc:Telephone>0522335111</cbc:Telephone>
		<cbc:ElectronicMail>giovanni.rossi@ausl.re.it</cbc:ElectronicMail>
	</cac:Contact>
    </cac:Party>
</cac:AccountingSupplierParty>
----

.Esempio di informazioni per un fornitore estero
[source, xml, indent=0]
----
</cac:AccountingSupplierParty>
    <cac:Party>
	 <cbc:EndpointID schemeID="9925">0999999999</cbc:EndpointID
	 <cac:PartyName>
	 	<cbc:Name>Fornitore Estero</cbc:Name>
	 </cac:PartyName>
	 <cac:PostalAddress>
	 	<cbc:StreetName> Rue Emile Claus 28</cbc:StreetName>
		<cbc:AdditionalStreetName>Quartiere</cbc:AdditionalStreetName>
		<cbc:CityName>Bruxelles</cbc:CityName>
		<cbc:PostalZone>1050</cbc:PostalZone>
		<cac:AddressLine>
		<cbc:Line>Deposito Consegnatario: Fornitore Estero</cbc:Line>
		</cac:AddressLine>
			<cac:Country>
			<cbc:IdentificationCode>BE</cbc:IdentificationCode>
			</cac:Country>
	 </cac:PostalAddress>
	 <cac:PartyTaxScheme>
	    <cbc:CompanyID>BE0848934496</cbc:CompanyID>
	    <cac:TaxScheme>
	        <cbc:ID>VAT</cbc:ID>
	    </cac:TaxScheme>
	 </cac:PartyTaxScheme>
	 <cac:PartyLegalEntity>
	 	<cbc:RegistrationName>Fornitore Estero</cbc:RegistrationName>
	 </cac:PartyLegalEntity>
	 <cac:Contact>
	 	<cbc:Name>Lucio Grande</cbc:Name>
	 	<cbc:Telephone>003241102030</cbc:Telephone>
	 	<cbc:ElectronicMail>lucio.grande@belgio.be</cbc:ElectronicMail>
	 </cac:Contact>
    </cac:Party>
</cac:AccountingSupplierParty>
----

#Il campo *cac:PartyLegalEntity/cbc:RegistrationName* può essere usato per indicare il dato FPA 1.2.1.3.1 Denominazione preceduto dalla stringa "Denominazione:". In alternativa, lo stesso può essere usato per indicare i dati FPA 1.2.1.3.2 Nome e 1.2.1.3.3 Cognome preceduti dalla stringa "Nome&Cognome:" e concatenati dal simbolo ""&#x0023;".#


#Le informazioni relative all'Albo vengono fornite nel *cac:PartyIdentification/cbc:ID* concatenando il Nome Albo, il numero e la data iscrizione con il simbolo "&#x0023;", preceduti dalla stringa "ALBO:".#

[NOTE]
Trattasi di CIUS domestica (DC)

.Esempio UBL per esprimere informazioni relative all'Albo

[source, xml, indent=0]
----
</cac:AccountingSupplierParty>
    <cac:Party>
    ...
        <cac:PartyIdentification>
            <cbc:ID>ALBO:NomeAlbo#12345#YYYY-MM-DD</cbc:ID>
        </cac:PartyIdentification>
    ...
    </cac:Party>
</cac:AccountingSupplierParty>
----


#Il numero del Codice EORI (Economic Operator Registration and Identification) basato sul Regolamento (CE) n. 312 del 16 aprile 2009 ed in vigore dal 1 luglio 2009, può essere anch'esso espresso nell'elemento *cac:PartyIdentification/cbc:ID* omettendo l'attributo @schemeID ma includendo il prefisso "EORI:" come nell'esempio di seguito.#

[NOTE]
Trattasi di CIUS domestica (DC)

.Esempio UBL per esprimere il codice EORI
[source, xml, indent=0]
----
<cac:PartyIdentification>
    <cbc:ID>EORI:12345678901</cbc:ID>
</cac:PartyIdentification>
----


#Il campo *cac:PartylegalEntity/cbc:CompanyID* può essere usato per indicare le informazioni relative a FPA 1.2.4.1 Ufficio e FPA 1.2.4.2 Numero REA  concatenando i due dati con il "&#x0023;", preceduti dalla stringa "REA:".#

[NOTE]
Trattasi di CIUS domestica (DC)


.Esempio UBL per esprimere informazioni relative al numero REA
[source, xml, indent=0]
----
<cac:PartyLegalEntity>
    ...
	<cbc:CompanyID>REA:MI#1713601</cbc:CompanyID>
	...
</cac:PartyLegalEntity>
----


#Il campo *cac:PartyLegalEntity/cbc:CompanyLegalForm* può essere usato per indicare informazioni legali addizionali quali FPA 1.2.4.3 CapitaleSociale, FPA 1.2.4.4 SocioUnico e FPA  1.2.4.5 StatoLiquidazione, concatenando i campi con il simbolo "&#x0023;".#

[NOTE]
Trattasi di CIUS domestica (DC)


.Esempio UBL per indicare il Capitale Sociale

[source, xml, indent=0]
----
<cac:PartyLegalEntity>
    ...
	<cbc:cbc:CompanyLegalForm>100000##</cbc:cbc:CompanyLegalForm>
	...
</cac:PartyLegalEntity>
----

#Nell'utilizzo dell’aggregato informativo *cac:PostalAddress*, è obbligatorio l'utilizzo delle informazioni di indirizzo, CAP, Comune e nazione.# +

[NOTE]
Trattasi di CIUS domestica (DC)

#Di seguito si riportano due esempi di come compilare le informazioni dell’indirizzo.#

.Indirizzo semplice
[source, xml]
<cac:PostalAddress>
	<cbc:StreetName>Via principale 2, Palazzo 4</cbc:StreetName>
	<cbc:CityName>Grande città</cbc:CityName>
	<cbc:PostalZone>54321</cbc:PostalZone>
	<cac:Country>
		<cbc:IdentificationCode>IT</cbc:IdentificationCode>
	</cac:Country>
</cac:PostalAddress>

.Indirizzo completo
[source, xml]
<cac:PostalAddress>
	<cbc:StreetName>Corso di Francia</cbc:StreetName>
	<cbc:AdditionalStreetName>I Parioli</cbc:AdditionalStreetName>
	<cbc:CityName>Roma</cbc:CityName>
	<cbc:PostalZone>00197</cbc:PostalZone>
	<cbc:CountrySubentity>RM</cbc:CountrySubentity>
	<cac:AddressLine>
		<cbc:Line>Informazioni Aggiuntive</cbc:Line>
	</cac:AddressLine>
	<cac:Country>
		<cbc:IdentificationCode>IT</cbc:IdentificationCode>
	</cac:Country>
</cac:PostalAddress>



= Il Cliente (AccountingCustomerParty)

Il Cliente, detto anche Cessionario o Committente, è la persona o organizzazione che acquisisce la proprietà di un prodotto o di un servizio in base ad un prezzo concordato e a dei termini di pagamento. +

#Il cliente può essere solo una Pubblica Amministrazione.#

Le informazioni inerenti al cliente sono obbligatorie e vengono fornite nell'elemento 'cac:AccountingCustomerParty'


.Esempio UBL di informazioni sul Cliente
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=buyer]
----
<1> L'attributo schemeID è obbligatorio per indirizzi elettronici, es. EndpointID

<2> Gli identificatori per il VAT/IVA devono incudere il prefisso del codice paese
<3> Il codice fiscale è preceduto dalla stringa "CF:"


#Il campo *cac:PartyLegalEntity/cbc:RegistrationName* può essere usato per indicare il dato FPA 1.2.1.3.1 Denominazione preceduto dalla stringa "Denominazione:". In alternativa, lo stesso può essere usato per indicare i dati FPA 1.2.1.3.2 Nome e 1.2.1.3.3 Cognome preceduti dalla stringa "Nome&Cognome:" e concatenati dal simbolo "&#x0023;".#


#Il Codice EORI può essere espresso nell'elemento *cac:PartyIdentification/cbc:ID* omettendo l'attributo @schemeID ma includendo il prefisso "EORI:" come nell'esempio di seguito.#

[NOTE]
Trattasi di CIUS domestica (DC)

.Esempio UBL per esprimere il codice EORI
[source, xml, indent=0]
----
<cac:PartyIdentification>
    <cbc:ID>EORI:12345678901</cbc:ID>
</cac:PartyIdentification>
----

= Il Beneficiario (PayeeParty)

Il beneficiario è una persona, istituto bancario o entità di business alla quale si effettua il pagamento.

Il beneficiario è una informazione facoltativa. Se questa informazione non è fornita, il fornitore/venditore è anche il beneficiario del pagamento.

Quando vengono fornite le informazioni del beneficiario significa che si evidenzia un caso di factoring.

Per riflettere l'assegnazione di una Fattura ad un factor è necessario:

. avere una dichiarazione di esclusione di responsabilità (avviso) sulla fattura che questa è stata assegnata ad un factor. La dichiarazione di esclusione di responsabilità dovrebbe essere fornita nella Invoice note (BT-22) a livello di testata.

. identificare il Factor con il Beneficiario

. modificare le coordinate bancarie a favore del Factor.


.Esempio UBL per le informazioni del beneficiario
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=payee]
----


#Il campo *cac:PartyIdentification/cbc:ID* può essere inoltreusato per fornire le informazioni anagrafiche del Quietanzante indicando i dati FPA 2.4.2.8 CognomeQuietanzante e  FPA 2.4.2.9 NomeQuietanzante concatenati con il simbolo "&#x0023;".#


= Rappresentante fiscale del fornitore (TaxRepresentativeParty)

In alcuni scenari di business, le aziende che commerciano oltre confine sono tenute secondo le autorità fiscali locali a nominare un rappresentante fiscale. 
Sono comprese le aziende extra-EU che operano in Europa, gli importatori in EU e i commercianti.  

I rappresentanti fiscali sono responsabili per la gestione corretta e la regolarizzazione dell'IVA per conto delle aziende, in linea con le normative locali. Un rappresentante fiscale è considerato come l'agente locale del commerciante.  In molti casi, il rappresentante fiscale è ritenuto responsabile in solido per le tasse del commerciante.

#Il Codice Fiscale può essere espresso all'interno del Party nell'elemento PartyIdentification/ID inserendo l’attributo @schemeID valorizzato con il codice "0210", come nell'esempio di seguito.#


.Esempio UBL per le informazioni del rappresentante fiscale
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=taxrep]
----
<1> Gli identificatori per il VAT/IVA devono incudere il prefisso del codice paese

#Il campo *cac:PartyName/cbc:Name* può essere usato per indicare il dato FPA 1.3.1.3.1 Denominazione preceduto dalla stringa "Denominazione:". In alternativa, lo stesso può essere usato per indicare i dati FPA 1.3.1.3.2 Nome e 1.3.1.3.3 Cognome preceduti dalla stringa "Nome&Cognome:" e concatenati dal simbolo "&#x0023;".#

#Il Codice EORI può essere espresso nell'elemento *cac:PartyIdentification/cbc:ID* omettendo l'attributo @schemeID ma includendo il prefisso "EORI:" come nell'esempio di seguito.#

[NOTE]
Trattasi di CIUS domestica (DC)

.Esempio UBL per esprimere il codice EORI
[source, xml, indent=0]
----
<cac:PartyIdentification>
    <cbc:ID>EORI:12345678901</cbc:ID>
</cac:PartyIdentification>
----

= #Stabile Organizzazione (AccountingSupplierParty/ServiceProviderParty)#

#Se il cedente/prestatore non residente ha una stabile organizzazione in Italia, si può specificare in fattura come parte dei dati del fornitore nell'elemento AgentParty.#

.Esempio UBL per la stabile organizzazione del fornitore
[source, xml, indent=0]
----
include::../../rules/snippets/agid-extensions.xml[tag=stabile_organizzazione_fornitore]
----


= #Il Terzo Intermediario o Soggetto Emittente (AccountingSupplierParty/ServiceProviderParty)#

Nel caso sia un soggetto terzo ad emettere fattura per conto del cedente / prestatore, si può specificare in fattura come parte dei dati del fornitore nell'elemento ServiceProviderParty.

.Esempio UBL per il terzo intermediario o soggetto emittente per conto del fornitore
[source, xml, indent=0]
----
include::{snippet-dir}/agid-extensions.xml[tag=terzo_intermediario]
----

Il Codice Fiscale può essere espresso all'interno del Party nell'elemento PartyIdentification/ID inserendo l’attributo @schemeID valorizzato con il codice "0210", come nell'esempio di seguito.

[source, xml, indent=0]
----
<cac:PartyIdentification>
    <cbc:ID schemeID="0210">CXXNXX68M06E123H</cbc:ID>
</cac:PartyIdentification>
----

#Il Codice EORI può essere espresso nell'elemento *cac:PartyIdentification/cbc:ID* omettendo l'attributo @schemeID ma includendo il prefisso "EORI:" come nell'esempio di seguito.#

[NOTE]
Trattasi di CIUS domestica (DC)

.Esempio UBL per esprimere il codice EORI
[source, xml, indent=0]
----
<cac:PartyIdentification>
    <cbc:ID>EORI:12345678901</cbc:ID>
</cac:PartyIdentification>
----

= #Il Vettore (Delivery/CarrierParty)#

Nei casi di fattura "accompagnatoria", come parte delle informazioni relative al trasporto è possibile specificare i dati fiscali e anagrafici del vettore che trasporta e consegna la merce, nell'elemento CarrierParty.

Il Codice Fiscale può essere espresso all'interno del Party nell'elemento PartyIdentification/ID inserendo l’attributo @schemeID valorizzato con il codice "0210", come nell'esempio di seguito.


.Esempio UBL per il vettore che effettua il trasporto
[source, xml, indent=0]
----
include::{snippet-dir}/agid-extensions.xml[tag=info_vettore]
----
