[[order-reference]]
= Riferimento all’Ordine

Usato per fornire riferimento all’ordine d’acquisto sul quale il Documento di Trasporto si basa e per favorirne la riconciliazione automatica.
Ci possono essere molteplici documenti di trasporto a fronte di un ordine d’acquisto.
Ogni Documento di Trasporto si può riferire ad uno o più ordini.

A seconda dei casi è possibile indicare il riferimento all’ordine in testata o dalle righe del Documento di Trasporto. I paragrafi seguenti indicano con precisione i casi possibili.

Inoltre, la sintassi UBL richiede di indicare obbligatoriamente nell’elemento <cbc:LineID> il numero della riga d’ordine cui si riferisce la riga del DDT.
Per supportare scenari dove è sufficiente riferirsi all’ordine in generale si deve usare il valore **NA**.

#Per riferirsi a un ordine è necessario riportare gli elementi che lo identificano mediante la concatenazione dei seguenti campi:#

* #ID dell’ordine;#
* #IssueDate valorizzato con la data dell’ordine;#
* #EndpointID dell’elemento BuyerCustomerParty dell’ordine;#

.Esempio a livello di testata
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-2.xml[tags=ref-order]
----

.Esempio 1 a livello di riga
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-2.xml[tags=ref-orderline]
----

.Esempio 2 a livello di riga
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-2.xml[tags=ref-orderlinena]
----

E' inoltre possibile riferirsi a più di un ordine in un singolo documento di trasporto.
In questo caso non ci deve essere un riferimento all'ordine a livello di testata.

Per riferirsi a più ordini sarà quindi possibile indicare uno o più numeri d’ordine su ogni riga del DDT. 

.Esempio 3 a livello di riga con riferimento a più ordini
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-3.xml[tags=ref-orderlinemulti]
----
