[[order-reference]]
= Riferimento all’Ordine

Usato per fornire riferimento all’ordine d’acquisto sul quale il Documento di Trasporto si basa e per favorirne la riconciliazione automatica.
Ci possono essere molteplici documenti di trasporto a fronte di un ordine d’acquisto.
Ogni Documento di Trasporto si può riferire ad un solo ordine.

La sintassi UBL richiede di indicare obbligatoriamente nell’elemento <cbc:LineID> il numero della riga d’ordine cui si riferisce la riga del DDT.
Per supportare scenari dove è sufficiente riferirsi all’ordine in generale si deve usare il valore **NA**.

.Esempio a livello di testata
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-2.xml[tags=ref-order]
----

.Esempio 1 a livello di riga
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-2.xml[tags=ref-orderline]
----

.Esempio 2 a livello di riga
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-2.xml[tags=ref-orderlinena]
----

E' inoltre possibile riferirsi a più di un ordine in un singolo documento di trasporto.
In questo caso non ci deve essere un riferimento all'ordine a livello di testata.
