[[parties]]
= Parti e Ruoli

Le seguenti parti/ruoli possono essere specificate nel messaggio.  Lo stesso attore gioca più di un ruolo a seconda dei casi.

[[despatch-party-despatchsupplierparty]]
== Speditore - Mittente (DespatchSupplierParty)

Lo Speditore è la persona o organizzazione che fornisce (spedisce) merce o servizi.
Questo ruolo è ricoperto dal Fornitore o per suo conto (Lo Speditore è anche conosciuto come Mittente).
Lo Speditore è un’informazione obbligatoria.  In particolare sono obbligatori il nome e l’identificativo come da Art. 21, comma 4 del DPR n. 633/1972.
#Le stesse informazioni sono richieste e verificate dall’Access Point di destinazione ai fini della riconciliazione con l’Ordine.#

Esempio:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=despatchsupplier]
----

[[consignee-deliverycustomerparty]]
== Consegnatario - Destinatario (DeliveryCustomerParty)

Il Consegnatario è la persona o organizzazione alla quale saranno spediti i prodotti e che ne prenderà il possesso.
Questo ruolo è ricoperto dal Cliente o per suo conto.
Il Consegnatario è un’informazione obbligatoria nel messaggio di Avviso Spedizione e lo è anche per legge come da Art. 21, comma 4 del DPR n. 633/1972.

Esempio:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=deliverycustomer]
----

[[buyer-buyercustomerparty]]
== Acquirente (BuyerCustomerParty)

L’Acquirente è la persona giuridica che acquista la merce o i servizi. Il ruolo è ricoperto dal Cliente o per suo conto.
L’Acquirente è un’informazione opzionale nel Documento di Trasporto.

Esempio:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=buyer]
----


[[seller-sellersupplierparty]]
== Venditore (SellerSupplierParty)

Il Venditore è la persona giuridica che vende la merce o i servizi al Cliente. Il ruolo è ricoperto dal Fornitore o per suo conto.
L’informazione del Venditore è opzionale nel Documento di Trasporto.

Esempio:
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=seller]
----


[[originating-party-originatorcustomerparty]]
== Committente (OriginatorCustomerParty)

La parte che eventualmente riceve e consuma la merce per cui conto l’Acquirente fa l’acquisto.
Il Committente è un’informazione opzionale nel Documento di Trasporto. 

Esempio:

[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=originator]
----


[[carrier-party-carrierparty]]
== Vettore (CarrierParty)

Il Vettore gestisce la consegna/trasporto fisico della spedizione inviata. Utilizzato se una terza parte effettua il trasporto fisico. 

Esempio:

[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=carrier]
----
<1> la P.IVA del Vettore viene specificata con il prefisso IT:VAT: e senza l'attributo @schemeID in quanto la codifica ICD non include gli identificativi fiscali