[[use-case-4-complex-ordering]]
= Caso d’uso 4 – Risposta ad un ordine di fornitura complesso

Questo caso d’uso è relativo a un ordine contenente quasi tutti gli elementi previsti per il messaggio dell’Ordine PEPPOL. +
L’ordine viene accettato completamente dal venditore.

[cols="1s,5",options="header"]
|====
|Caso d’uso nr.
|4

|Nome
|Ordine complesso

|Descrizione
a|
* Un ordine di articoli numerati con sconti e maggiorazioni sia a livello di testata che di riga e prezzo.


|Parti coinvolte
|Acquirente +
Venditore +
Committente

|Assunzioni
|L’acquirente ha a disposizione un catalogo o una lista di prodotti per effettuare l’ordine. +
Il catalogo contiene gli identificativi degli articoli, nomi e unità di misura. +
L’acquirente ha stretto uno speciale accordo con il venditore relativamente ad uno sconto sull’ordine, le righe d’ordine e sul prezzo.

|Il flusso
|L’acquirente crea l’ordine con 4 diverse righe e articoli. Il venditore accetta di consegnare tutti e 4 gli articoli. +
L’ordine è stato accettato senza modifiche. Nessuna riga deve essere inviata nella risposta all’ordine.

|Risultati
|L’acquirente e il venditore hanno raggiunto un accordo. +
L’acquirente ha aggiornato le informazioni dell’ordine in base alla risposta d’ordine. +
Se la fattura contiene il riferimento all’ordine, questa può essere correlata automaticamente.

|Esempio XML
|Vedi sezione "Downloads" della https://notier.regione.emilia-romagna.it/docs/[home]
|====
