[[hazardous-item]]
= Hazardous item

The Peppol Despatch Advice also contains the possibility to inform the Consignee about Hazardous Items (also referred to as HAZMAT, Hazard Material o Dangerous Goods). +

This is done by informing the dangerous regulation code for example ADR (Road transport), IMDG (transport by sea) or RID (railroad transport).  +

When declaring hazardous items it is recommended to use the UNDG code to inform about the convention the item is declared hazardous under. +

When the UNDG code has been declared the Hazard class is declared. +

The Hazard class corresponds to the hazardous class of the item for example class 2.3 which indicates Poisonous Gas.

.UBL example of declaring hazardous items.
[source, xml, indent=0]
----
include::{snippet-dir}/snippet-30-1.xml[tags=hazardous]
----

In certain sectors may be necessary to identify the hazardous items in a more precise way, by providing the following information:

.Extended information about the hazardous items
[width="100%", cols="2h,3m,1m"]
|===
| *Extended information*
| *Description*
| *UBL syntax*

| Hazardous item identifier 
| Assigned UN identifier (UN Number)
| cbc:ID

| Hazardous item technical name
| UN technical name
| cbc:TechnicalName

| Hazardous item category
| Name of the type of hazard for a material or substance
| cbc:CategoryName
|===

In the next paragraph provides an advanced example that utilizes all the extended information described above.


