[[Sconti-e-maggiorazioni]]
= Sconti e Maggiorazioni 

Gli elementi per specificare sconti e maggiorazioni si trovano su due livelli.

L’elemento `cac:AllowanceCharge` con il sotto elemento `cac:ChargeIndicator` permette di indicare se si sta specificando una maggiorazione (true) o uno sconto/abbuono (false).

Livello di testata:: _Si applica all’intero ordine ed è incluso nel calcolo dell’importo totale dell’ordine (se specificato)._
* Possono essere forniti sconti e maggiorazioni
* Le informazioni sulle imposte relative agli sconti e maggiorazioni (cac:TaxCategory con i suoi sotto elementi) devono essere fornite
* La somma di tutti gli sconti e maggiorazioni a livello di testata deve essere specificato rispettivamente nel AllowanceTotalAmount e nel ChargeTotalAmount, vedi paragrafo "6.9 Calcolo dei totali (AnticipatedMonetaryTotals)".

Elemento Prezzo a livello di riga:: _Il prezzo indicato deve essere sempre il prezzo netto, cioè l’importo base ridotto da uno sconto._
* Solamente una occorrenza di sconto è consentita
* Le informazioni sulle imposte relative agli sconti non devono essere specificate
* Gli sconti relativi al prezzo sono solo informativi e non sono considerati in qualsiasi altro calcolo
* Gli sconti relativi al prezzo possono specificare l’importo e l’importo base



== Sconti e maggiorazioni a livello di testata

Sconti e maggiorazioni a livello di testata sono costituiti da elementi contenenti informazioni sull’importo base di sconti/maggiorazioni e sulla percentuale di sconti/maggiorazioni.

Se l’importo base è presente, deve essere presente la percentuale, e se la percentuale è presente anche l’importo base deve essere presente. Il calcolo dell’importo è definito nel modo seguente:

====
stem:["Importo" =  "Importo base" times ("Percentuale" div 100)]
====


.Esempio di UBL di sconti e maggiorazioni a livello di testata, per l'IVA
[source, xml, indent=0]
----
<cac:AllowanceCharge>
        <cbc:ChargeIndicator>true</cbc:ChargeIndicator> <1>
        <cbc:AllowanceChargeReasonCode>FC</cbc:AllowanceChargeReasonCode>
        <cbc:AllowanceChargeReason>Freight service</cbc:AllowanceChargeReason>
        <cbc:MultiplierFactorNumeric>2</cbc:MultiplierFactorNumeric> <4>
        <cbc:Amount currencyID="EUR">20</cbc:Amount> <5>
        <cbc:BaseAmount currencyID="EUR">1000.00</cbc:BaseAmount> <3>
        <cac:TaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>22</cbc:Percent>
                <cac:TaxScheme>
                        <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
        </cac:TaxCategory>
</cac:AllowanceCharge>
<cac:AllowanceCharge>
        <cbc:ChargeIndicator>false</cbc:ChargeIndicator> <2> 
        <cbc:AllowanceChargeReasonCode>65</cbc:AllowanceChargeReasonCode>
        <cbc:AllowanceChargeReason>Production error discount</cbc:AllowanceChargeReason>
        <cbc:Amount currencyID="EUR">10.00</cbc:Amount>
        <cac:TaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>22</cbc:Percent>
                <cac:TaxScheme>
                        <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
        </cac:TaxCategory>
</cac:AllowanceCharge>
----

<1> 	ChargeIndicator = TRUE indica la presenza di una maggiorazione
<2> 	ChargeIndicator = FALSE indica la presenza di uno sconto
<3> Importo base, deve essere usato con la percentuale per calcolare l’importo
<4> Percentuale maggiorazione
<5> stem:["Importo" = "Importo base" times ("Percentuale" div 100)]


.Esempio di un UBL con una maggiorazione relativa ai costi di imballaggio
[source, xml, indent=0]
----
<cac:AllowanceCharge>
    <cbc:ChargeIndicator>true</cbc:ChargeIndicator>
    <cbc:AllowanceChargeReasonCode>ABL</cbc:AllowanceChargeReasonCode>
    <cbc:AllowanceChargeReason>Costi diimballaggio</cbc:AllowanceChargeReason>
    <cbc:MultiplierFactorNumeric>20</cbc:MultiplierFactorNumeric>
    <cbc:Amount currencyID="EUR">10.00</cbc:Amount>
    <cbc:BaseAmount currencyID="EUR">50.00</cbc:BaseAmount>
</cac:AllowanceCharge>
----

.Esempio di UBL che mostra uno sconto per l’intero ordine
[source, xml, indent=0]
----
<cac:AllowanceCharge>
    <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
	<cbc:AllowanceChargeReasonCode>41</cbc:AllowanceChargeReasonCode>
    <cbc:AllowanceChargeReason>Sconto</cbc:AllowanceChargeReason>
    <cbc:MultiplierFactorNumeric>2</cbc:MultiplierFactorNumeric>
	<cbc:Amount currencyID="EUR">2.00</cbc:Amount>
	<cbc:BaseAmount currencyID="EUR">100.00</cbc:BaseAmount>
</cac:AllowanceCharge>
----


== #Sconti e maggiorazioni sul prezzo#

Questo esempio mostra uno sconto di 10 EUR sul prezzo base:

[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
        <cbc:ID>1</cbc:ID>
        <cbc:Quantity unitCode="C62" unitCodeListID="UNECERec20">20</cbc:Quantity>
        <cbc:LineExtensionAmount currencyID="EUR">1800.00</cbc:LineExtensionAmount>
        ...
        <cac:Price>
            <cbc:PriceAmount currencyID="EUR">90.00</cbc:PriceAmount>
            <cac:AllowanceCharge>
                <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
                <cbc:Amount currencyID="EUR">10.00</cbc:Amount>
                <cbc:BaseAmount currencyID="EUR">100.00</cbc:BaseAmount>
            </cac:AllowanceCharge>
        </cac:Price>
    </cac:LineItem>
</cac:OrderLine>
----

:leveloffset: +1

[[titolo]]
= #Sconti e maggiorazioni a livello di riga#

Questo esempio mostra uno sconto applicato a tutta la riga d’ordine:

[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
        <cbc:ID>1</cbc:ID>
        <cbc:Quantity unitCode="C62" unitCodeListID="UNECERec20">10</cbc:Quantity>
        <cbc:LineExtensionAmount currencyID="EUR">90.00</cbc:LineExtensionAmount>
        <cac:AllowanceCharge>
			<cbc:ChargeIndicator>false</cbc:ChargeIndicator>
			<cbc:AllowanceChargeReason>Sconto sulla riga</cbc:AllowanceChargeReason>
			<cbc:MultiplierFactorNumeric>10</cbc:MultiplierFactorNumeric>
			<cbc:Amount currencyID="EUR">10.00</cbc:Amount>
			<cbc:BaseAmount currencyID="EUR">100.00</cbc:BaseAmount>
        </cac:AllowanceCharge>
        <cac:Price>
            <cbc:PriceAmount currencyID="EUR">10.00000</cbc:PriceAmount><!-- Opzionale -->
        </cac:Price>
    </cac:LineItem>
</cac:OrderLine>
----

:leveloffset: -1


:leveloffset: +1

[[titolo]]
= #Sconto Merce#

Per cessioni a titolo di sconto, premio o abbuono si inserisce una riga d’ordine separata prestando attenzione ad indicarne la relativa esenzione IVA.

Infatti ai fini IVA lo sconto merce rientra nelle operazioni Escluse ex Art. 15 D.P.R. 633/72.

[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
        <cbc:ID>1</cbc:ID>
        <cbc:Quantity unitCode="C62" unitCodeListID="UNECERec20">10</cbc:Quantity>
        <cbc:LineExtensionAmount currencyID="EUR">0.00</cbc:LineExtensionAmount>
        <cac:AllowanceCharge>
            <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
            <cbc:AllowanceChargeReason>Sconto Merce</cbc:AllowanceChargeReason>
            <cbc:MultiplierFactorNumeric>100</cbc:MultiplierFactorNumeric>
            <cbc:Amount currencyID="EUR">90.00</cbc:Amount>
            <cbc:BaseAmount currencyID="EUR">90.00</cbc:Amount>
        </cac:AllowanceCharge>
        <cac:Price>
            <cbc:PriceAmount currencyID="EUR">9.00000</cbc:PriceAmount>
        </cac:Price>
        <cac:Item>
            <cbc:Description>1x12 PACCHI</cbc:Description>
            <cbc:Name>ARTICOLO MERCE</cbc:Name>
            <cac:ClassifiedTaxCategory>
                <cbc:ID>O</cbc:ID>
            </cac:ClassifiedTaxCategory>
        </cac:Item>
    </cac:LineItem>
</cac:OrderLine>
----

:leveloffset: -1


:leveloffset: +1

[[titolo]]
= #Omaggi#

Per includere nell’ordine degli articoli in omaggio è necessario indicarli in riga separata rispetto a quelli a pagamento e poi si deve indicare sia l’importo di riga che il prezzo con importo a 0 (zero).

.Esempio di una riga d’ordine contenente in omaggio 12 pacchi di striscie per il test del glucosio:
[source, xml, indent=0]
----
<cac:orderline>
    <cac:LineItem>
        <cbc:ID>1</cbc:ID>
        <cbc:Quantity unitCode="C62" unitCodeListID=”UNECERec20”>20</cbc:Quantity>
        <cbc:LineExtensionAmount currencyID="EUR">0</cbc:LineExtensionAmount>
        <cac:Price>
            <cbc:PriceAmount currencyID="EUR">0</cbc:PriceAmount>
            <cbc:BaseQuantity unitCode="C62" unitCodeListID=”UNECERec20”>1</cbc:BaseQuantity>
            <cac:AllowanceCharge>
                <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
                <cbc:Amount currencyID="EUR">5.00</cbc:Amount>
                <cbc:BaseAmount currencyID="EUR">5.00</cbc:BaseAmount>
            </cac:AllowanceCharge>
        </cac:Price>
        <cac:Item>
            <cbc:Description>1x12 pacchi</cbc:Description>
            <cbc:Name>Striscie per glucosio</cbc:Name>
            <cac:SellersItemIdentification>
               <cbc:ID>79847-E</cbc:ID>
            </cac:SellersItemIdentification>
            <cac:ClassifiedTaxCategory>
                <cbc:ID schemeID="UNCL5305">S</cbc:ID>
                <cbc:Percent>22</cbc:Percent></cac:Item>
                <cac:TaxScheme>
                     <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
            </cac:ClassifiedTaxCategory>
        </cac:Item>
    </cac:LineItem>
</cac:OrderLine>
----

:leveloffset: -1
