[[parti]]
= Parti

Le seguenti parti/I seguenti ruoli possono essere specificate/i nel messaggio:

[[sellersupplierparty-seller]]
== Fornitore/Venditore (SellerSupplierParty)

Il Venditore è la persona giuridica o l’organizzazione che vende beni e/o servizi. +
Il Venditore è un’informazione obbligatoria in quanto destinatario dell’Ordine, pertanto è necessario includere l’EndpointID (ParticipantID) con il quale è registrato su Peppol.


.Esempio di informazioni per un fornitore italiano con indicazione della Partita Iva nell'Endpoint
[source, xml, indent=0]
----
<cac:SellerSupplierParty>
    <cac:Party>
	 <cbc:EndpointID schemeID="0211">IT01234567890</cbc:EndpointID>
	 <cac:PostalAddress>
	 	<cbc:StreetName>Indirizzo Riga 1</cbc:StreetName>
	 	<cbc:AdditionalStreetName>Indirizzo Riga 2</cbc:AdditionalStreetName>
	 	<cbc:CityName>Bologna</cbc:CityName>
	 	<cbc:PostalZone>40121</cbc:PostalZone>
	 	<cbc:CountrySubentity>BO</cbc:CountrySubentity>
	 	<cac:AddressLine>
	 		<cbc:Line>Zona Savena</cbc:Line>
	 	</cac:AddressLine>
	 	<cac:Country>
	 	<cbc:IdentificationCode>IT</cbc:IdentificationCode>
	 	</cac:Country>
	 </cac:PostalAddress>
	 <cac:PartyLegalEntity>
	 	<cbc:RegistrationName>Azienda fornitore</cbc:RegistrationName>
	 	<cac:RegistrationAddress>
	 		<cbc:CityName>Bologna</cbc:CityName>
	 	    <cac:Country>
	 	        <cbc:IdentificationCode>IT</cbc:IdentificationCode>
	 		</cac:Country>
	 	</cac:RegistrationAddress>
	 </cac:PartyLegalEntity>
	 <cac:Contact>
	 	<cbc:Name>Lucio Grande</cbc:Name>
	 	<cbc:Telephone>051102030</cbc:Telephone>
	 	<cbc:ElectronicMail>lucio.grande@fornitore.it</cbc:ElectronicMail>
	 </cac:Contact>
    </cac:Party>
</cac:SellerSupplierParty>
----

#Se il Venditore è un’amministrazione pubblica, il campo *EndpointID/@schemeID* deve essere valorizzato con “0201:” seguito dal Codice Univoco Ufficio (c.d. "Codice iPA", riportato nella rubrica "indicepa"dell'Indice delle Pubbliche Amministrazioni) della PA.#

#Nel caso in cui non si inserisca la Partita IVA nell’EndpointID, la Partita IVA va indicata nel campo *cac:PartyIdentification/cbc:ID*.#

#Nel caso in cui si voglia indicare anche il Codice Fiscale, quest’ultimo va indicato nel campo *cac:PartyLegalEntity/cbc:CompanyID*, valorizzando l’attributo @schemeID con *0210*.#

.Esempio di indicazione della Partita Iva e del Codice Fiscale
[source, xml, indent=0]
----
<cac:SellerSupplierParty>
 <cac:Party>
	<cbc:EndpointID schemeID="0201">UFY9MH</cbc:EndpointID>
	<cac:PartyIdentification>
		<cbc:ID schemeID="0211">IT01598570354</cbc:ID>
	</cac:PartyIdentification>
	<cac:PostalAddress>
		<cbc:StreetName>Via Amendola 2</cbc:StreetName>
		<cbc:CityName>Reggio Emilia</cbc:CityName>
		<cbc:PostalZone>42122</cbc:PostalZone>
		<cbc:CountrySubentity>RE</cbc:CountrySubentity>
		<cac:Country>
			<cbc:IdentificationCode>IT</cbc:IdentificationCode>
		</cac:Country>
	</cac:PostalAddress>
	<cac:PartyLegalEntity>
		<cbc:RegistrationName>Azienda USL di Reggio Emilia</cbc:RegistrationName>
		<cbc:CompanyID schemeID="0210">01598570354</cbc:CompanyID>
		<cac:RegistrationAddress>
			<cbc:CityName>Reggio Emilia</cbc:CityName>
			<cac:Country>
				<cbc:IdentificationCode>IT</cbc:IdentificationCode>
			</cac:Country>
		</cac:RegistrationAddress>
	</cac:PartyLegalEntity>
	<cac:Contact>
		<cbc:Name>Giovanni Rossi</cbc:Name>
		<cbc:Telephone>0522335111</cbc:Telephone>
		<cbc:ElectronicMail>giovanni.rossi@ausl.re.it</cbc:ElectronicMail>
	</cac:Contact>
    </cac:Party>
</cac:SellerSupplierParty>
----


In caso di invio di un ordine verso un fornitore estero, il campo EndpointID deve essere valorizzato dal relativo identificativo qualificato dallo schemeID corrispondente tratto dall’Electronic Address Scheme previsto dallo standard PEPPOL.


.Esempio di informazioni per un fornitore estero
[source, xml, indent=0]
----
<cac:SellerSupplierParty>
	<cac:Party>
		<cbc:EndpointID schemeID="9925">BE0848934496</cbc:EndpointID>
		<cac:PostalAddress>
			<cbc:StreetName>Rond-point Schuman 6</cbc:StreetName>
			<cbc:CityName>Brussels</cbc:CityName>
			<cbc:PostalZone>BE1040</cbc:PostalZone>
			<cac:Country>
				<cbc:IdentificationCode>BE</cbc:IdentificationCode>
			</cac:Country>
		</cac:PostalAddress>
		<cac:PartyTaxScheme>
			<cbc:CompanyID>BE0848934496</cbc:CompanyID>
			<cac:TaxScheme>
				<cbc:ID>VAT</cbc:ID>
			</cac:TaxScheme>
		</cac:PartyTaxScheme>
		<cac:PartyLegalEntity>
			<cbc:RegistrationName>OpenPEPPOL AISBL</cbc:RegistrationName>
			<cbc:CompanyID schemeID="0208">0848934496</cbc:CompanyID>
		</cac:PartyLegalEntity>
		<cac:Contact>
			<cbc:ElectronicMail>mairi.hayworth@penmarin.co.uk</cbc:ElectronicMail>
		</cac:Contact>
	</cac:Party>
</cac:SellerSupplierParty>
----

[yellow-background]#Il Venditore è un elemento essenziale del processo che, eccezionalmente, può non essere determinato a priori, ma divenirlo solo al momento della cessione dei beni e/o della prestazione dei servizi. Ad esempio quando la facoltà di scegliere il Venditore è riservata al Beneficiario.# 

[yellow-background]#In questo caso (Venditore non predeterminato) l’elemento “SellerSupplierParty/Party” deve contenere solo i campi di seguito indicati:# 

* [yellow-background]#“EndpointID”, valorizzato con “9999999999999999” (sedici volte 9) indicando il valore "0210" per lo "Scheme ID";# 

* [yellow-background]#“PostalAddress/Country/IdentificationCode”, valorizzato con il codice corrispondente allo Stato in cu verrà effettuato l’acquisto (per l’Italia “IT”);# 

* [yellow-background]#“PartyLegalEntity/RegistrationName”, valorizzato con “NDEF”.# 

.Esempio di Informazioni del Venditore non identificato
[source, xml, indent=0]
----
<cac:SellerSupplierParty>
    <cac:Party>
	 <cbc:EndpointID schemeID="0210">9999999999999999</cbc:EndpointID>
	 <cac:PostalAddress>
	 	<cac:Country>
	 	    <cbc:IdentificationCode>IT</cbc:IdentificationCode>
	 	</cac:Country>
	 </cac:PostalAddress>
	 <cac:PartyLegalEntity>
	 	<cbc:RegistrationName>NDEF</cbc:RegistrationName>
	 	<cac:RegistrationAddress>
	 		<cac:Country>
	 		    <cbc:IdentificationCode>IT</cbc:IdentificationCode>
	 		</cac:Country>
	 	</cac:RegistrationAddress>
	 </cac:PartyLegalEntity>
    </cac:Party>
</cac:SellerSupplierParty>
----


[[buyercustomerparty-buyer]]
== Cliente/Acquirente (BuyerCustomerParty)

L’Acquirente è la persona giuridica o l’organizzazione che acquista beni e/o servizi. +
L’Acquirente è un’informazione obbligatoria in quanto mittente dell’Ordine, pertanto è necessario includere l’EndpointID.


#Nel caso in cui il cliente abbia la Partita IVA, la Partita IVA va indicata nel cac:PartyTaxScheme/cbc:CompanyID.# +
#Nel caso in cui il cliente sia dotato solo di Codice Fiscale, questo va indicato nel cac:PartyLegalEntity/cbc:CompanyID, valorizzando l’attributo @schemeID con “0210”.# +

[IMPORTANT]
====
#Almeno uno tra Partita IVA e Codice Fiscale deve essere presente. +
Il campo cac:PartyLegalEntity/cbc:RegistrationName viene utilizzato per indicare la Ragione Sociale. In alternativa può essere usato per indicare la Denominazione.#
====

.Esempio di informazioni del cliente
[source, xml, indent=0]
----
<cac:BuyerCustomerParty>
   <cac:Party>
        <cbc:EndpointID schemeID="0201">OBSH87</cbc:EndpointID>
          <cac:PostalAddress>
            <cbc:StreetName>via Dei Mille 21</cbc:StreetName>
            <cbc:CityName>Bologna</cbc:CityName>
            <cbc:PostalZone>40121</cbc:PostalZone>
            <cac:Country>
              <cbc:IdentificationCode>IT</cbc:IdentificationCode>
            </cac:Country>
          </cac:PostalAddress>
          <cac:PartyTaxScheme>
            <cbc:CompanyID>IT02792731206</cbc:CompanyID>
            <cac:TaxScheme>
                <cbc:ID>VAT</cbc:ID>
            </cac:TaxScheme>
        </cac:PartyTaxScheme>
        <cac:PartyLegalEntity>
            <cbc:RegistrationName>Intercent-ER Agenzia Regionale</cbc:RegistrationName>
            <cbc:CompanyID schemeID="0210">91252510374</cbc:CompanyID>
        </cac:PartyLegalEntity>
    </cac:Party>
</cac:BuyerCustomerParty>
----

[[originatorcustomerparty-originator]]
== Richiedente (OriginatorCustomerParty)

Il Richiedente è la persona giuridica o l’organizzazione che inizializza il processo di emissione dell'Ordine e per la quale l'Acquirente effettua l'acquisto. +
Il Richiedente è un’informazione opzionale nel messaggio dell’Ordine.


.Esempio di informazioni del committente appartenente alla medesima organizzazione del cliente/acquirente
[source, xml, indent=0]
----
<cac:OriginatorCustomerParty>
  <cac:Party>
	<cac:PartyIdentification>
			<cbc:ID schemeID="0201">ABCDEF</cbc:ID>
	</cac:PartyIdentification>
	<cac:PartyName>
		<cbc:Name>U.O. Farmacia Ospedaliera</cbc:Name>
	</cac:PartyName>
	<cac:Contact>
		<cbc:Name>Roberto Gastone</cbc:Name>
		<cbc:Telephone>010150847</cbc:Telephone>
		<cbc:ElectronicMail>roberto.gastone@ospedale.it</cbc:ElectronicMail>
	</cac:Contact>
  </cac:Party>
</cac:OriginatorCustomerParty>
----

[yellow-background]#Qualora il Documento sia emesso con l’uso di strumenti messi a disposizione da un Intermediario (ad esempio, un Ordine emesso utilizzando la piattaforma telematica di una centrale di acquisto), è possibile evidenziare il committente valorizzando l’elemento “OriginatorCustomerParty”, come mostrato nel seguente esempio.#

.Esempio di informazioni del committente che utilizza una piattaforma telematica di un terzo intermediario per l’emissione dell’ordine
[source, xml, indent=0]
----
<cac:OriginatorCustomerParty>
  <cac:Party>
	<cac:PartyIdentification>
	    <cbc:ID schemeID="0201">AABBCC</cbc:ID>
	</cac:PartyIdentification>
	<cac:PartyName>
	    <cbc:Name>AUSL SALERNO</cbc:Name>
	</cac:PartyName>
	<cac:Contact>
		<cbc:Name>Roberto Gastone</cbc:Name>
		<cbc:Telephone>010150847</cbc:Telephone>
		<cbc:ElectronicMail>roberto.gastone@ospedale.it</cbc:ElectronicMail>
	</cac:Contact>
  </cac:Party>
</cac:OriginatorCustomerParty>
----

[[accountingcustomerparty-invoicee]]
==  Intestatario fattura (AccountingCustomerParty)

L’intestatario fattura è la persona giuridica o l’organizzazione a cui deve essere intestata la fattura relativa all'ordine. +
L’intestatario fattura è un’informazione opzionale nel messaggio dell’Ordine.

[IMPORTANT]
====
Qualora l’Acquirente (BuyerCustomerParty) sia una Pubblica Amministrazione, l’informazione deve essere fornita anche quando Intestatario della fattura (AccountingCustomerParty) e Acquirente coincidono, in tal caso il codice IPA deve essere inserito riportato nel *cac:EndpointID.*
====

.Esempio di informazioni dell’intestatario fattura
[source, xml, indent=0]
----
<cac:AccountingCustomerParty>
    <cac:Party>
        <cbc:EndpointID schemeID="0201">ABCDEF</cbc:EndpoinID>
        <cac:PostalAddress>
            <cbc:StreetName>Via del pensiero, 1</cbc:StreetName>
            <cbc:AdditionalStreetName>Primo Piano</cbc:AdditionalStreetName>
            <cbc:CityName>Maranello</cbc:CityName>
            <cbc:PostalZone>41053</cbc:PostalZone>
            <cbc:CountrySubentity>Modena</cbc:CountrySubentity>
            <cac:AddressLine>
                <cbc:Line>Stanza 18</cbc:Line>
            </cac:AddressLine>
            <cac:Country>
                <cbc:IdentificationCode>IT</cbc:IdentificationCode>
            </cac:Country>
        </cac:PostalAddress>
        <cac:PartyTaxScheme>
            <cbc:CompanyID>IT00234567890</cbc:CompanyID>
            <cac:TaxScheme>
                <cbc:ID>VAT</cbc:ID>
            </cac:TaxScheme>
        </cac:PartyTaxScheme>
        <cac:PartyLegalEntity>
            <cbc:RegistrationName>Ospedale Sant’Anna</cbc:RegistrationName>
            <cbc:CompanyID schemeID="0210">00234567890</cbc:CompanyID>
            <cac:RegistrationAddress>
                <cbc:CityName>Modena</cbc:CityName>
                <cac:Country>
                    <cbc:IdentificationCode>IT</cbc:IdentificationCode>
                </cac:Country>
            </cac:RegistrationAddress>
        </cac:PartyLegalEntity>
        <cac:Contact>
            <cbc:Name>Responsabile Fatturazione</cbc:Name>
            <cbc:ElectronicMail>responsabile.fatturazione@ospedale.it</cbc:ElectronicMail>
        </cac:Contact>
    </cac:Party>
</cac:AccountingCustomerParty>
----

==  Consegnatario/Destinatario (DeliveryParty)

Il Consegnatario/Destinatario è la persona giuridica o l’organizzazione che riceve i beni e/o i servizi oggetto dell’ordine.
L’indicazione del Consegnatario/Destinatario è prevista solo con riferimento all’intero Documento. +
Il Consegnatario/Destinatario è un’informazione opzionale nel messaggio dell’Ordine.


.Esempio di informazioni del Consegnatario/Destinatario
[source, xml, indent=0]
----
<cac:Delivery>
    <cac:DeliveryParty>
          <cac:PartyIdentification>
          <cbc:ID>UO07</cbc:ID>
          <cac:PartyName>
              <cbc:Name>Centro logistico</cbc:Name>
     </cac:PartyName>
     <cac:Contact>
         <cbc:Name>James Bond</Name
         <cbc:Telephone>0647611</cbc:Telephone>
         <cbc:ElectronicMail>james.bond@peo.it</ElectronicMail>
        </cac:Contact>
        </cac:PartyIdentification>
    </cac:DeliveryParty>
</cac:Delivery>
---- 

Qualora si indichi il Beneficiario, l’identificativo (campo “ID”) e la denominazione (campo “Name”) dell’unità organizzativa sono entrambi obbligatori. Se l’identificativo non è noto o non esiste, è sufficiente valorizzare il campo con il testo “UO”, che sta per unità organizzativa. +

Se invece il Beneficiario è una persona fisica è necessario contemperare l’esigenza di
tutelarne la riservatezza con la necessità di dare indicazioni complete ed esaurienti per
la consegna. A tal fine: +

* se non è strettamente necessario indicare per esteso il nome del Beneficiario, il
campo “Name” deve essere valorizzato con “PF”, che sta per persona fisica;
* se al Beneficiario è stato assegnato un identificativo, questo deve essere indicato
nel campo “ID”, altrimenti anche questo campo va valorizzato con “PF”.

