[[use-case-4-buyer-visits-the-sellers-physical-store]]
= Caso d’uso 4 – L'Acquirente visita il negozio fisico del Venditore

Questo caso d’uso descrive il processo dove un Cliente/Acquirente entra fisicamente nel negozio del Venditore per comprare e possibilmente  prende in consegna i prodotti.

[cols="1h,5",]
|====
|Caso d’uso nr.
|4

|Nome
|L'utente configura i beni/servizi

|Descrizione 
|L'Acquirente fisicamente acquista e prende in consegna.

|Ruoli coinvolti
a| * Acquirente
* Venditore

|Assunzioni 
|L'Acquirente ha un account con il Venditore con i dettagli necessari per inviargli un ordine pre-concordato.

|Il flusso
a|L'Acquirente necessita urgentemente di alcuni prodotti e preferirebbe discuterne direttamente con il Venditore prima di acquistare gli articoli.

Dopo aver selezionato gli articoli, l'Acquirente ottiene una ricevuta con le scelte. Potrebbe optare per portare con se tutti i prodotti nel momento della sua uscita dal negozio oppure schedulare la consegna per un secondo momento.

Il Venditore registra l'ordine nel proprio sistema ordini includendo un riferimento, come ad esempio il numero della richiesta, l'idendificativo della persona, identificativo del progetto, ecc.

Un Ordine pre-concordato con informazioni sull'articolo ed il prezzo degli articoli selezionati viene inviato dal Venditore al sistema di acquisto dell'Acquirente. L’Ordine pre-concordato è registrato nel sistema di acquisto dell'Acquirente. +

L'Acquirente quindi segue la normale procedura per completare l'ordine (se necessario).

Il Venditore invia una fattura che corrisponde all'ordine ed alla consegna, ma questo è al di fuori di questa specifica. 


|Risultati
|L'Acquirente e il Venditore hanno raggiunto un accordo. Un ordine è stato inserito e l'Acquirente ha preso in consegna i prodotti. L'Acquirente ha ricevuto un messaggio strutturato con i dettagli dell’ordine. La fattura ha un riferimento per  The invoice has a reference, to match the order.

|Esempio XML
|Vedi sezione "Downloads" nella link:../../../../../../[Homepage]

|====
