[[tipologia-ordine]]
= #Tipologia dell'ordine#

La tipologia dell’Ordine può essere espressa utilizzando le seguenti codifiche ufficiali disponibili nel package UBL.#


Per identificare il tipo di ordine si usa un «subset» della codifica ufficiale UNCL 1001. Si riporta di seguito il subset denominato «OrderTypeCode IT» definito da PEPPOL ed esteso al modello italiano di procurement (vedi, {link-codelist} evidenziati compatibili con NSO). +

Il tipo ordine è un elemento essenziale del processo, ve non precisato si presume il
codice 220 senza sotto-tipi.


[width="100%", cols="1,2,1,2"]
|===
2+^.^| *Tipo ordine* +
`cbc:OrderTypeCode`   2+^.^|**Sotto-tipo ordine** +
`cbc:SpecialTerms`

|*Codice* | *Descrizione* | *Codice* | *Descrizione* 

.2+|*220* .2+| Ordine di Acquisto | *OF*  | Ordine di fatturazione per prodotti già in possesso del Cliente o già consumati
|*OFR*  | Ordine di fatturazione e reintegro

.3+|*227* .3+| Ordine di consegna | *CD*  | Conto deposito
|*CV*  | Conto visione
|*CG*  | Comodato gratuito|
|===

#Note per l'utilizzo delle diverse tipologie d'ordine:#

*	**220** (Ordine di acquisto): corrisponde a un generico ordine di acquisto che può essere utilizzato sia per beni sia per servizi, con o senza emissione del relativo DDT. Sono inclusi gli ordini per l’acquisto di beni a scorta, gli ordini per l’acquisto di prodotti in transito ovvero prodotti che non vengono stoccati, gli ordini per l’invio di apparecchiature in riparazione e gli ordini di apparecchiature e beni di noleggio con canone. [underline]#Può# essere fornito un ulteriore dettaglio dell’ordine di acquisto usando i seguenti sotto-tipi: 
    
** *OF* (Ordine di fatturazione per prodotti già consumati): con l’ordine di fatturazione (OF) non si chiede al Fornitore la consegna di un bene
o la prestazione di un servizio, ma la sola emissione della fattura (o di un
documento equivalente) a fronte di un bene già in possesso del Cliente (ad
esempio, un bene in conto deposito che è stato utilizzato o un bene in conto
visione che si è deciso di acquistare) o di una prestazione già eseguita. 
+
Nella gestione dei beni acquisiti attraverso modalità di conto visione (ad esempio, dispositivi medici impiantabili gestiti direttamente da sala operatoria) l’ordine di fatturazione è utilizzato per autorizzare la fatturazione dei soli beni effettivamente trattenuti e quindi consumati. Inoltre, nell’ambito del conto deposito l’ordine di fatturazione è utilizzato per autorizzare la fatturazione di beni in conto deposito per i quali non si richiede il ripristino contestuale. Al codice 220#OF possono essere ricondotti in generale tutti gli ordini che riguardano la sola fatturazione di beni già consumati, per i quali il fornitore non deve effettuare una nuova consegna. L’ordine di tipo 220#OF riporta i riferimenti (in specifici campi) di Lotto, N. Seriale, Numero e data DDT di consegna dei prodotti utilizzati;

** *OFR* (Ordine di fatturazione e reintegro): con l’ordine di fatturazione e reintegro (OFR) si chiede al Fornitore la fatturazione
di un bene, già posseduto in conto deposito, che è stato utilizzato e il contestuale
reintegro dello stesso bene in conto deposito (si noti che i beni di cui si chiede la
fattura e i beni che si chiede di reintegrare devono essere i medesimi in termini di
prodotto, di quantità, di lotto, di causale di consegna nel documento di trasporto,
ecc.). 
+
La gestione delle scorte in conto deposito prevede normalmente una quantità di riordino prestabilita per ogni prodotto per mantenere le scorte minime necessarie. Non è a intervalli regolari ma avviene ad ogni utilizzo. Nell’ambito del Conto Deposito non è previsto l’ordine di solo ripristino. L’ordine di tipo 220#OFR è utilizzato anche per tutti i beni acquistati con fatturazione a referto, kit, test o validazione. L’ordine di tipo 220#OFR riporta i riferimenti (in specifici campi) di Lotto, N. Seriale, Numero e data DDT di consegna dei prodotti utilizzati.
+
In particolare, il codice “220” (Ordinazione di acquisto) indica che l’Ordine riguarda
una transazione che comporta, di regola, i seguenti effetti:
+
.. il trasferimento dal Fornitore al Cliente sia della proprietà (o di altro diritto reale)
sia del possesso sui beni;
.. la prestazione di servizi a titolo oneroso. Si noti che, sebbene alcune prestazioni
includano il trasferimento del possesso di beni (ad esempio il noleggio), l’oggetto
principale della fornitura non è il trasferimento dei beni ma la fornitura del servizio;
e, in particolari circostanze:
.. il trasferimento dal Fornitore al Cliente della proprietà (o di altro diritto reale) ma
non del possesso sui beni. 
In questa fattispecie, il trasferimento del possesso può
non essere necessario oppure essere regolato con separato ordine di consegna (v.
infra), che può precedere (ad esempio, per i beni in conto deposito) o seguire
l’ordine di acquisto.
+
Come regola generale, ciò che caratterizza le ordinazioni di acquisto in senso stretto
è il carattere oneroso (almeno nominalmente) della transazione, con conseguente
emissione di fattura o documento equivalente.



*	**227** (Ordine di consegna): corrisponde all’ordine di materiali che non contempla una fatturazione se non dopo l’utilizzo degli stessi e a seguito di specifico ordine tipo 220. Può essere fornito un ulteriore dettaglio dell’ordine di consegna usando i seguenti sotto-tipi ordine:

** *CD* (Conto deposito) vale per l’ordine di beni in conto deposito; 
** *CV* (Conto visione) vale per l’ordine di beni in conto visione; 
** *CG* (Comodato d’uso gratuito): corrisponde ad un ordine di materiale o apparecchiature in comodato d’uso senza fatturazione.

+
Al riguardo, si osservi che l’ordine in conto deposito (CD) va sicuramente emesso alla
costituzione del conto deposito e ogni qualvolta si intenda variare la quantità dei beni
in conto deposito. In caso di reintegro di beni consumati, invece, può utilizzarsi l’ordine
di fatturazione e reintegro (OFR), sopra menzionato.

+
Il codice “227” (Ordinazione di consegna), invece, va utilizzato unicamente per
regolare il trasferimento del possesso di beni dal Fornitore al Cliente, ma non della
proprietà oppure la prestazione di servizi a titolo gratuito. Ciò può verificarsi, ad
esempio, nelle fattispecie della concessione di beni in comodato d’uso, in conto
deposito, in conto visione, eccetera, che non comportano, di per sé, emissione di
fattura.

+
Si noti, tuttavia, che in molti casi il trasferimento del possesso di beni è accessorio di
una prestazione di servizi (v. precedente lettera b) oppure segue o precede un
trasferimento di proprietà (v. precedente lettera c), per cui un ordine di consegna può
essere collegato a uno o più ordini di acquisto.


Vedi la sezione CODIFICHE - Order type code (UNCL1001 subset).


.Esempio di utilizzo per Ordine di fatturazione e reintegro
[source, xml, indent=0]
----
<cbc:OrderTypeCode>220</cbc:OrderTypeCode>
        ...
<cac:DeliveryTerms>
    <cbc:SpecialTerms>OFR</SpecialTerms>
</cac:DeliveryTerms>
----

