
[[projectref]]
= Riferimento al progetto (CUP)

Il riferimento al progetto è opzionale e viene inviato nella fattura nell'elemento `cac:ProjectReference/cbc:ID`. +

#L'indicazione del Codice Unico di Progetto (CUP) è obbligatoria nei contesti in cui questo è richiesto, ed è necessario al fine dei processi di verifica, riconciliazione e approvazione al pagamento delle fatture.# +


In una nota di credito, questo elemento non esiste, il riferimento al progetto viene quindi inviato utilizzando l'elemento `cac:AdditionalDocumentReference[cbc:DocumentTypeCode='50']/cbc:ID`.

NOTE: Quando si invia il riferimento al progetto, solo il `cbc:ID` e il `cbc:DocumentTypeCode` sono permessi all'interno dell'elemento `cac:AdditionalDocumentReference`.


.Esempio UBL per il riferimento al progetto (CUP) in una fattura
[source, xml, indent=0]
----
include::../{snippet-dir}/Snippet-refs.xml[tags=project]
----



.Esempio UBL per il riferimento al progetto (CUP) in una nota di credito
[source, xml, indent=0]
----
include::../{snippet-dir}/CreditNote-snippets.xml[tags=project ]
----
<1> Il codice 50 indica che questo è il riferimento ad un progetto
<2> L'identificatore del riferimento al progetto


Per riferirsi a più progetti (CUP) dalle righe di fattura è necessario utilizzare *cac:DocumentReference* con il codice tipo documento = 130.

.Esempio UBL per il riferimento al progetto (CUP) dalle righe fattura
[source, xml, indent=0]
----
include::../{snippet-dir}/Snippet-refs.xml[tags=CUP_riga]
----