
[[buyerref]]
= Riferimento dell'acquirente (BuyerReference)

Il riferimento dell'acquirente è **facoltativo**. Una fattura deve avere il riferimento dell'acquirente o il riferimento dell'ordine (vedi <<orderref>>). 

L'elemento è utilizzato come riferimento per chi ha ordinato  prodotti/servizi. L'esempio è dato dal nome della persona che ordina, il numero del dipendente o un codice che identifica questa persona o dipartimento/gruppo. Il loro riferimento viene spesso utilizzato per lo smistamento interno al beneficiario, quindi è importante valorizzare questo elemento con i valori corretti in base alle necessità del beneficiario.

If neither buyer reference nor a reference to an order is supplied by the customer, the name of the person ordering or appointed for the customer can be supplied in buyer reference if known by the supplier.

IMPORTANT: When reference is provided by the customer, the correct element shall contain the provided reference.


.UBL example of buyer reference
[source, xml, indent=0]
----
<cbc:BuyerReference>0150abc</cbc:BuyerReference>
----