
[[orderref]]
= Ordine d'acquisto e riferimento all'ordine di vendita

L'ordine di acquisto è **facoltativo**. Se esiste un riferimento all'ordine bisogna utilizzarlo, altrimenti utilizzare il riferimento dell'acquirente (vedi <<buyerref>>).

Il cliente deve emettere un ordine caratterizzato da un identificativo univoco che deve essere fornito come ordine di riferimento nella fattura. +

#Se la fattura viene messa nell'ambito di un processo di Ordinazione Semplice o Ordinazione Completa rilevante ai fini del sistema NSO, occorre riportare il riferimento all'ordine nel seguente modo:#

1.	#Nel *cac:OrderReference/cbc:ID*  (BT-13 Purchase order reference) riportare il solo identificativo dell’ordine, come nel seguente esempio:#
+
[source, xml, indent=0]
----
<cac:OrderReference>
    <cbc:ID>110</cbc:ID>
</cac:OrderReference>
----

2.	#Nel *cbc:BuyerReference* (BT-10 Buyer reference) riportare la Tripletta di identificazione completa separando i componenti (Id, data e Endpoint) con il carattere &#x0023; senza interposizione di spazi, come nel seguente esempio:#
+
[source, xml, indent=0]
----
<cbc:BuyerReference>110#2018-01-30#aaaaaa</cbc:BuyerReference>
----

#Si evidenzia che, ove la fattura non sia stata emessa a fronte di un processo di Ordinazione elettronica e, perciò, non è legata ad alcun Ordine o Ordine pre-concordato rilevante per il sistema NSO:#

a. #se la fornitura non promana da alcun processo di ordinazione (elettronico o tradizionale), è sufficiente non compilare i campi sopra menzionati;#
b. #se la fornitura promana da un processo di ordinazione tradizionale (ad esempio, via lettera, fax, ecc.), ovvero non gestito tramite NSO, per dare maggior evidenza a tale circostanza si può indicare l’identificativo dell’ordine emesso nelle forme tradizionali nei campi di cui al precedente punto e valorizzare i campi di cui al precedente punto con il testo "&#x0023;NO&#x0023;".#

Se il riferimento dell'ordine è indicato a livello di testata, è possibile utilizzare l'elemento di riferimento all'ordine a livello di riga per specificare i numeri di riga dell'ordine.

Un ordine di vendita è emesso dal venditore, confermando la vendita di prodotti specificati.

IMPORTANT: Nella fattura è possibile fornire sia un ordine di acquisto che un riferimento all'ordine di vendita, ma tenendo presente che un'istanza della fattura non può avere un riferimento dell'ordine di vendita, senza il corrispondente riferimento dell'ordine di acquisto.

include::../../../syntax/references/_order.adoc[]

== #Riferimento a una riga d'ordine o a più ordini, dalle righe fattura#

Utilizzando l'elemento cac:OrderLineReference delle righe di fattura è possibile fare riferimento alle righe di uno o più ordini o ad un ordine completo, con le seguenti modalità alternative:

.#Esempio UBL con riferimento implicito all’Ordine fornito a livello testata#
[source, xml, indent=0]
----
<cac:OrderLineReference>
	<cbc:LineID>3</cbc:LineID>
</cac:OrderLineReference>
----

.#Esempio UBL con riferimento esplicito alla riga di un Ordine a livello di riga fattura#
[source, xml, indent=0]
----
<cac:OrderLineReference>
	<cbc:LineID>4</cbc:LineID>
	<cac:OrderReference>
		<cbc:ID>123</cbc:ID>
		<cbc:IssueDate>2020-10-01</cbc:IssueDate>
	</cac:OrderReference>
</cac:OrderLineReference>
----

.#Esempio UBL con riferimento esplicito ad un Ordine completo a livello di riga fattura#
[source, xml, indent=0]
----
<cac:OrderLineReference>
	<cbc:LineID>NA</cbc:LineID>
	<cac:OrderReference>
		<cbc:ID>123</cbc:ID>
		<cbc:IssueDate>2020-10-01</cbc:IssueDate>
	</cac:OrderReference>
</cac:OrderLineReference>
----
