
[[orderref]]
= Ordine d'acquisto e riferimento all'ordine di vendita

L'ordine di acquisto è **facoltativo**. Se esiste un riferimento all'ordine bisogna utilizzarlo, altrimenti utilizzare il riferimento dell'acquirente (vedi <<buyerref>>).

Il cliente deve emettere un ordine caratterizzato da un identificativo univoco che deve essere fornito come ordine di riferimento nella fattura. +

*A livello di testata*::

Se il riferimento dell'ordine è indicato a livello di testata, è possibile utilizzare l'elemento di riferimento all'ordine a livello di riga per specificare i numeri di riga dell'ordine.

IMPORTANT: Nella fattura è possibile fornire sia un ordine di acquisto che un riferimento all'ordine di vendita, ma tenendo presente che un'istanza della fattura non può avere un riferimento dell'ordine di vendita, senza il corrispondente riferimento dell'ordine di acquisto.

include::../../../syntax/references/_order.adoc[]

#Se la fattura viene emessa nell'ambito di un processo di Ordinazione elettronica, occorre riportare il riferimento all'ordine ("tripletta") nel seguente modo:#

1.	#Nel cac:OrderReference/cbc:ID (BT-13 Purchase order reference) riportare il solo identificativo dell'ordine, deve inoltre essere riportata la data dell'ordine nel cac:OrderReference/cbc:IssueDate:#
+
[source, xml, indent=0]
----
<cac:OrderReference>
    <cbc:ID>110</cbc:ID>
    <cbc:IssueDate>2018-01-30</cbc:IssueDate>
</cac:OrderReference>
----

2.	#Nel cbc:BuyerReference (BT-10 Buyer reference) riportare la Tripletta di identificazione completa separando i componenti (Id, data e Endpoint) con il carattere # senza interposizione di spazi, come nel seguente esempio:#
+
[source, xml, indent=0]
----
<cbc:BuyerReference>110#2018-01-30#aaaaaa</cbc:BuyerReference>
----

#Se invece la fattura viene emessa a fronte di un ordine analogico se ne può dare evidenza nel seguente modo:#

[source, xml, indent=0]
----
<cbc:BuyerReference>#NO#</cbc:BuyerReference>
----

#Se la fattura non è stata preceduta da un ordine occorre indicarlo nel seguente modo:#

[source, xml, indent=0]
----
<cac:OrderReference>
    <cbc:ID>#NO#</cbc:ID>
</cac:OrderReference>
----

#Ove la fattura sia riferita a più ordini elettronici referenziati in riga, occorre indicarlo nel seguente modo:#

[source, xml, indent=0]
----
<cac:OrderReference>
    <cbc:ID>#MULTI#</cbc:ID>
</cac:OrderReference>
----

Se si intende specializzare il collegamento tra una riga d'ordine e una riga di fattura il cui riferimento è inserito a livello di testata, è necessario indicare l'identificativo della riga d'ordine nell'elemento *cac:OrderLineReference/cbc:LineID* della riga di fattura (*cac:InvoiceLine*) nel seguente modo:

[source, xml, indent=0]
----
<cac:OrderLineReference>
        <cbc:LineID>3</cbc:LineID>
</cac:OrderLineReference>
----

*A livello di riga*

Il riferimento ad un ordine sulle righe di fattura avviene utilizzando gli elementi *cac:OrderLineReference* e *cac:DocumentReference*.

#Se la fattura viene emessa nell'ambito di un processo di Ordinazione elettronica, rilevante ai fini del sistema NSO, occorre riportare il riferimento all'ordine nell'elemento *cac:OrderLineReference* e la Tripletta di identificazione nell'elemento *cac:DocumentReference*.#

#Nell'elemento *cac:OrderLineReference/cbc:LineID* è possibile indicare l'identificativo della riga d'ordine alla quale si riferisce specificamente la riga di fattura. In caso contrario, l'elemento va valorizzato a "NA".#

.Esempio UBL di riga di fattura con riferimento generico ad un ordine inviato a mezzo NSO
[source, xml, indent=0]
----
<cac:OrderLineReference>
        <cbc:LineID>NA</cbc:LineID>
        <cac:OrderReference>
                <cbc:ID>123</cbc:ID>
                <cbc:IssueDate>2020-10-01</cbc:IssueDate>
        </cac:OrderReference>
</cac:OrderLineReference>
<cac:DocumentReference>
    <cbc:ID schemeID="ON">123#2020-10-01#aaaaaa</cbc:ID>
    <cbc:DocumentTypeCode>130</cbc:DocumentTypeCode>
</cac:DocumentReference>
----

.Esempio UBL di riga di fattura con riferimento specifico ad una riga di ordine inviato a mezzo NSO
[source, xml, indent=0]
----
<cac:OrderLineReference>
        <cbc:LineID>2</cbc:LineID>
        <cac:OrderReference>
                <cbc:ID>123</cbc:ID>
                <cbc:IssueDate>2020-10-01</cbc:IssueDate>
        </cac:OrderReference>
</cac:OrderLineReference>
<cac:DocumentReference>
    <cbc:ID schemeID="ON">123#2020-10-01#aaaaaa</cbc:ID>
    <cbc:DocumentTypeCode>130</cbc:DocumentTypeCode>
</cac:DocumentReference>
----

#Se la fattura viene emessa a fronte di un ordine analogico, occorre riportare il riferimento all'ordine nell'elemento *cac:OrderLineReference*.#

#Nell'elemento *cac:OrderLineReference/cbc:LineID* è possibile indicare l'identificativo della riga d'ordine alla quale si riferisce specificamente la riga di fattura. In caso contrario, l'elemento va valorizzato a "NA".#

.Esempio UBL di riga di fattura con riferimento generico ad un ordine analogico
[source, xml, indent=0]
----
<cac:OrderLineReference>
        <cbc:LineID>NA</cbc:LineID>
        <cac:OrderReference>
                <cbc:ID>456</cbc:ID>
                <cbc:IssueDate>2021-11-03</cbc:IssueDate>
        </cac:OrderReference>
</cac:OrderLineReference>
----

