[[altri-riferimenti]]
= #Riepilogo riferimenti ad altri documenti#

[cols="2,2,3,6", options="header"]
|====
^.^|Riferimento
^.^|Descrizione
^.^|Campo Fattura PA
^.^|Dove usarlo

|*CONTRATTO*
|Estremi Contratto
|
|In testata si usa +
`cac:ContractDocumentReference` (0.1) +

A livello di riga +
`cac:InvoiceLine/cac:DocumentReference/cbc:ID` (0..n) +
con @schemeID = CT


|*DDT*
|Documento di Trasporto +
|
|In testata si usa +
`cac:DespatchDocumentReference` (0.n) +

A livello di riga +
`cac:DespatchLineReference` (0..n) +


|*CIG*
|Codice Identificativo Gara +
|
|In testata si usa +
`cac:OriginatorDocumentReference` (0.1) +

A livello di riga +
`cac:InvoiceLine/cac:DocumentReference/cbc:ID` (0..n) +
con @schemeID = AGB


|*CUP*
|Codice Unico Progetto
|
|In testata si usa +
`cac:ProjectReference` (0.1) +

A livello di riga +
`cac:InvoiceLine/cac:DocumentReference/cbc:ID` (0..n) +
con @schemeID = AEP


|*CONVENZIONE*
|Estremi Convenzione
|
|In testata si usa +
`cac:AdditionalDocumentReference/cbc:ID` (0.n) +
con @schemeID = AVV

A livello di riga +
`cac:InvoiceLine/cac:DocumentReference/cbc:ID` (0..n) +
con @schemeID = AVV


|*Dati SAL*
|Riferimento alla fase di un SAL
|
|In testata si usa +
`cac:AdditionalDocumentReference/cbc:ID` (0.n) +
con @schemeID = AOR

A livello di riga +
`cac:InvoiceLine/cac:DocumentReference/cbc:ID` (0..n) +
con @schemeID = AOR



|====
