[[EndpointID]]
= #Endpoint ID - Identificativo di instradamento sulla rete PEPPOL#

Quando si specifica un Endpoint ID nel documento si vuole mantenere l’informazione dell’indirizzo elettronico del mittente o destinatario utilizzati per l’instradamento dei messaggi (delivery) sul circuito PEPPOL. L’Endpoint ID specificato nel documento DEVE coincidere con quello utilizzato dal protocollo di trasmissione adottato (es. AS2). L’Endpoint ID non è obbligatorio nel documento ma è consigliato perché mantiene il legame fra il documento, la parte di business e l’access point/circuito utilizzato.

Le tipologie di identificativi italiani riconosciuti da PEPPOL e consigliati sono:

* *9906* per IT:VAT (partite IVA)

* *9907* per IT:CF (codice fiscale persona fisica o giuridica)

* *0201* per IT:IPA (Indice Pubbliche Amministrazioni) +

In Italia si raccomanda l’uso del codice IPA per registrare le pubbliche amministrazioni sulla rete PEPPOL, tuttavia non è obbligatorio e in sua assenza si consiglia l’uso del codice fiscale.


.Esempio di Endpoint di un’Amministrazione registrata in PEPPOL con l’IPA:
[source, xml, indent=0]
----
    <cbc:EndpointID schemeID="0201">ABCDEF</cbc:EndpointID>
----

.Esempio di Endpoint di un’Amministrazione registrata in PEPPOL con il CF:
[source, xml, indent=0]
----
    <cbc:EndpointID schemeID="9907">07643520567</cbc:EndpointID>
----

.Esempio di Endpoint di Fornitore registrato in PEPPOL con la P.IVA:
[source, xml, indent=0]
----
    <cbc:EndpointID schemeID="9906">IT07643520567</cbc:EndpointID>
----

.Esempio di Endpoint di fornitore registrato in PEPPOL con un GLN (Global Location Number) secondo gli standard GS1:
[source, xml, indent=0]
----
    ​<cbc:EndpointID schemeID="0088">5790000435968</cbc:EndpointID
----

