
= Informazioni sulle imposte

I capitoli seguenti descrivono le diverse informazioni relative alle imposte che possono essere fornite in questo BIS.
Con imposta si intende a seconda del contesto applicativo, l'IVA, GST o la Sales Tax.

Si consiglia di consultare anche i codici  dellalink:../../../../../../xml/ITA/peppol-bis-3/codelist/UNCL5305.html[UNCL5305] per dettagli sulla codifica delle categorie delle imposte e il <<vat-calc>> per una rappresentazione più dettagliata ed esempi su come eseguire i calcoli nel riepilogo delle imposte.

:leveloffset: +1

include::../../shared/files/_vat-cat-line.adoc[]

:leveloffset: -1

[[vat-allowance]]
== Informazioni sulle imposte negli sconti e maggiorazioni

Ogni sconto o maggiorazione a livello di testata viene espresso mediante l'elemento UBL `cac:AllowanceCharge`. Ulteriori dettagli sugli sconti e maggiorazioni sono disponibili nel relativo paragrafo ("Sconti e Maggiorazioni").

Ogni sconto o maggiorazione a livello di testata deve essere associato ad un codice di categoria di imposta. Per tutte le categorie di imposta deve essere fornita l'aliquota relativa, ad eccezione del caso in cui tutto il documento non sia soggetto ad imposta  (es. "Non soggetto ad IVA" (O) in Europa).

.Esempio UBL di maggiorazione con informazioni sulla categoria d'imposta, per l'IVA
[source, xml, indent=0]
----
include::../snippets/snippet-oa-vat.xml[tags=vat-allowance]
----
<1> La classe `cac:TaxCategory` è utilizzata per informazioni sulla categoria IVA
<2> Categoria IVA secondo la link:../../../../../../xml/ITA/peppol-bis-3/codelist/UNCL5305.html[Codifica UNCL5305]
<3> Aliquota IVA
