[[response-code]]
= Response code

The Response code states the Sellers ability to fulfil the order and must be sent on both header level and line level if lines are sent.


[IMPORTANT]
====
* Response code *_must_* be sent on header level.
* Line response code *_must_* be sent on line level if lines are sent.
* Response code may have 4 values: AB, RE, AP and CA (subset of UNCL 4343 code list)
* Line response code may have 5 values: 1, 3, 5, 7 and 42. These values are extracted, as a subset, from the reference codelist UNCL 1229.
====

== Response code on Header level

[cols="1,11",options="header"]
|====
|Response code
|Action

|AB
a|
* The Order has been received.
* The Order has not yet been processed.
* No lines should be sent.

|RE
a|
* The Order is rejected.
* No lines should be sent.

|AP
a|
* The Order is accepted without amendment.
* No lines should be sent.

|CA
a|
* The Order is accepted with amendment on line level.
* All lines must be sent.
|====


.UBL example of Response code on Header level in an Order Response message
[source, xml, indent=0]
----
<cbc:OrderResponseCode listID="UNCL4343">CA</cbc:OrderResponseCode>
----

.UBL example of an order response using response code "AB" (order is received)
[source, xml, indent=0]
----
<?xml version="1.0" encoding="UTF-8"?>
<OrderResponse
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="urn:oasis:names:specification:ubl:schema:xsd:OrderResponse-2"
    xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
    xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2">
    <cbc:CustomizationID>urn:fdc:peppol.eu:poacc:trns:order_response:3</cbc:CustomizationID>
    <cbc:ProfileID>urn:fdc:peppol.eu:poacc:bis:ordering:3</cbc:ProfileID>
    <cbc:ID>0005a-2018</cbc:ID>
    <cbc:IssueDate>2018-12-01</cbc:IssueDate>
    <cbc:IssueTime>14:30:00</cbc:IssueTime>
    <!--Ordine ricevuto ma ancora non processato-->
    <cbc:OrderResponseCode listID="UNCL4343">AB</cbc:OrderResponseCode>  <1>
    <cbc:Note>Risposta Ordine Inviato al Cliente</cbc:Note>
    <cbc:DocumentCurrencyCode listID="ISO4217">EUR</cbc:DocumentCurrencyCode>
    <cac:OrderReference>
        <cbc:ID>5a-2018#2018-11-25#ABCDEF</cbc:ID>
    </cac:OrderReference>
    <!--Fornitore, Venditore-->
    <cac:SellerSupplierParty>
        <cac:Party>
            <cbc:EndpointID schemeID="9906">IT05501420900</cbc:EndpointID>
            <cac:PartyIdentification>
                <cbc:ID>PIVA:IT05501420900</cbc:ID>
            </cac:PartyIdentification>
            <cac:PartyLegalEntity>
                <cbc:RegistrationName>Fornitore S.p.A.</cbc:RegistrationName>
            </cac:PartyLegalEntity >
        </cac:Party>
    </cac:SellerSupplierParty>
    <!--Mittente, Cliente-->
    <cac:BuyerCustomerParty>
        <cac:Party>
            <cbc:EndpointID schemeID="0201">UFY9MH</cbc:EndpointID>
            <cac:PartyIdentification>
                <cbc:ID schemeID="0201">UFY9MH</cbc:ID>
            </cac:PartyIdentification>
            <cac:PartyLegalEntity>
                <cbc:RegistrationName>Azienda USL di Reggio Emilia </cbc:RegistrationName>
            </cac:PartyLegalEntity >
        </cac:Party>
    </cac:BuyerCustomerParty>
    <cac:Delivery>
        <cac:PromisedDeliveryPeriod>
            <cbc:StartDate>2018-12-10</cbc:StartDate>
            <cbc:EndDate>2018-12-20</cbc:EndDate>
        </cac:PromisedDeliveryPeriod>
    </cac:Delivery> <2> 
</OrderResponse>
----
<1> Response code AB indicates only that the order has been received, but is not yet processed. 
<2> No order lines are sent in this response


== Line response code on Line level

When the order is accepted without amendment (at line level), all the order lines must be sent including the respective code.

[cols="1,11",options="header"]
|====
|Response line code
|Action

|1
|The Order line is Added.

|3
|The Order line is Changed.

|5
|The Order line is Accepted without amendment.

|7
|The Order line is Not accepted.

|42
|The Order line is Already delivered.

|====


.Example of Response code on Line level in an Order Response message:
[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
	    <cbc:LineStatusCode>7</cbc:LineStatusCode>
	    <cbc:Note>Merce terminata</cbc:Note>
	    …
	</cac:LineItem>
	…
</cac:OrderLine>
----
