[[order-response-message]]
= Description of selected parts of the order response message

The Order response message is sent from the Seller to the Buyer stating the sellers ability to fulfil the order.
The following rules applies to the PEPPOL BIS Order Response:

* The Order response must refer to an Order.
* Seller may accept or reject the entire Order.
* If the order or any order line is rejected the Order response should contain a reason for rejection.
* Seller may accept or reject the separate order lines.
* If Seller accepts or rejects order lines, *_all_* order lines must be sent in the Order response. 
* The order lines in the order response must be related to the corresponding order line, 1 to 1.
* The following information may be changed in the Order response:
** Quantity
** Delivery period
** Replacement item
** Price


* #If the order is rejected or modified, the order response must include at the document level the Seller's contact information in the element *cbc:Note*#.

* #The order response must contain univocally the Buyer's identifier.#


:leveloffset: +1

include::response-code.adoc[]

include::order-ref.adoc[]

include::change.adoc[]

include::changeanddeliver.adoc[]

include::backorder.adoc[]

include::../../../shared/files/vat-cat-line.adoc[]

:leveloffset: -1
