
= Information about taxes

The follwing paragrapghs describe several information about taxes that can be provided with this BIS. 
"Tax" refers to VAT (IVA in Italy), GST or Sales Tax, according to the field of application.

Please also see link:../../../../../../xml/ITA/peppol-bis-3/codelist/UNCL5305.html[UNCL5305] for details on the TAX category code list, and <<anchor-7,Total TAX amount>> for detailed explanation and example on how to perform the calculations for TAX Breakdown.

:leveloffset: +1

include::../../shared/files/_vat-cat-line.adoc[]

:leveloffset: -1

[[vat-allowance]]
== Informazioni sulle imposte negli sconti e maggiorazioni

Ogni sconto o maggiorazione a livello di testata viene espresso mediante l'elemento UBL `cac:AllowanceCharge`. Ulteriori dettagli sugli sconti e maggiorazioni si trovano in <<allowance>>.

Ogni sconto o maggiorazione a livello di testata deve avere associato ad un codice di categoria di imposta. Per tutte le categorie di imposta deve essere fornita l'aliquota relativa, ad eccezione del caso in cui tutto il documento non sia soggetto ad imposta  (es. "Non soggetto ad IVA" (O) in Europa).

.Esempio UBL di maggiorazione con informazioni sulla categoria d'imposta, per l'IVA
[source, xml, indent=0]
----
include::../snippets/snippet-oa-vat.xml[tags=vat-allowance]
----
<1> La classe `cac:TaxCategory` è utilizzata per informazioni sulla categoria IVA
<2> Categoria IVA secondo la codifica {vat-codes}
<3> Aliquota IVA
