[[Ambito]]
= Ambito

Questo BIS descrive un processo che prevede l’emissione di un ordine elettronico da parte del Cliente senza che vi sia una conferma d’ordine da parte del Fornitore.

Le principali attività supportate da questo profilo sono:

Fornitura Strutturata:: La transazione dell’Ordine dovrebbe supportare la fornitura strutturata di beni o servizi, descritti sia mediante testo libero che identificatori. L’informazione di origine dei prodotti ordinati potrebbe provenire da un catalogo (cartaceo o elettronico).

Contabilità:: Il processo dell’ordine di fornitura deve supportare l’allocazione del budget, in modo che possano essere indicati gli importi relativi al valore dei prodotti ordinati. L’acquirente può fornire alcune informazioni che il fornitore dovrà inserire in fattura per facilitare e automatizzare il processo di fatturazione.

Verifica Fattura:: L’acquirente può fornire alcune informazioni che il fornitore dovrà inserire in fattura per facilitare e automatizzare il processo di approvazione di questa.

Resoconto IVA:: Il resoconto IVA non è un requisito generale negli ordini. Il livello di supporto negli ordini è il seguente:
* Abilitare il resoconto IVA nelle fatture indicando il codice IVA del cliente nel caso di inversione contabile.
* L’IVA può essere indicata come stimata per permettere ai clienti di indicare il valore previsto dell’ordine. Questo può essere utile per la correlazione automatica di ordini e relative fatture. Le informazioni IVA sono considerate informative e quindi non influiscono sui termini commerciali.

Trasporto e consegna:: Vi è solo un supporto limitato per le informazioni relative al trasporto, ma è noto che l’acquirente necessita di fornire alcune informazioni circa l’indirizzo o ubicazione di consegna richiesti, alcuni termini basilari, l’ora e la persona di contatto per la consegna dell’ordine.

Inventario:: Il supporto alla gestione dell’inventario non è previsto, ma gli ordini strutturati basati su cataloghi possono essere utilizzati per automatizzare la raccolta presso il magazzino del fornitore.
