////
= Introduzione a openPEPPOL e alla BIS

[preface]
Questa {peppol} BIS fornisce un insieme di specifiche per l’implementazione di un processo di business {peppol}.

Questo documento è volto a chiarire i requisiti necessari ad assicurare l'interoperabilità nell'eProcurement Pubblico pan-Europeo e fornisce le linee guida per il supporto e l'implementazione di questi requisiti anche in Italia.

Questa specifica è una Core Invoice Usage Specification (CIUS) della {EN16931}, che ne segue le indicazioni fornite al capitolo 7. Qualsiasi documento compatibile a questa specifica sarà sempre compatibile alla normativa europea ({EN16931}).

L’obiettivo di questo documento è descrivere l’uso dei messaggi della fattura e della nota di credito in PEPPOL, e facilitare un’efficiente implementazione e diffusione delle collaborazioni elettroniche per il processo di fatturazione in questi formati.

.Statement of copyright
****
This PEPPOL Business Interoperability Specification (PEPPOL BIS) document is a Core Invoice Usage Specification (CIUS) based on CEN/EN 16931:2017. The restrictions on CEN/EN 16931:2017 implemented in this PEPPOL BIS appear from the conformance statement provided in appendix A.

The copyright of CEN/EN 16931:2107 is owned by CEN and its members - the European National Standards Bodies. A copy of CEN/EN 16931-1:2017 may be obtained free of charge from any CEN member.

OpenPEPPOL AISBL holds the copyright of this PEPPOL BIS, developed and published subject to the conditions of the agreement between the European Commission and CEN allowing derivate works to be developed and distributed with no additional licensing requirements. CEN and the National  Standards Bodies bears no liability from the content and implementation of this PEPPOL BIS.

This PEPPOL BIS document may not be modified, re-distribute, sold or repackaged in any other way without the prior consent of OpenPEPPOL AISBL.
****

== A chi si rivolge

Questo documento si rivolge alle organizzazioni che intendono essere abilitate a PEPPOL per scambiare fatture e note di credito elettroniche, e/o ai loro fornitori ICT. Queste organizzazioni potrebbero essere:

     * Fornitori di Servizi (SP)
     * Autorità appaltanti (CA)
     * Operatori Economici (EO)
     * Sviluppatori Software

Più specificatamente, i ruoli affrontati sono i seguenti:

    * Architetti ICT
    * Sviluppatori ICT
    * Esperti di Business

Per ulteriori informazioni su PEPPOL/OpenPEPPOL, leggete {common}
////