[[istruzioni-noleggiobeni]]
= #Istruzioni particolari per il noleggio di beni#

Come anticipato nel Paragrafo "4.4 Tipologia Ordine", il noleggio a titolo oneroso può essere gestito, alternativamente:

a.	come un’Ordinazione avente ad oggetto il servizio di locazione di beni;

b.	come un’Ordinazione avente ad oggetto i beni da noleggiare (cessione temporanea di beni).

Si forniscono di seguito le istruzioni relative ad entrambe le procedure.

:leveloffset: +1

= Noleggio gestito come servizio 

Se il noleggio è gestito come servizio:

* a livello di Documento, bisogna indicare il codice “220” specificando il sotto-tipo di Ordinazione “ON” (Ordinazione di noleggio);
* a livello di linea d’ordine, bisogna indicare il servizio di noleggio oggetto della fornitura.

Si forniscono, di seguito, alcuni esempi di Ordine riferiti al noleggio per un anno di 10 stampanti, al prezzo unitario di € 1.500. Il contratto prevede che il pagamento avvenga in rate mensili di € 125 per ciascuna stampante (gli esempi non includono sconti e/o maggiorazioni). A fronte di questo ordine saranno emesse 12 fatture di €
1.250 alla scadenza di ciascuna rata mensile (negli esempi a) e b), questa  informazione è indicata nel campo “PaymentTerms/Note”; negli esempi c) e d), nel campo “LineExtensionAmount” di ciascuna delle 12 linee d’ordine corrispondente alla relativa rata mensile).

Il servizio può essere ordinato:

a)	con riferimento al complesso dei beni e per l’intero periodo di noleggio, come mostrato nell’esempio che segue:

[source, xml, indent=0]
----
…
<cbc:OrderTypeCode>220</cbc:OrderTypeCode>
…
<cac:Delivery>
<cac>RequestedDeliveryPeriod>
<cbc:StartDate>2018-09-03</cbc:StartDate>
<cbc>EndDate>2019-09-02</cbc:EndDate>
</cac:RequestedDeliveryPeriod>
</cac:Delivery>
…
<cac:PaymentTerms>
<cbc:Note>Pagamento in rate mensili di € 1.250</cbc:Note >
</cac:PaymentTerms>
…
<cac:OrderLine>
<cac:LineItem>
<cbc:ID>Numero della linea d’ordine</cbc:ID>
<cbc:Quantity unitCode=”C62”>1</cbc:Quantity>
<cbc:LineExtensionAmount currencyID=EUR>15000</cbc:LineExtensionAmount>
…
 

<cac:Price>
<cbc:PriceAmount currencyID=EUR>15000</cbc:PriceAmount>
</cac:Price>
<cac:Item>
<cbc:Description>Noleggio annuale di 10 stampanti mod. xxx</cbc:Description>
<cbc:Name>Modello della stampante</cbc:Name>
…
</cac:Item>
</cac:LineItem>
</cac:OrderLine>
…


b)	per l’intero periodo ma distintamente per ciascun bene (o insieme di beni) noleggiato, come mostrato nell’esempio che segue (un ordine per ciascun noleggio):
…
<cbc:OrderTypeCode>220</cbc:OrderTypeCode>
…
<cac:Delivery>
<cac>RequestedDeliveryPeriod>
<cbc:StartDate>2018-09-03</cbc:StartDate>
<cbc>EndDate>2019-09-02</cbc:EndDate>
</cac:RequestedDeliveryPeriod>
</cac:Delivery>
…
<cac:PaymentTerms>
<cbc:Note>Pagamento in rate mensili di € 1.250</cbc:Note>
</cac:PaymentTerms>
…
<cac:OrderLine>
<cac:LineItem>
<cbc:ID>Numero della linea d’ordine</cbc:ID>
<cbc:Quantity unitCode=”C62”>10</cbc:Quantity>
<cbc:LineExtensionAmount currencyID=EUR>15000</cbc:LineExtensionAmount>
…
<cac:Price>
<cbc:PriceAmount currencyID=EUR>1500</cbc:PriceAmount>
</cac:Price>
<cac:Item>
<cbc:Description>Noleggio annuale di stampante mod. xxx</cbc:Description>
<cbc:Name>Modello della stampante</cbc:Name>
…
</cac:Item>
</cac:LineItem>
</cac:OrderLine>
…
----

c)	con riferimento al complesso dei beni ma distintamente per ciascuna rata di canone, come mostrato nell’esempio che segue (l’esempio riporta una linea d’ordine per ciascuna rata, ma anche è possibile emettere un singolo Ordine per ogni singola rata):

[source, xml, indent=0]
----
…
<cbc:OrderTypeCode>220</cbc:OrderTypeCode>
…
<cac:OrderLine>
<cac:LineItem>
<cbc:ID>Numero della linea d’ordine</cbc:ID>
<cbc:Quantity unitCode=”C62”>1</cbc:Quantity>
<cbc:LineExtensionAmount currencyID=EUR>1250</cbc:LineExtensionAmount>
…
 

<cac:Delivery>
<cac:RequestedDeliveryPeriod>
<cbc:StartDate>2018-09-03</cbc:StartDate>
<cbc:EndDate>2018-10-02</cbc:EndDate>
<cac:Price>
<cbc:PriceAmount currencyID=EUR>1250</cbc:PriceAmount>
</cac:Price>
<cac:Item>
<cbc:Description>Prima rata di Noleggio annuale di 10 stampanti mod. xxx</cbc:Description>
<cbc:Name>Modello della stampante</cbc:Name>
…
</cac:Item>
</cac:LineItem>
</cac:OrderLine>
…
Rate mensili dalla 2 alla 11
…
<cac:OrderLine>
<cac:LineItem>
<cbc:ID>Numero della linea d’ordine</cbc:ID>
<cbc:Quantity unitCode=”C62”>1</cbc:Quantity>
<cbc:LineExtensionAmount currencyID=EUR>1250</cbc:LineExtensionAmount>
…
<cac:Delivery>
<cac:RequestedDeliveryPeriod>
<cbc:StartDate>2019-08-03</cbc:StartDate>
<cbc:EndDate>2019-09-02</cbc:EndDate>
<cac:Price>
<cbc:PriceAmount currencyID=EUR>1250</cbc:PriceAmount>
</cac:Price>
<cac:Item>
<cbc:Description>Dodicesima rata mensile di noleggio annuale di 10 stampanti mod. xxx</cbc:Description>
<cbc:Name>Modello della stampante</cbc:Name>
…
</cac:Item>
</cac:LineItem>
</cac:OrderLine>
----


d)	distintamente per ciascun bene (o insieme di beni) noleggiato e per ciascuna rata di canone, come mostrato nell’esempio che segue (l’esempio riporta una linea d’ordine per ciascuna rata, ma anche è possibile emettere un singolo Ordine per ogni singola rata):

[source, xml, indent=0]
----
…
<cbc:OrderTypeCode>220</cbc:OrderTypeCode>
…
<cac:OrderLine>
<cac:LineItem>
<cbc:ID>Numero della linea d’ordine</cbc:ID>
<cbc:Quantity unitCode=”C62”>10</cbc:Quantity>
<cbc:LineExtensionAmount currencyID=EUR>1250</cbc:LineExtensionAmount>
…
<cac:Delivery>
<cac:RequestedDeliveryPeriod>
<cbc:StartDate>2018-09-03</cbc:StartDate>
<cbc:EndDate>2018-10-02</cbc:EndDate>
<cac:Price>
<cbc:PriceAmount currencyID=EUR>125</cbc:PriceAmount>
</cac:Price>
 

<cac:Item>
<cbc:Description>Prima rata mensile di noleggio annuale di stampante mod. xxx</cbc:Description>
<cbc:Name>Modello della stampante</cbc:Name>
…
</cac:Item>
</cac:LineItem>
</cac:OrderLine>
…
Rate mensili dalla 2 alla 11
…
<cac:OrderLine>
<cac:LineItem>
<cbc:ID>Numero della linea d’ordine</cbc:ID>
<cbc:Quantity unitCode=”C62”>10</cbc:Quantity>
<cbc:LineExtensionAmount currencyID=EUR>1250</cbc:LineExtensionAmount>
…
<cac:Delivery>
<cac:RequestedDeliveryPeriod>
<cbc:StartDate>2019-08-03</cbc:StartDate>
<cbc:EndDate>2019-09-02</cbc:EndDate>
<cac:Price>
<cbc:PriceAmount currencyID=EUR>125</cbc:PriceAmount>
</cac:Price>
<cac:Item>
<cbc:Description>Dodicesima rata mensile di Noleggio annuale di stampante mod. xxx</cbc:Description>
<cbc:Name>Modello della stampante</cbc:Name>
…
</cac:Item>
</cac:LineItem>
</cac:OrderLine>
----

:leveloffset: -1

:leveloffset: +1

2.	Noleggio gestito come cessione temporanea di beni 

Se il noleggio è gestito come cessione temporanea di beni:

*	a livello di Documento, bisogna indicare il codice “220” specificando il sotto-tipo di Ordinazione “ON” (Ordinazione di noleggio);
* a livello di linea d’ordine, bisogna riportare i beni da noleggiare oggetto della fornitura.

Si forniscono, di seguito, alcuni esempi di Ordine riferiti al noleggio per un anno di 10 stampanti, al prezzo unitario di € 1.500. Il contratto prevede che il pagamento avvenga in rate mensili di € 125 per ciascuna stampante (gli esempi non includono sconti e/o maggiorazioni). A fronte di questo ordine saranno emesse 12 fatture di €
1.250 alla scadenza di ciascuna rata mensile (negli esempi a) e b), questa  informazione è indicata nel campo “PaymentTerms/Note”; negli esempi c) e d), nel campo “LineExtensionAmount” di ciascuna delle 12 linee d’ordine corrispndenta all corrispondente alla relativa rata mensile).
 

Il servizio può essere ordinato:

a)	con riferimento al complesso dei beni e per l’intero periodo di noleggio, come mostrato nell’esempio che segue:
…
<cbc:OrderTypeCode>220</cbc:OrderTypeCode>
…
<cac:Delivery>
<cac>RequestedDeliveryPeriod>
<cbc:StartDate>2018-09-03</cbc:StartDate>
<cbc>EndDate>2019-09-02</cbc:EndDate>
</cac:RequestedDeliveryPeriod>
</cac:Delivery>
…
<cac:DeliveryTerms>
<cbc:SpecialTerms>ON</SpecialTerms>
</cac:DeliveryTerms>
…
<cac:PaymentTerms>
<cbc:Note>Pagamento in rate mensili di € 1.250</cbc:Note >
</cac:PaymentTerms>
…
<cac:OrderLine>
<cac:LineItem>
<cbc:ID>Numero della linea d’ordine</cbc:ID>
<cbc:Quantity unitCode=”C62”>1</cbc:Quantity>
<cbc:LineExtensionAmount currencyID=EUR>15000</cbc:LineExtensionAmount>
…
<cac:Price>
<cbc:PriceAmount currencyID=EUR>15000</cbc:PriceAmount>
</cac:Price>
<cac:Item>
<cbc:Description>N. 10 stampanti mod. xxx a noleggio annuale</cbc:Description>
<cbc:Name>Modello della stampante</cbc:Name>
…
</cac:Item>
</cac:LineItem>
</cac:OrderLine>
…


b)	per l’intero periodo ma distintamente per ciascun bene (o insieme di beni) noleggiato, come mostrato nell’esempio che segue:
…
<cbc:OrderTypeCode>220</cbc:OrderTypeCode>
…
<cac:Delivery>
<cac>RequestedDeliveryPeriod>
<cbc:StartDate>2018-09-03</cbc:StartDate>
<cbc>EndDate>2019-09-02</cbc:EndDate>
</cac:RequestedDeliveryPeriod>
</cac:Delivery>
…
<cac:DeliveryTerms>
<cbc:SpecialTerms>ON</SpecialTerms>
</cac:DeliveryTerms>
…
<cac:PaymentTerms>
<cbc:Note>Pagamento in rate mensili di € 1.250</cbc:Note>
</cac:PaymentTerms>
…
<cac:OrderLine>
 

<cac:LineItem>
<cbc:ID>Numero della linea d’ordine</cbc:ID>
<cbc:Quantity unitCode=”C62”>10</cbc:Quantity>
<cbc:LineExtensionAmount currencyID=EUR>15000</cbc:LineExtensionAmount>
…
<cac:Price>
<cbc:PriceAmount currencyID=EUR>1500</cbc:PriceAmount>
</cac:Price>
<cac:Item>
<cbc:Description>Stampante mod. xxx a noleggio annuale</cbc:Description>
<cbc:Name>Modello della stampante</cbc:Name>
…
</cac:Item>
</cac:LineItem>
</cac:OrderLine>

c)	con riferimento al complesso dei beni ma distintamente per ciascuna rata di canone, come mostrato nell’esempio che segue (l’esempio riporta una linea d’ordine per ciascuna rata, ma anche è possibile emettere un singolo Ordine per ogni singola rata):
…
<cbc:OrderTypeCode>220</cbc:OrderTypeCode>
…
<cac:DeliveryTerms>
<cbc:SpecialTerms>ON</SpecialTerms>
</cac:DeliveryTerms>
…
<cac:OrderLine>
<cac:LineItem>
<cbc:ID>Numero della linea d’ordine</cbc:ID>
<cbc:Quantity unitCode=”C62”>1</cbc:Quantity>
<cbc:LineExtensionAmount currencyID=EUR>1250</cbc:LineExtensionAmount>
…
<cac:Delivery>
<cac:RequestedDeliveryPeriod>
<cbc:StartDate>2018-09-03</cbc:StartDate>
<cbc:EndDate>2018-10-02</cbc:EndDate>
<cac:Price>
<cbc:PriceAmount currencyID=EUR>1250</cbc:PriceAmount>
</cac:Price>
<cac:Item>
<cbc:Description>N. 10 stampanti mod. xxx a noleggio annuale – prima rata</cbc:Description>
<cbc:Name>Modello della stampante</cbc:Name>
…
</cac:Item>
</cac:LineItem>
</cac:OrderLine>
…
Rate mensili dalla 2 alla 11
…
<cac:OrderLine>
<cac:LineItem>
<cbc:ID>Numero della linea d’ordine</cbc:ID>
<cbc:Quantity unitCode=”C62”>1</cbc:Quantity>
<cbc:LineExtensionAmount currencyID=EUR>1250</cbc:LineExtensionAmount>
…
<cac:Delivery>
<cac:RequestedDeliveryPeriod>
<cbc:StartDate>2019-08-03</cbc:StartDate>
<cbc:EndDate>2019-09-02</cbc:EndDate>
<cac:Price>
<cbc:PriceAmount currencyID=EUR>1250</cbc:PriceAmount>
</cac:Price>
 

<cac:Item>
<cbc:Description> N. 10 stampanti mod. xxx a noleggio annuale – dodicesima rata</cbc:Description>
<cbc:Name>Modello della stampante</cbc:Name>
…
</cac:Item>
</cac:LineItem>
</cac:OrderLine>


d)	distintamente per ciascun bene (o insieme di beni) noleggiato e per ciascuna rata di canone, come mostrato nell’esempio che segue (l’esempio riporta una linea d’ordine per ciascuna rata, ma anche è possibile emettere un singolo Ordine per ogni singola rata):
…
<cbc:OrderTypeCode>220</cbc:OrderTypeCode>
…
<cac:DeliveryTerms>
<cbc:SpecialTerms>ON</SpecialTerms>
</cac:DeliveryTerms>
…
<cac:OrderLine>
<cac:LineItem>
<cbc:ID>Numero della linea d’ordine</cbc:ID>
<cbc:Quantity unitCode=”C62”>10</cbc:Quantity>
<cbc:LineExtensionAmount currencyID=EUR>1250</cbc:LineExtensionAmount>
…
<cac:Delivery>
<cac:RequestedDeliveryPeriod>
<cbc:StartDate>2018-09-03</cbc:StartDate>
<cbc:EndDate>2018-10-02</cbc:EndDate>
<cac:Price>
<cbc:PriceAmount currencyID=EUR>125</cbc:PriceAmount>
</cac:Price>
<cac:Item>
<cbc:Description>Stampante mod. xxx a noleggio annuale – prima rata</cbc:Description>
<cbc:Name>Modello della stampante</cbc:Name>
…
</cac:Item>
</cac:LineItem>
</cac:OrderLine>
…
Rate mensili dalla 2 alla 11
…
<cac:OrderLine>
<cac:LineItem>
<cbc:ID>Numero della linea d’ordine</cbc:ID>
<cbc:Quantity unitCode=”C62”>10</cbc:Quantity>
<cbc:LineExtensionAmount currencyID=EUR>1250</cbc:LineExtensionAmount>
…
<cac:Delivery>
<cac:RequestedDeliveryPeriod>
<cbc:StartDate>2019-08-03</cbc:StartDate>
<cbc:EndDate>2019-09-02</cbc:EndDate>
<cac:Price>
<cbc:PriceAmount currencyID=EUR>125</cbc:PriceAmount>
</cac:Price>
<cac:Item>
<cbc:Description>Stampante mod. xxx a noleggio annuale – dodicesima rata)</cbc:Description>
<cbc:Name>Modello della stampante</cbc:Name>
…
</cac:Item>
</cac:LineItem>
</cac:OrderLine>

:leveloffset: -1

.Esempio
[source, xml, indent=0]
----
<cac:PaymentTerms>
    <cbc:Note>30 giorni fattura</cbc:Note>
</cac:PaymentTerms>
----
