[[use-case-4-complex-ordering]]
= Caso d’uso 4 – Ordine di fornitura complesso

Questo caso d’uso è relativo a un ordine contenente quasi tutti gli elementi previsti per il messaggio dell’Ordine PEPPOL.

[cols="1s,5",options="header"]
|====
|Caso d’uso nr.
|4

|Nome
|Ordine complesso

|Descrizione
|Un ordine di articoli numerati con sconti e maggiorazioni sia a livello di testata che di riga.

|Ruoli coinvolti
|Acquirente +
Venditore +
Committente

|Assunzioni
|L’acquirente ha a disposizione un catalogo o una lista di prodotti per effettuare l’ordine. +
Il catalogo contiene gli identificativi degli articoli, nomi e unità di misura. +
L’acquirente ha stretto uno speciale accordo con il venditore relativamente ad uno sconto sull’ordine, le righe d’ordine e sul prezzo.

|Il flusso
|L’acquirente crea l’ordine con 4 diverse righe e articoli. +
Il venditore riceve l’ordine.

|Risultati
|L’acquirente e il venditore hanno raggiunto un accordo. +
Se la fattura contiene il riferimento all’ordine, questa può essere correlata automaticamente.

|Esempio XML
|Vedi sezione "Downloads" nella link:../../../../../../[Homepage]
|====
