[[use-case-5-order-incl-ultimate-consignee]]
= Caso d’uso 5 – Ordine con luogo di consegna e destinatario

Questo use case contiene un ordine con numerosi voci/articoli. L'ordine contiene informazioni relative al luogo di consegna e al Consegnatario/Destinatario finale al quale la consegna deve essere inoltrata.

[cols="1s,5",options="header"]
|====
|Nr. Caso d'uso
|5

|Nome Caso d'uso
|Ordine con luogo di consegna e destinatario

|Descrizione Caso d'uso
|Un ordine per articoli numerati con sconti e addebiti sia a livello di testata dell'ordine che a livello di riga

|Ruoli coinvolti
|Acquirente +
Venditore +
Consignee +
Delivery party


|Assunzioni
|The buyer has a catalogue or list of products to order. +
The catalogue contains the item numbers, names and type of unit of measure. +

|Il flusso
|The buyer creates an order with 3 different lines and items. +
The seller receives the order. +
At time for delivery the seller packs all items, print goods labels which are put on and all packages and a transport label put on the plastic wrapping that holds all the packages. +
The wrapped packages are delivered to and unloaded at the location of the consignee. +
The packages are reloaded and delivered by internal transport to the delivery party. +


|Risultati
|The buyer and the seller have reached an agreement. +
The delivery party has received the ordered items. +
If the invoice has an order reference, the invoice can be matched automatically.

|Esempio XML 
|Vedi {Esempi in XML} compatibili con NSO
|====
