.Esempio UBL per l'uso del CPV
[source, xml, indent=0]
----
include::{snippet-dir}/item.xml[tags=cpv]
----
<1> Il listID deve essere fra quelli della codifica UNCL7143 e il codice STI indica che questo è una classificazione CPV.

.Esempio UBL di UNSPSC (United Nation Standard Products and Services Code) 
[source, xml, indent=0]
----
include::{snippet-dir}/item.xml[tags=unspsc]
----
<1> Il listID deve essere fra quelli della codifica UNCL7143 e il codice TST indica che questo è una classificazione UNSPSC, mentre il listVersionID è opzionale, ma può essere usato per specificare la versione di UNSPSC. Notare che nelle versioni precedenti il codice MP era usato come soluzione temporanea per identificare UNSPSC. Nella fall release 2019 è stato sostituito con il nuovo codice TST 7143 che è specifico per UNSPSC.

.Esempio UBL di Dispositivo medico
#In questo esempio viene fornito il numero di registrazione attribuito al dispositivo medico nella Banca dati e Repertorio Dispositivi Medici dal Ministero della Salute.#

#L’attributo schemeID dovrà essere valorizzato con:#

* #DM1 per “Dispositivo medico o Dispositivo diagnostico in vitro”#
* #DM2 per “Sistema o kit Assemblato”#
* #DM0 per "Nessun numero di repertorio"#

[source, xml, indent=0]
----
<cac:CommodityClassification>
    <cbc:ItemClassificationCode listID="ZZZ">DM1:130209/R</cbc:ItemClassificationCode> <1>
</cac:CommodityClassification>
<cac:CommodityClassification>
    <cbc:ItemClassificationCode listID="STO">M0201030202</cbc:ItemClassificationCode> <2> 
</cac:CommodityClassification>
----
<1> Il listID deve essere fra quelli della codifica UNCL7143 e il codice *ZZZ* indica che questo è una classificazione in base ad accordi bilateali, mentre il listVersionID è opzionale.
<2> Il listID deve essere fra quelli della codifica UNCL7143 e il codice *STO* indica il codice CND (Classificazione Nazionale dei Dispositivi Medici)

