

= Il Fornitore (AccountingSupplierParty)

Il fornitore è colui che vende la merce o i servizi al cliente. Il fornitore è obbligatorio in quanto è il emittente del documento, inoltre è obbligatorio includere l’EndpointID (ParticipantID) con il quale è registrato su PEPPOL.


.Esempio di informazioni per un fornitore italiano con indicazione della Partita Iva nell'Endpoint
[source, xml, indent=0]
----
<cac:AccountingSupplierParty>
    <cac:Party>
	 <cbc:EndpointID schemeID="9906">IT01234567890</cbc:EndpointID>
	 <cac:PartyName>
	 	<cbc:Name>Fornitore S.p.A.</cbc:Name>
	 </cac:PartyName>
	 <cac:PostalAddress>
	 	<cbc:StreetName>Indirizzo Riga 1</cbc:StreetName>
	 	<cbc:AdditionalStreetName>Indirizzo Riga 2</cbc:AdditionalStreetName  >
	 	<cbc:CityName>Bologna</cbc:CityName>
	 	<cbc:PostalZone>40121</cbc:PostalZone>
	 	<cbc:CountrySubentity>BO</cbc:CountrySubentity >
	 	<cac:AddressLine>
	 		<cbc:Line>Zona Savena</cbc:Line>
	 	</cac:AddressLine>
	 	<cac:Country>
	 	<cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
	 	</cac:Country>
	 </cac:PostalAddress>
	 <cac:PartyTaxScheme>
	    <cbc:CompanyID>IT01234567890</cbc:CompanyID>
	    <cac:TaxScheme>
	        <cbc:ID>VAT</cbc:ID>
	    </cac:TaxScheme>
	 </cac:PartyTaxScheme>
	 <cac:PartyLegalEntity>
	 	<cbc:RegistrationName>Azienda fornitore</cbc:RegistrationName>
	 	<cac:RegistrationAddress>
	 		<cbc:CityName>Bologna</cbc:CityName>
	 		<cac:Country>
            <cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
	 		</cac:Country>
	 	</cac:RegistrationAddress>
	 </cac:PartyLegalEntity>
	 <cac:Contact>
	 	<cbc:Name>Lucio Grande</cbc:Name>
	 	<cbc:Telephone>051102030</cbc:Telephone>
	 	<cbc:ElectronicMail>lucio.grande@fornitore.it</cbc:ElectronicMail>
	 </cac:Contact>
    </cac:Party>
</cac:AccountingSupplierParty>
----

#Se il Fornitore è un’amministrazione pubblica, il campo *EndpointID/@schemeID* deve essere valorizzato con “0201:” seguito dal Codice UFE della PA.#

#Nel caso in cui non si inserisca la Partita IVA nell’EndpointID, la Partita IVA va indicata nel *Seller party identification*.#

#Nel caso in cui si voglia indicare anche il Codice Fiscale, quest’ultimo va indicato nel *Seller legal registration identifier*.#

.Esempio di indicazione della Partita Iva e del Codice Fiscale
[source, xml, indent=0]
----
<cac:AccountingSupplierParty>
 <cac:Party>
	<cbc:EndpointID schemeID="0201">UFY9MH</cbc:EndpointID>
	<cac:PartyIdentification>
		<cbc:ID>PIVA:IT01598570354</cbc:ID>
	</cac:PartyIdentification>
	<cac:PartyName>
		<cbc:Name>Azienda USL di Reggio Emilia</cbc:Name>
	</cac:PartyName>
	<cac:PostalAddress>
		<cbc:StreetName>Via Amendola 2</cbc:StreetName>
		<cbc:CityName>Reggio Emilia</cbc:CityName>
		<cbc:PostalZone>42122</cbc:PostalZone>
		<cbc:CountrySubentity>RE</cbc:CountrySubentity>
		<cac:Country>
			<cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
		</cac:Country>
	</cac:PostalAddress>
	<cac:PartyLegalEntity>
		<cbc:RegistrationName>Azienda USL di Reggio Emilia</cbc:RegistrationName>
		<cbc:CompanyID>CF:01598570354</cbc:CompanyID>
		<cac:RegistrationAddress>
			<cbc:CityName>Reggio Emilia</cbc:CityName>
			<cac:Country>
				<cbc:IdentificationCode listID="ISO3166-1:Alpha2">IT</cbc:IdentificationCode>
			</cac:Country>
		</cac:RegistrationAddress>
	</cac:PartyLegalEntity>
	<cac:Contact>
		<cbc:Name>Giovanni Rossi</cbc:Name>
		<cbc:Telephone>0522335111</cbc:Telephone>
		<cbc:ElectronicMail>giovanni.rossi@ausl.re.it</cbc:ElectronicMail>
	</cac:Contact>
    </cac:Party>
</cac:AccountingSupplierParty>
----

.Esempio di informazioni per un fornitore estero
[source, xml, indent=0]
----
</cac:AccountingSupplierParty>
    <cac:Party>
	 <cbc:EndpointID schemeID="9925">0999999999</cbc:EndpointID
	 <cac:PartyName>
	 	<cbc:Name>Fornitore Estero</cbc:Name>
	 </cac:PartyName>
	 <cac:PostalAddress>
	 	<cbc:StreetName> Rue Emile Claus 28</cbc:StreetName>
		<cbc:AdditionalStreetName>Quartiere</cbc:AdditionalStreetName>
		<cbc:CityName>Bruxelles</cbc:CityName>
		<cbc:PostalZone>1050</cbc:PostalZone>
		<cac:AddressLine>
		<cbc:Line>Deposito Consegnatario: Fornitore Estero</cbc:Line>
		</cac:AddressLine>
			<cac:Country>
			<cbc:IdentificationCode listID="ISO3166-1:Alpha2">BE</cbc:IdentificationCode>
			</cac:Country>
	 </cac:PostalAddress>
	 <cac:PartyTaxScheme>
	    <cbc:CompanyID>BE0848934496</cbc:CompanyID>
	    <cac:TaxScheme>
	        <cbc:ID>VAT</cbc:ID>
	    </cac:TaxScheme>
	 </cac:PartyTaxScheme>
	 <cac:PartyLegalEntity>
	 	<cbc:RegistrationName>Fornitore Estero</cbc:RegistrationName>
	 	<cac:RegistrationAddress>
	 		<cbc:CityName>Bruxelles</cbc:CityName>
	 		<cac:Country>
            <cbc:IdentificationCode listID="ISO3166-1:Alpha2">BE</cbc:IdentificationCode>
	 		</cac:Country>
	 	</cac:RegistrationAddress>
	 </cac:PartyLegalEntity>
	 <cac:Contact>
	 	<cbc:Name>Lucio Grande</cbc:Name>
	 	<cbc:Telephone>003241102030</cbc:Telephone>
	 	<cbc:ElectronicMail>lucio.grande@belgio.be</cbc:ElectronicMail>
	 </cac:Contact>
    </cac:Party>
</cac:AccountingSupplierParty>
----


= Il Cliente (AccountingCustomerParty)

Il Cliente, detto anche Cessionario o Committente, è la persona o organizzazione che acquisisce la proprietà di un prodotto o di un servizio in base ad un prezzo concordato e a dei termini di pagamento. +

#Il cliente può essere una PA, un operatore economico, un cittadino o un soggetto residente, non residente, non stabilito/identificato in Italia.#

Le informazioni inerenti al cliente sono obbligatorie e vengono fornite nell'elemento 'cac:AccountingCustomerParty'

.Esempio UBL di informazioni sul Cliente
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=buyer]
----
<1> L'attributo schemeID è obbligatorio per indirizzi elettronici, es. EndpointID
<2> L'attributo schemeID è raccomandato per tutti gli identificatori delle parti
<3> Gli identificatori per il VAT/IVA devono incudere il prefisso del codice paese
<4> L'attributo schemeID è raccomandato per gli identificatori di registrazione legale delle imprese

Nel contesto B2C il Cliente può essere un cittadino (una persona fisica). +

.Esempio di un soggetto residente in possesso della PEC.

[source, xml]

<cac:AccountingCustomerParty>
	<cac:Party>
		<cbc:EndpointID schemeID="0202">nome.cognome@pec-domain.it</cbc:EndpointID>
		<cac:PartyName>
			<cbc:Name>Mario Rossi</cbc:Name>
		</cac:PartyName>
                <cac:PostalAddress>
                        <cbc:StreetName>Via Riviera di Chiaia, 99A</cbc:StreetName>
                        <cbc:CityName>Napoli</cbc:CityName>
                        <cbc:PostalZone>80121</cbc:PostalZone>
                        <cac:AddressLine>
                        <cbc:Line> Informazioni Aggiuntive /cbc:Line>
                    </cac:AddressLine>
                        <cac:Country>
                            <cbc:IdentificationCode>IT</cbc:IdentificationCode>
                        </cac:Country>
                </cac:PostalAddress>
                <cac:PartyTaxScheme>
                    <cbc:CompanyID>RSSMRA68M06F839G</cbc:CompanyID>
                    <cac:TaxScheme>
                        <cbc:ID>VAT</cbc:ID>
                    </cac:TaxScheme>
                </cac:PartyTaxScheme>
                <cac:Contact><!— PEC opzionale -->
                        <cbc:Telephone>06123456</cbc:Telephone>
                        <cbc:ElectronicMail>nome.cognome@pec-domain.it</cbc:ElectronicMail>
                </cac:Contact>
                <cac:Person><!— C.F. Persona Fisica -->
                        <cbc:ID schemeID="9907">RSSMRA68M06F839G</cbc:ID>
                        <cbc:FirstName>Mario</cbc:FirstName>
                        <cbc:FamilyName>Rossi</cbc:FamilyName>
                </cac:Person>
	</cac:Party>
</cac:AccountingCustomerParty>


Nel contesto B2B o G2B, in base alla specifica della FatturaPA italiana, il Cliente può essere identificato mediante il *Codice Destinatario*. +

.Esempio di un soggetto (non persona fisica) in possesso del Codice Destinatario accreditato presso l'Agenzia delle Entrate.

[source, xml]

<cac:EndPointID>
    <cbc:ID schemeID="0205">L0U7KO4</cbc:ID>
</cac:EndPointID>

.Esempio di un soggetto residente privo di Codice Destinatario e di PEC:

[source, xml]

<cac:EndPointID>
    <cbc:ID schemeID="0205">0000000</cbc:ID>
</cac:EndPointID>


.Esempio di un soggetto (non persona fisica) non residente, non stabilito o identificato in Italia, privo di Codice e Destinatario e di PEC.

[source, xml]

<cac:EndPointID>
    <cbc:ID schemeID="0205">XXXXXXX</cbc:ID>
</cac:EndPointID>



= Il Beneficiario (PayeeParty)

Il beneficiario è una persona, istituto bancario o entità di business alla quale si effettua il pagamento.

Il beneficiario è una informazione facoltativa. Se questa informazione non è fornita, il fornitore/venditore è anche il beneficiario del pagamento.

Quando vengono fornite le informazioni del beneficiario significa che si evidenzia un caso di factoring.

Per riflettere l'assegnazione di una Fattura ad un factor è necessario:

. avere una dichiarazione di esclusione di responsabilità (avviso) sulla fattura che questa è stata assegnata ad un factor. La dichiarazione di esclusione di responsabilità dovrebbe essere fornita nella Invoice note (BT-22) a livello di testata.

. identificare il Factor con il Beneficiario

. modificare le coordinate bancarie a favore del Factor.


.Esempio UBL per le informazioni del beneficiario
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=payee]
----
<1> L'attributo schemeID è raccomandato per tutti gli identificatori delle parti
<2> L'attributo schemeID è raccomandato per gli identificatori di registrazione legale delle imprese


= Rappresentante fiscale del fornitore (TaxRepresentativePary)

In alcuni scenari di business, le aziende che commerciano oltre confine sono tenute secondo le autorità fiscali locali a nominare un rappresentante fiscale. 
Sono comprese le aziende extra-EU che operano in Europa, gli importatori in EU e i commercianti.  

I rappresentanti fiscali sono responsabili per la gestione corretta e la regolarizzazione dell'IVA per conto delle aziende, in linea con le normative locali. Un rappresentante fiscale è considerato come l'agente locale del commerciante.  In molti casi, il rappresentante fiscale è ritenuto responsabile in solido per le tasse del commerciante.

.Esempio UBL per le informazioni del rappresentante fiscale
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=taxrep]
----
<1> Gli identificatori per il VAT/IVA devono incudere il prefisso del codice paese


= #Il Rappresentante fiscale del cliente (AccountingCustomerParty/Party/PowerOfAttorney)#

Nella fatturazione tra privati (B2B), se il cessionario/committente si avvale di un rappresentante fiscale in Italia, si può specificare in fattura come parte dei dati del fornitore nell'elemento PowerOfAttorney, come procura per la rappresentanza fiscale.

.Esempio UBL per il rappresentante fiscale del cliente
[source, xml, indent=0]
----
----


= #Il Terzo Intermediario o Soggetto Emittente (AccountingSupplierParty/ServiceProviderParty)#

Nel caso sia un soggetto terzo ad emettere fattura per conto del cedente / prestatore, si può specificare in fattura come parte dei dati del fornitore nell'elemento ServiceProviderParty.

.Esempio UBL per il terzo intermediario o soggetto emittente per conto del cliente
[source, xml, indent=0]
----
----


= #Il Vettore (Delivery/CarrierParty)#

Nei casi di fattura "accompagnatoria", come parte delle informazioni relative al trasporto è possibile specificare i dati fiscali e anagrafici del vettore nell'elemento CarrierParty.

.Esempio UBL per il vettore che effettua il trasporto
[source, xml, indent=0]
----
----
