[[Sconti-e-maggiorazioni]]
= Sconti e Maggiorazioni

Gli elementi per specificare sconti e maggiorazioni si trovano a livello di documento

L’elemento `cac:AllowanceCharge` con il sotto elemento `cac:ChargeIndicator` permette di indicare se si sta specificando una maggiorazione (true) o uno sconto/abbuono (false).

_L'informazione relativa a sconti e/o maggiorazioni si applica all'intero ordine pre-concordato ed è inclusa nel calcolo dell'ammontare totale dell'ordine_

* Possono essere forniti più sconti e maggiorazioni
* Le informazioni sulle imposte relative agli sconti e maggiorazioni (cac:TaxCategory con i suoi sotto elementi) devono essere fornite
* La somma di tutti gli sconti e maggiorazioni a livello di testata deve essere specificato rispettivamente nel `cbc:AllowanceTotalAmount` e `cbc:ChargeTotalAmount`. Vedi paragrafo <<anchor-1,6.2 Calcolo dei totali>>


== Calcolo di sconti e maggiorazioni

Sconti e maggiorazioni a livello di testata sono costituiti da elementi contenenti informazioni sull’importo base di sconti/maggiorazioni e sulla percentuale di sconti/maggiorazioni.

Se l’importo base è presente, deve essere presente la percentuale, e se la percentuale è presente anche l’importo base deve essere presente. Il calcolo dell’importo è definito nel modo seguente:

====
stem:["Importo" =  "Importo base" times ("Percentuale" div 100)]
====


.Esempio di UBL di sconti e maggiorazioni a livello di testata, per l'IVA
[source, xml, indent=0]
----
<cac:AllowanceCharge>
        <cbc:ChargeIndicator>true</cbc:ChargeIndicator> <1>
        <cbc:AllowanceChargeReasonCode>FC</cbc:AllowanceChargeReasonCode>
        <cbc:AllowanceChargeReason>Freight service</cbc:AllowanceChargeReason>
        <cbc:MultiplierFactorNumeric>2</cbc:MultiplierFactorNumeric> <4>
        <cbc:Amount currencyID="EUR">20</cbc:Amount> <5>
        <cbc:BaseAmount currencyID="EUR">1000.00</cbc:BaseAmount> <3>
        <cac:TaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>22</cbc:Percent>
                <cac:TaxScheme>
                        <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
        </cac:TaxCategory>
</cac:AllowanceCharge>
<cac:AllowanceCharge>
        <cbc:ChargeIndicator>false</cbc:ChargeIndicator> <2> 
        <cbc:AllowanceChargeReasonCode>65</cbc:AllowanceChargeReasonCode>
        <cbc:AllowanceChargeReason>Production error discount</cbc:AllowanceChargeReason>
        <cbc:Amount currencyID="EUR">10.00</cbc:Amount>
        <cac:TaxCategory>
                <cbc:ID>S</cbc:ID>
                <cbc:Percent>22</cbc:Percent>
                <cac:TaxScheme>
                        <cbc:ID>VAT</cbc:ID>
                </cac:TaxScheme>
        </cac:TaxCategory>
</cac:AllowanceCharge>
----

<1> 	ChargeIndicator = TRUE indica la presenza di una maggiorazione
<2> 	ChargeIndicator = FALSE indica la presenza di uno sconto
<3> Importo base, deve essere usato con la percentuale per calcolare l’importo
<4> Percentuale maggiorazione
<5> stem:["Importo" = "Importo base" times ("Percentuale" div 100)]
