[[attachements]]
= Allegati a livello di documento

I documenti non-XML possono essere inviati come allegato all’Ordine pre-concordato Peppol. Questi potrebbero essere disegni o resoconti di ore lavorate o altri documenti rilevanti per l’Ordine. L’allegato può essere inviato come oggetto binario codificato in Base64, incorporato nel message o come URI ad un indirizzo esterno.

Si raccomanda di inviare allegati in modo incorporato, oggetti binari e non come riferimenti esterni.

====
IMPORTANT: Gli allegati possono essere utilizzati come informazioni aggiuntive ma non come copie dell’ordine.
====


.Esempio di allegato incorporato, oggetto binario nel messaggio dell’Ordine PEPPOL a livello di documento
[source, xml, indent=0]
----
include::{snippet-dir}/OA full.xml[tags=AdditionalDocumentReference]
----

= Allegati e riferimenti a documenti a livello di riga

I documenti non-XML possono essere inviati come allegato all’Ordine pre-concordato Peppol a livello di riga. Questi potrebbero comprendere specifiche del prodotto, disegni o resoconti di ore lavorate o altri documenti rilevanti per l’Ordin pre-concordato. Vedi informazioni sopra relative agli allegati.

.Esempio di allegato incorporato, oggetto binario nel messaggio dell’Ordine PEPPOL a livello di riga
[source, xml, indent=0]
----
include::{snippet-dir}/OA full.xml[tags=ItemSpecificationDocumentReference]
----


.Esempio di un link relativo ad un ticket scaricabile 
[source, xml, indent=0]
----
include::{snippet-dir}/OA full.xml[tags=ItemSpecificationDocumentReference2]
----
