[[parti]]
= Parti

Le seguenti parti/I seguenti ruoli possono essere specificate/i nel messaggio:

== Fornitore/Venditore (SellerSupplierParty)

Il Venditore è la persona giuridica o l’organizzazione che vende beni e/o servizi. +
Il Venditore è un’informazione obbligatoria in quanto mittente dell’Ordine Pre-concordato, pertanto è necessario includere l’EndpointID.


#Nel caso in cui si voglia indicare la Partita IVA, questa va indicata nel campo Seller party identification.# +
#Nel caso in cui si voglia indicare il Codice Fiscale, questo va indicato nel Seller legal registration identifier.#


.Esempio di informazioni per un fornitore privato
[source, xml, indent=0]
----
<cac:SellerSupplierParty>
	<cac:Party>
		<cbc:EndpointID schemeID="0211">IT01234567890</cbc:EndpointID>
		<cac:PartyIdentification>
			<cbc:ID schemeID="0211"> IT01234567890</cbc:ID>
		</cac:PartyIdentification>
		<cac:PostalAddress>
			<cbc:StreetName>Indirizzo Riga 1</cbc:StreetName>
			<cbc:AdditionalStreetName>Indirizzo Riga 2</cbc:AdditionalStreetName>
			<cbc:CityName>Bologna</cbc:CityName>
			<cbc:PostalZone>40121</cbc:PostalZone>
			<cbc:CountrySubentity>BO</cbc:CountrySubentity>
			<cac:AddressLine>
				<cbc:Line>Zona Savena</cbc:Line>
			</cac:AddressLine>
			<cac:Country>
				<cbc:IdentificationCode>IT</cbc:IdentificationCode>
			</cac:Country>
		</cac:PostalAddress>
		<cac:PartyLegalEntity>
			<cbc:RegistrationName>Azienda fornitore</cbc:RegistrationName>
			<cbc:CompanyID schemeID="0210">01598570354</cbc:CompanyID>
			<cac:RegistrationAddress>
				<cbc:CityName>Bologna</cbc:CityName>
				<cac:Country>
					<cbc:IdentificationCode>IT</cbc:IdentificationCode>
				</cac:Country>
			</cac:RegistrationAddress>
		</cac:PartyLegalEntity>
		<cac:Contact>
			<cbc:Name>Lucio Grande</cbc:Name>
			<cbc:Telephone>051102030</cbc:Telephone>
			<cbc:ElectronicMail>lucio.grande@fornitore.it</cbc:ElectronicMail>
		</cac:Contact>
	</cac:Party>
</cac:SellerSupplierParty>
----

#Se il Venditore è un’amministrazione pubblica, il campo *EndpointID/@schemeID* deve essere valorizzato con “0201:” seguito dal Codice Univoco Ufficio (c.d. "Codice iPA", riportato nella rubrica "indicepa"dell'Indice delle Pubbliche Amministrazioni) della PA.#

.Esempio di informazioni per un fornitore Pubblica Amministrazione
[source, xml, indent=0]
----
<cac:SellerSupplierParty>
	<cac:Party>
		<cbc:EndpointID schemeID="0201"> UFY9MH</cbc:EndpointID>
		<cac:PartyIdentification>
			<cbc:ID schemeID="0211"> IT01234567890</cbc:ID>
		</cac:PartyIdentification>
		<cac:PostalAddress>
			<cbc:StreetName>Via Amendola 2</cbc:StreetName>
			<cbc:CityName>Reggio Emilia</cbc:CityName>
			<cbc:PostalZone>42122</cbc:PostalZone>
			<cbc:CountrySubentity>RE</cbc:CountrySubentity>
			<cac:Country>
				<cbc:IdentificationCode>IT</cbc:IdentificationCode>
			</cac:Country>
		</cac:PostalAddress>
		<cac:PartyLegalEntity>
			<cbc:RegistrationName>Azienda USL di Reggio Emilia</cbc:RegistrationName>
			<cbc:CompanyID schemeID="0210">01234567890</cbc:CompanyID>
			<cac:RegistrationAddress>
				<cbc:CityName>Reggio Emilia</cbc:CityName>
				<cac:Country>
					<cbc:IdentificationCode>IT</cbc:IdentificationCode>
				</cac:Country>
			</cac:RegistrationAddress>
		</cac:PartyLegalEntity>
		<cac:Contact>
			<cbc:Name>Giovanni Rossi</cbc:Name>
			<cbc:Telephone>0522335111</cbc:Telephone>
			<cbc:ElectronicMail>giovanni.rossi@ausl.re.it</cbc:ElectronicMail>
		</cac:Contact>
	</cac:Party>
</cac:SellerSupplierParty>
----

.Esempio di informazioni per un fornitore estero
[source, xml, indent=0]
----
<cac:SellerSupplierParty>
    <cac:Party>
	 <cbc:EndpointID schemeID="9925">0999999999</cbc:EndpointID
	 <cac:PostalAddress>
        <cbc:StreetName> Rue Emile Claus 28</cbc:StreetName>
		<cbc:AdditionalStreetName>Quartiere</cbc:AdditionalStreetName>
		<cbc:CityName>Bruxelles</cbc:CityName>
		<cbc:PostalZone>1050</cbc:PostalZone>
		<cac:AddressLine>
		    <cbc:Line>Deposito Consegnatario: Fornitore Estero</cbc:Line>
		</cac:AddressLine>
		<cac:Country>
		    <cbc:IdentificationCode>BE</cbc:IdentificationCode>
			</cac:Country>
	 </cac:PostalAddress>
	 <cac:PartyLegalEntity>
	 	<cbc:RegistrationName>Fornitore Estero</cbc:RegistrationName>
	 </cac:PartyLegalEntity>
	 <cac:Contact>
	 	<cbc:Name>Lucio Grande</cbc:Name>
	 	<cbc:Telephone>003241102030</cbc:Telephone>
	 	<cbc:ElectronicMail>lucio.grande@belgio.be</cbc:ElectronicMail>
	 </cac:Contact>
    </cac:Party>
</cac:SellerSupplierParty>
----


== Cliente/Acquirente (BuyerCustomerParty)

L’Acquirente è la persona giuridica o l’organizzazione che acquista beni e/o servizi. +
L’Acquirente è un’informazione obbligatoria in quanto destinatario dell’Ordine Pre-concordato, pertanto è necessario includere l’EndpointID (ParticipantID) con il quale è registrato su Peppol.


#Se l’Amministrazione Aggiudicatrice è identificata in Peppol con il Codice Univoco Ufficio (ID Partecipante nei registri SMP), deve essere indicato il suddetto codice come endpoint (cac:EndpointID):#

[source, xml, indent=0]
----
<cac:BuyerCustomerParty>
    <cac:Party>
        <cbc:EndpointID schemeID="0201">ABCDEF</cbc:EndpointID>
    …
    </cac:Party>
</cac:BuyerCustomerParty>
----

#Nel caso in cui si voglia indicare la Partita IVA, questa va indicata nel campo Buyer party identification.# +
#Nel caso in cui si voglia indicare il Codice Fiscale, questo va indicato nel Buyer legal registration identifier.#


.Esempio di informazioni del cliente
[source, xml, indent=0]
----
<cac:BuyerCustomerParty>
	<cac:Party>
		<cbc:EndpointID schemeID="0201">UFY9MH</cbc:EndpointID>
		<cac:PartyIdentification>
			<cbc:ID schemeID="0211">IT01598570354</cbc:ID>
		</cac:PartyIdentification>
		<cac:PostalAddress>
			<cbc:StreetName>Via Amendola 2</cbc:StreetName>
			<cbc:CityName>Reggio Emilia</cbc:CityName>
			<cbc:PostalZone>42122</cbc:PostalZone>
			<cbc:CountrySubentity>RE</cbc:CountrySubentity>
			<cac:Country>
				<cbc:IdentificationCode>IT</cbc:IdentificationCode>
			</cac:Country>
		</cac:PostalAddress>
		<cac:PartyLegalEntity>
			<cbc:RegistrationName>Azienda USL di Reggio Emilia</cbc:RegistrationName>
			<cbc:CompanyID schemeID="0210">01598570354</cbc:CompanyID>
		</cac:PartyLegalEntity>
	</cac:Party>
</cac:BuyerCustomerParty>
----

== Richiedente (OriginatorCustomerParty)

Il Richiedente è la persona giuridica o l’organizzazione che inizializza il processo di emissione dell'Ordine e per la quale l'Acquirente effettua l'acquisto. +
Il Richiedente è un’informazione opzionale nel messaggio dell’Ordine Pre-concordato.

#Nel caso in cui si volesse inserire o la Partita IVA o il Codice Fiscale, questi vanno indicati *Seller party identification*, preceduti rispettivamente dagli attributi "schemedID" valorizzati con "0211" per la Partita IVA oppure "0210" per il Codice Fiscale. Non è possibile indicare sia la Partita IVA sia il CF per il Venditore nell'Ordine pre-concordato.#

.Esempio
[source, xml, indent=0]
----
<cac:OriginatorCustomerParty>
        <cac:Party>
                <cac:PartyIdentification>
                        <cbc:ID schemeID="0210">01598570354</cbc:ID>
                </cac:PartyIdentification>
                <cac:PartyName>
                        <cbc:Name>Information services</cbc:Name>
                </cac:PartyName>
        </cac:Party>
</cac:OriginatorCustomerParty>
----

==  Intestatario fattura (AccountingCustomerParty)

L’intestatario fattura è la persona giuridica o l’organizzazione a cui deve essere intestata la fattura relativa all'ordine. +
L’intestatario fattura è un’informazione opzionale nel messaggio dell’Ordine Pre-concordato.

#Nel caso in cui si volesse inserire o la Partita IVA o il Codice Fiscale, questi vanno indicati *Seller party identification*, preceduti rispettivamente dagli attributi "schemedID" valorizzati con "0211" per la Partita IVA oppure "0210" per il Codice Fiscale. Non è possibile indicare sia la Partita IVA sia il CF per il Venditore nell'Ordine pre-concordato.#

.Esempio
[source, xml, indent=0]
----
<cac:AccountingCustomerParty>
        <cac:Party>
                <cac:PartyIdentification>
                        <cbc:ID schemeID="0211">IT01234567890</cbc:ID>
                </cac:PartyIdentification>
                <cac:PartyName>
                        <cbc:Name>Information services</cbc:Name>
                </cac:PartyName>
        </cac:Party>
</cac:AccountingCustomerParty>
----

==  #Consegnatario/Destinatario (DeliveryParty)#

Il Consegnatario/Destinatario è la persona giuridica o l’organizzazione che riceve i beni e/o i servizi oggetto dell’ordine.
L’indicazione del Consegnatario/Destinatario è prevista solo con riferimento all’intero Documento. +
Il Consegnatario/Destinatario è un’informazione opzionale nel messaggio dell’Ordine Pre-concordato.


.Esempio di informazioni del Consegnatario/Destinatario
[source, xml, indent=0]
----
<cac:Delivery>
    <cac:DeliveryParty>
        <cac:PartyIdentification>
            <cbc:ID>UO07</cbc:ID>
        </cac:PartyIdentification>
        <cac:PartyName>
            <cbc:Name>Centro logistico</cbc:Name>
        </cac:PartyName>
    </cac:DeliveryParty>
</cac:Delivery>
---- 

Qualora si indichi il Beneficiario, l’identificativo (campo “ID”) e la denominazione (campo “Name”) dell’unità organizzativa sono entrambi obbligatori. Se l’identificativo non è noto o non esiste, è sufficiente valorizzare il campo con il testo “UO”, che sta per unità organizzativa. +

Se invece il Beneficiario è una persona fisica è necessario contemperare l’esigenza di
tutelarne la riservatezza con la necessità di dare indicazioni complete ed esaurienti per
la consegna. A tal fine: +

* se non è strettamente necessario indicare per esteso il nome del Beneficiario, il
campo “Name” deve essere valorizzato con “PF”, che sta per persona fisica;
* se al Beneficiario è stato assegnato un identificativo, questo deve essere indicato
nel campo “ID”, altrimenti anche questo campo va valorizzato con “PF”.
