[[product-identification]]
= Identificazione prodotto

L’individuazione del prodotto può essere fatta attraverso l'utilizzo di codici identificativi descritti di seguito:

* il codice attribuito dal Fornitore (elemento `cac:SellersItemIdentification/CBC:ID`);

* il codice attribuito dal Cliente (elemento `cac:BuyersItemIdentification/cbc:ID`);

* il codice standard, corrispondente all’identificativo assegnato al prodotto da un sistema di identificazione univoca (elemento `cac:StandardItemIdentification/cbc:ID`) selezionato tra quelli presenti nell’apposita code list PEPPOL "ISO 6523 ICD list".


Quale identificatore deve essere usato dipende dalle informazioni conosciute al momento dell’ordine o da quello comunemente utilizzato nel settore business di riferimento.

.Esempio di ordine pre-concordato con Seller ID e Standard ID (GTIN):
[source, xml, indent=0]
----
include::{snippet-dir}/OA full.xml[tags=ItemIdentifiers]
----

[[product-name-and-description]]
= Nome prodotto e descrizione

Il nome del Prodotto deve essere fornito nell’elemento `cac:Item/cbc:Name` a livello di riga. La sua descrizione può essere fornita in `cac:Item/cbc:Description`.

Il nome del prodotto è spesso inviato dall'Acquirente al Venditore nell'ordine pre-concordato.


.Esempio di ordine con descrizione e nome:
[source, xml, indent=0]
----
include::{snippet-dir}/OA full.xml[tags=ItemDescription]
----
