[[product-identification]]
= Identificazione prodotto

L’individuazione del prodotto può essere fatta attraverso l'utilizzo di codici identificativi descritti di seguito:

* il codice attribuito dal Fornitore (elemento `cac:SellersItemIdentification/CBC:ID`);

* il codice attribuito dal Cliente (elemento `cac:BuyersItemIdentification/cbc:ID`);

* il codice standard, corrispondente all’identificativo assegnato al prodotto da un sistema di identificazione univoca (elemento `cac:StandardItemIdentification/cbc:ID`) selezionato tra quelli presenti nell’apposita code list Peppol "ISO 6523 ICD list".


Quale identificatore deve essere usato dipende dalle informazioni conosciute al momento dell’ordine o da quello comunemente utilizzato nel settore business di riferimento.

.Esempio di ordine pre-concordato con Seller ID e Standard ID (GTIN):
[source, xml, indent=0]
----
include::{snippet-dir}/OA full.xml[tags=ItemIdentifiers]
----


:leveloffset: +1

[[product-identification]]
= #Dettaglio sui Farmaci e loro identificazione - AIC Farmaco#

Per i prodotti farmaceutici provvisti del codice di Autorizzazione all’Immissione in Commercio (AIC) rilasciato dell’Agenzia Italiana del Farmaco (AIFA), l’elemento “SellersItemIdentification/ID” deve essere valorizzato sempre con il relativo codice AIC, preceduto dalla stringa "AICFARMACO:".

.Esempio di ordine pre-concordato con l'indicazione del codice AIC farmaco
[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
    ...
        <cac:Item>
            <cbc:Description>NORVASC*5MG 28CPR</cbc:Description>
            <cbc:Name>NORVASC</cbc:Name>
            <cac:SellersItemIdentification>
                <cbc:ID>AICFARMACO:027428010</cbc:ID>
            </cac:SellersItemIdentification>
            <cac:CommodityClassification>
                <cbc:ItemClassificationCode listID=”STL” listIVersionID=”UNCL7143”>C08CA01</cbc:ItemClassificationCode>
            </cac:CommodityClassification>
        </cac:Item>
    </cac:LineItem>
</cac:OrderLine>
----

[NOTE]
====
In particolari circostanze taluni farmaci esteri sono commercializzati in Italia in assenza dell’autorizzazione rilasciata dall’AIFA. Questi farmaci non rientrano nell’ambito di applicazione del Decreto del Ministero dell’economia e delle finanze 20 dicembre 2017, recante “Modalità tecniche di indicazione dell'AIC sulla fattura elettronica, nonché modalità di accesso da parte dell'AIFA ai dati ivi contenuti”, e il codice alfanumerico ad essi associato non è propriamente un codice AIC, pertanto non deve essere indicato premettendo il testo “AICFARMACO:”.
====

Si evidenzia inoltre che, talvolta, l’indicazione dell’AIC può non essere sufficiente ad individuare univocamente il prodotto, ad esempio per le sacche di plasma o le capsule di Jodio. +

In questi casi, è opportuno indicare le informazioni aggiuntive necessarie all’interno dell’elemento “Name” o nell’elemento “Description” (es. per il plasma: “PLASMASAFE*IV SACCA 200 ML GRUPPO 0”).

:leveloffset: -1

:leveloffset: +1

[[product-identification]]
= #Dettaglio sui Dispositivi Medici e loro identificazione - Codice UDI#

Per i dispositivi medici provvisti del codice UDI (Unique Device Identification) rilasciato dall'unico ente autorizzato GS1 Italy, l’elemento “SellersItemIdentification/ID” deve essere valorizzato sempre con il relativo codice UDI, prefissato dalla stringa "UDI:".

.Esempio di ordine con l'indicazione del codice UDI
[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
    ...
        <cac:Item>
            <cbc:Name>Nome articolo</cbc:Name>
            <cac:SellersItemIdentification>
              <cbc:ID>UDI:(01)47964367965424(11)173434(17)226565(10)A379B3(21)1237</cbc:ID>
            </cac:SellersItemIdentification>
        </cac:Item>
</cac:OrderLine>

----


:leveloffset: -1


:leveloffset: +1

[[gestione-tipo-carburante]]
= #Gestione tipo Carburante#

La gestione del tipo carburante è operata a mezzo dell’elemento “SellersItemIdentification/ID” in cui viene inserito il valore della tabella di riferimento per i prodotti energetici TA13 - pubblicata sul sito dell’Agenzia delle Dogane preceduto dalla stringa “CARB:”.

.Esempio di ordine pre-concordato con l'indicazione del tipo carburante
[source, xml, indent=0]
----
<cac:OrderLine>
    <cac:LineItem>
    ...
        <cac:Item>
            <cbc:Name>Benzina senza piombo, ottani>=98</cbc:Name>
	        <cac:SellersItemIdentification>
		        <cbc:ID>CARB:27101249</cbc:ID>
	        </cac:SellersItemIdentification>
	        <cac:ClassifiedTaxCategory>
	            <cbc:ID>S</cbc:ID>
		        <cbc:Percent>22</cbc:Percent>
		        <cac:TaxScheme>
			        <cbc:ID>VAT</cbc:ID>
			    </cac:TaxScheme>
	        </cac:ClassifiedTaxCategory>
        </cac:Item>
    </cac:LineItem>
</cac:OrderLine>
----

:leveloffset: -1



[[product-name-and-description]]
= Nome prodotto e descrizione

Il nome del Prodotto deve essere fornito nell’elemento `cac:Item/cbc:Name` a livello di riga. La sua descrizione può essere fornita in `cac:Item/cbc:Description`.

Il nome del prodotto è spesso inviato dall'Acquirente al Venditore nell'ordine pre-concordato.


.Esempio di ordine pre-concordato con descrizione e nome:
[source, xml, indent=0]
----
<cac:Item>
    <cbc:Description>Descrizione</cbc:Description>
    <cbc:Name>Salviette per bambini</cbc:Name>
          …
</cac:Item>
----
