= Product identification

Product identification may be done using the identifiers described below:


* il codice attribuito dal Fornitore (elemento “SellersItemIdentification/ID”);

* il codice standard, corrispondente all’identificativo assegnato al prodotto da un sistema di identificazione univoca (elemento “StandardItemIdentification/ID”) selezionato tra quelli presenti nell’apposita code list PEPPOL "ISO 6523 ICD list".

* il codice attribuito dal Cliente (elemento “SellersItemIdentification/ID”);


The order agreement requires that an item has an identifier. This can be either the sellers identifier or a standard identifier. 



Quale identificatore deve essere usato dipende dalle informazioni conosciute al momento dell’ordine o da quello comunemente utilizzato nel settore business di riferimento.

.Example of an PEPPOL BIS Order Agreement item using both Sellers ID and Standard ID (GTIN)
[source, xml, indent=0]
----
include::{snippet-dir}/OA full.xml[tags=ItemIdentifiers]
----

[[product-name-and-description]]
= Nome prodotto e descrizione

Il nome del Prodotto deve essere fornito nell’elemento `cac:Item/cbc:Name` a livello di riga. La sua descrizione può essere fornita in `cac:Item/cbc:Description`.

Il nome del prodotto è spesso inviato dall'Acquirente al Venditore nell'ordine pre-concordato.


.Esempio di ordine con descrizione e nome:
[source, xml, indent=0]
----
include::{snippet-dir}/OA full.xml[tags=ItemDescription]
----
