[[quantities-and-units]]
= Quantità e unità di misura

Nell’Ordine PEPPOL possono essere fornite diverse Quantità e le relative Unità di misura. Esse sono relazionate sia al processo dell’ordine che a quello della logistica. +

La tabella seguente elenca le quantità e le relative unità di misura previste. Ogni quantità deve avere la sua unità di misura espressa secondo la codelist "Recommandation 20".

[cols="1,3",options="header"]
|====
|Nome elemento / (Tag name)
|Descrizione

|Price Quantity +
(`cbc:BaseQuantity`)
|Quantità relative al Prezzo.

|Order Quantity +
(`cbc:Quantity`)
|Quantità ordinate, es. Il numero dei pezzi o il volume in litri.
|====

.Example of an order agreement line with a quantity of 120 pieces (cbc:Quantity) and price is given per 12 items. When calculating the line amount the price is applied pr 12 pieces, that is 120/12x50 = €500
[source, xml, indent=0]
----
include::{snippet-dir}/OA full.xml[tags=LineItem]
<!-- code omitted for clarity -->
include::{snippet-dir}//OA full.xml[tags=price]
----
