= #Other management data#

The elments *cac:AdditionalItemProperty/cbc:Name* and *cac:AdditionalItemProperty/cbc:Value* could be used to provide information regarding other management data (FPA 2.2.1.16 AltriDatiGestionali).

The *cac:AdditionalItemProperty/cbc:Name* can be set to "DatiVeicoli" (see par. 11.17), "Ritenuta" (see par. 5.7), "TipoCessionePrestazione" (see par. 11.9.3), "Natura" (see par. 8.3) or as follows:

* If cbc:Name is set to "Testo" (text), then fill cbc:Value with the referred data (FPA 2.2.1.16.2 RiferimentoTesto). 

* If cbc:Name is set to "Numero" (number), then fill cbc:Value with the referred number (FPA 2.2.1.16.3 RiferimentoNumero). 

* If cbc:Name is set to "Data" (date), then fill cbc:Value with the referred date (FPA 2.2.1.16.4 RiferimentoData). 

= #Vehicle data#

The elements *cac:AdditionalItemProperty/cbc:Name* and *cac:AdditionalItemProperty/cbc:Value* could be used to provide information regarding the Vehicle data (FPA 2.3 DatiVeicoli).

* In this case, if cbc:Name is set to "DatiVeicoli" (vehicles data), then fill cbc:Value with the date of the travel (FPA 2.3.1 Data) and the distance traveled (FPA 2.3.2 TotalePercorso), concatenated with the "#" symbol.