= #Payment terms#

#For the cross-border invoicing, the payment conditions code must be a fixed value equal to "TP02" indicated in the element *cac:PaymentTerms/cbc:Note*.#

.UBL example of a cross-boarder invoice
[source, xml, indent=0]
----
<cac:PaymentTerms>
    <cbc:Note>TP02</cbc:Note>
</cac:PaymentTerms>
----

== #Terms and conditions of payment# (Domestic CIUS)

Within the italian context, the element *cac:PaymentTerms/cbc:Note* must be used only to indicate the data of the Payment Conditions (FPA 2.4.1 CondizioniPagamento) and the Days for Payment Terms (FPA 2.4.2.4 GiorniTerminiPagamento), concatenated using the "#" symbol.

.UBL example of a domestic invoice
[source, xml, indent=0]
----
<cac:PaymentTerms>
    <cbc:Note>TP02#60</cbc:Note>
</cac:PaymentTerms>
----

== #Advance payment# (Extension)

In the case of an advance payment, it is possible to offer a discount by specifying both the amount and the deadline date by which the payment must be completed. 

.UBL example of an advance payment
[source, xml, indent=0]
----
<cac:PaymentTerms>
    <cbc:Note>TP02#60</cbc:Note>
    <cbc:SettlementDiscountAmount currencyID="EUR">100.00</cbc:SettlementDiscountAmount>
    <cac:SettlementPeriod>
        <cbc:EndDate>2020-10-31</cbc:EndDate>
    </cac:SettlementPeriod>
</cac:PaymentTerms>
----

== #Late payment# (Extension)

In the case of a late payment, it is possible to define a penalty by specifying both the amount due and the date from which the penalty applies.

.UBL example of a late payment
[source, xml, indent=0]
----
<cac:PaymentTerms>
    <cbc:Note>TP02#60</cbc:Note>
    <cbc:PenaltyAmount currencyID="EUR">100.00</cbc:PenaltyAmount>
    <cac:PenaltyPeriod>
        <cbc:StartDate>2020-10-01</cbc:StartDate>
    </cac:PenaltyPeriod>
</cac:PaymentTerms>
----