
= #Termini di pagamento#

#Per la fatturazione cross-border il campo Note ha valore fisso e pari a TP02.#

.Esempio
[source, xml, indent=0]
----
<cac:PaymentTerms>
    <cbc:Note>TP02</cbc:Note>
</cac:PaymentTerms>
----

== #Termini e condizioni di pagamento# (CIUS domestica)

##Il campo *cac:PaymentTerms/cbc:Note* deve essere usato solo per indicare il dato FPA 2.4.1 CondizioniPagamento e FPA 2.4.2.4 GiorniTerminiPagamento, concatenati con il simbolo "#".##

.Esempio
[source, xml, indent=0]
----
<cac:PaymentTerms>
    <cbc:Note>TP02#60</cbc:Note>
</cac:PaymentTerms>
----

== #Pagamento Anticipato# (estensione)

#A fronte di un pagamento anticipato è possibile offrire uno sconto specificandone l'importo e la data limite entro il quale il pagamento deve essere perfezionato.#

.Esempio UBL per specificare un pagamento anticipato
[source, xml, indent=0]
----
<cac:PaymentTerms>
    <cbc:Note>TP02#60</cbc:Note>
    <cbc:SettlementDiscountAmount currencyID="EUR">100.00</cbc:SettlementDiscountAmount>
    <cac:SettlementPeriod>
        <cbc:EndDate>2020-10-31</cbc:EndDate>
    </cac:SettlementPeriod>
</cac:PaymentTerms>
----

== #Pagamento Ritardato# (estensione)

#A fronte di un pagamento ritardato è possibile fissare una penalità specificandone l'importo dovuto e la data di decorrenza della penale.#

.Esempio UBL per specificare un pagamento ritardato
[source, xml, indent=0]
----
<cac:PaymentTerms>
    <cbc:Note>TP02#60</cbc:Note>
    <cbc:PenaltyAmount currencyID="EUR">100.00</cbc:PenaltyAmount>
    <cac:PenaltyPeriod>
        <cbc:StartDate>2020-10-01</cbc:StartDate>
    </cac:PenaltyPeriod>
</cac:PaymentTerms>
----
