
[[confezionamento]]
= Confezionamento

Per fornire informazioni sul confezionamento è possibile usare due diverse modalità a seconda di come era stato effettuato l’ordine, e quindi se l’articolo corrispondeva alla singola unità o alla confezione.

Se l’articolo ordinato era una confezione è importante indicarne l’unità di misura corretta utilizzando “PK” (pack).

Nella tabella seguente si fornisce la metodologia per aggiungere informazioni sulle singole unità all’interno della confezione e viceversa, quando l’articolo coincide con l’unità base, per fornire informazioni sul confezionamento.

.Metodologia Confezionamento
[width="100%", cols="1h,2m,2m"]
|===

| *Informazioni* 2+^| *Articolo*

|
| Caso 1: *Unità Base*
| Caso 2: *Confezione*

| Unità di Misura
| NAR  (o altra più specifica)
| PK

| Numero unità base nella confezione
| cac:Item/cbc:PackSizeNumeric
| cac:Item/cbc:PackQuantity

| Identificativo Unità Base
| cac:Item/cac:SellersItemIdentification (o altro identificativo standard)
| cac:Item/cac:AdditionalItemProperty/
cbc:Name = UnitIdentification
cbc:Value = XYZ 

| Identificativo Confezione
| cac:Item/cac:AdditionalItemProperty/
cbc:Name = PackIdentification
cbc:Value = AIC12345
| cac:Item/cac:SellersItemIdentification (o altro identificativo standard)
|===

Seguono due esempi significativi.

== Caso 1: Articolo ordinato per singola unità

.Esempio in cui l’articolo ordinato corrisponde alla singola unità e non alla confezione, con evidenza del numero di pezzi per confezione primaria:
[source, xml, indent=0]
----
<cac:DespatchLine>
	<!—5000 guanti -->
	<cbc:DeliveredQuantity unitCode="NAR">5000</cbc:DeliveredQuantity>
	<cac:Item>
		<!-- Una confezione contiene 500 guanti -->
		<cbc:PackSizeNumeric>500</cbc:PackSizeNumeric> 
		<cbc:Name>GUANTI</cbc:Name> 
		<!—O altro identificativo (es. Standard) -->  
		<cac:SellersItemIdentification>
			<cbc:ID>XYZ</cbc:ID> 
		</cac:SellersItemIdentification>
		<cac:AdditionalItemProperty>
			<cbc:Name>PackIdentification</cbc:Name>
			<!—Codice confezione -->   
			<cbc:Value>AIC12345</cbc:Value> 
		</cac:AdditionalItemProperty>
	</cac:Item>
</cac:DespatchLine>
----

== Caso 2: Articolo ordinato a confezione

.Esempio in cui l’articolo ordinato corrisponde alla confezione:
[source, xml, indent=0]
----
<cac:DespatchLine>
	<!-- 10 confezioni di guanti -->
	<cbc:DeliveredQuantity unitCode="PK">10</cbc:DeliveredQuantity>
	<cac:Item>
		<!-- Un articolo (confezione) contiene 500 guanti -->
		<cbc:PackQuantity>500</cbc:PackQuantity>
		<cbc:Name>CONFEZIONE GUANTI</cbc:Name> 
		<!-- O altro identificativo (es. Standard) -->  
		<cac:SellersItemIdentification>
			<cbc:ID>XYZ500</cbc:ID> 
		</cac:SellersItemIdentification>
		<cac:AdditionalItemProperty>
			<cbc:Name>UnitIdentification</cbc:Name>
			<!-- Codice unità base -->
			<cbc:Value>XYZ</cbc:Value> 
		</cac:AdditionalItemProperty>
	</cac:Item>
</cac:DespatchLine>
----


