
[[projectref]]
= Project reference (CUP)

The project reference is optional to use, and is sent in an invoice in the element `cac:ProjectReference/cbc:ID`. +

#L'indicazione del Codice Unico di Progetto (CUP) è obbligatoria nei contesti in cui questo è richiesto, ed è necessario al fine dei processi di verifica, riconciliazione e approvazione al pagamento delle fatture.# +


In a credit note, this element does not exist, and project reference
is sent by using the element `cac:AdditionalDocumentReference[cbc:DocumentTypeCode='50']/cbc:ID`.

NOTE: Quando si invia il riferimento al progetto, solo il `cbc:ID` e il `cbc:DocumentTypeCode` sono permessi all'interno dell'elemento `cac:AdditionalDocumentReference`.


.UBL example of proejct reference (CUP) in an invoice
[source, xml, indent=0]
----
include::../{snippet-dir}/Snippet-refs.xml[tags=project]
----



.UBL example of project reference (CUP) in a credit note
[source, xml, indent=0]
----
include::../{snippet-dir}/CreditNote-snippets.xml[tags=project ]
----
<1> Il codice 50 indica che questo è il riferimento ad un progetto
<2> L'identificatore del riferimento al progetto


#Per riferirsi a più progetti (CUP) dalle righe di fattura è necessario utilizzare *cac:DocumentReference* con il codice tipo documento = 130.#

.Esempio UBL per il riferimento al progetto (CUP) dalle righe fattura
[source, xml, indent=0]
----
include::../{snippet-dir}/Snippet-refs.xml[tags=CUP_riga]
----