[[projectref]]
= Project reference (CUP)

The project reference is optional to use, and is sent in an invoice in the element *cac:ProjectReference/cbc:ID*. +

#The indication of the Unique Project Code (CUP) is compulsory in contexts where this is required, and is necessary for the verification, reconciliation and approval processes for the payment of invoices.# +

In a credit note, this element does not exist, and project reference is sent by using the element *cac:AdditionalDocumentReference[cbc:DocumentTypeCode='50']/cbc:ID*.

NOTE: When sending the project reference, only the *cbc:ID* and the *cbc:DocumentTypeCode* are allowed in the *cac:AdditionalDocumentReference* element.

.UBL example of project reference (CUP) in an invoice
[source, xml, indent=0]
----
include::../{snippet-dir}/Snippet-refs.xml[tags=project]
----

.UBL example of project reference in a credit note
[source, xml, indent=0]
----
include::../{snippet-dir}/CreditNote-snippets.xml[tags=project ]
----
<1> Code 50 indicating this is a project reference
<2> The project reference identifier

#To refer to a project from invoice line, the information can be specified in *cac:DocumentReference* with document type code = 130, as in the following example:#

.UBL example of project reference (CUP) in the invoice line
[source, xml, indent=0]
----
<cac:DocumentReference>
    <cbc:ID schemeID="AEP">project333</cbc:ID>
    <cbc:DocumentTypeCode>130</cbc:DocumentTypeCode>
</cac:DocumentReference>
----