[[benefici]]
= Benefici

In seguito al successo derivato dall’automatizzazione del ciclo di fatturazione, vi è un crescente interesse anche per l’automatizzazione del ciclo dell’ordine. Questo approccio ha due dimensioni: supportare ulteriori automazioni per il ciclo di fatturazione e utilizzare cataloghi strutturati come base per l’emissioni di ordinativi di fornitura. Implementare questo BIS è un passo importante per molte aziende ed agenzie governative per raggiungere la piena automazione dei processi di fornitura (procurement).

Per i venditori, l’approvazione, raccolta e fatturazione può essere automatizzata in modo significativo.

Per l’agenzia di approvvigionamento, l’approvazione e la contabilità delle fatture può essere automatizzata e la procedura di emissione dell’ordine può essere strutturata per mezzo dei cataloghi.

Altri potenziali benefici derivati dall’uso di questo BIS sono, fra gli altri:

* Può essere utilizzato dale agenzie di approvvigionamento come passo verso l’automazione del processo di approvvigionamento. La flessibilità delle specifiche permette agli acquirenti di automatizzare e strutturare gradualmente l’emissione degli ordini, in base ad un approccio costo/beneficio.

* Le PMI possono offrire ai loro partner commerciali l’opzione di scambiare documenti standardizzati in modo uniforme e quindi muovere tutti gli ordini in formato elettronico.

* Le grandi aziende possono implementare questo BIS come documenti standardizzati per le operazioni principali ed implementare connessioni personalizzate mediante accordi bilaterali con i partner commerciali più importanti.

* Può essere utilizzato come base per ristrutturare i processi interni degli ordini e delle fatture.

* Le agenzia di approvvigionamento possono realizzare risparmi significativi attraverso l’automatizzazione e la semplificazione dei processi interni.

* I venditori possono realizzare risparmi significativi automatizzando e semplificando i processi interni. Il collegamento fra la raccolta e la fatturazione può essere migliorata in modo significativo mediante l’uso di ordini di qualità superiore, ristrutturando la risoluzione delle dispute sulle fatture e accorciando i tempi di pagamento.

* Per l’agenzia di approvvigionamento, l’automatizzazione delle fatture e degli ordinativi può essere strutturata.
