
= Sconti e maggiorazioni

L'elemento `cac:AllowanceCharge` con il sotto elemento `cbc:ChargeIndicator` indica se siamo in presenza di una maggiorazione (true) o di uno sconto (false).

Gli elementi informativi relativi agli sconti e maggiorazioni si trovano in tre livelli.

A livello di testata::

_Applicati a tutta la fattura e inclusi nel totale documento._
* Possono essere indicati diversi sconti e maggiorazioni.
* L’IVA relativa a sconti e maggiorazioni deve essere specificata attraverso l'elemento `cac:TaxCategory` e i suoi sotto elementi.
* La somma di tutti gli sconti e maggiorazioni a livello di testata deve essere specificata rispettivamente in `cbc:AllowanceTotalAmount` e `cbc:ChargeTotalAmount`. Vedi <<totals>>

[IMPORTANT]
====
#Per la fatturazione verso soggetti italiani la sezione è utilizzata solo per Bollo (vedi paragrafo 4.9) e Rivalsa Cassa Previdenziale (vedi paragrafo 4.8).#
====

_#Sconti e maggiorazioni che non incidono sull’imponibile.#_

* #Espressi mediante estensione UBL.#
* #Possono essere indicati diversi sconti e maggiorazioni.#
* #Non modificano nè l'imponibile, nè l'IVA.#


[NOTE]
====
La somma algebrica delle maggiorazioni (con segno meno) e degli sconti (con segno più) va ricompresa nel valore inserito in cbc:PrepaidAmount. Si evidenzia che il cbc:PrepaidAmount non è supportato in FatturaPA ma viene utilizzato per valorizzare correttamente il dato cbc:PayableAmount (BT-115 Amount due for payment) che è obbligatorio per la EN 16931.
====

.#Esempio UBL per fornire lo sconto sul totale documento, mediante estensione#.
[source, xml, indent=0]
----
include::../../../rules/snippets/agid-extensions.xml[tag=ext_ScontoFatturaPA]
----

A livello di riga:: _Il livello di riga si applica alle sole righe ed è incluso nel calcolo dell’importo di riga._
* Possono essere indicati diversi sconti e maggiorazioni.
* L’IVA relativa a sconti e maggiorazioni non deve essere specificata, in quanto la categoria IVA fornita sulla stessa riga fattura si applica anche agli sconti/maggiorazioni della riga.
* Quando si calcola il totale della riga fattura bisogna tenere conto della somma di tutti gli sconti e maggiorazioni sulla stessa riga e sottraendola o sommandola opportunamente. Questi sconti e maggiorazioni a livello di riga non devono essere calcolati a livello di testata.

[IMPORTANT]
====
#Per la fatturazione verso soggetti italiani la sezione sconto/maggiorazione a livello di riga non è utilizzata.#
====

All'interno del prezzo :: _Le informazioni sugli sconti e maggiorazioni a questo livello possono essere fornite per informare l’acquirente su come è composto il prezzo. E’ inoltre importante nel caso in cui il fornitore o l’acquirente desiderino importare le informazioni sugli sconti e maggiorazioni nel loro sistema contabile._ 
* Il prezzo netto (cbc:PriceAmount) deve essere sempre espresso 
* #Il prezzo lordo (cbc:BaseAmount) deve essere sempre espresso.#
* #Il segmento cac:AllowanceCharge deve essere sempre espresso#
* L'elemento cbc:ChargeIndicator deve essere sempre espresso e valorizzato con "false". 
* #Per indicare uno sconto, fornire un importo positivo nel cac:AllowanceCharge/cbc:Amount. +
Per indicare una maggiorazione, fornire un importo negativo nel cac:AllowanceCharge/cbc:Amount. +
Se nessuno Sconto/Maggiorazione è applicato all'articolo, valorizzare cac:AllowanceCharge/cbc:Amount con "0".# 
* Solo un'occorrenza dello sconto è permessa.
* Non sono ammessi sconti/maggiorazioni in percentuale.
* L’IVA relativa a sconti/maggiorazioni non deve essere specificata.
* Gli sconti e le maggiorazioni relativi al prezzo non dovranno essere parte di qualsiasi altro calcolo.

Dettagli ulteriori sul calcolo degli sconti/maggiorazioni sono disponibili presso <<allowance-calc>>

//include::../../syntax/_allowance.adoc[]

.Esempio UBL di sconto su prezzo
[source, xml, indent=0]
----
<cac:InvoiceLine>
    <!-- ... -->
    <cac:Price>
      <cbc:PriceAmount currencyID="EUR">5.00</cbc:PriceAmount>
      <cac:AllowanceCharge>
        <cbc:ChargeIndicator>false</cbc:ChargeIndicator>
        <cbc:Amount currencyID="EUR">1.00</cbc:Amount>
        <cbc:BaseAmount currencyID="EUR">6.00</cbc:BaseAmount>
      </cac:AllowanceCharge>
    </cac:Price>
</cac:InvoiceLine>
----
