= Informazioni sull'articolo (Item)

== Identificatore dell'articolo

In una riga di fattura possono essere specificati l'identificativo attribuito all'articolo dal venditore (seller item identifier), quello dell'acquirente (buyer item identifier) e l'identificativo standard dell'articolo (standard item identifier). Per gli identificativi attribuiti all'articolo dal venditore o dall'acquirente, non viene usato l'attributo dello schema relativo, mentre è obbligatorio l'uso dello `schemeID`
per gli identificatori standard dell'articolo, e deve essere fra gli schemi della codifica ISO 6523 ICD.

include::../../syntax/_item-identification.adoc[]

== Classificazione dell'articolo

Sulla riga di fattura possono essere forniti diversi codici di classificazione per l'attributo e questi devono essere fra gli schemi di classificazione della codifica UNCL7143.

include::../../syntax/_item-classification.adoc[]

== #Tipo cessione prestazione#

La gestione del tipo cessione prestazione è operata a mezzo dell’utilizzo di: +

1.	*cac:AdditionalItemProperty/cbc:Name* 
(BT-160 Item attribute name), inserendo la stringa _TipoCessionePrestazione_;
2. *cac:AdditionalItemProperty/cbc:Value* 
(BT-161 Item attribute value) inserendo il valore ammesso da FatturaPA: _[SC] sconto, [PR] premio, [AB] abbuono, [AC] spesa accessoria_.

.Esempio sulla gestione del tipo cessione prestazione

[source, xml, indent=0]
----
<cac:InvoiceLine>
  <!-- ... -->
  <cac:Item>
    <!-- ... -->
    <cac:AdditionalItemProperty>
      <cbc:Name>TipoCessionePrestazione</cbc:Name>
      <cbc:Value>AB</cbc:Value>
    </cac:AdditionalItemProperty>
  </cac:Item>
</cac:InvoiceLine>
----
