sudo: required
services:
- docker
script:
- sh build.sh
deploy:
  provider: s3
  access_key_id:
    secure: Au2AO0rLJYA7E/X14Of3lmZvMFwiuyAGJW1oBsaDrNKcfQnIFvl4+GhpPJFC6YIv9/RNXtfajH8Ac+lyqItIfV/7i08QHoXXcjuPt2GooiepTwAQD49c16rUOELf93uE9nJK8P0mAaL8rjWzqTdOOcjm8ZoU2rl0zG0YZOUloXCsBdAg74/WrH+Bw7rtwCdbcoJMtzyFD1aYkyCW4KWk6/rrWbMRnbx56kIJ6gpuTi0cnOW/ovx3jZ62Hrhez2h6caVVfzB4TAOl855dOes8BhAK0DHO+aLdXS599Mthhf+om1s6ye4iKes6aoXKKzaPO/UxJlGX1Dy8iKTjqmXleno0sQ4r+XBcM06pX9W6RmW36HY+xQU9QzN+mihhDsOXgrFJ/biJxITJtv7/AIVTOLztrAD9yY4Ya+M30FNSpejMLNFrVZKn3cXTbAUc1Pzcu0vaUQ17z5/XIPn+12lYxcf8JnJ01xqhRBelujaUaAzRnn5oaNBVlpTgVo+7WiBlOs+r3BhLKbByDAZzGyr1fOO0MVNQB0ADws8Q8YDiI8mDC9i0LMGwHRR/E7AXSYlWI+eTMemD9WYFlU93DjhVZpvpgErJkUSp0BvOna9CRKfnKOVrAiCe25ikmdNfiA+vuhC66/SWSG0pZi1eacq4sm+S08tr4ZRe2bqMEttaDzw=
  secret_access_key:
    secure: KykiwYSSFhzAfDgtx4GJCqezpNGrRZsh7skBOuKxUTuXXsct0rGiRJyzPmckn7hjjFafE50UpYGD+7zemRkKwXYH1oDMcjSTl7qAWypztp2K6ogo5yCPAZ1GvzB0+Jox8vAPKjcr+ZViReBNUGegV7eVAPZO2725QvjfFkaVWCRteiiMx5F/KVu+ZbxJImsmAbliXtOIaO3A+TtoGUQuSeXhsNKZBmUiKMFN4nqDT4Ut0S7CxLjNa7+v/EnK5f/jZfUgqrQTCxkKt1JAcFjxbzaOaECGBRmAfJ6UwASpJ/NlmgYBjRMgtWvLDy03Ha/pZEYyDEZPmCb2rs2nVQiRcrWp0HC5gLQrLc1arlaEvJplqaH1niQA1+GiUw1tDG/T5nbA8GEt1m5Oy3b1en92DT9i7DI2NyajRAMbv+aRaPA8zeivm5hBjQsoSIKlDYExJ9+YiLm4OZ+peok0g3Hn+EHXrOEIOKvZj72WkD3FxkwH2Vmes0twQyRON2PvYfY2H7i9mOyxt/M1mjfLFtRjjDC9JJ2Tp5JOcPIv2RzloHppxM4LSNw3k+qg+HSGkiPhL48X72W897R5xfUYWh1a+vrDzWjfZ3/BjgSz9IJDst0vCTkfiCHTVQlQ2c5/j4WRWzvFw4RYdjuIQRt1Z6mP4KyqUCbFcIrgsju4Eh6q4jc=
  bucket:
    secure: MlPKnPA1a98AK2bNVFkFDQ08E0ce8BUyAf6Bq7xkMMdiwBrIVo02BgO3m5/n0WGQy6GdaDZiySlP5ob9ZZ3r1MJHjBfsCHigzA740XO1dzPenJRA9wcoBty/nUP8W47CC59CCgJ4VOITScl0clwDPbwcsNaLbebWL4Zb8pncG4r8NBCUS33djHQPcCseB2pduiIAFJfvEa3/6KUf7O0BfDwdqT/JyeEF309hC5dIgZs3ai9xLRNne2doEqOSDfgt67GL7vYvc2vYhtNewVMdsqMWYfjCfhlwytYz68OaxysWZTmIX5B7t13nOPaqtxCyxuH8mVD04I3tCl7sSFlFuKYqZ3qA8qMahMjygigYBDp7yFUYutZdmVQyQHrUHsnc9rEHb2V6ntWmqUzLidtjhTEa2GLz8VaWdKG1jHltsso5PAOcj0vR0nIPFpCzcsVftKbtbI5peqWjN+6Gu5fy5xkAr/SVg3ZIJ+CyfHmzJWmVzwl9qL5TEA0SC0WBzAhZ4QHO/Qc8lOQ+XUhHTaHtoYgDQX7D2GCnT+vhP3UM06n+DpQA/A0fpeWdeAoiWzGtb+tHECLQRXv4PcRurDvnhcGxtOf00v5u6K4/Y3BT4ckGEbJBRO1oBlERgAUnCf3xko/EzFcf7jV9gKOW1UkjL8favIywZko5VzecZHYPH5U=
  region: eu-west-1
  local-dir: target/site
  upload-dir: poacc/billing/3.0
  acl: public_read
  skip_cleanup: true
  on:
    repo: OpenPEPPOL/peppol-bis-invoice-3
    branch: master
