
= Informazioni sulle modalità di pagamento

== Bonifico

Se il pagamento viene effettuato mediante bonifico, l'elemento Payment account identifier (BT-84) è obbligatorio

Vedi <<payment-means>> per tutti i codici ammessi. Esempi di codici per i pagamenti con bonifico sono:

* 30 - Bonifico
* 58 - Bonifico SEPA (SEPA credit transfer o SCT)

include::../../syntax/credit-payment.adoc[]

== Pagamento con carta

Se l'Acquirente ha scelto di pagare mediante una carta di pagamento come ad esempio una carta di credito o di debito, le informazioni relative al Primary Account Number (PAN) dovranno essere presenti in fattura.

Vedi <<payment-means>> per tutti i codici ammessi. Esempi di codici per i pagamenti con carta sono:

* 48 - Bancomat (es. ATM)
* 54 - Carta di credito (es. VISA, Mastercard, ...)
* 55 - Carta di debito (es. VISA Electron)

include::../../syntax/card-payment.adoc[]

== Addebito diretto

Vedi <<payment-means>> per tutti i codici ammessi. Esempi di codici per l'addebito diretto sono:

* 49 - Addebito diretto
* 59 - Addebito diretto SEPA (SEPA direct debit o SDD)

include::../../syntax/direct-debit.adoc[]

== Pagamento mediante postagiro o giroconto bancario

Vedi <<payment-means>> per tutti i codici ammessi. Esempi di codici per il postagiro o giroconto sono:

* 50 - Giroconto postale (Postagiro o bollettino postale)
* 56 - Giroconto bancario

include::../../syntax/giro.adoc[]

== Pagamento mediante contante

Vedi <<payment-means>> per tutti i codici ammessi. Esempio di codice per il pagamento in contante:

* 10 - Contante

include::../../syntax/cash-payment.adoc[]

== Pagamento non specificato

Se il venditore non dà indicazioni su come regolarizzare il pagamento della fattura, esiste solitamente un contratto che lo regola.

Indicando il codice 1, l’acquirente non viene informato sulle modalità di pagamento della fattura e può essere indicata solo una data di pagamento.

include::../../syntax/unspecified-payment.adoc[]
