
= Informazioni sulle modalità di pagamento

== Bonifico

Se il pagamento viene effettuato mediante bonifico, l'elemento Payment account identifier (BT-84) è obbligatorio

Vedi <<payment-means>> per tutti i codici ammessi. Esempi di codici per i pagamenti con bonifico sono:

* 30 - Bonifico
* 58 - Bonifico SEPA (SEPA credit transfer o SCT)

include::../../syntax/credit-payment.adoc[]

== Pagamento con carta

Se l'Acquirente ha scelto di pagare mediante una carta di pagamento come ad esempio una carta di credito o di debito, le informazioni relative al Primary Account Number (PAN) dovranno essere presenti in fattura.

Vedi <<payment-means>> per tutti i codici ammessi. Esempi di codici per i pagamenti con carta sono:

* 48 - Bank card (bancomat, ATM)
* 54 - Carta di credito
* 55 - Carta di debito

include::../../syntax/card-payment.adoc[]

== Addebito diretto

Vedi <<payment-means>> per tutti i codici ammessi. Esempi di codici per l'addebito diretto sono:

* 49 - Addebito diretto
* 59 - Addebito diretto SEPA (SEPA direct debit o SDD)

include::../../syntax/direct-debit.adoc[]

== Pagamento mediante postagiro o giroconto bancario

vedi <<payment-means>> per tutti i codici ammessi. Esempi di codici per il postagiro o giroconto sono:

* 50 - Giroconto postale (Postagiro)
* 56 - Giroconto bancario

include::../../syntax/giro.adoc[]
