
= Restrizioni ai processi supportati

Il capitolo 5.2 nella {EN16931} definisce i processi di business supportati dalla {EN16931}.

Questa {CIUS} ha applicato delle restrizioni per non supportare esplicitamente i seguenti processi di business:

P10 - Fattura correttiva::
Il processo descritto per la fatturazione correttiva è stato visto come non chiaro rispetto alla distinzione tra una fattura correttiva e una nota di credito, e questo processo è stato per questo definito fuori ambito.

P11 - Fatturazione parziale e finale::
A causa del fatto che le fatture parziali e finali non richiedono tutte le informazioni richieste, questo processo non rientra nell'ambito di questa BIS PEPPOL.

P12 - Auto fatturazione:: La Direttiva 2006/112/CE (Articolo 224) richiede che venga osservato un processo specifico, che preveda un accordo preliminare e una procedura in cui il fornitore deve accettare ciascuna fattura. L'auto-fatturazione richiede una configurazione specifica a causa dei requisiti presenti nell'accordo preliminare e nella procedura per l'accettazione di ogni auto-fattura. Specifici traguardi dovranno essere osservati nel momento in cui sarà configurata e durante la sua messa in produzione.
